### ISSUE TITLE
Compatibility Request Better Foliage Round Logs

### ISSUE THREAD

**Issue by SulpherStaer** [ferreusveritas/Dynamic-Trees#101]
This mod is awesome, but it would be nice if Better Foliage knew they were trees.

https://minecraft.curseforge.com/projects/better-foliage

**Comment by ghost** [comment]
Round logs will not be implemented.  Sorry.
- Violates minecraft aesthetic
- Model would be too difficult to implement
- Would need to be implemented in Better Foliage which most likely will not be done
