### ISSUE TITLE
Dynamic Giant Mushrooms

### ISSUE THREAD

**Issue by Sunconure11** [ferreusveritas/Dynamic-Trees#103]
Since vanilla has tree-sized mushrooms, and yet are not touched by your mod, how feasible is it to pull this off ever?

**Comment by ghost** [comment]
It's being considered with low priority since how the mushroom would grow in steps is unclear.

**Comment by Sunconure11** [comment]
You could always separate the small mushrooms from the giant ones entirely, although this might force it slightly out of your scope. Instead, you'd have to use a potion on a small mushroom as opposed to bonemeal to even get a giant mushroom, aside from natural gen.

As for stages... https://www.youtube.com/watch?v=us79TMh5Dkk

Mix those up with some more fantastic takes on them as well. [Since let's be clear, the only fungus that probably would've hit the same sizes as the ones in MC is long extinct.](https://en.wikipedia.org/wiki/Prototaxites)

**Comment by Sunconure11** [comment]
There was a bit of discussion regarding this on Mangoose's discord channel. (https://discord.gg/dse4X5V)

At least one image for a possible concept was made.

https://cdn.discordapp.com/attachments/420010799545712643/466784813228097566/unknown.png

**Comment by aycfes** [comment]
well, you could use the way irl mushrooms grow as a base (insert shrug)

**Comment by ghost** [comment]
I'm no longer interested in doing mushrooms as part of the DynamicTrees base.  If I ever do add dynamic mushrooms it will be as an Add-On.
