### ISSUE TITLE
Maple Samara server bug

### ISSUE THREAD

**Issue by JoeSGT** [ferreusveritas/Dynamic-Trees#104]
so on the server if you spam place and break the Maple Samara it kick you this happen on the server can't reproduce this on singleplayer https://pastebin.com/raw/bLhaZ2K5 this happen on client side console when the issue happens no errors on server side console tho

**Comment by Deshiba** [comment]
If this is even DynamicTrees I think you are looking for the following Git:
https://github.com/the-realest-stu/Dynamic-Trees-BOP

**Comment by JoeSGT** [comment]
oop's my bad didn't this I made an issue their https://github.com/the-realest-stu/Dynamic-Trees-BOP/issues/19 going to close this
