### ISSUE TITLE
Serverside java exception. Tested with multiple modpacks and servers. Need help figuring it out

### ISSUE THREAD

**Issue by netcore10** [ferreusveritas/Dynamic-Trees#106]
Hi! I have your mod in my modpack, but there's a bug that when you break a maple samara sapling. This only happens on a server, it just kicks the player that broke it with a java exception, but you can get back in just fine. Just hoping this could be fixed. *Please note it doesn't happen in single player, and i've tested on a modpack with 100 mods and 39 mods, both the same issue, sometimes when player breaks, other times its host only. (Tried and tested, host is more common)

Here's the error  in client you get when you(host) break it. 
![image](https://user-images.githubusercontent.com/181536/42912804-2c222ad8-8ae9-11e8-9843-8a1abc3d818b.png)

Here's the error in the server tracker. there are cases when its other players who break it too, but not on this current server.
![image](https://user-images.githubusercontent.com/181536/42912796-22df232c-8ae9-11e8-952a-6639b680b2d0.png)

am i doing something wrong?

**Comment by ghost** [comment]
Does this also happen with the magic tree?

**Comment by ghost** [comment]
I was able to reproduce this and it only happens with the maple samara and/or maple sapling.

**Comment by netcore10** [comment]
Oh! So i'm not doing something wrong? Good to know. 

- It doesn't happen with magic trees. I'm glad i could make you aware of this.

**Comment by ghost** [comment]
This is now fixed in dev version.  The tile entity was being destroyed before the tree species could be determined and as a result was getting an invalid seed.

**Comment by netcore10** [comment]
Great! thanks a lot
