### ISSUE TITLE
Json BiomeDataBasePopulator feature

### ISSUE THREAD

**Issue by ghost** [ferreusveritas/Dynamic-Trees#108]
Placeholder for future feature.  Discussions and ideas go here.

**Notes about feature:**
Many players and world builders want to fine tune how trees in biomes work.  A method to add forest density characteristics and biome tree spawning behavior via a json config file would be extremely useful.

At the moment Dynamic Trees uses a BiomeDataBasePopulator that injects tree spawn information into it's internal database for deciding what kind of trees go where.  Mods like the Dynamic Trees Biome O' Plenty add-on use this feature to extend the world gen for vanilla biomes as well as adding trees in Biomes O' Plenty.  There's no reason why a crafted Json config file couldn't do the same.

My question for the community is this:
  Should this be added to the base Dynamic Trees mod or should this be a separate add-on?
[vote here](https://strawpoll.com/sx18y2gp)

**Comment by Deshiba** [comment]
I'd say implement it as long as it doesn't take time away from more pressing features like 2 by 2 and 3 by 3 trees etc.

**Comment by ghost** [comment]
This has been implemented in Dynamic Trees - Control
