### ISSUE TITLE
Mod needs compat with Item Physic Full

### ISSUE THREAD

**Issue by Sunconure11** [ferreusveritas/Dynamic-Trees#109]
As far as I can tell, the two systems from this mod and Item Physic Full both do not work well together. Trees do not grow from dropped acorns, which I used to test. Though I could just be impatient. Even though I used 512 acorns.

**Comment by ghost** [comment]
Looks like Item Physic Full does some code transformation that might be difficult to unravel.  Dynamic Trees doesn't do anything fancy but it does rely on entityItem.lifespan and entityItem.ticksExisted.  If either of those have been modified by Item Physic Full then it won't likely work.  At this point i'm not sure if there's anything I can do.

**Comment by ghost** [comment]
I tried version ItemPhysic_Full_1.4.16_mc1.12.2 in my dev environment for testing and it works fine.  It works exactly like you'd expect and the seeds randomly germinate according to the dynamic tree rules when dropped on the ground.  I had zero problems getting it working.  Could you send a screenshot of where you are trying to get this planted or maybe give a further description of the method you are using?

**Comment by Sunconure11** [comment]
I simply tried throwing stacks of seeds at the ground.

**Comment by ghost** [comment]
Strangely enough when I tried to throw stacks of items they would disappear before they hit the ground.  But one at a time seems to work.  Are you using the ItemPhysic_Full_1.4.16_mc1.12.2 version?

**Comment by ghost** [comment]
Could not reproduce, tested fine
