### ISSUE TITLE
Crash while breeaking leaves, BirdsNests compatibility

### ISSUE THREAD

**Issue by ZephaniahNoah** [ferreusveritas/Dynamic-Trees#11]
I'm not sure which mod is causing this but when I install BirdsNests and try to break the dynamic leaves the game will eventually crash.
Dynamic Trees: 0.6.5
MC: 1.11.2

**Comment by ghost** [comment]
You got a crash log for me?

**Comment by ZephaniahNoah** [comment]
[crash-2017-10-22_04.44.39-server.txt](https://github.com/ferreusveritas/Dynamic-Trees/files/1404834/crash-2017-10-22_04.44.39-server.txt)

**Comment by ghost** [comment]
Looks like the birdsnests mod is expecting my leaves to have a "decayable" property which it does not.  Dynamic leaves are derived from vanilla leaves but do not decay in the same way as vanilla leaves.

The author of birdsnests might consider putting in a check for leaves in case a mod(such as mine) does the leaves a bit differently.

if (blockState.getProperties().containsKey(DECAYABLE)) {
    // do leafy stuff here
}

For me to institute a fix on my end I would have to do a tremendous amount of work to implement a non-standard IBlockState interface to return a fake "decayable" value and I don't know if the mod would be happy with true or false.

**Comment by ghost** [comment]
This is on BirdsNests to fix.  I've given my suggestion on how to fix it.  Looks like BirdsNests hasn't been updated in a while so I don't foresee this being fixed.

**Comment by ghost** [comment]
This has been fixed by cleverpanda.
