### ISSUE TITLE
Dynamic Tree Munchdew Detection - Feature Request

### ISSUE THREAD

**Issue by Peach774** [ferreusveritas/Dynamic-Trees#112]
Currently the munchdew can eat dynamic tree leaves and then the leaves regrow. Is there a way to make the trees stop regrowing leaves when near a munchdew or to make the munchdew ignore dynamic tree leaves?
Currently I've disabled the munchdew since this ability makes them overpowered, but I would like to re-enable it if possible.

**Comment by ghost** [comment]
I don't think this is going to be possible.  This seems to represent an unresolvable incompatibility with Botanica.

**Comment by Peach774** [comment]
Is it possible to make leaves not regrow on a tree if all the leaves are removed? That seems to be the main issue - the flower strips all the leaves, but the tree continues to regrow them. Maybe stopping tree/leaf growth if all leaves are removed could work, if that is possible.

**Comment by ghost** [comment]
I don't think it's a good idea to change the dynamic of the mod and potentially add bugs on account of a leaf eating flower.  I realize there's mods out there that expect leaves not to come back after they are broken.  I'm sorry, this mod isn't compatible with those.

**Comment by Peach774** [comment]
That's okay. Ill just change the recipe of the flower. Thanks for informing me
