### ISSUE TITLE
Crash on dropblock

### ISSUE THREAD

**Issue by Tencao** [ferreusveritas/Dynamic-Trees#113]
Using latest dev build of 0.8.1c, crash seems to be an endless loop of dropBlock

Crash Report - https://gist.github.com/Tencao/12623793e117643b93d3a06ae567726a

**Comment by ghost** [comment]
Steps to reproduce?  Dedicated server or client mode? Which sapling specifically is causing the problem?  I'm unable to get it to crash like this.

**Comment by Tencao** [comment]
Dedicated but this may have actually being a world issue. Since starting a new world this hasn't surfaced again, however I shall keep an eye on this and report back if the issue returns.
