### ISSUE TITLE
Floating Trees

### ISSUE THREAD

**Issue by danielkeyes137** [ferreusveritas/Dynamic-Trees#116]
I read through the closed issues and this seems to be unaddressed. My apologies if I didn't look hard enough.

I've been noticing that quite of few of the trees in my forests are floating. Upon further investigation, I've found that their rooty soil has become a regular grass block. Destroying this will not affect the tree, but if I destroy any part of the tree, the rest of it disappears. Though I thought that these floating trees had become completely static, I've observed some of them regenerating leaves (if, for example, I knock down a different nearby tree and clear up some room). Wood growth, on the other hand, seems to have stopped. In fact, some trees float more than others. Potions are ineffective. 
About half the trees continue to grow as expected; for these, acorns and catkins still take root.

I've attached a video and a screenshot, in which I'm using the Conquest resource pack. You can see your rooty soil texture under a normal tree, as opposed to the grass/dirt texture under the corrupted trees.
https://youtu.be/QjOGpDxYNWw

Also a picture for convenience.
![minecraft 1 11 2 8_16_2018 9_28_01 pm](https://user-images.githubusercontent.com/42459494/44247850-2440d980-a19c-11e8-8c3b-8be99ab704a2.png)

I'm playing Minecraft 1.11.2 with Forge 13.20.1.2386.

**Comment by ghost** [comment]
There was a bug a while back where rooty blocks that were randomly ticked in a chunk next to an unloaded chunk would cause the rooty dirt to turn to dirt.  That was fixed in 1.12.2 but probably never was fixed in 1.11.X before support for it ended.

**Comment by danielkeyes137** [comment]
Ah, no worries then. :)
Love the mod, by the way. You and your work are appreciated!
