### ISSUE TITLE
Cactus Roots Render Issues

### ISSUE THREAD

**Issue by RainbowSaber** [ferreusveritas/Dynamic-Trees#118]
The cactus root block texture doesnt render properly for me. Current Forge Version, no Optifine

![image](https://user-images.githubusercontent.com/10180141/44408931-a5fc8280-a561-11e8-85bc-bc3e05d10c62.png)

**Comment by ghost** [comment]
Can you see if this happens in the latest alpha release of Dynamic Trees?

**Comment by ghost** [comment]
Unable to reproduce/Non-productive issue

**Comment by Peach774** [comment]
I'm getting this issue with the current release

**Comment by ghost** [comment]
Like I said, I'm able to reproduce this.  Somebody throw me a bone here.  A modlist or something to get started, anything.

**Comment by ferreusveritas** [comment]
> The cactus root block texture doesnt render properly for me. Current Forge Version, no Optifine
> 
> ![image](https://user-images.githubusercontent.com/10180141/44408931-a5fc8280-a561-11e8-85bc-bc3e05d10c62.png)

**Comment by ghost** [comment]
@RainbowSaber Don't leave issues with something like "Current Forge Version" use the actual forge version number.

**Comment by Peach774** [comment]
For context, Forge: 14.23.5.2768
Here is my mod list: 
minecraft - Minecraft - 1.12.2
mcp - Minecraft Coder Pack - 9.42
FML - Forge Mod Loader - 8.0.99.99
forge - Minecraft Forge - 14.23.5.2768
smoothfontcore - Smooth Font Core - mc1.12.2-1.16
foamfixcore - FoamFixCore - 7.7.4
obfuscate - Obfuscate - 0.2.6
botania_tweaks_core - Botania Tweaks Core - -100
dsurroundcore - DynamicSurroundingsCore - 
smoothfont - Smooth Font - mc1.12.2-1.16.1
flintblock - A Block of Flint - 1.0
actuallyadditions - Actually Additions - 1.12.2-r143
baubles - Baubles - 1.5.2
actuallybaubles - Actually Baubles - 1.1
aether_legacy - Aether Legacy - 1.12.2-v3.2
akashictome - Akashic Tome - 1.2-10
biomesoplenty - Biomes O' Plenty - 7.0.1.2402
botania_tweaks - Botania Tweaks - 1.7.1
crafttweaker - CraftTweaker2 - 4.1.11
mtlib - MTLib - 3.0.5
modtweaker - Mod Tweaker - 4.0.15
jei - Just Enough Items - 4.13.1.222
thaumcraft - Thaumcraft - 6.1.BETA26
botania - Botania - r1.10-357
redstoneflux - Redstone Flux - 2.1.0
cofhcore - CoFH Core - 4.6.1
craftstudioapi - CraftStudio API - 1.0.0
mantle - Mantle - 1.12-1.3.3.39
natura - Natura - 1.12.2-4.3.2.62
harvestcraft - Pam's HarvestCraft - 1.12.2z
quark - Quark - r1.5-130
ctm - CTM - MC1.12.2-0.3.2.20
twilightforest - The Twilight Forest - 3.8.689
animania - Animania - 1.6.0.2
applecore - AppleCore - 3.1.4
appleskin - AppleSkin - 1.0.9
astralsorcery - Astral Sorcery - 1.10.3
psi - Psi - r1.1-59
autoreglib - AutoRegLib - 1.3-20
codechickenlib - CodeChicken Lib - 3.2.2.353
avaritia - Avaritia - 3.2.0
badwithernocookiereloaded - Bad Wither No Cookie! Reloaded - 1.12.2-3.1.14
bard_mania - Bard Mania - 0.14.0-alpha
bdlib - BD Lib - 1.14.3.12
forestry - Forestry - 5.8.2.366
beebetteratbees - Bee Better at Bees - 2.0.3
betteradvancements - Better Advancements - 0.0.5.17
bettermobgriefinggamerule - Better mobGriefing GameRule - 1.12.2-7.0.1
bibliocraft - BiblioCraft - 2.4.5
binniecore - Binnie Core - 2.5.0.168
binniedesign - Binnie's Design - 2.5.0.168
genetics - Binnie's Genetics - 2.5.0.168
botany - Binnie's Botany - 2.5.0.168
extrabees - Binnie's Extra Bees - 2.5.0.168
extratrees - Binnie's Extra Trees - 2.5.0.168
guideapi - Guide-API - 1.12-2.1.7-62
bloodmagic - Blood Magic: Alchemical Wizardry - 1.12.2-2.3.3-101
bonsaitrees - Bonsai Trees - 1.1.1
bookshelf - Bookshelf - 2.3.568
buildcraftlib - BuildCraft Lib - 7.99.18
buildcraftcore - BuildCraft - 7.99.18
buildcraftfactory - BC Factory - 7.99.18
buildcrafttransport - BC Transport - 7.99.18
buildcraftsilicon - BC Silicon - 7.99.18
buildinggadgets - Building Gadgets - 2.4.4
careerbees - careerbees - 1.0
carryon - Carry On - 1.11.1
chameleon - Chameleon - 1.12-4.1.3
chisel - Chisel - MC1.12.2-0.2.1.35
chiselsandbits - Chisels & Bits - 14.27
cofhworld - CoFH World - 1.3.0
cyclopscore - Cyclops Core - 0.11.11
colossalchests - Colossal Chests - 1.6.11
refinedstorage - Refined Storage - 1.6.9
compactmachines3 - Compact Machines 3 - 3.0.12
endercore - EnderCore - 1.12.2-0.5.43
thermalfoundation - Thermal Foundation - 2.6.1
thermalexpansion - Thermal Expansion - 5.5.2
enderio - Ender IO - 5.0.37
enderiointegrationtic - Ender IO Integration with Tinkers' Construct - 5.0.37
tconstruct - Tinkers' Construct - 1.12.2-2.11.0.106
conarm - Construct's Armory - 1.2.0.1
controlling - Controlling - 3.0.6
cookingforblockheads - Cooking for Blockheads - 6.4.65
ctgui - CT-GUI - 1.0.0
crafttweakerjei - CraftTweaker JEI Support - 2.0.2
p455w0rdslib - p455w0rd's Library - 2.0.35
theoneprobe - The One Probe - 1.4.25
danknull - /dank/null - 1.4.43
diethopper - Diet Hopper - 1.1
dirt2path - Dirt2Path - 1.7.1
dsurround - Dynamic Surroundings - 3.4.10.0
presets - Presets! - 3.4.10.0
dynamictrees - Dynamic Trees - 1.12.2-0.8.2
dynamictreesbop - Dynamic Trees BOP - 1.12.2-1.3.2
dynamictreestc - Dynamic Trees TC - 1.12.2-1.1.2
eerieentities - Eerie Entities - 1.0.4
eleccore - ElecCore - 1.8.434
ebwizardry - Electroblob's Wizardry - 4.1.2
csb_ench_table - Lapis Stays in the Enchanting Table - 1.1.3
enderiobase - Ender IO Base - 5.0.37
enderioconduits - Ender IO Conduits - 5.0.37
enderioconduitsappliedenergistics - Ender IO Applied Energistics Conduits - 5.0.37
enderioconduitsopencomputers - Ender IO Open Computers Conduits - 5.0.37
enderioconduitsrefinedstorage - Ender IO Refined Storage Conduits - 5.0.37
enderiointegrationforestry - Ender IO Integration with Forestry - 5.0.37
enderiointegrationticlate - Ender IO Integration with Tinkers' Construct - 5.0.37
ftblib - FTBLib - 5.3.1.57
enderiomachines - Ender IO Machines - 5.0.37
enderiopowertools - Ender IO Powertools - 5.0.37
enderioendergy - Ender IO endergy - 5.0.37
immersiveengineering - Immersive Engineering - 0.12-86
engineersdoors - Engineer's Doors - 0.8.0
shadowmc - ShadowMC - 3.8.0
extrarails - Extra Rails - 1.3.0
extrautils2 - Extra Utilities 2 - 1.0
farseek - Farseek - 2.3.1
foamfix - FoamFix - 0.10.2-1.12.2
forgelin - Shadowfacts' Forgelin - 1.8.0
ftbguides - FTB Guides - 1.0.2.24
ftbg - FTB Guide Book - 1.12.1-1.0.07
ftbutilities - FTB Utilities - 5.3.0.53
gendustry - GenDustry - 1.6.5.8
gendustryjei - Gendustry JEI Addon - 1.0.2
geolosys - Geolosys - 2.1.3.1
ichunutil - iChunUtil - 7.1.4
hats - Hats - 7.0.0
librarianlib - LibrarianLib - 4.15
hooked - Hooked - %VERSION%
hungerpersistence - Hunger Persistence - 1.0.1
llibrary - LLibrary - 1.7.15
iceandfire - Ice and Fire - 1.5.2
immersivepetroleum - Immersive Petroleum - 1.1.9
immersivetech - Immersive Tech - 1.3.10
initialinventory - InitialInventory - 2.0.2
ironchest - Iron Chest - 1.12.2-7.0.52.837
jehc - Just Enough HarvestCraft - 1.12.2
jetif - Just Enough Throwing In Fluids - 1.1.0
journeymap - JourneyMap - 1.12.2-5.5.2
jaff - Just a Few Fish - 1.7_for_1.12
justenoughpetroleum - Just Enough Petroleum - 0.1
jeresources - Just Enough Resources - 0.8.9.48
kleeslabs - KleeSlabs - 5.4.11
lex - LibEx - 1.0.8
lttweaker - Loot Table Tweaker - 1.1.14
lunatriuscore - LunatriusCore - 1.2.0.42
magicbees - MagicBees - 1.0
malisiscore - MalisisCore - 1.12.2-6.4.0
malisisdoors - MalisisDoors - 1.12.2-7.3.0
mcjtylib_ng - McJtyLib - 3.0.6
meecreeps - MeeCreeps - 1.2.2
modularmachinery - Modular Machinery - 1.9.4
modulardiversity - Modular Diversity - 1.1
monk - Monk Mod - 1.4
morelibs - More Libs - 1.0.6
moreoverlays - MoreOverlays - 1.14
plustic - PlusTiC - 6.5.3.0
moreplates - More Plates - 5.4.3
mousetweaks - Mouse Tweaks - 2.9
nex - NetherEx - 2.0.8
netherportalfix - NetherPortalFix - 5.3.17
noctrl - NoCtrl - 1.2
nofov - No FOV - 1.0.1
recipehandler - NoMoreRecipeConflict - 0.12
nonausea - NoNausea - 1.0
oreexcavation - OreExcavation - 1.4.129
oeintegration - OreExcavation Integration - 2.3.4
placebo - Placebo - 1.5.0
portalgun - PortalGun - 7.0.2
poweradapters - Power Adapters - 1.0.11
progressivebosses - Progressive Bosses - 1.4.0
realdrops - Realistic Item Drops - 1.2.14
redstonearsenal - Redstone Arsenal - 2.6.1
refined_avaritia - Refined Avaritia - 2.4
refinedstorageaddons - Refined Storage Addons - 0.4.3
rftools - RFTools - 7.56
rftoolscontrol - RFTools Control - 1.9.1
schematica - Schematica - 1.8.0.169
signals - Signals - 1.4.0-29
solcarrot - Spice of Life: Carrot Edition - 1.3.1
storagedrawers - Storage Drawers - 1.12-5.3.5
storagedrawersextra - Storage Drawers Extras - @VERSION@
streams - Streams - 0.4.4
supersoundmuffler - Super Sound Muffler - 1.0.2.9
thaumicjei - ThaumicJEI - 1.2.1
thaumicperiphery - Thaumic Periphery - 0.3.0
thermaldynamics - Thermal Dynamics - 2.5.3
thermalinnovation - Thermal Innovation - 0.3.1
tinkersaether - Tinker's Aether - 1.2.0
tinkertoolleveling - Tinkers Tool Leveling - 1.12.2-1.1.0.DEV.b23e769
tipline - TipLine - 1.0.4
tombmanygraves - Tomb Many Graves - 1.12-4.2.0
tombmanygraves2api - TombManyGraves2 API - 1.12.2-1.0.0
topaddons - TOP Addons - 1.12.2-1.9.1
totemic - Totemic - 1.12.2-0.11.3

**Comment by Reshirou** [comment]
I found the issue; it's the Connected Textures Mod. It adds a sort of "dynamic wet sand" feature, that's really quite cool, but I assume that conflicts with the sand roots in Dynamic Trees.

When sand is near water, the half or so of the block near the water gets darker, and when sand is underwater or surrounded, all of it turns darker and wet.

Specifically it's the connected textures mod, and the required texture pack. The texture pack is what makes the mod have any use, if you try to replicate the issue.

**Comment by ghost** [comment]
@Reshirou nice work :)

**Comment by MrGreenTea** [comment]
I can confirm the problem is with Connected Textures Mod. I can reproduce this issue with only CTM, their default ressource pack and DynamicTrees installed.

![2018-11-27_12 55 18](https://user-images.githubusercontent.com/9407731/49080434-eb58dc00-f243-11e8-9c26-1e373364be6b.png)
![2018-11-27_12 55 23](https://user-images.githubusercontent.com/9407731/49080437-ed229f80-f243-11e8-9161-c0397c03bf0f.png)
