### ISSUE TITLE
DT:BoP Bamboo Tesselating Crash

### ISSUE THREAD

**Issue by TakunSho** [ferreusveritas/Dynamic-Trees#119]
My first issue of the day. While trying to debug the other issue I'm having, I created a debug world. When the DT trees loaded into rendering range, it immediately (before I even saw them) CTD. The error was an issue tesselating the Bamboo branches from DT:BoP. I haven't ever found bamboo previously in other modpacks I've had so I can't say for sure when this issue started.

[Tesselating Render Crash Log](https://github.com/ferreusveritas/DynamicTrees/files/2307014/latest.log)

**Comment by ghost** [comment]
This was actually in the Dynamic Trees Biomes O'Plenty mod.  But I made a fix for it to clamp the radius range of bamboo.  Since I wasn't able to reproduce the bug myself it's untested.  If the problem persists then file another issue under the right mod along with steps to reproduce the problem.
