### ISSUE TITLE
[Compatibility] Tree Branch drops and BlockEvent.HarvestDropsEvent

### ISSUE THREAD

**Issue by An-Sar** [ferreusveritas/Dynamic-Trees#12]
Hello, this is the followup to our conversation on curse, 
My mod PrimalCore has a survival feature that forces the player to use a proper tool to harvest logs.  

I am currently using the BlockEvent.HarvestDropsEvent to cancel the drops, however it seems that the branch items are not included in the list provided by the event.

Thank You

**Comment by ghost** [comment]
I just reworked the block harvesting logic flow so it contains and reacts to a ForgeEventFactory.fireBlockHarvesting() call.  This should fix your problem.  The code update is in the 1.10.2 branch.  I'll be melding it with the other MC versions when I get closer to a release date.
