### ISSUE TITLE
Chopping down tree cause loud leaf noise and lag

### ISSUE THREAD

**Issue by Lictor000** [ferreusveritas/Dynamic-Trees#121]
Latest release of the mod, 0.8.1e for 1.12.2, and last recommended forge version, 14.23.4.2705.
When attempting to chop down the a tree with the new falling feature there's a very loud noise caused by the breaking of several leaf blocks. This brings also lag to the world. I'm usually run smoothly at 50-60 fps without problems, but in the moment the log block is broken and the falling event starts the fps dropped down a lot around 10-20, once even at less than 10 fps, and then return to normal once the animation of the falling starts.
I replicated the issue using only DynamicTrees.
I know this probably just needs some optimization for the lag, since it's a feature in alpha, but I think the most annoying thing is the breaking leaf noise when you chop down the tree.

**Comment by ghost** [comment]
It's probably the multiplicity of leaf block breaking sounds and the thousands of leaf particles that spawn that cause the lag.  I'll look into it.

Shame on me, I normally develop the mod with the sound turned down because I'm listening to music. :)

**Comment by ghost** [comment]
Fixed in dev
