### ISSUE TITLE
getRadius() Call Needs Updated

### ISSUE THREAD

**Issue by Voxel-Friend** [ferreusveritas/Dynamic-Trees#123]
The forge logger spams the following line a lot when chunks are being generated:
[18:26:26] [Server thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.blocks.BlockBranch:getRadius:207]: Please have mod author update API calls for getRadius()

**Comment by ghost** [comment]
It only spams it a set number of times.  You're probably running with Rustic which will update it's API calls when Dynamic Trees makes a stable release of 0.8.x

**Comment by Voxel-Friend** [comment]
Ah, gotcha. Had no idea this was on rustic's end. Sorry to pester!
