### ISSUE TITLE
[Question - 1.12] Tree type override?

### ISSUE THREAD

**Issue by Deightine** [ferreusveritas/Dynamic-Trees#127]
I have been rather impressed with the simplicity of Dynamic Trees since trying it and I want to integrate it into a pack I'm building out. But I'm having issues matching it up with the themes in my worldgen, because it's a post-apocalypse pack.

Is there currently some way of configuring DT to allow only a single type (or a small set of types) of trees to spawn during world gen?  I'm using Biomes o'Plenty and Thaumcraft 6 with the DT compats for both, and I want my overworld dimension to _only_ spawn with Dead Trees, while players are still capable of planting seeds for other trees from BoP/TC/DT.

I keep staring into the DT config and feel like I'm missing something obvious. My goal is to make seeds/acorns/saplings and so on into a key treasure commodity, since its a blasted, poisonous hellhole.

**Comment by ghost** [comment]
I can appreciate what you're trying to achieve but at the moment Dynamic Trees doesn't have this capability.  I do plan to add something like this eventually.  What I might suggest for the time being is to make the entire dimension a BoP wasteland biome.  It sounds pretty much like what you're after anyway with dead trees and poison pools.  Use a drop modifier mod to add acorns to dungeon chests or as a rare mob drop.

Edit:  If you want to experiment you can open up the Dynamic Trees jar file and delete all of the JoCodes from the text files for each tree you don't want to spawn.  Don't delete the files themselves. Just erase all of the lines in them and save it.  This will only prevent them from spawning though.  It won't replace the trees in the world with another tree.

**Comment by Deightine** [comment]
Thank you for the info. :) 

Yeah, I was afraid that having to rely on Wasteland would be the only way to pull it off. Unfortunately it gets a little monotonous to look at after awhile, since it has poor hill variety, etc. 

The core of the pack is running off of Lost Cities, interspersing cities with wasteland and other biomes that normally BoP doesn't spawn trees into. This was working great but I've been noticing that with DT in, it's spawning Dynamic Oaks in places where some different biomes touch despite both being modified in BoP to prevent tree generation. (Edit: Also, Greatwood/Silverwoods spawning randomly about the world). These aren't an issue with DT in my opinion, but a place where cross-mod interaction is getting weird.

Seeing if a master override could be set in DT first was an attempt to eliminate cross-mod generation problems by cutting the head off the snake. Since your mod is so clean and can already override vanilla tree generation, it seemed the right place to start in this use-case. Next step will be overhauling BoP at a higher level, which is going down a rabbit hole of json configs.

Thank you for all you do in contributing this mod to the community, by the way. I read back through your issue tracker before posting and was really impressed with your engagement with people asking questions, making requests, etc. I look forward to seeing where your vision takes the mod. :)

**Comment by ghost** [comment]
DynamicTrees-Control mod created to provide this functionality.
