### ISSUE TITLE
Language naming conflicts

### ISSUE THREAD

**Issue by TartaricAcid** [ferreusveritas/Dynamic-Trees#128]
Dynamictrees mod's I18n don't have namespace, and have some conflicts with other mods 
>  `item.staff.name`
> abyssalcraft: `Staff of The Gatekeeper`
> dynamictrees: `Woodland Staff`
> roots: `Staff`

I think the forge doc can help your: <https://mcforge.readthedocs.io/en/latest/concepts/internationalization/#usage-with-blocks-and-items>
> Unlike registry names, translation keys are not namespaced. It is therefore highly recommended to prefix your modid somewhere to the translation key (e.g. examplemod.example_item) to avoid naming conflicts. Otherwise, in the event of a conflict, the localization of one object will override the other.

And I submit the same issues in https://github.com/Shinoow/AbyssalCraft/issues/296

**Comment by ghost** [comment]
Fixed in dev
