### ISSUE TITLE
[0.7.2c] World/Server Freezes at Specific Coordinates

### ISSUE THREAD

**Issue by kulkalkul** [ferreusveritas/Dynamic-Trees#129]
How to reproduce:
Version: 1.7.10-0.7.2c
Seed: 1093744196215899990
Coordinates: -24, 111, -529

If you directly teleport to the coordinate, chunks do not load. If you fly towards it, some of the chunks load but then it freezes. I don't think the problem occurs at the coordinate, it's probably towards Z -650.

I tried this on both my PC and dedicated server. I don't think it's hardware related etc.

As everything freeze, it does not cover anything. But still, I'm including the log for archival purposes.

https://wastebin.party/ehiqagodod.md

**Comment by ghost** [comment]
I'm sorry.  1.7.10 is no longer maintained or supported.

**Comment by kulkalkul** [comment]
Still, do you have any ideas on why it might happen? I might try to avoid it or patch it.

**Comment by ghost** [comment]
I can't think of anything.  1.7.10-0.7.2c has been around for a while and has been more or less rock solid.  I played with it for a long time and never had anything like that happen. No similar bug reports were ever submitted for this issue.  Depending on your technical ability you could set it up in a dev environment and see where it hangs.  Also rule out mod interaction by testing with only Dynamic Trees installed.

**Comment by kulkalkul** [comment]
I will try, thanks!
