### ISSUE TITLE
[1.12.2] Lighting

### ISSUE THREAD

**Issue by BuilderDan** [ferreusveritas/Dynamic-Trees#13]
Hello,

Getting this lighting glitch when the base of trees are next to blocks:

![image](https://user-images.githubusercontent.com/19805371/32127184-e4f521fe-bb29-11e7-829d-94418002de4e.png)

![image](https://user-images.githubusercontent.com/19805371/32127199-fcf84de4-bb29-11e7-8ce4-f5fa97aea4f7.png)

**Comment by ghost** [comment]
I have this listed in the known bugs list on the curse description page.  You get this with optifine installed.  If anyone has any tips on why this happens then please let me know.

**Comment by ghost** [comment]
Enabling ambient occlusion on the branch model seemed to fix this.  Should be fixed in the next release.
