### ISSUE TITLE
[Compatibility Issue] Pam's Harvestcraft

### ISSUE THREAD

**Issue by gustavosouza1997** [ferreusveritas/Dynamic-Trees#131]
Hi, I'm using your mod with Pam's and it still generates the Pam's fruit trees using vanila wood instead of the branches from Dynamic Trees. There are any possibilitie to create an addon like the one for Thaumcraft and Traverse that also allow the sapplings to grow like the one from Dynamic?

Minecraft Version: 1.12.2
Forge Version: 14.23.4.2760
Pam's HarvestCraft: 1.12.2z
DynamicTrees: 1.12.2-0.7.8

![sample](https://user-images.githubusercontent.com/11525501/45602741-8be78000-b9f9-11e8-8180-bcf434a89e3b.png)

**Comment by ghost** [comment]
https://github.com/ferreusveritas/DynamicTrees-PHC
It's not quite ready yet but it's nearly finished.

**Comment by gustavosouza1997** [comment]
Do you mind to say if there is any ETA for the mod release?

**Comment by ghost** [comment]
No ETA.  I thought I would get it done this weekend if that's any indication of how close it is to being finished.

**Comment by gustavosouza1997** [comment]
Thank you, I'll wait the release.
