### ISSUE TITLE
Suggestion: Tree Oredict

### ISSUE THREAD

**Issue by IdrisQe** [ferreusveritas/Dynamic-Trees#134]
Simple suggestion this time: It would be nice if the dynamic branches were registered to the oredictionary as logWood, or if you'd prefer, to avoid them showing in crafting recipes, instead make them "treeWood" or something.

This would allow much faster config editing, for say, if I was using a mod like No More Punching Tree, which has a config like so:
```
# Configuration file

general {
    # The list of wood/log that cannot be broken with your hand. [default: [ore:logWood]]
    S:Wood <
        ore:logWood
     >
}
```
With the current system I need to get the individual block names for each branch type individually and input them, which, with addons, amounts to quite a bit.
```
dynamictrees:oakbranch
dynamictrees:sprucebranch
dynamictrees:birchbranch
dynamictrees:junglebranch
dynamictrees:acaciabranch
dynamictrees:darkoakbranch
dynamictreesbop:magicbranch
dynamictreesbop:umbranbranch
dynamictreesbop:firbranch
dynamictreesbop:cherrybranch
dynamictreesbop:deadbranch
dynamictreesbop:jacarandabranch
dynamictreesbop:willowbranch
dynamictreesbop:hellbarkbranch
dynamictreesbop:pinebranch
dynamictreesbop:palmbranch
dynamictreesbop:mahoganybranch
dynamictreesbop:ebonybranch
dynamictreesbop:bamboobranch
dynamictreesbop:eucalyptusbranch
dynamictreestc:greatwoodbranch
dynamictreestc:silverwoodbranch
```
and that's before I even think to install the WIP Pam's Addon once it's ready...

**Comment by ghost** [comment]
The Pam's Addon will only have 3 new dynamic branches, the rest will be vanilla variants that you already have in your list.  If I did add an ore entry it might be something like "ore:dynamicBranch".  However I'd have to have a more compelling reason to add this since I'm not convinced that this won't cause problems elsewhere.

**Comment by IdrisQe** [comment]
Hmmm... Fair enough. I don't get why ore:dynamicBranch would cause issues unless another mod used that very specific name (and even then, since you can't obtain dynamic branches it shouldn't be an issue) but it's good to know that the Pam's addon is light.
That said, this isn't an issue (for me, anyway) anymore since I modded a mod to let me just put:
dynamictrees*:*branch and get them all at once.

And since I can't think of a particularily compelling reason aside from convienience, I think I'll just close this here.

**Comment by ghost** [comment]
I'm not saying "no".. I'm just holding off on it until I can learn more.
