### ISSUE TITLE
Dynamic Tree Spawn Issue (Again)

### ISSUE THREAD

**Issue by IdrisQe** [ferreusveritas/Dynamic-Trees#137]
I honestly don't know what could possibly be the cause this time. I have no structure mods installed. I'm pretty certain the only mods I do have that add structures are Thaumcraft, and Immersive Engineering. There were no Thaumcraft structures around, and IE only generates stuff in villages, yet my Dynamic Tree spawning has been very inconsistent.

Despite having the Thaumcraft addon, it seems many Thaumcraft Magical Forests don't have any Dynamic Trees spawning inside them, despite other Thaumcraft Magical Forests working perfectly fine with DT.
I've seen a few other cases of trees not spawning right in a few BOP biomes but I'm not sure if that is intentional or not. This is especially weird since unlike the Recurrent Comples Roofed Forest issue, this one happens sometimes, but doesn't happen other times, with seemingly no rhyme or reason.
<details>
<summary>images</summary>

![2018-10-01_02 40 22](https://user-images.githubusercontent.com/40530630/46283206-9c831480-c528-11e8-9962-0b55770ae652.png)
![2018-10-01_02 40 40](https://user-images.githubusercontent.com/40530630/46283207-9d1bab00-c528-11e8-9816-283e4079f5bb.png)
![2018-10-01_02 40 47](https://user-images.githubusercontent.com/40530630/46283208-9d1bab00-c528-11e8-99cb-d009f777e296.png)
![2018-10-01_02 41 24](https://user-images.githubusercontent.com/40530630/46283209-9d1bab00-c528-11e8-9c71-f5a1e86c7e83.png)
![2018-10-01_02 41 26](https://user-images.githubusercontent.com/40530630/46283210-9d1bab00-c528-11e8-8d9b-e2b213bedeb2.png)
![2018-09-29_02 29 58](https://user-images.githubusercontent.com/40530630/46283211-9db44180-c528-11e8-8331-92c864b52200.png)
![2018-09-29_02 30 49](https://user-images.githubusercontent.com/40530630/46283212-9db44180-c528-11e8-81e4-418be36a347d.png)
</details>

Edit: Put pictures in details to remove clutter.

**Comment by Deshiba** [comment]
A full mod list with versioning would be helpful in these kinds of issues.

**Comment by IdrisQe** [comment]
I didn't want to spam a wall of mods but okay, here's my list in full, categorized into things that I know add or alter worldgen in some way, things that might, and things which probably don't (with a few exceptions that add single ores that I've disabled)

<details>
<summary>Modlist:</summary>

```
Definitely Affect/Add Worldgen:
Bamboozled 1.1.0
Biomes O Plenty 7.0.1.2399
Chisel 0.2.1.35 (worldgen disabled)
Dynamic Trees 0.7.8
Dynamic Trees BOP 1.2
Dynamic Trees TC 1.1.0
Exotic Birds 2.1.0
Hunger Overhaul
Immersive Engineering 0.12-85
Immersive Petroleum 1.1.9
Mowzie's Mobs 1.4.2
Muon 0.2
Ore Stone Variants 4.1
Pam's Harvestcraft 1.12.2z
Rustic 1.0.9
Streams 0.4.4
Thaumcraft 6.1.BETA24
Quark r1.5-130
Waystones 4.0.63
Weeping Angels 21
Worley Caves 1.3.0

May Affect Worldgen:
ClientTweaks 2.0.43
Farseek 2.3.1
Foamfix 0.10.2
Inspirations 0.2.2
RandomTweaks 2.1.5.0
RandomPatches 1.6.0.1
Repose 1.6.1
VanillaFix 1.0.9-97
VanillaTweaks 1.3.6

Shouldn't Affect/Add Worldgen:
Alternating Flux 0.12.2-1
Antique Atlas 4.4.9
Angel of Vengeance 0.8.14
AppleCore 3.1.4
AppleSkin 1.0.9
AppleJuiceSkin 1.0.0.4
AtlasExtras 1.3
AttributeFix 1.0.1
AutoRegLib 1.3-20
Backups 1.4.2
Baubles 1.5.2
BetterCombat 1.5.6
BetterFPS 1.4.8
BetterPlacement 1.0.0-1
BetterRecords 1.5.8
Bloodmoon 1.5.3
Bookshelf 2.3.560
Bullseye 3.0.6
Caliper 1.1.36
Camoflague Creepers 1.6
Cathedral 1.9.7g
Ceramics 1.3.4
ColorChat 2.0.43
Colytra 1.1.0
Comforts 1.3.0
Consecration 0.0.10
Controlling 3.0.6
CookingForBlockheads 6.4.65
CoroUtil 1.2.13
Corpse Complex 1.0.2.2
CosmeticArmorReworked 1.12.2-v3
Crowmap 1.1.0
CTM 0.3.2.18
Curse Silence 1.1
CustomBackgrounds 1.1.1
CustomMainMenu 2.0.8
Dynamic Surroundings 3.4.9.16
ElytraBoost 2.0.0.0.0
EmptyHand 0.1.0-1
EnchantingPlus 5.0.168
Engineer's Doors 0.7.2
Enhanced Visuals 1.12.2
Extra Alchemy 0.3.8.5
Third Person Camera Fix 1.2
Familiar Fauna 1.0.10
FancyBlockParticles 2.4.0
FarmingForBlockheads 3.1.26
FastFurnace 1.1.0 (Added after issue started)
FastWorkbench 1.5.3 (Added after issue started)
FindMe 1.0.2-6
Fists Of Flesh 1.3.1 (I made this, can confirm it doesn't affect worldgen)
Shadowfacts' Forgelin 1.7.4
Fullscreen Windowed 1.6.0
Giacomo's Foundry 1.3.13
Hardcore Darkness 2.0
Hardcore Revival 1.1.8
Hooked 1.0.3
HorseTweaks 1.0.4
Immersive Tech 1.3.10
Instant Unify 1.1.2
Inventory Tweaks 1.63
ItemPhysics Lite 1.3.7
JEI 4.12.1.217
JER 0.8.9.48
K4Lib 2.1.81
LibrarianLib 4.15
LLibrary 1.7.15
MAGE 0.2.3
Mantle 1.3.2.24
MetalChests v3.5.6.g296a413
MouseTweaks 2.8
Nether Chest 0.2.3
Nether Portal Fix 5.3.17
No More Glowing Potions 1.0
No More Recipe Conflict 0.11
No Nausea 1.0
No Nightvision Flash 1.2.0.3
No Slow 1.0.0
Optifine 1.12.2 HD_U_E2
Outfox 0.1.3
Overpowered Armor Bar 0.3.2
Shield Parry 1.0hotfix
Passable Leaves 2.0.0
Ping 1.4.4
Placebo 1.4.1
Potion of Aiming 1.0.0
Power Drop 1.1.2
Primitive Crafting 1.2 (Added after issue started)
Primitive Mobs 1.1.6 Beta
Proportional Destruction Particles 1.2.0
Questionably Immersive 0.1.0
Quick Leaf Decay 1.2.4
Realistic Torches 2.1.1 (Added after issue started)
Redstone Paste 1.7.5
ResourceLoader 1.5.3
Roost 1.2.0
RS Gauges and Switches 1.0.2
Rustic Thaumaturgy 2.4
Scaling Health 1.3.28-129
Schematics 1.12.2.12
Serene Seasons 1.2.6
Server Password 1.6.8R
SilentLib 3.0.5-152
SmartHUD 2.0.2
SmoothFont 1.16
Rin's So Many Enchantments 0.3.1
Sophisticated Wolves 3.13.4
Sound Filters 0.10
StepUp 1.0.2
Swing Through Grass 1.2.3
Survival Additions 1.1.1
Survivalist's Brush 0.4
Tails 1.10.0
TamModized 0.15.5
TAN Campfire Spit 1.3
TC6 Aspects for JEI 0.0.2a
Thaumic JEI 1.5.3-20
Thaumic Periphery 0.2.4
Tick Dynamic 1.0.1
Toast Control 1.7.1
Tomb Many Graves 4.2.0
Adventurer's Toolbox 0.2.12
Toolbox Addons 1.3
ToroHUD 1.12.2-3 (Added after issue started)
Totem Expansion 1.2.2
Unlimited Chisel Works 0.2.0
WallJump 1.1.6
Wearable Backpacks 3.1.3
Wings 1.0.6
Wither Skeleton Tweaks 2.6.1
World Tooltips 1.2.7-102
Zombie Awareness 1.11.14
```

</details>
Edit: Should now be slightly less of a wall of text.

**Comment by naqaden** [comment]
@IdrisQe
<details>
<summary>Here's a way to collapse a wall of text:</summary>
&#60;details&#62;<br>
&#60;summary&#62;Here's a way to collapse walls of text:&#60;/summary&#62;<br>
Wall<br>
of<br>
text<br>
here<br>
&#60;/details&#62;<br>
</details>

**Comment by ghost** [comment]
@IdrisQe Could you make a few screenshots next to the "vanilla" trees with your F3 HUD being displayed?  I would like to know for certain the name of the biome this is happening in.

**Comment by IdrisQe** [comment]
Of note: I've updated DT to 0.8.2 and the addons for BOP (1.3.2), TC (1.1.2), and Rustic (1.0.12) as of just before this post. As such, the screenshots I'll get will be of these versions.
...Just a moment, I need to deal with a crash from another mod before I get these pictures.

**Comment by IdrisQe** [comment]
Huh.
The biome was "Magical Forest" from Thaumcraft (id: thaumcraft:magical_forest)
But it seems in 0.8.2 this bug no longer occurs. I've been to three or four Magical Forests now and every tree is Dynamic. And in that same world, part of the Magical Forest that I hadn't generated, when I went that way, did generate as Dynamic now. so... This doesn't appear to be a problem anymore, for reasons that are beyond me. Presumably one of the changes in the Falling Trees update fixed it.

**Comment by ghost** [comment]
Resolved in latest release
