### ISSUE TITLE
[Request] Seed planting should work thru snow/plant blocks.

### ISSUE THREAD

**Issue by Tokeli** [ferreusveritas/Dynamic-Trees#138]
Forge: 14.23.4.2760
Dynamic Trees: 1.12.2-0.8.1i

Currently, right-clicking seeds and acorns on the ground does not work if there is any vanilla plant cover or snow layers in the way. It would be nice if it detected these and checked the block beneath for viability.

~~I'm also assuming that naturally-planted seeds behave the same way, which prevents natural forest spread in snow biomes- as I haven't seen any baby trees around.~~

Edit: Upon actual testing I can see that they actually *do* plant thru grass when done naturally, so nevermind about that portion!

**Comment by ghost** [comment]
Good catch.  I never noticed that.  I'll see what I can come up with.

**Comment by kierajreed** [comment]
In Minecraft some blocks can be placed into grass and replace it IIRC.

**Comment by naqaden** [comment]
I use a mod to apply a similar concept to combat. It only works if there is an enemy on the other side of the grass but maybe it's a useful reference: https://github.com/Exidex/SwingThroughGrass
