### ISSUE TITLE
[Bug] [Also Suggestion] Cocoa Beans and Mod Support

### ISSUE THREAD

**Issue by GazbonicAcid** [ferreusveritas/Dynamic-Trees#14]
[MinecraftForum](https://minecraft.curseforge.com/projects/dynamictrees?comment=251)

A)

Vanilla cocoa beans don't work on dynamic tree's jungle trees.

B)

I'd say adding support for non-vanilla modded trees is *not* outside of the scope of this mod.

Why?

THEY'RE TREES!!!

I request that at the very least you add the ability for pack/mod makers to add other mods' trees themselves.

All you'd really have to do is have three to four things in config.

1) Log texture.

2) Leaf texture.

3) Tree-gen algorithm.

4) Drop configs for what block(s) to drop. Depending on how you handle 1 and 2 you may or may not need to add this config option.

**Comment by ghost** [comment]
A.) Vanilla cocoa beans work on Dynamic Jungle trees when the trunk grows to a full block.  They also spawn randomly on fully mature jungle trees.

B.) Non-Vanilla trees are outside the scope of the base mod and that's all there is to it.  I've stated that other trees should be implemented in an outside mod.  It's very much my intention to allow other mod makers to easily add trees.  I've been working to make the API clean, workable, and concise but it's not yet ready.  I have a example expansion tree mod that I wrote for 1.10.2 that I will soon polish and port up to 1.11.2 and 1.12.2.  If I can make trees definable via JSON files then I'll take a stab at it but that'll be after the API is finished anyway.
