### ISSUE TITLE
[Suggestion] Compatibility with Cubic Chunks

### ISSUE THREAD

**Issue by ZephaniahNoah** [ferreusveritas/Dynamic-Trees#140]
![2018-10-07_16 49 19](https://user-images.githubusercontent.com/14168013/46588425-03388e80-ca51-11e8-925b-18f44019cfd8.png)
No trees generate.

**Comment by ghost** [comment]
I just noticed that [Open Cubic Chunks](https://minecraft.curseforge.com/projects/opencubicchunks) was release on curseforge as an alpha not but 22 hours ago.  Is this the mod you're talking about?

**Comment by ZephaniahNoah** [comment]
Yes. That is the mod.

**Comment by ghost** [comment]
Add-on was created by the cubic chunks author to make this work.
