### ISSUE TITLE
[Maven] DynamicTrees Maven Repo

### ISSUE THREAD

**Issue by Raycoms** [ferreusveritas/Dynamic-Trees#141]
Hey, is there a DynamicTrees maven repo we can access in order to code compatibility between Dynamic trees and Minecolonies?

If you have none we could help you with setting it up as well.

**Comment by ghost** [comment]
There isn't one.  I would appreciate the help setting it up as I've never done that before.

**Comment by Raycoms** [comment]
I'll check back with the guy who is responsible for our infrastructure including maven, do you have a discord where we could reach you, that'd be easier than via this thread here.

**Comment by ghost** [comment]
I mill about on Mangoose's mods discord: https://discord.gg/GZBVVEj
