### ISSUE TITLE
Trees not dropping any seeds

### ISSUE THREAD

**Issue by wilbowma** [ferreusveritas/Dynamic-Trees#144]
Running:
- Minecraft 1.12.2
- Forge 14.23.5.2768
- Dynamic Trees 0.8.2
- Traverse 1.6.0-69
- Dynamic Tree for Traverse 1.2
- Rustic 1.0.12
- Serene Seasons 1.2.4
- Passable Leaves 2.0.0

and other mods that are hopefully unrelated.

Trees work fine, and the new tree felling mechanism is fun, except trees don't seem to be dropping any seeds over time. ~I'm going to try downgrading to 0.7.8 and report back.~

Downgrading to 0.7.8 didn't help.

**Comment by Deshiba** [comment]
I'm guessing this is a configuration option not set. There should be a line in your config file, can you check if it's not set to 0?

seedDropRate = config.getFloat("dropRate", "seeds", 1f/8f, 0, 1, "The rate at which seeds voluntarily drop from branches");


If you meant that trees don't drop seeds when you harvest them, better wait for the dev.

**Comment by wilbowma** [comment]
No, seeds drop when I harvest trees, just not while they're alive.

The configuration option looks right to me:
```
seeds {
    # The rate at which seeds voluntarily drop from branches [range: 0.0 ~ 1.0, default: 0.25]
    S:dropRate=0.25

    # The rate at which seeds plant themselves in their ideal biomes [range: 0.0 ~ 1.0, default: 0.125]
    S:plantRate=0.125

    # Ticks before a seed in the world attempts to plant itself or despawn. 1200 = 1 minute [range: 0 ~ 6000, default: 1200]
    I:timeToLive=1200
}
```

0.7.8 was working for me in an earlier world, so there must be some conflicting mod that I've added. Any thoughts where I should start looking?

**Comment by ghost** [comment]
What other mods did you install or upgrade since the time it was working in the 0.7.8 world?

**Comment by wilbowma** [comment]
The ones listed above seem most related: Traverse, Rustic, and Serene Seasons.
Oh, Passable Leaves might be related too; will add that to the list.

I've also added Twilight Forest, Spartan Shields, Millenaire, Improve Backpacks, Journey Map, Open Modular Turrets, Recycler, Hwyla, Wawla, maybe some others. All these seem pretty unlikely to conflict, though.

**Comment by wilbowma** [comment]
Okay, found the problem: Passable Leaves is incompatible (which makes sense). I've disabled it.
