### ISSUE TITLE
SpongeForge server Don't drop after break tree.

### ISSUE THREAD

**Issue by yaroslav4167** [ferreusveritas/Dynamic-Trees#147]
SpongeForge : 1.12.2-2768-7.1.2-RC3487                                                                                                                                      Minecraft Forge : 14.23.5.2768 
DynamicTrees: 1.12.2-0.8.2

I [openned](https://github.com/SpongePowered/SpongeForge/issues/2448) issue in git spongeForge, but they never answered.
ServerLog after break tree: [https://hastebin.com/oxohuhumah.hs](https://hastebin.com/oxohuhumah.hs)

**Comment by ghost** [comment]
Whatever you have set up it looks like it blocks entity spawns for whatever reason.

**Comment by yaroslav4167** [comment]
In sponge 7.1.3-RC3495 bug don't reproduced.
Problem solved! =)
