### ISSUE TITLE
Vanilla Trees Still Spawn Alongside Dynamic Trees

### ISSUE THREAD

**Issue by bellyrose** [ferreusveritas/Dynamic-Trees#150]
![desktop screenshot 2018 10 27 - 09 37 15 100](https://user-images.githubusercontent.com/34819855/47604759-ee09ac80-d9cb-11e8-9862-974b4fd738ed.png)
Not sure if this is intentional but I want to only have dynamic trees with no vanilla trees.

**Comment by kierajreed** [comment]
Mod list?

**Comment by ghost** [comment]
Are you using the Traverse add-on?

**Comment by bellyrose** [comment]
> 
> 
> Mod list?

![modlist](https://user-images.githubusercontent.com/34819855/47612219-4da79c80-da4c-11e8-92ee-50fe2e87950e.PNG)
Here's my current modlist, Biomes o' Plenty and the Diverse Trees addon for it are disabled.

**Comment by Deshiba** [comment]
Can you take a screenshot of that area of F3 open?

**Comment by aycfes** [comment]
the problem's OTG, as manny of the biome packs (such as Biome Bundle) include custom trees, and those aren't compatible with dynamic trees, as in, they end up like vanilla ones.
if you don't want vanilla trees, i recommend you remove Biome Bundle or replace it with another biome pack that has DT support.

also, i've used OTG and Biome Bundle with BOP for quite a while, and never ran into crashes (at least not ones related to that, i tend to make some ridiculously large packs...) so don't worry that much about it.

**Comment by bellyrose** [comment]
> 
> 
> Can you take a screenshot of that area of F3 open?

I tried to but all of my worlds started crashing from what I assume was me enabling and disabling mods and loading worlds a bunch.


> 
> 
> the problem's OTG, as manny of the biome packs (such as Biome Bundle) include custom trees, and those aren't compatible with dynamic trees, as in, they end up like vanilla ones.
> if you don't want vanilla trees, i recommend you remove Biome Bundle or replace it with another biome pack that has DT support.
> 
> also, i've used OTG and Biome Bundle with BOP for quite a while, and never ran into crashes (at least not ones related to that, i tend to make some ridiculously large packs...) so don't worry that much about it.

That did seem to be the problem; after making a new MultiMC instance and using the same modlist except with Biomes o' Plenty instead of OTG and Biome Bundle, everything seems to work fine now.

**Comment by straef** [comment]
![annotation 2018-12-19 144537](https://user-images.githubusercontent.com/20950411/50247596-ee0ba480-039d-11e9-8786-c0ad58169f0b.jpg)

in a brand new world with no other mods installed and i am getting a mixture of dynamic trees and vanilla trees. it seems the small trees that spawn with leaves touching the ground like are generated in the jungle are the ones that are vanilla.

world seed:-8787506139940303180
world gen options are default
![image](https://user-images.githubusercontent.com/20950411/50249849-d08e0900-03a4-11e9-8f81-fbdc9d59208c.png)


screenshots:
![2018-12-19_14 21 17](https://user-images.githubusercontent.com/20950411/50249267-1ba71c80-03a3-11e9-84c1-208206c3364a.png)
![2018-12-19_14 21 22](https://user-images.githubusercontent.com/20950411/50249268-1ba71c80-03a3-11e9-97bc-1315a4af0a44.png)

**Comment by ghost** [comment]
This is intentional as those small bushes are just decoration to break up the jungle floor.

**Comment by straef** [comment]
good to know
