### ISSUE TITLE
Tinkers' Lumberaxe Fails to Chop Down Trees

### ISSUE THREAD

**Issue by Avakining** [ferreusveritas/Dynamic-Trees#151]
When using a Tinkers' Construct lumberaxe, the tree chops at the same speed as punching.

**Comment by kierajreed** [comment]
Mod list?

**Comment by Avakining** [comment]
Here:
[modlist.txt](https://github.com/ferreusveritas/DynamicTrees/files/2532646/modlist.txt)

**Comment by aycfes** [comment]
why would you even use the lumberaxe, tho?

**Comment by ghost** [comment]
Using a lumberaxe to cut dynamic trees doesn't make sense.  Just use a regular axe.  Whatever tinkers construct is doing seems to be complicating things and I don't think I can support it.
