### ISSUE TITLE
When I cut the tree, the game crash

### ISSUE THREAD

**Issue by HappySheepAndWolf** [ferreusveritas/Dynamic-Trees#157]
[crash-2018-11-06_08.56.05-client.txt](https://github.com/ferreusveritas/DynamicTrees/files/2551233/crash-2018-11-06_08.56.05-client.txt)
I may have added so many Mods that I don't know which mod caused the conflict, but I can be sure that I did crash the game when I cut a tree empty-handed. The mod version I used was Dynamic Trees-1.12.2-0.8.2, and Forge was 1.12.2-forge 1.12.2-14.23.5.2772.

**Comment by Deshiba** [comment]
Just a small tip. You have 66 mods active. Unless there's a clear culprit, someone would have to be bored to test these mods for you.

To speed things up you could try to find the culprit by splitting your mod list in half and run it with dynamic trees. Reproduce the steps you took to get the crash and see if it happens again. Take the half of the mods that still gives you issues and then rinse and repeat. This should get you to the mod(s) that are misbehaving fairly quickly.

**Comment by ghost** [comment]
Try running without Special AI mod.

**Comment by TheOrionsun** [comment]
I run 76 mods with this mod and the Biomes O' Plenty Compat mod plus tree chopper mod and I have no crashes. Tree chopper only works on Dynamic trees if you crouch... I chopped down a vanilla tree and a Dynamic tree with no crash. However, I don't have many of the mods you have listed...

**Comment by ghost** [comment]
Closing as non-productive issue
