### ISSUE TITLE
Allow to get nbt with ctrl

### ISSUE THREAD

**Issue by aycfes** [ferreusveritas/Dynamic-Trees#158]
Similar to how you can get a chest with its contents using Ctrl middle click in creative, allow us to get dynamic logs with the varying thicknesses

(Sorry for the bad elaboration)

**Comment by Deshiba** [comment]
Afaik the thickness and build of a tree isn't contained in the branches and logs themselves but in the rooty soil. If that is the case then implementing this would require a rewrite of the entire mod.

But I'm not a coder so wait for the official response from the devs.

**Comment by aycfes** [comment]
Well, I mess with the trees all the time, and I frequently end up with floating branches, that retain all of their characteristics, even if I break the rooty soil.

I believe that the rooty soil has the instructions for that, but the thickness, species, and related information is stored in the block itself.

You can easily alter the way the tree grows by putting new branches in manually, even from other species

**Comment by aycfes** [comment]
From what I can gather, the info in the block, as in, the code you get on the staff and such is just where each branches are and the species, all of the rest, like thickness and leaf arrangement is handled directly by the mod's algorithm.

But indeed, let's wait for ferreus

**Comment by ghost** [comment]
Just to clarify some things:
-Rooty dirt has no information other than the fertility of the soil(0-15).
-Branch blocks only hold the radial thickness of that single block(1-8).
-The woodland staff creates JoCodes which are Base64 encoded turns and forks of the tree structure with no reference to branch thickness, species or any leaf data whatsoever.

One method to build a custom tree in creative mode is simply use the branch block item to build the structure on a juvenile tree.  Then use the woodland staff on the structure to create a JoCode.  Then use the coded staff again on viable soil to create the custom tree structure with the proper thicknesses and leaves for that species.

I will not make the branch block items have encoded thicknesses.  Doing this would allow for creative mode players to create tree structures that were never intended and could potentially be buggy enough to even crash.  I've even considered removing the branch block items entirely for good measure.

You always have access to Minecraft's setBlock command if you want to defy all artificially imposed limits.  You assume the risk of your actions under these circumstances and any resulting crashes are your problem alone.  Consider yourself disclaimed.

**Comment by Deshiba** [comment]
Thank you for the clarification.
