### ISSUE TITLE
Computercraft turtles can't fell trees

### ISSUE THREAD

**Issue by Jummit** [ferreusveritas/Dynamic-Trees#160]
Simple issue: When a turtle performs a turtle.dig() on a dynamic trees trunk only the block the turtle targets gets destroyed, but the tree still stands. I am using CC-tweaked (from SquidDev), a maintained fork of CC.

**Comment by kierajreed** [comment]
This might be because the code is casting something to a player-related class, or using player-related events. Another cause could be if they use the `World` class to break blocks instead of using a player.

**Comment by SkyHawkB** [comment]
Or it may be an error in the way `Turtle.dig()` is made.

**Comment by ghost** [comment]
I always assumed that the computercraft turtle used a fake player.

**Comment by SkyHawkB** [comment]
They might just directly use `World`.

**Comment by Jummit** [comment]
The use fake players so permissions work. I was wondering too, why that doesn't work.

**Comment by SkyHawkB** [comment]
```
public class TurtlePlayer extends FakePlayer {
```
Yep. But something is breaking somewhere.

**Comment by ghost** [comment]
So here's the problem:

https://github.com/dan200/ComputerCraft/blob/914df8b0c7cc28451ea56a53808024511ff52642/src/main/java/dan200/computercraft/shared/turtle/upgrades/TurtleTool.java#L290 

Even though it makes a fakePlayer it's not used to destroy the block.

**Comment by kierajreed** [comment]
So how should this be handled? Since it can also cause other issues with any code that uses `World`.

**Comment by ghost** [comment]
Might be worth trying now in the latest alpha on curseforge.

**Comment by ghost** [comment]
This works now but it does not work for thick trees.  Use turtle.suck() twice after turtle.dig() to obtain the dropped log and stick items.
