### ISSUE TITLE
Sand block under the cactuse bug

### ISSUE THREAD

**Issue by Zack7292** [ferreusveritas/Dynamic-Trees#161]
Hi there! i find a little texture bug when i walk on my little modded desert they are only under cactus modded by you beutifuls mod. the a link to my screen: [https://prnt.sc/lkheki](url)

**Comment by Deshiba** [comment]
This is probably a mod conflict. Which other mods do you have in your pack?

**Comment by ghost** [comment]
Duplicate of #118
