### ISSUE TITLE
[DT0.9.1a] ConcurrentModificationException

### ISSUE THREAD

**Issue by Voxel-Friend** [ferreusveritas/Dynamic-Trees#163]
Occurred when entering the nether.
Modlist: https://www.modlister.com/user/Voxel_Friend
Crashlog: https://gist.github.com/Voxel-Friend/19c3be4584ebdb561c20f2e32790d80d

**Comment by Voxel-Friend** [comment]
[latest.log](https://github.com/ferreusveritas/DynamicTrees/files/2612485/latest.log)

**Comment by ghost** [comment]
Do you think you could build from source and see if this fixes it?  I'm unable to reproduce the problem but I added a change for what I think is the most likely cause.

**Comment by Voxel-Friend** [comment]
OK, I'll give it a shot.

**Comment by Voxel-Friend** [comment]
Works like a charm
