### ISSUE TITLE
crash in the new version

### ISSUE THREAD

**Issue by aycfes** [ferreusveritas/Dynamic-Trees#164]
[crash-2018-11-25_18.37.03-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/2613495/crash-2018-11-25_18.37.03-server.txt)
this one has happened a few times, seems to be more common in places i've screwed the world generation with my modded shenanigans, but isn't dependent on it.

the last time it happened i saw a mohogany tree have all branches and the runk turn into the thinnest variant, just as the game froze and crashed. so it may have something to do with intake overflow or something like that (in my head, at least).

Ps: the modlist in already ingluded in the crash report, that counts, right?

**Comment by Lordbaane** [comment]
Heres mine for the same problem, try cutting down a cactus and got a crash.
https://paste.dimdev.org/dipoluwahi.mccrash

**Comment by straef** [comment]
[---- Minecraft Crash Report ----.txt](https://github.com/ferreusveritas/DynamicTrees/files/2613928/----.Minecraft.Crash.Report.----.txt)
i think this is the same or at least a similar crash as the others are experiencing. running the alpha so i can have the harvestcraft compatibility. i was picking up a fallen piece of harvestcraft tree fruit when the crash occurred.

swapped to the release build and playing that, removing the harvestcraft compatibility. with a very short play test picking up several pieces of harvestcraft tree fruit, no crashes.

**Comment by ghost** [comment]
Just uploaded a fix for this problem on curseforge available as version 0.9.1b.  Update DynamicTrees-BoP to latest as well if you're using it.

**Comment by Flyrija** [comment]
Will there be an update for Pam's Compat too?

**Comment by ghost** [comment]
The Pam's add-on is unaffected.

**Comment by Flyrija** [comment]
> The Pam's add-on is unaffected.

Thanks for the reply, will run my map with the changes then =)

**Comment by Voxel-Friend** [comment]
Lordbaane's crash is a different crash than OP's. Please create a seperate issue.
