### ISSUE TITLE
[Suggestion] Placing seedlings over existing grass

### ISSUE THREAD

**Issue by DarkYuan** [ferreusveritas/Dynamic-Trees#165]
Unlike vanilla saplings (or for example, torches) these can't be placed where tall grass already occupies. Seedlings should be allowed to replace grass when planted. Optionally, would that work with self-planting drops too?

**Comment by ghost** [comment]
This should be working in the latest alpha.

**Comment by DarkYuan** [comment]
Oh! My bad, didn't notice the alpha 2 days ago

**Comment by ghost** [comment]
Feature already implemented
