### ISSUE TITLE
Crash upon entering nether

### ISSUE THREAD

**Issue by BrokenDoop** [ferreusveritas/Dynamic-Trees#166]
Entering the nether results in instantly crashing, I don't know if its because i'm using the Biomes-O-Plenty support or not though.
I tried growing a tree in the nether and after 2 bone meal it disappeared, then my game crashed about 10 seconds after. Yeah, I just removed the BOP support mod and BOP itself and it still crashed, didn't crash after I removed the dynamic trees mod.

**Comment by ghost** [comment]
Fixed. Same as #163
