### ISSUE TITLE
yet another new bug (as far as i can tell, at least)

### ISSUE THREAD

**Issue by aycfes** [ferreusveritas/Dynamic-Trees#167]
[crash-2018-11-26_21.15.55-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/2617657/crash-2018-11-26_21.15.55-server.txt)
it happened when i brokea redwood tree's branches, twice. (using the newest version, the one with the intake overflow already fixed)

(i got no clue on how to tell if this isa problem with DT itself or with the BOP compat, so i'm posting it here, for now)

(modlist included in the crash report)

**Comment by ghost** [comment]
What do you mean broke it twice?

**Comment by ghost** [comment]
Fixed same as #168

**Comment by aycfes** [comment]
i mean, the bug happened twice, as in two separate times

sorry for being unclear
