### ISSUE TITLE
Replace oak trees in the Ice Plains/Ice Mountains with spruce trees

### ISSUE THREAD

**Issue by Forstride** [ferreusveritas/Dynamic-Trees#173]
Self-explanatory title.  Not sure what version that was changed in vanilla, but they shouldn't have oak trees.

**Comment by ghost** [comment]
Made any straggler vanilla biomes that are cold default to spruce.  Ice plains are classified as WASTELAND so they have no trees at all.  You may be seeing trees from bordering biomes for that one.
