### ISSUE TITLE
Found a crash between: Minestrappolation 5, Dynamic Trees and Primal mod

### ISSUE THREAD

**Issue by RodrigoTaipe93** [ferreusveritas/Dynamic-Trees#177]
Hello! There seems to be an issue with the following mods:

- Dynamic trees

- Minestrappolation 5

- Primal mod

I discovered this while I was in the Nether!

https://paste.dimdev.org/umoxokipaf.mccrash

**Comment by ghost** [comment]
Do you get this crash with 0.9.1e?  I fixed a bug that was related to the block break animation and concurrent modification exception.

**Comment by ghost** [comment]
Could not reproduce. Non-productive/Abandoned issue. Assuming fixed.
