### ISSUE TITLE
[1.12.2] WorldGen Crash

### ISSUE THREAD

**Issue by ruyanve** [ferreusveritas/Dynamic-Trees#18]
I know I did something that is not recommended, but I'll leave the crash here anyway just in case it's of any use. :-)

I wanted to see how your mod behaves when used in conjunction with OTG and Biome Bundle.
Some trees were generated dynamicly, while most were, as expected generated, by BB.

https://gist.github.com/ruyanve/3fa911692056f777f9aafb5fc8f655d5

Cheers

**Comment by ghost** [comment]
Looks like I overlooked something judging by the crash log.  I doubt it has much to do with your other mods.

**Comment by ghost** [comment]
Just to verify that I've received a similar crash related to handleRot; https://pastebin.com/NyY6vK3Q

Other than that crash, the world gen runs noticeably quicker and has less TPS lag on start up, so great job there!

**Comment by ghost** [comment]
I just released a fix and a new alpha version 0.7.1c on curseforge. This should fix the problem though It's a mystery to me how it could get into that state to begin with.  *shrug*
