### ISSUE TITLE
Suggestion: Root Blocks should turn back into the original type of grass fitting the biome.

### ISSUE THREAD

**Issue by SirAron111** [ferreusveritas/Dynamic-Trees#181]
Suggestion: Root Blocks should turn back into the original type of grass fitting the biome.

Atm the Grass changes to vanilla grass/dirt when the root block reverts. This kills immersion in all biomes that don’t use vanilla grass. But use biomes o plenty grass types or quark grass types.

Will also add this to the bop compat.

**Comment by ghost** [comment]
Fix in dev
