### ISSUE TITLE
Alpha 1.12.2-0.9.1e All Saplings show they will be removed when loading saved game?

### ISSUE THREAD

**Issue by TheOrionsun** [ferreusveritas/Dynamic-Trees#182]
Hello,

Not sure if item saplings get replaced with new items, but when I have the new Alpha release of Dynamic Trees 1.12.2-0.9.1e loaded, and load a previous version-save it says that all the saplings will be removed.

Have you changed the sapling items?

I realize this is an Alpha, so you may know of this?

Thank you for your time and your very cool mod!

TheOrionsun

**Comment by ghost** [comment]
Yes.  Instead of consuming a block for every tree species I unified all of the sapling blocks into one tile entity block.  The transient nature of saplings made this an obvious choice.  The warning of all the missing blocks is alarming but it's intended.

**Comment by TheOrionsun** [comment]
Awesome, I was hoping it was something like that...

Thank you for the quick response!

Thanks again for your time and your excellent mod,
