### ISSUE TITLE
Crash while Initializing Game

### ISSUE THREAD

**Issue by WenXin20** [ferreusveritas/Dynamic-Trees#183]
###  Mod Versions

- Forge **v14.23.5.2796-1.12.2**
- Dynamic Trees - BOP **v1.4.1e**
- Dynamic Trees - Climatic Biomes **v1.0.1**
- Dynamic Trees **v0.9.1f**
- Rustic **v1.0.14**

### Crash Report
I get **[this crash](https://paste.dimdev.org/opatileraz.mccrash)** while loading the game.

**Comment by HentaiHamster** [comment]
Oh i think I got this same exact error with the same set up...I opened my own issue with it...hopefully someone can figure it out.

**Comment by kierajreed** [comment]
Both of you have many other mods. Can you try reproduce the issue with only Dynamic Trees, Rustic, and the DT addons and share the results here?

**Comment by ghost** [comment]
This crash is related to resource packs.  It's caused by log blocks models that don't properly set a "cullface" in the model json.  Although the resource pack should fix this for performance sake this is my problem to fix since it shouldn't make my code crash.  As a simple work around just disable the offending resource pack until I can get it fixed.

**Comment by WenXin20** [comment]
Ok, thanks -----------------------Sincerely, David NewvilleOn Dec 24, 2018 11:03 PM, Ferreus Veritas <notifications@github.com> wrote:This crash is related to resource packs.  It's caused by log blocks models that don't properly set a "cullface" in the model json.  Although the resource pack should fix this for performance sake this is my problem to fix since it shouldn't make my code crash.  As a simple work around just disable the offending resource pack until I can get it fixed.

**Comment by HentaiHamster** [comment]
I dont get how it's a resource pack issue though. I've been using dynamic trees with my current set up this whole time and nothing has every crashed. The only thing I changed was I added in BOP and the compatibility file for it for Dyn Trees. And then I also switched to using the latest Alpha of Rustic and Dyn Trees.

**Comment by ghost** [comment]
Read my explanation more carefully.  I didn't say this was a resource pack issue.

**Comment by ghost** [comment]
0.9.1g should take care of this.
