### ISSUE TITLE
Missing Particle Error

### ISSUE THREAD

**Issue by MishkaG** [ferreusveritas/Dynamic-Trees#184]
Occurs when I go to plant a Spruce Cone - after I chop down a spruce.
Version 0.9.1f - Forge 14.23.5.2796

https://hastebin.com/qilevuyiro.cs

**Comment by MishkaG** [comment]
Occurs when I go to plant a Spruce Cone.

**Comment by kierajreed** [comment]
Please use [hastebin](https://hastebin.com/) for long logs and stack traces.

**Comment by ghost** [comment]
I don't see a crashlog. Can you see if you can fix that?

**Comment by MishkaG** [comment]
Sorry about that - was trying to reduce noise.

I just recreated it with 0.9.1g on a test world with reduced mods. Hopefully I do this right and this gives you more information.

[Crash Log](https://hastebin.com/iwikumiyur.cs)

**Comment by kierajreed** [comment]
There is still a lot of mods. Dynamic trees does a bunch of stuff that might break in large modpacks. I recommend binary-search testing to see which mod is causing the issue.

**Comment by MishkaG** [comment]
I'll recreate in isolation in a bit, but 18 is not a large mod pack (a few of those are a single jar with various registered components)... and the majority of those were incidentally added when I recreated the issue. They were absent when I originally performed the isolation test. 

Also, for clarity, if it helps - the error only occurs when planting a cone after chopping down a spruce... I can't recreate it under any other event.

Thanks for reviewing. I don't want to understate how amazing this mod is.
