### ISSUE TITLE
Small Problem with texture packs and thick trees.

### ISSUE THREAD

**Issue by SirAron111** [ferreusveritas/Dynamic-Trees#187]
Thick Trees don’t grab the textures not even in a stretched form or anything and will always turn to vanilla textures once the normal block size is overtaken. The roots will still use the textures from texture packs I made some pictures to show this.
![2018-12-26_15 21 18](https://user-images.githubusercontent.com/39855956/50449077-2b83ab00-0925-11e9-9f32-8fee7a1593b9.png)
![2018-12-26_15 21 03](https://user-images.githubusercontent.com/39855956/50449078-2b83ab00-0925-11e9-855a-3bc9c841c596.png)

**Comment by ghost** [comment]
This is an issue for the Dynamic Trees - Thaumcraft Add-on

**Comment by SirAron111** [comment]
Ye i posted it there to wasnt sure
