### ISSUE TITLE
Crash from Dynamic Trees without the mod?

### ISSUE THREAD

**Issue by MokahTGS** [ferreusveritas/Dynamic-Trees#189]
Getting a crash the calls out dynamic trees but we aren't using this mod.  Obviously something else is and its crashing.  Any idea what other mods use your code?

Crash Log: https://paste.dimdev.org/elabefepal.mccrash

Mod list: https://pastebin.com/0U0KZtTS

Forge Version 2779

**Comment by MokahTGS** [comment]
Found the issue: https://github.com/the-realest-stu/Rustic/issues/229

Rustic made DT a hard dependency without telling anyone and just for compatibility reasons.  **sigh**

**Comment by ghost** [comment]
It wasn't "without telling anyone" it was simply a mistake.
