### ISSUE TITLE
cc+dt= nether gen hanging

### ISSUE THREAD

**Issue by Redd56** [ferreusveritas/Dynamic-Trees#191]
exactly what it says, cubic chunks and dynamic trees dont work well together, nether generation just hangs forever for some reason, may need to do some digging for the issue

**Comment by ghost** [comment]
I'm pretty sure Barteks2x was working on a compatibility add-on to bridge the two mods.  Loading the nether without it will not work.  Check here: https://github.com/OpenCubicChunks/CubicDynamicTreesAddon

**Comment by Redd56** [comment]
I thought it was just too have them gen in custom cubic worlds

**Comment by ghost** [comment]
What version of DT are you running?  I don't see anything in the current DT generation code that would cause it to hang when you enter the nether.

**Comment by Redd56** [comment]
latest and one version back. ive tested it with 2 versions in fact

**Comment by Redd56** [comment]
and its the second you load chunks the server hangs...... idk why..,.

**Comment by Redd56** [comment]
without a chunk loaded at all its fine but the milisecond that it tries to load one it breaks... which is wierd

**Comment by pressRtowin** [comment]
This issue is still very much a thing. Just an update.

**Comment by Redd56** [comment]
Ill look at the code today and see if i see anything wonky

**Comment by pressRtowin** [comment]
worth noting that the issue only occurs with the Nether, not the End.

**Comment by Redd56** [comment]
Ik.
And thats the wierd thing.

**Comment by Redd56** [comment]
It may have to do with the nether being marked as subterranean

**Comment by Redd56** [comment]
its working? no more crash? hmm
