### ISSUE TITLE
boring jungles

### ISSUE THREAD

**Issue by Wolfram96** [ferreusveritas/Dynamic-Trees#194]
The jungle trees this mod adds are great, but sadly the understory seems so bland now. I'm not sure if its because the small jungle trees are missing, the thickness of the tall ones is reduced, or if it has less brushes, fact is it feels empty.

so my question does this mod just replace the trees or does it reduce lower lvl foliage as well?
Regardless, could more foliage be added?
I loved that jungles were a mess and this mod makes tham too neat for my tastes.

**Comment by ghost** [comment]
Jungles are going to be overhauled in the next version.
