### ISSUE TITLE
[Bug] Conjoined trees

### ISSUE THREAD

**Issue by Deshiba** [ferreusveritas/Dynamic-Trees#195]
When travelling trough my world I noticed that sometimes there are trees that have this narrow part on them. This happens when a branch intersects with a trunk of another tree. In this way the trees will be joined and they will both topple over when chopped down with an axe.

![2019-01-07_16 46 20](https://user-images.githubusercontent.com/10565800/50813676-72a37000-1317-11e9-9b32-afa22eae5e8f.png)
![2018-12-29_16 40 40](https://user-images.githubusercontent.com/10565800/50813681-746d3380-1317-11e9-96f8-d8f0cee5a868.png)

Both examples shown are with BOP trees, I'm not sure if it has ever happened with just DT.

**Comment by aycfes** [comment]
I have encountered this problem a few times too (and forced it to happen, in creative, but that doesn't count). Most of the time it involves mods, be it a new biome, bop trees, or a dimension like the twilight forest, but I think I've seen it once or twice with vanilla dynamic trees in vanilla biomes, etc.

**Comment by ghost** [comment]
This is a BoP add-on bug.  The pre-generated models were recorded with the incorrect generation radius.
