### ISSUE TITLE
dark oak/spruce trees refuse to grow.

### ISSUE THREAD

**Issue by majijn** [ferreusveritas/Dynamic-Trees#196]
![2019-01-09_16 09 22](https://user-images.githubusercontent.com/18368034/50909285-d0c17780-142b-11e9-875e-8f05378ae9cf.png)
I've just added this to the pack im playing, and dark oaks and spruce trees , which are the vanilla trees I was interested in growing with this mod  refuse to grow more branches/leaves after a certain point, plain oaks work fine, but If I transform the oak to a dark oak or a spruce it stops growing,

it doesnt matter if I bonemeal them , or if I use the growing potion , or if I set randomtickspeed to 3000, they dont budge.

I have rustic installed if that may be causing it or something =/ 

![2019-01-09_16 09 52](https://user-images.githubusercontent.com/18368034/50909513-488fa200-142c-11e9-9a35-cbaa49656b49.png)

**Comment by ghost** [comment]
The problem is that you're trying to grow them in the desert.

**Comment by majijn** [comment]
is that it? oh! fair enough! 

edit: sorry to bother you then!
