### ISSUE TITLE
Server Side Crash

### ISSUE THREAD

**Issue by CritFlaw** [ferreusveritas/Dynamic-Trees#197]
Forge 2796
Mod 0.9.3
Minecraft 1.12.2

Server crashes with this crash log https://hastebin.com/uqoxesubet.rb

**Comment by ghost** [comment]
Just curious.. Do you have worldgen disabled?

**Comment by CritFlaw** [comment]
I do. I want to give people the option of planting dynamic trees, but not having them generate in the world.

**Comment by CritFlaw** [comment]
Also, worth noting the crash doesn't happen with the previous version.

**Comment by ghost** [comment]
I know exactly what happened.  I've already fixed it in the dev version.  For now you can downgrade to the previous version since you won't really have any changes considering that you're running without world gen anyway.
