### ISSUE TITLE
Crash Report. Never Seen This One.

### ISSUE THREAD

**Issue by KillTest** [ferreusveritas/Dynamic-Trees#199]
I was making a private modpack but it crashed when I loaded the world. It said it had something to do with old leaf or something. BTW I used 1.7.10 because that was the only version that had LOTR and I experience heavy lagspikes and frequent fps drops when I use version 1.12.2. (Even when I chuck in every single performance-improving mods I could find and lower my video settings, it still won't go away.) I really like this mod and I really don't want to throw it in the trash bin. Plz help!
Anyways, here's the crash report and the log.
(BTW I know that it mentions Better Foliage but I am pretty sure the mod said that it was compatible with Dynamic Trees.)
[2019-01-14-7.log.gz](https://github.com/ferreusveritas/DynamicTrees/files/2755597/2019-01-14-7.log.gz)
[crash-2019-01-14_23.37.06-client.txt](https://github.com/ferreusveritas/DynamicTrees/files/2755601/crash-2019-01-14_23.37.06-client.txt)

**Comment by ghost** [comment]
Sorry, 1.7.10 is no longer supported and hasn't been for quite some time.
