### ISSUE TITLE
Light Bug on Thick Trees (Optifine)

### ISSUE THREAD

**Issue by Lordician** [ferreusveritas/Dynamic-Trees#200]
This issue was first seen in a Thaumcraft Forest where the vishrooms were right next to some greatwood thick trees.
![Image of Bug](https://media.discordapp.net/attachments/420010799545712643/535496974661713949/2019-01-17_17.31.38.png)
But after some testing, this also happens with non TC dynamic trees, like for example the thick dark oak trees.
High light levels do not seem to reproduce this bug but for example a redstone torch right next to the trees causes the same issue.

Versions:
Forge (recommended): 1.12.2 - 14.23.5.2768
Dynamic Trees: DynamicTrees-1.12.2-0.9.4
Dynamic Trees Thaumcraft: DynamicTreesTC-1.12.2-1.4.1e
Thaumcraft: Thaumcraft-1.12.2-6.1.BETA26
Optifine: OptiFine_1.12.2_HD_U_E3

No shaders, default settings on everything.
Generate a world, find or create any thick trees, put low level light (redstone torch) right next to thick tree.
Test images with dark oak & redstone torch:
![2019-01-17_19 06 08](https://user-images.githubusercontent.com/26574603/51338800-182eb000-1a8b-11e9-806d-c8992c48d982.png)
![2019-01-17_19 06 30](https://user-images.githubusercontent.com/26574603/51338806-1a910a00-1a8b-11e9-89cf-b2f361ba2931.png)

**Comment by ghost** [comment]
Thank you for such a concise and accurate bug report.  The images were most helpful and I can reproduce the problem easily.  I've tried everything I can think of and it looks to me like it's an optifine bug.  Likely related to the block models being much larger than a  single block, which is not something optifine typically deals with.  There's nothing I can do to fix the rendering aside from rewriting the entire way that blocks are done for thick trees, which I don't think is worth it.
