### ISSUE TITLE
Dynamic Trees Harvesting

### ISSUE THREAD

**Issue by MizuNomy** [ferreusveritas/Dynamic-Trees#201]
I've been trying to collect wood from the trees. Apparently I cannot get wood drop with bare hand breaking it. Only with axe. Any fix?

**Comment by Deshiba** [comment]
It would be helpful to include what version of Forge and Dynamic Trees you are using. Also a screenshot or list of the mods you are using would be useful in tracking down the issue.

Also Look at #110 If you are using any of the following mods that might be the issue;
Better With Mods
PrimalCore
No Tree Punching

Other mods might be the cause if you don't have any of these, hence the question for all the mods you use.

**Comment by ghost** [comment]
This is the result of interaction with a mod designed to prevent a player from using hands to break a tree.
