### ISSUE TITLE
Crash server of the mod "dttraverse-#.#"

### ISSUE THREAD

**Issue by SeagalKru** [ferreusveritas/Dynamic-Trees#202]
This crash version of the mod "dttraverse-1.4.jar":
[crash-2019-01-20_14.51.36-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/2776545/crash-2019-01-20_14.51.36-server.txt)
[server.log](https://github.com/ferreusveritas/DynamicTrees/files/2776546/server.log)
[latest.log](https://github.com/ferreusveritas/DynamicTrees/files/2776547/latest.log)

This crash version of the mod "dttraverse-1.5.jar":
[crash-2019-01-20_15.09.43-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/2776555/crash-2019-01-20_15.09.43-server.txt)
[server.log](https://github.com/ferreusveritas/DynamicTrees/files/2776557/server.log)
[latest.log](https://github.com/ferreusveritas/DynamicTrees/files/2776556/latest.log)

**Comment by SeagalKru** [comment]
Previous crash with version 1.4.
This crash version of the mod "dttraverse-1.5.jar":
[crash-2019-01-20_15.09.43-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/2776555/crash-2019-01-20_15.09.43-server.txt)
[latest.log](https://github.com/ferreusveritas/DynamicTrees/files/2776556/latest.log)
[server.log](https://github.com/ferreusveritas/DynamicTrees/files/2776557/server.log)

**Comment by ghost** [comment]
Update the dynamic trees BoP add-on.

**Comment by SeagalKru** [comment]
Made! Thank you!
