### ISSUE TITLE
"harvestMultiplier" - Config option and Hwyla

### ISSUE THREAD

**Issue by SSKirillSS** [ferreusveritas/Dynamic-Trees#204]
In main config file I'm had tried to change option from "S:harvestMultiplier=1.0" to "S:harvestMultiplier=2.0" (Line 83). Surprisingly, it works fine, but there is one flaw - When you hover the cursor on a tree, displayed  not the actual amount of wood that should fall, but the amount with the original configuration parameter.
Versions:
Forge - forge-1.12.2-14.23.5.2768
SpongeForge - spongeforge-1.12.2-2768-7.1.5-RC3526
DynamicTrees - DynamicTrees-1.12.2-0.9.4
Hwyla - Hwyla-1.8.26-B41_1.12.2

Screenshots:
After felling a tree - http://prntscr.com/maxsqs
Result - http://prntscr.com/maxt7m

**Comment by kierajreed** [comment]
I'll look through the code to find where this happens. I think it's a missing operation to update the number which can be easily fixed.

**Comment by Deshiba** [comment]
Seems like the multiplier isn't applied to the whyla read out.

**Comment by kierajreed** [comment]
It might be in `Species#getLogsAndSticks()` but I'm not sure.

**Comment by ghost** [comment]
Fixed
