### ISSUE TITLE
Help Understanding Config

### ISSUE THREAD

**Issue by VinterNacht** [ferreusveritas/Dynamic-Trees#205]
Could I get some assistance with the config file?  How would I slow the rate at which trees grow?

What is the difference between GrowthMultiplier and GrowthRateMultiplier, and how do they play together to affect tree growth rates on the server?

**Comment by kierajreed** [comment]
This is the place to report bugs with the mod. For help with the mod I recommend asking in the [official Discord](https://discord.gg/2wN8MKj) or in another modding forum/reddit/IRC.
