### ISSUE TITLE
Roofed Forests still generate vanilla 2x2 trees

### ISSUE THREAD

**Issue by cybercat5555** [ferreusveritas/Dynamic-Trees#206]
**Describe the bug**
In Roofed Forests and their variants, vanilla 2x2 trees still generate along side the original dynamic 1x1 trees and the new dynamic thick trees, despite the fact the config is set to replace vanilla trees. 

**To Reproduce**
> Install Dynamic Trees 1.12.2-0.9.4
> Find a Roofed Forest biome and explore it a bit

**Screenshots**
https://i.imgur.com/ZMMLUjN.png
https://i.imgur.com/mKDoTOd.png

The vanilla large trees were not planted by me, they generated naturally.

**Rendering Glitches**
No rendering glitches, not using Optifine

**Additional context**
In Roofed Forests, both vanilla 2x2 trees and the new dynamic thick trees generate, despite the fact vanilla trees are set to be replaced in the config. Other biomes with thick trees, such as jungles and mega taigas, are fine and only the dynamic trees generate (both thick and original).

I also just noticed this in the screenies, but other vanilla trees that generate in Roofed Forest biomes (such as birch and normal oak) also use the vanilla type instead of the dynamic type
https://i.imgur.com/S2LKC8T.png

**Crashes**
N/A

**Mods List**
Forge .2796
I can include a mod list, but I don't think it will help since this seems to be a purely Dynamic Trees issue

**Comment by Deshiba** [comment]
It might still be a conflict with another mod, including a pastebin with the modlist would be advisable.

**Comment by cybercat5555** [comment]
Here's a list:
[list.txt](https://github.com/ferreusveritas/DynamicTrees/files/2801052/list.txt)

The only possible conflict I can think of would be Traverse, but this is a vanilla biome, and Traverse does not affect them
While I do have recurrent complex installed, I have all its structures (including its trees) disabled and am only using it as a means to save builds

**Comment by ghost** [comment]
Does this happen near the edge of the roofed forest?  Do you see this happening in the middle of it?

**Comment by cybercat5555** [comment]
It seems to happen in any Roofed Forest type biome, be it on the edge or right smack in the middle. I also removed Traverse to test, and the bug still persisted. In fact, the vanilla trees seem to be more common still than the dynamic trees.

Tested with a fresh seed generated after removing Traverse.
https://i.imgur.com/kp0XtZx.png
https://i.imgur.com/QRjO35H.png (location in the biome)

**Comment by CuriousKey** [comment]
I can confirm I had this issue as well, same versions of DT and Traverse, happens with or without Traverse.

Could still be a mod conflict, but I was unable to identify what it could be.

**Comment by Graywaren** [comment]
I also had this bug, but not just with the roofed forest or 2x2 trees. I had it happen in many biomes with any size tree. I rolled back all my mods and then added one by one until it started happening again. It definitely seems to be an issue with recurrent complex. It only started happening once I enabled that. =/ I'd really like to use RC since it does add some neat things, but ughhhh I want my dynamic trees! From flying around looking at the world I can't discern a pattern to it either. It isn't just at the edge of biomes, it doesn't seem to be specifically around RC structures either.

**Comment by Graywaren** [comment]
I googled a bit and found a reddit mentioning setting RC "Whether the nature (e.g. trees, mushrooms) added by the mod should be actively generating" to false in its config fixing vanilla trees spawning, so I tested that. It did seem to fix some of it, I didn't see any vanilla trees in the birch forest like I had been, however Roofed Forested is still a mess. There's a thread on RC's git hub about it as well, so it's definitely the culprit.

https://github.com/Ivorforce/RecurrentComplex/issues/349

*edit* Even with natural gen disabled and tree related things disabled in decoration I was still seeing the occasional vanilla tree (aside from in roofed forest), mostly seemed to be large spruces on the edge of a biome.

**Comment by Deshiba** [comment]
@cybercat5555, could you test your pack without recurrent complex? It's the easiest way to confirm it's the culprit in this issue.

**Comment by cybercat5555** [comment]
yep, it seems removing RC fixes it. Vanilla trees no longer generate

**Comment by Graywaren** [comment]
Any updates on this issue? Or anyone find a work around? I'd really like to be able to use RC & DT together.  I'm planning to take another whack at figuring it out, but I'm pretty new to mods, so I don't know if I'll be able to identifying anything.

**Comment by Avery93** [comment]
Hello all, [a thread over in RC](https://github.com/Ivorforce/RecurrentComplex/issues/349) found a solution:
> The only other thing I modified is the name of the jar... and that appears to be it. I downloaded a fresh copy of RC, prefixed the jar name with a plus sign, kept my existing configs, gen'd a new world... roofed forest was 'dynamic.' Apparently it had nothing to do with removing files.
> 
> Now, I feel insane believing in this solution even though it works every time I test it. Can you confirm?
> 
> Edit: Yes, the trick is getting Dynamic Trees to load after Recurrent Complex by manipulating their alphabetical order. Renaming either jar to that effect solves the problem.

**Comment by ghost** [comment]
Thanks @Avery93  Knowing that the solution is mod load order I can put in a requirement to load after Recurrent Complex in the future.

**Comment by ghost** [comment]
This has been fixed.
