### ISSUE TITLE
Missing blocknames.

### ISSUE THREAD

**Issue by efimov90** [ferreusveritas/Dynamic-Trees#207]
Version 1.7.10-0.7.2c.

**Describe the bug**
When use Waila don't see names of blocks, they are missing.

**To Reproduce**
Install Waila and look at tree.

**Additional context**

I wrote small script for Minetweaker3 to fix this:

`
<dynamictrees:acaciabranch>.displayName = "Acacia Wood";
<dynamictrees:birchbranch>.displayName = "Birch Wood";
<dynamictrees:darkoakbranch>.displayName = "Dark Oak Wood";
<dynamictrees:fruitcocoa>.displayName = "Cocoa Fruit";
<dynamictrees:junglebranch>.displayName = "Jungle Wood";
<dynamictrees:leaves0>.displayName = "Leaves";
<dynamictrees:leaves1>.displayName = "Leaves";
<dynamictrees:oakbranch>.displayName = "Oak Wood";
<dynamictrees:sapling>.displayName = "Sapling";
<dynamictrees:sprucebranch>.displayName = "Spruce Wood";
`

**Mods List**
Forge 1.7.10-10.13.4.1614

**Comment by ghost** [comment]
Sorry, 1.7.10 is no longer supported and hasn't been for quite some time.
