### ISSUE TITLE
Falling animation bug with Valkyrien Warfare mod

### ISSUE THREAD

**Issue by koravel** [ferreusveritas/Dynamic-Trees#213]
Normally, when tree is chopped, falling animation is playing.
With ValkyrienWarfare mod this animation brokes.
It looks like tree is freeze and then falls very quickly.

I'm not sure is that because Valkyrien Warfare  or Dynamic Trees itself...

Mods versions:
ValkyrienWarfare-0.9_prerelease_5+[Optimization+Update]
DynamicTrees-1.12.2-0.9.4

**Comment by Bucky420** [comment]
i can confirm :)

**Comment by AriDrSteam** [comment]
Yeah, I see this one, It seems to be caused for ValkyrienWarfare... a shame.

**Comment by Nianor** [comment]
This is almost certainly because of Valkyrien Warfare. They have a number of compatibility issues with other mods, and when I've asked them about similar issues, they've flat out refused to fix them. I wouldn't hold your breath for them to fix this one.
