### ISSUE TITLE
[Imcompatibility with astral sorcery] Server side crash Exception ticking world

### ISSUE THREAD

**Issue by Lifeismana** [ferreusveritas/Dynamic-Trees#214]
**Describe the bug**
Server crash when approaching an area, removing dynamictrees makes the server crash stop.
Removing BOP, traverse and Harvestcraft addon doesn't solve the problem.

**Crashes**
First occurrence of the crash 
[crash-2019-02-07_17.24.42-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/2842401/crash-2019-02-07_17.24.42-server.txt)
[2019-02-07-2.log](https://github.com/ferreusveritas/DynamicTrees/files/2842403/2019-02-07-2.log)

**Comment by kierajreed** [comment]
Please use [hastebin](https://hastebin.com/) for error logs and stack traces.

**Comment by Lifeismana** [comment]
Whoops, sorry
crashlog:
https://hastebin.com/qisefopomu.rb
The log file is too big for hastebin, i don't know if it is needed, also is the debug log useful ?

**Comment by Lifeismana** [comment]
So deleting a lot of chunk with mc-edit solved the problem, also if i wasn't clear, removing DynamicTree and its addons also solved the issue

**Comment by Lifeismana** [comment]
Found the problem astral sorcery meteorites are somehow making crash the server when they hit the ground and probably hit DynamicTrees'tree

**Comment by linuskr** [comment]
I had the same issue, but without astral sorcery. I believe it's caused by Thutcore, as i described in https://github.com/Thuts-Mods/ThutCore/issues/3.

**Comment by ghost** [comment]
Thanks linuskr.  @Lifeismana I know it's been a while but is there a way to test your crash by running a session without ThutCore?

**Comment by kashinoda** [comment]
@ferreusveritas Removing Thutscore fixed our world after the same crash, was driving me mad for days!
@linuskr Many thanks for discovering this.
