### ISSUE TITLE
[Feature/Improvement]Vanilla sapling always give Dynamic Tree

### ISSUE THREAD

**Issue by Sablam** [ferreusveritas/Dynamic-Trees#216]
Hi,

I am doing some worldbuilding with world edit and dynamic trees. I can't use use the forest world edit feature, because it plant vanilla trees. 
I would like to use the flora feature by generating lot of tallgrass and replace it with vanilla sapling. Unfortunatly, the sapling generated are growing vanilla tree, unlike the vanilla sapling that we plant ourself and that are converted to dynamicTrees sapling.

Do you see a way out ? (like make the vanilla sapling always convert to dynamicTrees, or add a tool to plant forests).

Thank you,

Sincerely.

**Comment by ghost** [comment]
Same as #351
