### ISSUE TITLE
[SUGGESTION] Better seed first stage.

### ISSUE THREAD

**Issue by BentoGambin** [ferreusveritas/Dynamic-Trees#218]
In the mod you place seeds in the ground which would lead to a small lump of dirt appearing on the ground, and then, after a while, a sappling. The Dynamic trees mod currently presents a sappling instantly, which is very similar to the vanilla's seedling system.

**Comment by ghost** [comment]
Cute idea.  But needlessly adds blockstates which may not be an issue for 1.12.2(because it uses a tile entity) but will be an issue in 1.14.4+.  I'd regret adding a feature and then removing it in later versions.  I'll consider it.  Thanks for the suggestion.
