### ISSUE TITLE
[suggestion] make seeds oreDictionaried with treeSapling

### ISSUE THREAD

**Issue by 3nd0fw0r1d** [ferreusveritas/Dynamic-Trees#22]
Would go a long way for compatibility with recipes without having to craft into saplings first.

**Comment by ghost** [comment]
I guess since I implemented the dirt bucket which changes seed to saplings and vice-versa for free then this actually makes a lot of sense.

**Comment by ghost** [comment]
I just added the code to register all of the "Vanilla" dynamic seeds as "treeSapling" in the OreDictionary.
