### ISSUE TITLE
Dirt Bucket Right-click Config

### ISSUE THREAD

**Issue by NielsPilgaard** [ferreusveritas/Dynamic-Trees#225]
**Request**
I would like to request a config option to disable the right-click functionality of the Dirt Bucket. I'm making a modpack where Iron is restricted until a certain stage, and the Dirt Bucket is made from a Clay Bucket + Dirt, so it's a bit game-breaking to have it turn into an empty bucket when used :P

I hope you'll consider it, and thank you for a great mod.

**Comment by kierajreed** [comment]
Alternatively, have it turn back into a clay bucket rather than an iron one.

**Comment by NielsPilgaard** [comment]
That would be great, but I think it's too much to ask for :p

**Comment by kierajreed** [comment]
It actually could be as simple as changing one line, however a config for this could be good as well.
https://github.com/ferreusveritas/DynamicTrees/blob/619d419e7c6904ae62d21b48d48a7b4b76571593/src/main/java/com/ferreusveritas/dynamictrees/items/DirtBucket.java#L68

**Comment by NielsPilgaard** [comment]
Thanks!
