### ISSUE TITLE
**Not a bug report** Assistance adding Dynamic Trees support in my mod

### ISSUE THREAD

**Issue by GreatOrator** [ferreusveritas/Dynamic-Trees#226]
I wanted to see if I could request any assistance in adding a soft dependency for your mod in mine, Tolkien Tweaks - Mobs Edition.  I have received a rather large number of requests to add support and I am still relatively new to modding so any assistance you might be willing to provide would be awesome.

Thank you in advance!

**Comment by kierajreed** [comment]
This is not a help forum. Go ask on Discord.
