### ISSUE TITLE
Request For Info: Growing Trees indoors

### ISSUE THREAD

**Issue by wadiv76** [ferreusveritas/Dynamic-Trees#227]
I am trying to find information on how dynamic trees might be grown indoors if the mod supports some artificial light source in place of the open sky above the tree.  I've tried modifying the config regarding the scaleBiomeGrowthRate hoping that might allow for it, but no luck.  Is there any way at all or are indoor trees doomed?

**Comment by ghost** [comment]
You can make light conduits that channel sky light from above ground.  Aside from that, no you can't grow with artificial light and it will never be a feature that you can.
