### ISSUE TITLE
Dynamic Trees randomly crashing dedicated server

### ISSUE THREAD

**Issue by Sharpy84** [ferreusveritas/Dynamic-Trees#228]
**Describe the bug**
Dynamic Trees is crashing the server at random times, with no player interaction.

**To Reproduce**
Unable to reproduce as it is random and has happened with and without players online, currently have 6 crash reports over 2 days.

Mod Version: DynamicTrees-1.12.2-0.9.4
Forge Version: Forge-14.23.5.2810

[crash-2019-03-02_05.10.36-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/2922256/crash-2019-03-02_05.10.36-server.txt)

**Comment by kierajreed** [comment]
Please use [hastebin](https://hastebin.com/) for error logs and stack traces.

**Comment by Sharpy84** [comment]
It didn't specify any method of sharing crash logs in the template.

https://paste.dimdev.org/gehecajocu.rb

**Comment by Sharpy84** [comment]
It didn't specify any method for sharing crash logs in the template.

https://paste.dimdev.org/gehecajocu.rb

**Comment by ghost** [comment]
How the log was posted is fine in my opinion.

**Comment by kierajreed** [comment]
It is easier to open a link rather than downloading and opening a file for most people.

**Comment by kierajreed** [comment]
Closed as pertaining to an outdated version.
