### ISSUE TITLE
NoSuchMethodError crash for Species.addAcceptableSoil (MC 1.12.2)

### ISSUE THREAD

**Issue by Trynthlas** [ferreusveritas/Dynamic-Trees#229]
Server crash log here: https://pastebin.com/NLwnbXiS

I also set up a profile which will turn into my private pack and tried to launch the client side. Similar crash here: https://pastebin.com/NtxPkhpR

**Comment by kierajreed** [comment]
Does this bug persist if you try with only Dynamic Trees?
Also, the links seem to be empty.

**Comment by Trynthlas** [comment]
Switched to pastebin.

Error does not show with only Dynamic Trees. Going for adding one at a time now...

**Comment by Trynthlas** [comment]
Added only BoP and Dynamic Trees BoP, crash shows up again.

https://pastebin.com/vJr5fgES

**Comment by kierajreed** [comment]
You're using outdated versions. Please update your mods to the latest versions and reopen this if the error persists.

**Comment by Trynthlas** [comment]
The versions used are the latest Release tagged versions of each mod. If there's a compatibility issue between the release versions, is there a specific set of versions which does work (this should probably be specified as dependencies between the mods)?

I don't think updating to a non-stable build (alpha/beta) is the best suggestion? Thanks.

**Comment by kierajreed** [comment]
For Dynamic Trees mods, you SHOULD\* always use the latest version, even alpha and beta versions.

\* See [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt).
