### ISSUE TITLE
Max size configurable

### ISSUE THREAD

**Issue by celittle3** [ferreusveritas/Dynamic-Trees#233]
Is there a max size and is it configurable. I would like to see really big trees.

**Comment by kierajreed** [comment]
IIRC, there is a maximum width of 3x3 blocks and maximum height varies by species. A library could be made for even thicker trees but it would be very complicated.

**Comment by celittle3** [comment]
I see, thank you. How about making the height configurable for really tall trees?

**Comment by kierajreed** [comment]
It depends. Most species don't grow tall because that is not their natural shape. If you like tall trees, large jungle, large spruce, spruce, and birch are the tallest species if I recall correctly.
