### ISSUE TITLE
DT leaves seems to not be affected by shader waving

### ISSUE THREAD

**Issue by Zergmazter** [ferreusveritas/Dynamic-Trees#235]
**Describe the bug**
When I put on any shaders the leaves will not have their waving effect. This is strange since when I hover over the leaves it says its minecraft leaves.

**To Reproduce**
Put on any shader pack that allows plant waving.

**Rendering Glitches**
I'm using optifine.

**Comment by NovaMaiden** [comment]
Same here. Still haven't found a way to fix it.

**Comment by SkyHawkB** [comment]
I don't think DT leaves work the same as vanilla leaves. Let me look over the code real quick and I'll try to find what code causes this.

**Comment by RazielvvPL** [comment]
I have tried every version for M 1.12.2 and neither one of them have working waving.
Hey Devs its possible to add this feature (weaving leaves) ?

**Comment by Zergmazter** [comment]
It doesnt look like this mod adds its own leaves when you hover over them (it says it is a default minecraft leaf). If it does add it's own leaves it would be nice to at least know the ID so that I can add it myself to better foliage.

**Comment by Dyntee4m** [comment]
I am also having this issue. I tried changing some DT configs around and I tried playing with the shader pack (I am using SEUS Revival) and nothing seems to work.

The biggest thing to note is that this only occurs on the generated leaves from DT. If you place any leaves into the world, they are fine. Even stranger (at least personally) is that it seems like the bushes generated by DT also work perfectly fine.

Any hotfix for this would be amazing

**Comment by Demonmiker** [comment]
With F3 you can look real ID of leaves and config shader yourself.

**Comment by SoggieWafflz** [comment]
Yes! This worked! I'll share the full list of block IDs once I add them all to my shaderpack!

**Comment by SoggieWafflz** [comment]
The blocks to add if you're using dynamic trees, dynamic trees biomes o plenty, and dynamic trees pam's harvestcraft are:

dynamictrees:leaves0 dynamictrees:leaves1 dynamictreesbop:leaves_flowering dynamictreesbop:leaves0 dynamictreesbop:leaves1 dynamictreesbop:leaves2 dynamictreesbop:leaves3 dynamictreesbop:leaves4 dynamictreesbop:leaves_palm dynamictreesbop:leaves7 dynamictreesphc:leaves0

**Comment by ProtocolArcus** [comment]
@SoggieWafflz Where and how did you add the blocks IDs to the shader's configs? I'm having the same issue and can't figure out where to paste the IDs you've posted

**Comment by Demonmiker** [comment]
I use Sildurs Enhanced Default and edit block.properties file

edited block.properties : https://drive.google.com/open?id=1UvwErFssjcOS3DV588sM-UyOVw4kKwuE

**Comment by SkeleBones** [comment]
> I use Sildurs Enhanced Default and edit block.properties file
> 
> edited block.properties : https://drive.google.com/open?id=1UvwErFssjcOS3DV588sM-UyOVw4kKwuE

You threw away this file.

**Comment by Draglorr** [comment]
can i please have the modified block>properties file?? Your link is broken, i use the same shaders and I can not figure how to solve this on my own! Please help!

**Comment by Draglorr** [comment]
> I use Sildurs Enhanced Default and edit block.properties file
> 
> edited block.properties : https://drive.google.com/open?id=1UvwErFssjcOS3DV588sM-UyOVw4kKwuE

can i please have the modified block>properties file?? Your link is broken, i use the same shaders and I can not figure how to solve this on my own! Please help!
