### ISSUE TITLE
[Minor Issue] Trees that has no supporting does not break.

### ISSUE THREAD

**Issue by Water-Moon** [ferreusveritas/Dynamic-Trees#236]
DT Version: 1.12.2-0.9.4
MC Version: 1.12.2
Forge 14.23.5.2815

Something like this happened everywhere after the use of World Edit or /setblock command:
![2019-03-25_06 13 30](https://user-images.githubusercontent.com/43123946/54886676-ac6f2600-4ec5-11e9-8ba6-87458294be21.png)
or like this:
![image](https://user-images.githubusercontent.com/43123946/54886746-5f3f8400-4ec6-11e9-9e76-a54fc1020e64.png)

Or, sometimes caused by structure generation:
![image](https://user-images.githubusercontent.com/43123946/54886807-218f2b00-4ec7-11e9-8389-9486aaaabde5.png)

Maybe add a check to see if the root block exists each time the tree updates?

**Comment by kierajreed** [comment]
This is caused by those block changes not properly updating the blocks near them. However, this could be an acceptable solution.

**Comment by ghost** [comment]
The update comes from the root block, not any of the branches.  So this won't work.  Setting/destroying the tree blocks with a setblock command is not a proper interaction and not supported by this mod.
