### ISSUE TITLE
[FEATURE] Adjustable Apple/Cocoa Tree Spawn Rate

### ISSUE THREAD

**Issue by Axebeard2025** [ferreusveritas/Dynamic-Trees#237]
I would very much like to see a config option that allows for changing the spawn rate of Apple Trees & Cocoa Trees vs DT Oak Trees / Jungle Trees.

This is an amazing mod.  Thank you for all your hard work.  :)

**Comment by ghost** [comment]
This is currently possible using the existing json config system.
