### ISSUE TITLE
Structure Overlap Issues During Generation

### ISSUE THREAD

**Issue by Avery93** [ferreusveritas/Dynamic-Trees#238]
I've got both Dynamic Trees (0.9.4 for 1.12.2) and Roguelike Dungeons (1.8.0 for 1.12.2) installed. Roguelike dungeons that spawn naturally seem to have a bad habit of overlapping with other structures, like trees and villages. To an extent, this is probably unavoidable and ultimately tolerable. However, something weird happens when they overlap spatially with blocks generated by Dynamic Trees. The dungeon overrides the tree, destroying the blocks but leaving invisible and impassable glitched space in their place. Player model is unable to move into or out of this space except on very specific vectors and vibrates continuously once caught in this space. The filled blocks do not register to WAILA/HWYLA, cannot be destroyed, and are invisible.

I have no clue which mod is responsible, but it is exclusively at the intersection of these two mods that this occurs so I will submit it to both threads.

This occurs both with and without optifine, on vanilla and modded dynamic trees (BOP, PHC, climatic). Dynamic trees grow around vanilla structures, and similarly do not have any trouble interacting with other structure mods (including Recurrent Complex, despite how it messes up the Roofed Forest [#349](https://github.com/Ivorforce/RecurrentComplex/issues/349)). My issue isn't simply that the trees are destroyed and spam item drops (RAM load is not an issue for me), as in #224, but what happens afterwards in the conflicted spaces.

I can't get a good screenshot since the relevant feature of the problem requires motion capture to fully demonstrate the issue.

**Comment by CREEATION** [comment]
@Avery93 You might want to look into [LICEcap](https://www.cockos.com/licecap/). You can record GIFs with it. Just set the frames to something like 5-15 so it doesn't generate too large files.

**Comment by Avery93** [comment]
That was a good idea, thanks. Took me a while to find a good example, since it required an above-ground structure from this mod spawning into relatively dense forest. Also had to set the framerate high enough to catch the jittering from trying to walk into the "occupied" space.
![issue tracking outside](https://user-images.githubusercontent.com/48781885/54897326-520e9f00-4e9e-11e9-90b9-91454dca396b.gif)
![issue tracking the approach](https://user-images.githubusercontent.com/48781885/54897328-520e9f00-4e9e-11e9-941a-563b5255fbf7.gif)
![issue tracking small](https://user-images.githubusercontent.com/48781885/54897327-520e9f00-4e9e-11e9-83d6-9ac2e7f91f51.gif)

**Comment by Avery93** [comment]
Per the recommendation of [#187](https://github.com/Greymerk/minecraft-roguelike/issues/187), I checked if reloading the world fixed this issue, which it did. Rebooting resolved the conflict by getting rid of the tree and restoring the structure. Looks to be a client/server communication conflict. I didn't even think that would be an issue since I'm only playing single player, but the client does indeed set up an internal server. It'll still be a pain to reboot every time I find this issue, but that's acceptable.

**Comment by naqaden** [comment]
I notice the same issue between Recurrent Complex structures + Dynamic Trees. Same solution too, so I'm pregenerating my world to work around this.

**Comment by naqaden** [comment]
I think it'd be fair to reopen this. It looks like it is DT setting broken trees' branches and leaves to air, based on [this line](https://github.com/ferreusveritas/DynamicTrees/blob/45090027fbe6d400949630ad4188169f33739717/src/main/java/com/ferreusveritas/dynamictrees/entities/EntityFallingTree.java#L180). It doesn't seem account for trees being replaced by structures. DT has the server and client handle this separately in different ways, leaving the client to believe there is air where there is not.

**Comment by kierajreed** [comment]
This is a recurring issue, and it's unfair to expect users to take extra steps to resolve it if it can be fixed nicely in code. I'll reopen this.
