### ISSUE TITLE
about compatibility 

### ISSUE THREAD

**Issue by Roberto-Rmz** [ferreusveritas/Dynamic-Trees#239]
this mod is compatible with veinminer?

**Comment by kierajreed** [comment]
Test it for yourself. Probably not because this implements advanced breaking mechanics but you can try.

**Comment by croaganey** [comment]
I'm not sure about VeinMiner, but Ore Excavation is similar and it works well. Hope that helps someone.

OreExcavation-1.4.140.jar

Edit: It's not necessary to use a mod to chop trees as that mechanic is already in Dynamic Trees. I'm just providing confirmation of compatibility as OreExcavationis in our pack for other reasons.

**Comment by Deshiba** [comment]
Would you really need to use either?

DT is set up to chop down the entire tree when you mine the bottom block.

**Comment by kierajreed** [comment]
I'm closing this by Monday unless someone has a comment to make.

**Comment by ghost** [comment]
Is this mod compatible with natura?

**Comment by kierajreed** [comment]
with an addon, if there's one, yes

**Comment by kierajreed** [comment]
Alright, I'm adding an FAQ here so this stops.
