### ISSUE TITLE
[ADDON REQUEST] Can we have a support patch/addon for Cuisine?

### ISSUE THREAD

**Issue by chief-turkler** [ferreusveritas/Dynamic-Trees#241]
Cuisine: https://minecraft.curseforge.com/projects/cuisine

The game adds some trees which don't work, can we please get a compability patch? Thanks.

**Comment by kierajreed** [comment]
As in #240, Ferreus didn't say this, but if you want to get an addon, you gotta make it yourself or pay someone to do it. This isn't the place to ask for addons. Hope that clears it up.
