### ISSUE TITLE
BIG BUG: Infinitely Duplicating Block Break particles after staying in the death screen for more than 10 seconds.

### ISSUE THREAD

**Issue by SirAron111** [ferreusveritas/Dynamic-Trees#242]
**Rules(Read this first!)**
This is just a template to help you post a useful issue.  Erase these rules and any irrelevant categories and content as you see fit.  Do not make issues requesting compatibility with other tree providing mods such as Forestry.  Only submit issues related to the latest version of the mod for the currently supported version of Minecraft(which is currently only 1.12.2).  When referring to software versions always use the actual version number and never "latest".

**Describe the bug**
Infinitely duplicating particles (after reviving and breaking blocks etc) for every second you are in death screen until relogging!

**To Reproduce**
Make a World with Dynamic Trees break a block to see its all ok than get killed or type /kill and wait a bit in the death screen to give the particles time to accumulate so like 10-20 seconds than respawn break a block and see the lag magic happen.

**Screenshots**
This is how it looks before i kill myself:
![2019-04-06_01 27 45](https://user-images.githubusercontent.com/39855956/55661320-8160cc80-580b-11e9-8ab5-40e1480bb472.png)

And this is after with around 10 sec waiting in death screen:
![2019-04-06_01 28 23](https://user-images.githubusercontent.com/39855956/55661337-a5241280-580b-11e9-8c0e-45d46bcd0dba.png)
![2019-04-06_01 28 55](https://user-images.githubusercontent.com/39855956/55661349-b10fd480-580b-11e9-9214-3f7469d3a62e.png)
![2019-04-06_01 28 54](https://user-images.githubusercontent.com/39855956/55661350-b10fd480-580b-11e9-830c-3b618952d328.png)
![2019-04-06_01 28 54_2](https://user-images.githubusercontent.com/39855956/55661351-b10fd480-580b-11e9-8e51-d8326f7a27d6.png)
![2019-04-06_01 29 07](https://user-images.githubusercontent.com/39855956/55661356-b8cf7900-580b-11e9-9c19-dec392ece32b.png)
![2019-04-06_01 29 06](https://user-images.githubusercontent.com/39855956/55661357-b8cf7900-580b-11e9-9111-a833c83225d7.png)

**Rendering Glitches**
Optifine doesn’t matter I tested with and without Optifine. (Actually to find this bug in my Modpack I tested for like 4 hours every single mod separately and some together and or alone etc.) Narrowed it down to Dyn Trees reason (the bug occurred with only this mod installed and nothing else reinstalling all other Mods and deleting the Dyn Trees fixed it I even double checked)

**Additional context**
OK I have found a terrible bug with the otherwise so perfect mod. It breaks stability and performance as well as visual glitches among others.
I am talking about the fact that after the player dies from whatever the source even /kill drowning fire mobs etc everything. The longer you stay in the respawn screen the more particles you will get on mostly everything especially block breaking. Meaning that if you are like 10 or 20 sec in respawn screen for some reason you get like a trillion particles from any block broken meaning if I for example break one little flower it explodes into a performance killing lagging supernova.

**Crashes**
- Are you running the latest version of Dynamic Trees?(Currently 0.9.4) yes i am using DynamicTrees-1.12.2-0.9.4.jar

- If you are using the DT Biome O' Plenty Add-on do you have the latest version?(Currently 1.4.1e) In the Modpack I am using it but on my test runs you can even reproduce the bug with just the standard Dyn Trees and nothing else.

- If you are using the DT Thaumcraft Add-on do you have the latest version?(Currently 1.4.1e)
In the Modpack I am using it but on my test runs you can even reproduce the bug with just the standard Dyn Trees and nothing else.

**Mods List**
Doesn’t Crash just Lags intensely and let’s say you break a 100 blocks or so with a fast pick you get like 5 min freeze but no crash it just takes ages and every hit slows down the game by 100-200 fps so you only have like 10 or 1 fps until all particles are gone.

What version of Forge are you running?(e.g. 1.12.2-14.23.5.2768)
Running on Miencraft 1.12.2 Forge Version 14.23.5.2822 but it also happened like 20+ versions down the line even with the 1.12.2-14.23.5.2768 one. You should test it against the newer ones thought since many mods started using newer versions to actually run and many modpacks thus need the newer forge versions as they fix a few important things.

PS: Here as a little laughter https://youtu.be/7iyjUXFA9Ak?list=PLS8-AGqCp1L-BEPbLuBVuSB6wdGK0Oq9c&t=3257 a victim of a tree caught on Stream

**Comment by SirAron111** [comment]
PS: it’s not the texture pack tested it with no textures as well

**Comment by SirAron111** [comment]
The bug seems to do some wired thing with particles in general because the more someone dies the longer someone is dead the leggier it gets. I have no idea how that happens. But I tested all my 200+ mods separately and it is coming from dyn trees.

**Comment by SirAron111** [comment]
https://github.com/ferreusveritas/DynamicTrees/issues/221 this hotfix seems to fix it you should implement whatever it does into the main mod.
Yep tested it works fine.

**Comment by kierajreed** [comment]
Closed by #220.
