### ISSUE TITLE
Some trees only drop sticks?

### ISSUE THREAD

**Issue by zerafox** [ferreusveritas/Dynamic-Trees#244]
**Describe the bug**
Felling certain trees appear to result in nothing but sticks or only 1 log:
Minecraft: Birch
Biomes O' Plenty: Ebony _(Yes, the add on is installed as well)_
Biomes O' Plenty: Eucalyptus
Biomes O' Plenty: Fir
Minecraft: Dark Oak
Minecraft: Jungle (This makes no sense, I've broken several very tall Jungle trees and only received sticks)

Narrow trees like the Birch will "revert" to the smallest form of log (like the end of the branches) before falling over.
This occurs even to trees that have their trunk as wide/large as the block they sit on.

**To Reproduce**
Chop down a Dynamic Tree of any of the above listed

**Mods List**
FML: MCP 9.42 Powered by Forge 14.23.5.2823
Dynamic Trees v1.12.2-0.9.4
Dynamic Trees BOP v1.12.2-1.4.1e
Dynamic TreesPHC v1.12.2-1.4.2
Tinker's Construct v1.12.2-2.12.0.135

And several other non-world specific related mods.. If these are needed I will try to compile entire list.

**NOTES**
I will try to add to this ticket as I find more that behave the same way, so far these are all I've noticed behaving this way.
It makes it incredibly difficult to harvest wood from trees that appear to be full-grown.

**Comment by zerafox** [comment]
:| 
I was still waiting to hear what would become of this issue.

Kind of a real let-down to only see it "Closed" after waiting this long.

**Comment by kierajreed** [comment]
I closed it because it was a mod conflict on an older version. It's nearly impossible to identify those without a full list and tracing the code is not worth the devs' time. Therefore, unless you have a specific bug, it's highly unlikely that it'll be fixed.
