### ISSUE TITLE
Corsage dirt turns into ordinary dirt after choped down a tree on it.

### ISSUE THREAD

**Issue by Lovatic123** [ferreusveritas/Dynamic-Trees#245]
So a DT planted itself on corsage dirt...I choped it down, and the corsage dirt turned into regular dirt. This seems like a minor problem, but I placed the corsage dirt there for a reason, and I dont want it to change into normal dirt as I dont want a grass block there. 

**To Reproduce**
Just plant a DT on a corsage dirt block, let it grow a little and then chop it down. Dont know if you have to be in survival mode.

**Comment by ghost** [comment]
What's corsage dirt?
