### ISSUE TITLE
incompatibility with Streams, causing crash.

### ISSUE THREAD

**Issue by TheOneTraveler** [ferreusveritas/Dynamic-Trees#247]
**Rules(Read this first!)**
This is just a template to help you post a useful issue.  Erase these rules and any irrelevant categories and content as you see fit.  Do not make issues requesting compatibility with other tree providing mods such as Forestry.  Only submit issues related to the latest version of the mod for the currently supported version of Minecraft(which is currently only 1.12.2).  When referring to software versions always use the actual version number and never "latest".

**Describe the bug**
crash when loading streams with dynamic trees, not entirely sure the specifics it's just all i could gather from the crash report

**To Reproduce**
install streams and dynamic trees and walk around a bit? idk?

**Screenshots**
N/A

**Rendering Glitches**
Are you using Optifine?
nay
**Additional context**
im playing on my WIP modpack Recentibus focusing on enhanced vanilla, if you search for it on curseforge you can get a list of my other mods as well as how i've set the config.

**Crashes**
- Are you running the latest version of Dynamic Trees?(Currently 0.9.4)
aye
- If you are using the DT Biome O' Plenty Add-on do you have the latest version?(Currently 1.4.1e)
indeed
- If you are using the DT Thaumcraft Add-on do you have the latest version?(Currently 1.4.1e)
Not applicable
If the above mods are current then please submit a full crash log.  The crash log normally contains the names of mods and their versions.  Don't be that guy who submitted a crash report without first checking that the versions are current.
https://pastebin.com/98K9ziTX
**Mods List**
If your crash log does not contain a list of mods or you have no crash log then please provide a full list of the mods you are using complete with mod versions.
i believe it already has the mod list in the crash report, if not i'll gladly revise,
What version of Forge are you running?(e.g. 1.12.2-14.23.5.2768)
forge-14.23.5.2820

**Comment by Deshiba** [comment]
FML: MCP 9.42 Powered by Forge 14.23.5.2820 92 mods loaded, 92 mods active

There's 9 core mods active.

I've had no issues running this combination in a pack so far. Could you test with just Streams, farseek and DT?

**Comment by TheOneTraveler** [comment]
i mean. what's farseek?

**Comment by TheOneTraveler** [comment]
oh right. an API mod. i already have that. it's necessary to run streams, right? anyway im not surprised you've never encountered the issue before, i played the game for 4 hours coming across streams with no issues but some weird generation stuff occured and it crashed.

**Comment by kierajreed** [comment]
Please test this with only Streams and Dynamic Trees and edit with the result. Conflicts between more than two mods are really hard to deal with.
