### ISSUE TITLE
[Suggestion] Cactus Spores/Spikes

### ISSUE THREAD

**Issue by UnlimatedStone9** [ferreusveritas/Dynamic-Trees#248]
Hey there, I was wondering if a spore or spike type item could be added that could be used to grow Dynamic Cacti, alternatively the cactus plant could have a config option to instead of dropping vanilla Cacti to instead drop themselves, this would make growing these Cacti much more possible and would allow an alternative to vanilla Cacti to exist
The Dynamic Trees Cacti should be part of the ore dictionary ore:blockCactus which would allow them to be used in place of vanilla ones in any ore dictionary supporting recipes

Thanks!                       -UnlimitedStone9

**Comment by WrongWeekend** [comment]
Dynamic cacti already drop cactus seeds for growing more dynamic cacti.

**Comment by UnlimatedStone9** [comment]
I haven't seen anything of the sort drop from the cacti, It's just from breaking the cacti as normal?
Anyways one thing I was bothered about was the fact that they drop vanilla cacti which results in you having two types of cacti obtainable even if only Dynamic Trees ones generate
It's definitely useful in a normal playthrough but in a modpack it's a little awkward as I'd rather have just Dynamic Cacti
Take that with a grain of sal- sand... sand, though

**Comment by Deshiba** [comment]
Cactus seeds are 100% in the game, there's textures and code for it.

https://github.com/ferreusveritas/DynamicTrees/blob/1.12.2/src/main/resources/assets/dynamictrees/textures/items/cactusseed.png

Try harvesting just the bottom block when the cactus is fully grown.

**Comment by kierajreed** [comment]
It's added to the drops too, right here.

https://github.com/ferreusveritas/DynamicTrees/blob/3cc66712f5e3c2edefe3f1c16a64885d93a42c40/src/main/java/com/ferreusveritas/dynamictrees/trees/TreeCactus.java#L52

**Comment by ghost** [comment]
This appears to be working fine.  Issue is no longer productive.  If the original poster is still unable to get seeds from cactus they can comment here with new information and I'll reopen the issue.
