### ISSUE TITLE
Sound and visual bug when player is die

### ISSUE THREAD

**Issue by Xoma163** [ferreusveritas/Dynamic-Trees#249]
1.12.2 minecraft forge + DynamicTrees

1. Go to Single
2. Open to LAN with cheats
3. /kill (x3 times for example)
4. Try to destoy block

I hear the block break many times. Both sound and visualization are broken.
In multiplayer too

**Comment by Deshiba** [comment]
What version of Forge and Dynamic Trees are you running? Do you have any other mods running at the same time?

**Comment by Xoma163** [comment]
> What version of Forge and Dynamic Trees are you running? Do you have any other mods running at the same time?

UPD: Break ANY block (not only tree's blocks)

lastest on https://files.minecraftforge.net/ (DynamicTrees-1.12.2-0.9.4, DynamicTreesPHC-1.12.2-1.4.2, DynamicTreesTC-1.12.2-1.4.1e)
lastest on https://minecraft.curseforge.com/ (forge-1.12.2-14.23.5.2836-universal)

Yes, I have other mods, but it working (without DynamicTrees), and when I add DynamicTrees this problem appears

My mods:
![image](https://user-images.githubusercontent.com/35608430/56577499-381ac600-65dc-11e9-87bc-50876b1e23a6.png)
![image](https://user-images.githubusercontent.com/35608430/56577530-449f1e80-65dc-11e9-8a95-6ced789dbb36.png)

**Comment by kierajreed** [comment]
this is probably the issue from #220 that is resolved in Dynamic Trees 9.0.5

**Comment by SkyHawkB** [comment]
this issue is resolved in Dynamic Trees 9.0.5

**Comment by kierajreed** [comment]
update your Dynamic Trees (helps to try that before coming here too)

**Comment by Xoma163** [comment]
> update your Dynamic Trees (helps to try that before coming here too)

thanks!
