### ISSUE TITLE
Fruit, tasty, healthy fruit

### ISSUE THREAD

**Issue by AlexRover** [ferreusveritas/Dynamic-Trees#25]
Hello, did not you think to add fruit trees with fruit inside the leaves like in rustic, he has an apple tree with apples in the foliage, I would like of course all fruits from harvestcraft, but I would be happy at least with an apple tree, I'm from Russia and do not understand English, on this if something google translated is not true and that it is not clear, write to me and I will re-organize, thank you in advance

**Comment by ghost** [comment]
The code for an apple tree is half completed in Dynamic Trees.  You can expect it in the next version.

**Comment by AlexRover** [comment]
It's just fine, but what about the rest of the fruit trees? And can you throw off the translation file of your fashion into Russian?

**Comment by AlexRover** [comment]
Вот

**Comment by AlexRover** [comment]
[en_RU.zip](https://github.com/ferreusveritas/DynamicTrees/files/1590345/en_RU.zip)
I did it by analogy with two files that you had, I can not check, but suddenly it will work)

**Comment by ghost** [comment]
Thanks for the Russian translation.  I've converted it to unicode and added it to project.  Support for harvestcraft trees in the base mod is not going to happen.  It will have to be in a separate mod.

**Comment by AlexRover** [comment]
Hello, this is again I, I do not know if it's Waila's fault, but here's what I see now, is this supposed to be so?
![2017-12-30_03 53 53](https://user-images.githubusercontent.com/34899332/34448150-14fe00ba-ed15-11e7-8fad-7a51e281208a.png)

**Comment by AlexRover** [comment]
That is how it should be?*

**Comment by ghost** [comment]
That was fixed today actually.  But you won't see an update for it until I make a release on curseforge.
