### ISSUE TITLE
axe chopping speeds

### ISSUE THREAD

**Issue by SodaSpartan** [ferreusveritas/Dynamic-Trees#250]
I noticed that the speed at which i break trees is wildly inconsistent between different tools.  sometimes I'm able to chop trees faster with my hand or wooden axes than iron or diamond axes.  sometimes it doesn't happen though and i cant see any obvious pattern as to when it will happen.

Edit: it only seems to happen with vanilla axes, axes added with mods like the copper axe from thermal foundation and anything made with tinkers construct seems to work fine.

another edit: some tinkers tools work for example i tried an all stone hatchet and it was really fast but then i made a stone hatchet with a wood handle and all of a sudden it was slower than my fist again. also i know I'm including other mods in this report but i figured the extra info of whats going on would help figure this out

**Comment by SodaSpartan** [comment]
so uhhh, im going to leave this here just in case anyone else derps as hard as i did... dont accidentally install both tree chopper and dynamic trees, they don't like each other. im gonna go beat my head against a wall now.

**Comment by Deshiba** [comment]
@SodaSpartan If you want to go the extra mile, maybe ask tree chopper to disable itself if DT is present?

**Comment by kierajreed** [comment]
And maybe also show a warning?
