### ISSUE TITLE
Fast Leaf Decay

### ISSUE THREAD

**Issue by ThoBekMic** [ferreusveritas/Dynamic-Trees#251]
Is there any way to make Dynamic Trees work with the mod "Fast Leaf Decay"? Having leaves hanging in the air for the longest time, after removing a tree, is not cool.

Thank you.

**Comment by kierajreed** [comment]
Or just auto decay when the tree is chopped.

**Comment by croaganey** [comment]
Working well on our server. Have the latest versions? (Obvious, I know.)

MC 1.12.2 
FastLeafDecay-v14.jar
DynamicTrees-1.12.2-0.9.5.jar
DynamicTreesBOP-1.12.2-1.4.1e.jar
DynamicTreesPHC-1.12.2-1.4.2.jar
dttraverse-1.5.jar

**Comment by Evolution0** [comment]
Sounds more like you have a mod incompatibility causing dynamic tree leaves to be replaced by another type. Trees fall as a whole _with the leaves_, so none should be left in the air.

**Comment by ghost** [comment]
Recommending to remove the Fast Leaf Decay as it's not necessary with DT installed.
