### ISSUE TITLE
Crash with Harvest Tweaks and DT Thaumcraft

### ISSUE THREAD

**Issue by Dragnier** [ferreusveritas/Dynamic-Trees#253]
**Describe the bug**
Attempting to cut down a Dynamic Greatwood or Silverwood causes a crash with Harvest Tweaks installed; even if I remove all Dynamic Trees from Harvest Tweaks config. This does not happen with regular Dynamic Trees or other compat add-ons like Rustic or Climatic Biomes.

**To Reproduce**

1. Get any axe.
2. Find a Dynamic Greatwood or Silverwood.
3. Try to chop it down with the axe.
4. Crash.

**Crashes**
- Dynamic Trees? 0.9.5
- DT Thaumcraft Add-on? 1.4.1e

Crashlog: https://paste.dimdev.org/mucovuyebu.mccrash

**Mods List**
What version of Forge are you running? 1.12.2 - 14.23.5.2836
Modpack: Terra Confictura - https://minecraft.curseforge.com/projects/terra-confictura

**Comment by Deshiba** [comment]
What exactly did you enter in the Harvest Tweaks config?

**Comment by kierajreed** [comment]
Please post this to the [addon's issue tracker](https://github.com/the-realest-stu/DynamicTrees-TC/issues/new).

**Comment by Dragnier** [comment]
I did not enter anything to start with. It populates itself by default. After the crash, I tried adding dynamictrees:trunkshell I think? I got the block info for the tree trunk using craft tweaker. That did not work either. I also tried removing all references to dynamic trees and it's add-ons from the config, which should make it not affect them. That did not help either. The default config portion for DT is part of the axe section of the blocks config and reads as follows:

```
blocks {
         axe {
                ...
                "dynamictrees:acaciabranch"=-1
                "dynamictrees:birchbranch"=-1
                "dynamictrees:cactusbranch"=-1
                "dynamictrees:darkoakbranch"=-1
                "dynamictrees:darkoakbranchx"=-1
                "dynamictrees:darkoakroot"=-1
                "dynamictrees:junglebranch"=-1
                "dynamictrees:oakbranch"=-1
                "dynamictrees:oakbranchx"=-1
                "dynamictrees:sprucebranch"=-1
                "dynamictrees:sprucebranchx"=-1
                "dynamictreesphc:cinnamonbranch"=-1
                "dynamictreesphc:maplebranch"=-1
                "dynamictreesphc:paperbarkbranch"=-1
                "dynamictreestc:greatwoodbranch"=-1
                "dynamictreestc:greatwoodbranchx"=-1
                "dynamictreestc:greatwoodroot"=-1
                "dynamictreestc:silverwoodbranch"=-1
                "dynamictreestc:silverwoodbranchx"=-1
                "dynamictreestc:silverwoodroot"=-1
                 ...
              }
        }
```

**Comment by Dragnier** [comment]
> 
> 
> Please post this to the [addon's issue tracker](https://github.com/the-realest-stu/DynamicTrees-TC/issues/new).

Posted there and linked back to here.

**Comment by kierajreed** [comment]
Thanks. Regardless, this does not belong here because it's solely a DT-TC issue.
