### ISSUE TITLE
NPE in Server tick loop

### ISSUE THREAD

**Issue by ZyorTaelon** [ferreusveritas/Dynamic-Trees#255]
**Describe the bug**
We're playing on a server that has the dynamic trees mod. All of a sudden the server crashes.

**To Reproduce**
Join our server. Play for a while and see the server crash...
I don't see any specific action one of the players may have done that triggered the crash.

**Screenshots**
[crash-2019-05-05_08.42.32-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/3145526/crash-2019-05-05_08.42.32-server.txt)
https://pastebin.com/j0tHa2dU
[crash-2019-05-05_08.39.49-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/3145527/crash-2019-05-05_08.39.49-server.txt)
https://pastebin.com/uj4RFn01
[crash-2019-05-05_07.44.42-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/3145528/crash-2019-05-05_07.44.42-server.txt)
https://pastebin.com/yQSiXFkr
[crash-2019-05-05_07.42.03-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/3145529/crash-2019-05-05_07.42.03-server.txt)
https://pastebin.com/WAmML185

**Rendering Glitches**
Are you using Optifine?

**Additional context**

**Crashes**
- Are you running the latest version of Dynamic Trees?(Currently 0.9.4) 1.12.2-0.9.5
- If you are using the DT Biome O' Plenty Add-on do you have the latest version?(Currently 1.4.1e) 1.12.2-1.4.1e
- BOP version 1.12.2-7.0.1.2427-universal

**Mods List**
The Mods list and forge version are in the uploaded and pastebinned crach reports.
(btw hastebin is broken)

**Comment by kierajreed** [comment]
Please edit your issue to make it more concise. Also, please add a mod list and put the logs on [hastebin](https://hastebin.com/).

**Comment by ZyorTaelon** [comment]
I've edited the initial report.

**Comment by kierajreed** [comment]
You have many mods. Can you recreate the issue with only Dynamic Trees (and at most one other mod)?
