### ISSUE TITLE
[Question] How to grow Mega taiga trees...?

### ISSUE THREAD

**Issue by Elmfeather7** [ferreusveritas/Dynamic-Trees#256]
Just a question, I wanted to grow some of the mega spruce trees but I can't get seem to do it, Is it possible? Or do I just need to keep going back and forth between my base and the biome they spawn in? Thanks! (picture is just funny trees I found spawned near my home, They are holding hands!)
![2019-05-03_03 37 07](https://user-images.githubusercontent.com/37834855/57381413-32cd9600-71ee-11e9-9d08-26735e73626b.png)

**Comment by Deshiba** [comment]
When looking at https://github.com/ferreusveritas/DynamicTrees/blob/1.12.2/src/main/java/com/ferreusveritas/dynamictrees/trees/TreeSpruce.java, the class for mega spruce is as follows.

```
	public class SpeciesMegaSpruce extends SpeciesBaseSpruce {
		
		private static final String speciesName = "megaspruce";
		
		SpeciesMegaSpruce(TreeFamily treeFamily) {
			super(new ResourceLocation(treeFamily.getName().getResourceDomain(), speciesName), treeFamily);
			setBasicGrowingParameters(0.25f, 24.0f, 7, 5, 0.9f);
			setGrowthLogicKit(new ConiferLogic(5.0f));
			
			setSoilLongevity(16);//Grows for a while so it can actually get tall
			
			addGenFeature(new FeatureGenClearVolume(8));//Clear a spot for the thick tree trunk
			addGenFeature(new FeatureGenMound(999));//Place a 3x3 of dirt under thick trees
		}
		
		//Mega spruce are just spruce in a mega taiga..  So they have the same seeds
		@Override
		public ItemStack getSeedStack(int qty) {
			return getCommonSpecies().getSeedStack(qty);
		}
		
		//Mega spruce are just spruce in a mega taiga..  So they have the same seeds
		@Override
		public Seed getSeed() {
			return getCommonSpecies().getSeed();
}
```

As seen from the comments in that code:
>  //Mega spruce are just spruce in a mega taiga..  So they have the same seeds



There was talk of adding a potion to grow big tree variants outside of their native habitat trough the use of a potion, ("potion of giga" iirc) however that's not implemented yet afaik. So for now you can only grow big spruce trees in the mega taiga.

**Comment by Elmfeather7** [comment]
Ah, I see. Thank you! Hopefully it might get added soon :D
