### ISSUE TITLE
suggestion to make it so trees only drop wood etc when harvested by the player only.

### ISSUE THREAD

**Issue by mattrix444** [ferreusveritas/Dynamic-Trees#257]
hi not sure if this is the right place so delete if necessary. however i would to suggest an option to only allow wood, sticks etc to be dropped when the tree was actually harvested by the player only. im creating a spawn structure for players who join and it is inescapable unless you do certain things but im finding sometimes the structure is spawning into the overworld surface and obviously destroying tree in the process which let the wood and stuff fall into where the player is and allows folks to cheese their way through tons of my dungeon lol, so i would love the option i suggest if possible, i could remove the mod as i don't really need it but i really like it. thanks

**Comment by kierajreed** [comment]
You could solve this on your side by listening for `net.minecraftforge.event.entity.player.EntityItemPickupEvent` and canceling it if the item is not to be picked up.
