### ISSUE TITLE
i got some crashes.

### ISSUE THREAD

**Issue by XxFallenAngelxX** [ferreusveritas/Dynamic-Trees#259]
https://paste.dimdev.org/tuqokijuto.mccrash 
First I wanted to say that my english is not good!
so i have many mods yeah but It was still going on yesterday.
i just update some mods and yeah game broke xD

would be very cool if someone could help me!

**Comment by kierajreed** [comment]
Does this happen when you play with only Dynamic Trees? You have a lot of other mods too.
Edit: I can confirm that there is unsafe division in [this method](https://github.com/ferreusveritas/DynamicTrees/blob/1.12.2/src/main/java/com/ferreusveritas/dynamictrees/client/TextureUtils.java#L174-L196) as if there is no pixels with alpha above 127, the denominator will be 0, throwing the exception. However, the offending texture is probably from some other mod and not from Minecraft or Dynamic Trees.

**Comment by XxFallenAngelxX** [comment]
yeah i just install one mod that makes conflicts but i dont know which one... i just re-install the game an now workes...
i think i still have old folders have made the problems
