### ISSUE TITLE
feature request: leaves replaced with dynamic tree leaves

### ISSUE THREAD

**Issue by Shivaxi** [ferreusveritas/Dynamic-Trees#260]
This mod is amazing, but one of the things that would really help, especially compatibility with other mods that add trees or bushes or whatnot, would be if there was an option that replaced all vanilla leaves with leaves from dynamic trees.

Even in some areas like the jungle for example, you still get bushes spawning on the ground that are normal leaves, which normally you can't tell, until you fall on them and break your legs rofl, since I have the option enabled for cushioning your fall.  It makes it a game of chance sometimes, hoping they're the "right" leaves so you don't die haha.

**Comment by ghost** [comment]
I like the idea however the reason why we decided to go with vanilla leaves is that they won't decay in the dark undergrowth of the forest.  So we'd have to make special leaves for this purpose.  I'll take it into consideration.  Thanks for pointing out the leg breaking problem.
