### ISSUE TITLE
Feature Request : Sound Effect for Trees As The Fall Over

### ISSUE THREAD

**Issue by Blue001** [ferreusveritas/Dynamic-Trees#263]
Simple enough, Why not add a sound that plays when a tree is falling over, and a thud for when it hits an obect?

**Comment by kierajreed** [comment]
But if no one is around to hear it, does it still play? :P

Jokes aside, this is a great suggestion.

**Comment by ghost** [comment]
Thanks for the suggestion.  We're still looking for acceptable, traceable, and royalty free sound effects for this purpose.  When we find them we'll add them.
