### ISSUE TITLE
Witchery

### ISSUE THREAD

**Issue by kegandog** [ferreusveritas/Dynamic-Trees#264]
Whenever attempting to use mutandis on a sapling it immediately turns into the dynamic trees version. Would it be possible to add like a 1 or 2 second delay to allow for mods that do things like this?

**Comment by Deshiba** [comment]
For those of us that haven't touched witchery in a while. What does mutandis do? What do you get out of it and why would the delay be nescesary?

**Comment by kegandog** [comment]
Mutandis is an item than when used on certain saplings (oak, birch, and
jungle I believe) it turns them into a new sapling (such as Rowan,
hawthorn, and alder depending on the sapling). This delay would allow
someone to be able to change the type of tree before it changes into the
dynamic version.

**Comment by Deshiba** [comment]
And are you using default config?

You could try to force vanilla saplings trough configuration. 
replaceVanillaSapling = config.getBoolean("replaceVanillaSapling", "vanilla", false, "Right clicking with a vanilla sapling places a dynamic sapling instead.");

If this doesn't work then I don't know what's going on.

**Comment by kegandog** [comment]
Ok, thanks!
