### ISSUE TITLE
Feature Request: Even Larger Trees?

### ISSUE THREAD

**Issue by RexOrbis** [ferreusveritas/Dynamic-Trees#266]
Some trees from the mods DT has compatibility with grow even larger than DT's versions, such as BOP's 2x2 firs which grow up to 35-40 blocks while DT's only get to around 30 (as far as I could tell using bone meal and burgeoning). Heck, firs in real life can reach 60 metres. Just a suggestion, I think it would be great to have trees grow even larger.

**Comment by ghost** [comment]
Super tall tree structures are avoided for performance reasons.  As time goes on and computers get better we may yet extend these limits.  Thanks for the suggestion.
