### ISSUE TITLE
[Bug]  1. Roofed Forest not replacing all trees 2. Lighting glitch on some trees

### ISSUE THREAD

**Issue by GeminiMarshdevil** [ferreusveritas/Dynamic-Trees#267]
**Describe the bug**
Two bugs for the price of one report.

1. Vanilla trees are not being replaced consistently in Roofed Forest biomes by dynamic trees with the setting to have dynamic trees fully replace said trees enabled.  this only happens in Roofed Forest biomes. Everywhere else its working perfectly.

2. some trees are having a light glitch effecting them, see screenshot below.

**To Reproduce**
1. walk into any Roofed Forest biome, possibly with or without BOP installed. (i have BOP installed)

2. walk into any fir tree forest, snowy or not at night, and place a torch somewhere, then continue walking around at night while looking at the tall trunks

**Screenshots**
Bug 1,
https://cdn.discordapp.com/attachments/546964295360053248/582688101042749440/unknown.png

Bug 2.
https://cdn.discordapp.com/attachments/546964295360053248/582690119283376148/unknown.png
https://cdn.discordapp.com/attachments/546964295360053248/582690365656530944/unknown.png

**Rendering Glitches**
Are you using Optifine? 
Answer: nope.
and it happens with or without Phospher/moving lightsources/ or any of the light related mods installed in the mod list below.

**Additional context**
1.
the vanilla biome that is in question is the only one where this happens, and its random.  some darkwood trees are dynamic, others are not.  

2. 
the glitch has mostly been seen with modded trees, i cant remember all the trees i seen with it, but i think its mainly huge ones, Fir, redwood, etc. 

**Crashes**
1. - Are you running the latest version of Dynamic Trees?(Currently 0.9.4) <- lul old
2. - If you are using the DT Biome O' Plenty Add-on do you have the latest version?(Currently 1.4.1e)

1. yes
2. yes

No crashes result from these bugs.

**Mods List**
MC 1.12.2
forge version: 14.23.2831
ActuallyAdditions-1.12.2-r147.jar
ActuallyBaubles-1.12-1.1.jar
Additional-Compression-1.12.2-3.3.jar
advanced_darkness-1.12.2-1.5.jar
aether_continuation-1.12.2-v1.2.3.jar
aether_legacy-1.12.2-v1.4.4.jar
AkashicTome-1.2-12.jar
animania-1.12.2-1.6.2.jar
antiqueatlas-1.12.2-4.5.1.jar
AoV-1.12-0.11.5.jar
AppleCore-mc1.12.2-3.2.0.jar
AppleSkin-mc1.12-1.0.9.jar
astralsorcery-1.12.2-1.10.18.jar
AtlasExtras-1.12.2-1.6.jar
Atum-1.12.2-2.0.6.jar
AutoRegLib-1.3-29.jar
Baubles-1.12-1.5.2.jar
betteranimals-5.2.1.jar
betteranimalsplus-1.12.2-6.0.1.jar
BetterFoliage-MC1.12-2.2.0.jar
BetterFps-1.4.8.jar
BiblioCraft[v2.4.5][MC1.12.2].jar
BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar
blockcraftery-1.12.2-1.2.0.jar
Bookshelf-1.12.2-2.3.577.jar
bookworm+-+2.2.0+(1.12.2).jar
Botania r1.10-361.jar
CarryOn+MC1.12.2+v1.12.1.jar
CD4017BE_lib-1.12.2-6.4.1.jar
ChunkAnimator-MC1.12-1.2.jar
Clumps-3.1.2.jar
CodeChickenLib-1.12.2-3.2.2.353-universal.jar
CoFHCore-1.12.2-4.6.2.25-universal.jar
CoFHWorld-1.12.2-1.3.1.7-universal.jar
comforts-1.12.2-1.4.1.2.jar
Controlling-3.0.6.jar
CookingForBlockheads_1.12.2-6.4.70.jar
coroutil-1.12.1-1.2.31.jar
CosmeticArmorReworked-1.12.2-v4a.jar
CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar
Curio-1.0.4.jar
Currency-1.12.0-1.3.9.jar
CustomStartingGear-1.12-1.2.0.9-universal.jar
DarkUtils-1.12.2-1.8.226.jar
deepmoblearning-1.12.2-2.5.1-universal.jar
DungeonTactics-1.12.2-0.16.3.jar
DynamicStealth-1.12.2.071.jar
DynamicSurroundings-1.12.2-3.5.4.3.jar
DynamicSurroundingsHuds-1.12.2-3.5.4.0BETA.jar
DynamicTrees-1.12.2-0.9.5.jar
DynamicTreesBOP-1.12.2-1.4.1e.jar
Electroblob's+Wizardry+-+4.1.4+-+MC+1.12.2.jar
EmbersRekindled-1.13-hotfix2.jar
EnderCore-1.12.2-0.5.57.jar
endercrop-1.12.2-1.6.0.jar
EnderIO-base-1.12.2-5.0.44.jar
EnderIO-conduits-1.12.2-5.0.44.jar
EnderIO-conduits-refinedstorage-1.12.2-5.0.44.jar
EnderIO-machines-1.12.2-5.0.44.jar
EnderStorage-1.12.2-2.4.5.135-universal.jar
engineersdecor-1.12.2-1.0.6.jar
environmentaltech-1.12.2-2.0.20.1.jar
Erebus-1.0.29.jar
f5fix-1.2.jar
fairylights-2.1.6-1.12.2.jar
FantasticLib-1.12.2.012.jar
foamfix-0.10.5-1.12.2.jar
ForgeEndertech-1.12.2-4.4.17.1-build.0328.jar
Forgelin-1.8.2.jar
FreeLook-1.2.2.jar
GamblingStyle-v1.0.1-1.12.2.jar
GarbageBins-1.1.1.jar
GasConduits-1.12.2-1.2.1.jar
GrimoireOfGaia3-1.12.2-1.6.9.3.jar
HammerCore-1.12.2-2.0.4.7.jar
healthhungertweaks-1.12-2.1.2.jar
heroicarmory-1.2.0.jar
Hexxit+Gear-1.12.2-2.8.0.jar
iceandfire-1.7.1-1.12.2.jar
iChunUtil-1.12.2-7.2.1.jar
ImmersiveEngineering-0.12-89.jar
ImprovableSkills-1.12.2-3.6.2r.jar
industrialforegoing-1.12.2-1.12.12-236.jar
instantunify-1.12.2-1.1.2.jar
ironchest-1.12.2-7.0.59.842.jar
IvToolkit-1.3.3-1.12.jar
jei_1.12.2-4.15.0.279.jar
jeiintegration_1.12.2-1.5.1.36.jar
jeivillagers-1.12-1.0.2.jar
jepb-1.12-1.2.1.jar
JustAFewFish-1.7_for_1.12.jar
JustEnoughResources-1.12.2-0.8.9.48.jar
living_enchantment-3.1.9.jar
llibrary-1.7.19-1.12.2.jar
lsOutput.log
Mekanism-1.12.2-9.7.4.375.jar
MekanismGenerators-1.12.2-9.7.4.375.jar
MekanismTools-1.12.2-9.7.4.375.jar
modnametooltip_1.12.2-1.10.0.jar
Morph-1.12.2-7.1.3.jar
MouseTweaks-2.10-mc1.12.2.jar
moveplus-1.12.1-2.4.6.jar
movinglightsource-1.12.2-1.0.15.jar
mowziesmobs-1.5.4.jar
MrTJPCore-1.12.2-2.1.3.35-universal.jar
MyCommands-1.12.2-01.jar
mysticallib-1.12.2-1.1.1.jar
NaturesCompass-1.12.2-1.5.1.jar
NetherPortalFix_1.12.1-5.3.17.jar
Nimble-0.0.2.jar
NoMoreRecipeConflict-0.13(1.12.2).jar
NotEnoughIDs-1.5.4.4.jar
omlib-1.12.2-3.1.0-232.jar
OpenBlocks-1.12.2-1.8.1.jar
OpenModsLib-1.12.2-0.12.2.jar
openmodularturrets-1.12.2-3.1.0-335.jar
OreLib-1.12.2-3.5.2.2.jar
overloadedarmorbar-1.0.4f.jar
Patchouli-1.0-19.jar
phosphor-1.12.2-0.2.4+build46-universal.jar
Placebo-1.12.2-1.6.0.jar
Plants-1.12.2-2.10.7.jar
platforms-1.12.0-1.4.6.jar
Quark-r1.5-152.jar
randomconfigs-1.12.2-1.3.2.3.jar
randompatches-1.12.2-1.15.1.0.jar
RandomThings-MC1.12.2-4.2.7.1.jar
randomtweaks-1.12.2-2.5.0.5.jar
RealBench-1.12.2-1.3.3.jar
reauth-3.6.0.jar
RecurrentComplex-1.4.8.2.jar
RedstoneControl-1.12.2-0.0.4.jar
RedstoneFlux-1.12-2.1.0.6-universal.jar
refinedstorage-1.6.14.jar
refinedstorageaddons-0.4.4.jar
Reliquary-1.12.2-1.3.4.786.jar
rustic-1.1.0.jar
shetiphiancore-1.12.0-3.5.9.jar
signpost-1.12.2-1.08.2.jar
SpartanShields-1.12.2-1.5.3.jar
SpartanWeaponry-1.12.2-beta-1.2.3.jar
stg-1.12.2-1.2.3.jar
TamModized-1.12.2-0.15.6.jar
tesla-core-lib-1.12.2-1.0.15.jar
TheBetweenlands-3.4.6-universal.jar
theoneprobe-1.12-1.4.28.jar
ThermalDynamics-1.12.2-2.5.5.21-universal.jar
ThermalExpansion-1.12.2-5.5.4.43-universal.jar
ThermalFoundation-1.12.2-2.6.3.27-universal.jar
ThermalInnovation-1.12.2-0.3.3.12-universal.jar
tinyprogressions-1.12.2-3.3.32-Release.jar
tnt_utilities-mc1.12-1.2.3.jar
tombstone-3.5.0-1.12.jar
topaddons-1.12.2-1.11.0.jar
twilightforest-1.12.2-3.8.689-universal.jar
V0id's Smart Backpacks-1.0.6.jar
valkyrielib-1.12.2-2.0.20.1.jar
Welcome+To+The+Jungle-1.2001.1222.jar
wirelessutils-1.12.2-1.7.76-universal.jar

**Comment by botaxalim** [comment]
Compability with RecurrentComplex mod
just configure the .minecraft\config\reccomplex.cfg

B:generateNature=false


S:baseSaplingSpawnWeight=0

S:baseWeight_cactus=0

S:baseWeight_tree=0

S:saplingTriggerChance=0

then go to .minecraft\mods
rename RecurrentComplex-1.4.8.2.jar to something like +RecurrentComplex-1.4.8.2.jar
you could change "+" with "A" or "B" or "C" example: BRecurrentComplex-1.4.8.2.jar
as long RecurrentComplex on top from DynamicTrees
to compesate load order in mods folder

if you not renaming the jar there will be a problem with Roofed Forest biome trees
or any mods add that biome such as BiomeOPlenty & DynamicTrees & DynamicTreesBOP

**Comment by ghost** [comment]
Latest version of DT fixes problem without the mid filename rename trick.
