### ISSUE TITLE
Vanilla Trees not Being Replaced

### ISSUE THREAD

**Issue by antontarvo** [ferreusveritas/Dynamic-Trees#268]
I have yet to see the mod trees spawning naturally, i just see vanilla trees. The only way to get the mod acorns is by crafting them or creative mode. I simply create a new world and all trees are vanilla.

I am using forge 14.23.5.2768. Here are my mods:
AdditionalEnderBlocks-2.0-1.12.2
AmbientSounds v2.0.8 mc1.12
ArchitectureCraft-ElytraDev-Mod-1.12.2
Artifice-1.1.2-182
AsmodeusCore-1.12.2-0.0.4
AutoRegLib-1.12.2
Backpacks-Mod-1.12.2
Better-Storage-Too-Mod-1.12.2
BiblioCraft[v2.4.3][MC1.12.0]
BiomesOPlenty-1.12.2-7.0.1.2422-universal
Bookshelf-1.12.2-2.3.557
BuildCraft-Mod-1.12.2
Cave-Generator.zip
CoFHCore-1.12.2-4.6.1.22-universal
DimensionalDoors-3.0.9-287
DynamicSurroundings-1.12.2-3.5.4.3
DynamicSurroundings-1.12.2-3.5.4.3-core
DynamicTrees-1.12.2-0.9.4
DynamicTreesBOP-1.12.2-1.4.1e
EnchantingPlus-1.12.2-5.0.176
Exotic+Birds+1.12.2-2.2.1
ExtraPlanets-1.12.2-0.5.2
Fog-World-Mod-1.12.2
forge-1.12.2-14.23.5.2768
forge-1.12.2-14.23.5.2768.log
Galacticraft-Mod-1.12.2
Galacticraft-Planets-Mod-1.12.2
Gravity-Gun-Mod-1.12.2
Hwyla-1.8.26-B41_1.12.2
iChun-Util-Mod-1.12.2
InventoryTweaks-1.63
IvToolkit-1.3.3-1.12
jei_1.12.2-4.13.1.222
JourneyMap-Mod-1.12.2-Unlimited
Just-Copy-It-Mod-1.12.2
LLibrary-1.12.2
lostcities-1.12-2.0.20
Mantle-Mod-1.12.1
MicdoodleCore-1.12.2
millenaire-1.12.2-7.2.0
MistWorld_1.12.1_alpha_c_03
MJRLegendsLib-1.12.2-1.1.6
movinglightsource-1.12.2-1.0.15
MrCrayfishs-Furniture-Mod-1.12.2
mw-1.11.7.7_mc1.12.2
Natura-Mod-1.12.1
NEIPlugins-1.1.0.6
NetherEx-Mod-1.12.2
NetherPortalFix.zip
OreLib-1.12.2-3.5.2.1BETA
Quark-Mod-1.12.2
reap-1.5.1
RecurrentComplex-1.4.8.2
RedstoneFlux-1.12-2.1.0.6-universal
Redstone-Paste-Mod-1.12.1
SanLib-1.12.1
Secret-Rooms-Mod-1.12.2
SlimeModSSP-1.12.2-2.1
Snow-Accumulation-Mod-1.12.2
Sophisticated-Wolves-Mod-1.12.2
Sound-Filters-Mod-1.12
SubLib-1.12.2
TamModized-1.12.1-0.15.5
tardis-0.0.9B
TelePads-Mod-1.12.2
TheBetweenlands-3.4.4-core
TheBetweenlands-3.4.4-universal
Tinkers-Construct-Mod-1.12.2"
Uncrafting-Table-Mod-1.12.1
VillageInfoSSP-1.12.2-2.1
weeping-angels-37
ToughAsNails-1.12.2-3.1.0.140-universal
tumbleweed-1.11-0.4.4
Twilight-Forest-Mod-1.12.2

**Comment by botaxalim** [comment]
maybe check ur mods list which one change biome world generation trees
try mods one by one until you found the culprit, change their config
for me solved on this topic 
https://github.com/ferreusveritas/DynamicTrees/issues/265#issuecomment-496346056
its compability with reccurent complex,

**Comment by antontarvo** [comment]
> maybe check ur mods list which one change biome world generation trees
> try mods one by one until you found the culprit, change their config
> for me solved on this topic
> [#265 (comment)](https://github.com/ferreusveritas/DynamicTrees/issues/265#issuecomment-496346056)
> its compability with reccurent complex,

I have moved all of my mods to another folder, and still no mod trees. i can still get the mod items in creative, but no trees, so it can't be a compatability issue

**Comment by botaxalim** [comment]
dont reload your save, keep makign new world, since tree dont magically change in your save game when you add dynamic tree
maybe need clear your config, some vanilla biome setting is persist, try make another profile fresh minecraft  with only basic mod (forge, optifine  etc) with only DynamicTrees 0.9.5.

**Comment by antontarvo** [comment]
> dont reload your save, keep makign new world, since tree dont magically change in your save game when you add dynamic tree
> maybe need clear your config, some vanilla biome setting is persist, try make another profile fresh minecraft with only basic mod (forge, optifine etc) with only DynamicTrees 0.9.5.

I did make a new world

**Comment by Deshiba** [comment]
Can you upload your config?
