### ISSUE TITLE
Sand Color shading want to disable DynamicTress for cactus

### ISSUE THREAD

**Issue by botaxalim** [ferreusveritas/Dynamic-Trees#269]
its not a really big deal since im making the texture myself
somehow block under cactus for sand(rooty sand block ) have different shading color
already tinker the BDcraft texture, removing all other mods that have connected texture, reading other topic that have similar problem.
as you stated https://github.com/ferreusveritas/DynamicTrees/issues/188
""I have not yet done this for the rooty sand block since I haven't yet decided if it's worth it""

is there a way i disable only cactus dynamic trees, cause i really hate the colour
https://i.imgur.com/SyW9Qqk.png

**Comment by ghost** [comment]
Set vanillaCactusWorldGen to false in the config file to disable the generation of Dynamic Cactus.
