### ISSUE TITLE
[Feature Request] Configurable tree density

### ISSUE THREAD

**Issue by SpeakerHornet** [ferreusveritas/Dynamic-Trees#270]
Basically this configuration feature would allow for modpack makers and users to define how much spread out are trees. This would allow for better customization and would allow people with lower performance to still enjoy this wondeful mod.

**Comment by ghost** [comment]
Dynamic Trees in ludicrously configurable when you consider the capabilities of <MC dir>/config/dynamictrees/worldgen.json.
The file is empty by default but you can add customization by following this example for it's formatting:
https://github.com/ferreusveritas/DynamicTrees/blob/1.12.2/src/main/resources/assets/dynamictrees/worldgen/default.json

You can do much more than simply changing the forest density.

**Comment by Ronaldo17890** [comment]
Buenas tardes, el mod me funciona casi bien, el unico problema que tengo es que cuando los quiero talar se demoran como 3 minutos en talarse
son muy duros y no se pueden talar facil, me demoro demasiado y tengo entendido que se los tala normalmente y no se demora ni 15 segundos, porque me pasa esto? por favor ayuda
