### ISSUE TITLE
[Feature Request] Better Jungle Trees?

### ISSUE THREAD

**Issue by Mizhok** [ferreusveritas/Dynamic-Trees#271]
The mod looks absolutely amazing, but I've always had a problem with the jungle trees.

I think if you kept the old thinner trees but made them shorter, while adding some thicker trees with the leaf generation from the Acacia or Dark Oak Trees and added some branches and vines along the way, it would improve the mod and the over world around it greatly. 

Again, thank you for such a wonderful mod, it makes modded Minecraft much more tolerable to look at. :)

**Comment by ghost** [comment]
Thank you for the suggestion.  This adds to the pie-in-the-sky plans I have for revamping the jungle biome.
