### ISSUE TITLE
Critical incompat with Dynmap rendering

### ISSUE THREAD

**Issue by Noire86** [ferreusveritas/Dynamic-Trees#273]
**Describe the bug**
Dynmap does not render dynamic trees at all. Just blank places with shadows.

**To Reproduce**
Install Dynmap and DynamicTrees simultaneously

**Screenshots**
![image](https://user-images.githubusercontent.com/9317997/59148215-852ced00-8a0e-11e9-9852-28e422e57c2c.png)

**Comment by Magi1053** [comment]
+1

**Comment by kierajreed** [comment]
This is probably Dynmap not seeing the dynamic blocks and leaving them transparent. That could easily be fixed from their side with an addon or similar.

**Comment by YaibaToKen** [comment]
Afaik this happens with most modded blocks, or at least used to happen. Dynmap doesn't know what texture to use and, in the case of a block that isn't considered a full block, treats it as if it's see-through while, if it's a full block, uses a black texture.

**Comment by Druwan-ctrl** [comment]
Can this be looked into? I really LOVE both mods and it would be amazing seeing dynamic trees in dynmap

**Comment by ghost** [comment]
Unfortunately this is a Dynmap problem.  I can't do anything about it.
