### ISSUE TITLE
Trunkshell and Branch blocks: Inconsistent Break-Time

### ISSUE THREAD

**Issue by IdrisQe** [ferreusveritas/Dynamic-Trees#274]
In the latest 1.12.2 version (0.9.5) I've observed that breaking the bottom block of a tree by hand with no axe is SIGNIFICANTLY faster if said block is a "trunkshell" rather than a large "branch" despite trunkshells being thicker than radius 7 branches. This is not a major issue, given you would still need to be an utter lunatic to try breaking one of these trees by hand, but it's still annoyingly inconsistent as thicker tree parts should take longer to cut, especially with more tree attached.

**Comment by ghost** [comment]
This has been fixed
