### ISSUE TITLE
Black texture on some leaves in Orchard biome?

### ISSUE THREAD

**Issue by Kehaan** [ferreusveritas/Dynamic-Trees#275]
**Describe the bug**
When using DynamicTrees-1.12.2-0.9.5 and DynamicTreesBOP-1.12.2-1.4.1e, Orchard trees from Biomes O Plenty generate in a Lost citites world, with black "leaves" as can be seen on the attached screenshot. Without those 2 mods, the trees generate the leaves just fine. 

**To Reproduce**
Every Orchard Biome have this issue when using the above 2 mods. Also tried new worlds.

**Screenshots**
![2019-06-14_22 05 18](https://user-images.githubusercontent.com/6755642/59535531-8029db00-8ef1-11e9-93d5-4159f87e34ee.png)

**Rendering Glitches**
- I am not using Optifine

**Additional context**
Logs:
[logs.zip](https://github.com/ferreusveritas/DynamicTrees/files/3294012/logs.zip)

**Crashes**
No crashes

**Version Minecraft*
1.12.2 - forge-14.23.5.2838

**Mods List**
+----------------------------+---------------------------------+
| ModID                      | Mod name                        |
+----------------------------+---------------------------------+
| FML                        | Forge Mod Loader                |
| additionalresources        | Additional Resources            |
| advancedrocketry           | Advanced Rocketry               |
| advancedrocketrycore       | Advanced Rocketry Core          |
| advancementbook            | Advancement Book                |
| animania                   | Animania                        |
| apotheosis                 | Apotheosis                      |
| applecore                  | AppleCore                       |
| appleskin                  | AppleSkin                       |
| appliedenergistics2        | Applied Energistics 2           |
| astralsorcery              | Astral Sorcery                  |
| audiodeath                 | Audio Death                     |
| autoreglib                 | AutoRegLib                      |
| baubles                    | Baubles                         |
| bdlib                      | BD Lib                          |
| betteradvancements         | Better Advancements             |
| bettertitlescreen          | Better Title Screen             |
| bibliocraft                | BiblioCraft                     |
| binniecore                 | Binnie Core                     |
| binniedesign               | Binnie's Design                 |
| biomesoplenty              | Biomes O' Plenty                |
| bnbgamingcore              | BnBGamingCore                   |
| bnbgaminglib               | BNBGamingLib                    |
| botania                    | Botania                         |
| botania_tweaks             | Botania Tweaks                  |
| botania_tweaks_core        | Botania Tweaks Core             |
| botany                     | Binnie's Botany                 |
| buildcraftbuilders         | BuildCraft Builders             |
| buildcraftcompat           | BuildCraft Compat               |
| buildcraftcore             | BuildCraft                      |
| buildcraftenergy           | BuildCraft Energy               |
| buildcraftfactory          | BuildCraft Factory              |
| buildcraftlib              | BuildCraft Lib                  |
| buildcraftrobotics         | BuildCraft Robotics             |
| buildcraftsilicon          | BuildCraft Silicon              |
| buildcrafttransport        | BuildCraft Transport            |
| chameleon                  | Chameleon                       |
| chancecubes                | Chance Cubes                    |
| chisel                     | Chisel                          |
| chiselsandbits             | Chisels & Bits                  |
| codechickenlib             | CodeChicken Lib                 |
| controlledburn             | Controlled Burn                 |
| craftstudioapi             | CraftStudio API                 |
| crafttweaker               | CraftTweaker2                   |
| crafttweakerjei            | CraftTweaker JEI Support        |
| ctgui                      | CT-GUI                          |
| ctm                        | CTM                             |
| cucumber                   | Cucumber Library                |
| culinaryconstruct          | Culinary Construct              |
| custommainmenu             | Custom Main Menu                |
| dcs_asm                    | HeatAndClimateASM               |
| dcs_climate                | HeatAndClimateMod               |
| dcs_lib                    | HeatAndClimateLib               |
| defaultworldgenerator-port | Default World Generator         |
| dldungeonsjbg              | Doomlike Dungeons               |
| dynamictrees               | Dynamic Trees                   |
| dynamictreesbop            | Dynamic Trees BOP               |
| dynamictreestc             | Dynamic Trees TC                |
| extendedcrafting           | Extended Crafting               |
| extrabees                  | Binnie's Extra Bees             |
| extratrees                 | Binnie's Extra Trees            |
| extrautils2                | Extra Utilities 2               |
| foamfix                    | FoamFix                         |
| foamfixcore                | FoamFixCore                     |
| forestry                   | Forestry                        |
| forge                      | Minecraft Forge                 |
| gendustry                  | GenDustry                       |
| genetics                   | Binnie's Genetics               |
| gregtech                   | GregTech Community Edition      |
| gtadditions                | Shadows of Greg                 |
| hardcoredarkness           | Hardcore Darkness               |
| headcrumbs                 | Headcrumbs                      |
| hungeroverhaul             | Hunger Overhaul                 |
| iceandfire                 | Ice and Fire                    |
| immersiverailroading       | Immersive Railroading           |
| infernalmobs               | Infernal Mobs                   |
| inventorypets              | Inventory Pets                  |
| inventorytweaks            | Inventory Tweaks                |
| itlt                       | It's the little things          |
| jei                        | Just Enough Items               |
| jeibees                    | JEI Bees                        |
| jeiintegration             | JEI Integration                 |
| journeymap                 | JourneyMap                      |
| justenoughdimensions       | Just Enough Dimensions          |
| libvulpes                  | Vulpes library                  |
| livingenchantment          | Living Enchantment              |
| llibrary                   | LLibrary                        |
| lostcities                 | The Lost Cities                 |
| lostsouls                  | Lost Souls                      |
| magicbees                  | MagicBees                       |
| mainmenuscale              | Main Menu Scale                 |
| mantle                     | Mantle                          |
| matteroverdrive            | MatterOverdrive: Legacy Edition |
| mcjtylib_ng                | McJtyLib                        |
| mcp                        | Minecraft Coder Pack            |
| meecreeps                  | MeeCreeps                       |
| minecraft                  | Minecraft                       |
| mob_grinding_utils         | mob_grinding_utils              |
| modtweaker                 | Mod Tweaker                     |
| mousetweaks                | Mouse Tweaks                    |
| mtlib                      | MTLib                           |
| mtrm                       | MineTweakerRecipeMaker          |
| mysticalagradditions       | Mystical Agradditions           |
| mysticalagriculture        | Mystical Agriculture            |
| placebo                    | Placebo                         |
| plants2                    | Plants                          |
| psi                        | Psi                             |
| quark                      | Quark                           |
| reborncore                 | Reborn Core                     |
| redstoneflux               | Redstone Flux                   |
| resourceloader             | Resource Loader                 |
| rftools                    | RFTools                         |
| rftoolsdim                 | RFTools Dimensions              |
| roughtweaks                | Rough Tweaks                    |
| rustic                     | Rustic                          |
| rusticthaumaturgy          | Rustic Thaumaturgy              |
| spiceoflife                | The Spice of Life               |
| storagedrawers             | Storage Drawers                 |
| tcinventoryscan            | Thaumcrafft Inventory Scanning  |
| tconstruct                 | Tinkers' Construct              |
| tellme                     | Tell Me                         |
| thaumcraft                 | Thaumcraft                      |
| thaumicenergistics         | Thaumic Energistics             |
| thaumicjei                 | ThaumicJEI                      |
| thaumicperiphery           | Thaumic Periphery               |
| thebetweenlands            | The Betweenlands                |
| theoneprobe                | The One Probe                   |
| tinkertoolleveling         | Tinkers Tool Leveling           |
| tips                       | Tips                            |
| trackapi                   | Track API                       |
| triumph                    | Triumph                         |
| twilightforest             | The Twilight Forest             |
| weirdinggadget             | The Weirding Gadget             |
| worldstripper              | World Stripper                  |
| zensummoning               | Zen Summoning                   |
+----------------------------+---------------------------------+
| ModID                      | Mod name                        |
+----------------------------+---------------------------------+

**Comment by kierajreed** [comment]
Please edit your issue to have more information than just a screenshot and remove placeholders.

**Comment by Kehaan** [comment]
> Please edit your issue to have more information than just a screenshot and remove placeholders.

Ok, that was embarrassing. I guess i did not correctly add the info xD As i had written it all, haha. Sorry.
Have added text now.

**Comment by Kehaan** [comment]
Also a update. I removed all mods, and only have BiomesOPlenty-1.12.2-7.0.1.2439-universal, DynamicTrees-1.12.2-0.9.5, DynamicTreesBOP-1.12.2-1.4.1e, lostcities-1.12-2.0.20 in. And it still does the strange rendering of the leaves. Here is a newer log with only those 4 mods in, in a new world:
[logs.zip](https://github.com/ferreusveritas/DynamicTrees/files/3294062/logs.zip)

**Comment by kierajreed** [comment]
Also, please use [hastebin](https://hastebin.com/) for error logs and stack traces to make it so that people don't need to download files.

**Comment by Kehaan** [comment]
> Also, please use [hastebin](https://hastebin.com/) for error logs and stack traces to make it so that people don't need to download files.

I was not sure, which of the logs from the logs folder, that was needed. So i thought it was better to just upload them here, than use pastebin or hastebin :)

**Comment by ghost** [comment]
This bug only shows up when the leaves rendering is set to fast.  It's also not a bug in the Dynamic Trees base mod but instead the Dynamic Trees BoP add-on.
