### ISSUE TITLE
[Question/bug] Item ID for dynamic trees leaves?

### ISSUE THREAD

**Issue by Winddbourne** [ferreusveritas/Dynamic-Trees#276]
I'm having a problem . . . I use scavenge to make tree leaves drop sticks and other items and since you replace the leaves it isn't working. Apparently, dynamic tree leaves aren't ore dictionaried to be leaves so other mods can recognize the blocks and respond correctly.

It should be an easy fix to just add the blocks to the ore dictionary but I can't grab one in creative mode to get the ID. lol.  I could even make specific scavenge code just for these blocks if I knew the right ID to use! Unfortunately, it's hidden at the moment.

**Comment by Winddbourne** [comment]
I managed to find the ID using the one probe in it's most descriptive mode . . . weirdly all the trees seem to share the same ID: Leaves0, and the BOP branch does the same thing just changing the mod name in front . . . it's very weird but I got my scavenge code working.

I'll leave this up here for now in case anyone else has the same problem, and so that you can read it and think about whatever changes might be made to make this more clear and simple for pack makers. :)

**Comment by Nolij** [comment]
Anyone have the numeric ID? Would be much appreciated.

**Comment by ghost** [comment]
Modded Minecraft no longer works with static item ids and hasn't for years.  Forge now assigns these serially per game world so they will vary.  The ids are stored in the level.dat file.  You'll have to use a mod like "the one probe" like Winddbourne did.
