### ISSUE TITLE
Suggestion: Dynamic Trees Combat for silkworms from ex:nihilo creatio

### ISSUE THREAD

**Issue by SirAron111** [ferreusveritas/Dynamic-Trees#278]
Is there a way to make the dynamic trees leaves compatible with silkworms from ex:nihilo creatio?

**Comment by SirAron111** [comment]
https://github.com/BloodyMods/ExNihiloCreatio/issues/244

**Comment by ghost** [comment]
I'm pretty sure it's incompatible by the way the leaves in Dynamic Trees regenerate constantly.  At any rate the leaves should just need to be detected by their blockstate and properties.  Nothing fancy needed.  I think that ex:nihilo just replaces leaves block with an infested one if I'm not mistaken.
