### ISSUE TITLE
Random ConcurrentModificationException crash while exploring.

### ISSUE THREAD

**Issue by Yldales** [ferreusveritas/Dynamic-Trees#283]
Hi,

**Describe the bug**
Randomly (we still trying to find when, exactly) when exploring the world, the Minecraft client crash with a ConcurrentModificationException error.

**To Reproduce**
1. Explore the world, but, well... this is very random.

**Screenshots**
None.

**Crash Report**
https://pastebin.com/raw/vrtT5maT

**Rendering Glitches**
Are you using Optifine?
Yes. OptiFine_1.12.2_HD_U_E3.

**Additional context**
Our world is generated using the mod Painted Biomes.

**Crashes**
- Are you running the latest version of Dynamic Trees?
Yes (1.12.2-0.9.5).
- If you are using the DT Biome O' Plenty Add-on do you have the latest version?
Yes (1.12.2-1.4.1e).
- If you are using the DT Thaumcraft Add-on do you have the latest version?
No.

We're also using the DT PHC Addon-on versiong 1.12.2-1.4.2.

**Mods List**
Included in the crash report.

What version of Forge are you running?
Forge 1.12.2-14.23.5.2838

**Comment by ghost** [comment]
Fixed. Same as #373
