### ISSUE TITLE
Rendering falling tree crash

### ISSUE THREAD

**Issue by Erosion139** [ferreusveritas/Dynamic-Trees#284]
Using ICBM explosives with dynamic trees results in a crash due to a rendering error. 

[https://paste.dimdev.org/dizicacupo.mccrash]

To reproduce the crash you will need to set off a red matter explosive in a dynamic forest. As the radius of the crater expands the trees around it break and anyone in the general area gets this crash. The server is fine during this (obv because rendering error) but some clients need to go as far as to reinstall the entire game in order to fix the crash when they join. This is very likely because some players have very low-end systems. Mine is fine after I do a server rollback. 

As of right now I quickly looked over the client settings in the configs and saw a falling tree enabled option. I will try to disable this to see if that fixes the crash. 
After disabling it didnt fix the issue. The crash still persists with the same entity falling tree error.

**Comment by Erosion139** [comment]
To be clear my system has higher-end specs (R5 1600x GTX 1070) and I still get this crash.

**Comment by TynotWolfDragon** [comment]
Appologies if I am doing this wrong, But I am also having the same issue. although, I dont have a red matter bomb in my pack, and its on 1.12.2. [https://pastebin.com/ngQt1xC7]

update, this happens when i am not cutting down trees too.

**Comment by Erosion139** [comment]
This seems to be caused by non player entities destroying the tree. I have no clue why this happens as I suspect (I have not tested this) normal TNT and Creepers should break the trees without issue. I have however also encountered regular players break the tree and have it happen to them as well. As well as everyone else within render range.

**Comment by ghost** [comment]
This is fixed. Same as #367
