### ISSUE TITLE
Branch Destruction Crash

### ISSUE THREAD

**Issue by WenXin20** [ferreusveritas/Dynamic-Trees#293]
**Describe the bug**
As I was away from my computer at the time of this crash, I'm unsure as to what caused the crash. But I do have a Lumberjack from Minecolonies that was going around chopping trees down. There were Dynamic Spruce trees around that I assume he was trying to chop down. There were also Acacia, Orange Autumn Oak, Red Autumn Oak, and Autumn Yellow Birch trees around.

**To Reproduce**
(Tentative) Steps to reproduce the behavior:
1. Hire a lumberjack
2. Have him cut down dynamic trees.

**Rendering Glitches**
Are you using Optifine? Yes

**Crashes**
- [Crash Log](https://paste.dimdev.org/elacowizut.mccrash)
- DT v0.9.5
- DT BOP v1.4.1e
- DT Traverse v1.5
- DT Climatic Biomes v1.3.0
- Minecolonies v0.10.334-Alpha

**Comment by kierajreed** [comment]
Known crash when a non-player entity breaks a branch.

**Comment by ghost** [comment]
This is fixed.
