### ISSUE TITLE
Option to disable tree felling?

### ISSUE THREAD

**Issue by Boymann** [ferreusveritas/Dynamic-Trees#294]
I'm trying to balance felling trees, and I used the mod Felling to add an enchant which makes it available. The trees from your mod get completely destroyed even when punched with bare hands. Could we get an option to turn off tree felling from your mod? Or some sort of an alternative? It's kind of OP right now imho.

**Comment by kierajreed** [comment]
The tree felling is how the mod is designed. If you don't like that, get a different mod.
