### ISSUE TITLE
Weird trees generating near AE2 meteors.

### ISSUE THREAD

**Issue by Octaeon** [ferreusveritas/Dynamic-Trees#295]
Description:
When trees are generated near meteors from AE2, the tree generation gets funky. Sometimes the trees are disjointed and floating single blocks have to be chopped down individually(the collision detection on the individual floating blocks is strange too). Also, there are some instances where the tree will generate and then will be chopped down just as it generated because a meteor presumably generated on top of it. In that instance, the tree will disappear and just the items it would drop upon being chopped down will remain.

To reproduce:
Generate a world using both Dynamic Trees and AE2, and find a meteor site. The trees near said meteor will be what I described earlier.

Screenshots:
![2019-08-04_18 41 47](https://user-images.githubusercontent.com/52536877/62426653-dcd29680-b6e7-11e9-96c2-c1d708c6dd23.png)
![2019-08-04_18 42 07](https://user-images.githubusercontent.com/52536877/62426654-e0feb400-b6e7-11e9-93b2-2b7860de299e.png)
![2019-08-04_18 39 49](https://user-images.githubusercontent.com/52536877/62426645-d17f6b00-b6e7-11e9-9fcb-fa3196285a4c.png)

The bug does not cause a crash.

**Comment by kierajreed** [comment]
This is probably due to AE2 meteors overwriting trees. A workaround is to try and generate as late as possible, but another better way is to validate all trees after other mods generate their structures.

**Comment by ghost** [comment]
Issue with AE2 incompatibility #440

**Comment by Jordankcarney** [comment]
Could trees also check a chunk before generating to see if a meteor will generate and not spawn within a radius of that chunk?
