### ISSUE TITLE
Plains and other Biomes are filled with Dynamic Trees

### ISSUE THREAD

**Issue by stormbringerGT** [ferreusveritas/Dynamic-Trees#296]
**Describe the bug**
The Plains Biome spawns filled with trees similar to a forest biome
BoP Meadow Biome has the same issue

**To Reproduce**
Start up a new world with the Dynamic Trees mod loaded and travel to a plains biome

**Mods List**
Dynamic Trees
Biomes O Plenty
Dynamic Trees Biomes O Plenty Compat

**Comment by ghost** [comment]
Can not reproduce this issue.
