### ISSUE TITLE
[BUG] Minecraft failed to start

### ISSUE THREAD

**Issue by sambm775** [ferreusveritas/Dynamic-Trees#297]
So hello everyone,
I enjoy playing a modded Minecraft game (with Dynamic Trees obviously) but my game couldn't crash and I don't know how to spot a problem in a crash log.

I am using DT 1.5, the last version available for 1.12.2

When Forge loads my mods, at the end he displays a crash error (see the screenshot below).

Maybe something significant : I allow 8 GB of RAM to Java

[image](https://user-images.githubusercontent.com/53912802/62722367-8ed2d100-ba0e-11e9-8e54-3fb2393cbbfd.png)

I am using the last official release of OptiFine, the HD_U_E3

Here are the DT mods I'm using (all are the most recent versions available) :
- Dynamic Trees 0.9.5
- DT Biome O' Plenty Add-on 1.4.1e
- DT Pam's HarvestCraft Add-on 1.4.2
- DT Traverse 1.5

I'm running on the last version of Forge, the forge1.12.2-14.23.5.2838

***************

Here is the full crashlog :

[crash-2019-08-08_18.47.53-client.txt](https://github.com/ferreusveritas/DynamicTrees/files/3482876/crash-2019-08-08_18.47.53-client.txt)

**Comment by kierajreed** [comment]
Please use [pastebin](https://pastebin.com/) for error logs and stack traces.

**Comment by sambm775** [comment]
So i tried to make a paste, here it is : https://pastebin.com/UXw6x4cp

**Comment by ghost** [comment]
You are using a very outdated version of DT.  This bug has been fixed in later versions.  Upgrade to latest.
