### ISSUE TITLE
An option to remove huge mushrooms

### ISSUE THREAD

**Issue by Leggerrr** [ferreusveritas/Dynamic-Trees#299]
Add in an option to turn off or remove huge mushrooms in the config file. Currently, there's no _easy_ way of removing the huge mushrooms while Dynamic Trees is installed. This creates compatibility issues with mods that control world generation.

**Comment by ghost** [comment]
Something like this in your config/dynamictrees/worldgen.json file should disable giant mushrooms in mushroom type biomes:
```
[
  {
    "select": {
      "type": "mushroom",
      "name": "minecraft:.*"
    },
    "apply": {
      "cancelvanilla": false,
      "chance": 0
    }
  }
]
```
