### ISSUE TITLE
Server crash with GrowingTrees-1.7.10-0.5.1

### ISSUE THREAD

**Issue by CaptGates** [ferreusveritas/Dynamic-Trees#3]
From what I can tell googling the crash it's caused from particle spawning being called server side.

[Crash File](https://www.dropbox.com/s/y9jb1jvc7593jvv/crash-2017-08-23_10.23.16-server.txt?dl=0)

**Comment by ferreusveritas** [comment]
You are correct.  I've moved the particle spawning code to the client proxy.  Just checking for client side wasn't enough, the function itself cannot exist on the server.   I'll test this when I get home and post an update hopefully tonight.

**Comment by CaptGates** [comment]
Fixed in GrowingTrees-1.7.10-0.5.2.jar
