### ISSUE TITLE
I can't chop trees in survival mode

### ISSUE THREAD

**Issue by some0ne3** [ferreusveritas/Dynamic-Trees#300]
If i try to cut tree i can't see any progress of it, only in creative mode

**Comment by kierajreed** [comment]
Please provide a mod list and versions.

**Comment by some0ne3** [comment]
![image](https://user-images.githubusercontent.com/53973517/62857695-8c1af900-bcf8-11e9-8c32-009d83712054.png)

**Comment by kierajreed** [comment]
Try doing a binary search to find the offending mod. Especially consider mods which interact with block breaking - here it's TreeChopper.

**Comment by some0ne3** [comment]
I downloaded treechopper when i was sure that DynamicTress don't work so it's not that. Can you please tell me how to do binary search? I am new in minecraft mods.
