### ISSUE TITLE
No dynamic trees generate on server

### ISSUE THREAD

**Issue by MochaMoth** [ferreusveritas/Dynamic-Trees#301]
**Describe the bug**
Trees generate fine on single player worlds, but won't generate on server worlds.

**To Reproduce**
Create a new server using forge 1.12.2-14.23.5.2837 and add Dynamic Trees to the mod directory. After starting the server, log in with a client running the same forge version with Dynamic Trees and enter the server world. Only vanilla trees are present.

**Additional context**
I did not read anything on the Curseforge page about this only being a single player mod, so I'm assuming there is some kind of bug preventing dynamic trees from spawning on the hardware server.

**Mods List**
DynamicTrees - 1.12.2-0.9.5

**Forge Version**
1.12.2-14.23.5.2837

**Comment by MochaMoth** [comment]
Actually, I was running the wrong server jar file. Looks like it's running just fine.

**Comment by tonicwraith** [comment]
what do u mean
?
