### ISSUE TITLE
 Suggestion: add compatibility for Ice and Fire Dragons to be able to knock trees over.

### ISSUE THREAD

**Issue by SirAron111** [ferreusveritas/Dynamic-Trees#303]
Suggestion: add compatibility for Ice and Fire Dragons to be able to knock trees over.

Currently the Big mighty Dragons get stuck on the trees all the time since the leaves and branches re grow faster than the dragon breaks them.

Is it possible to make it so if a Big Monster like a Dragon a wither or any other boss like mob touches the Trees even just the leaves they fall over?

https://github.com/Alex-the-666/Ice_and_Fire/issues/1728

**Comment by ghost** [comment]
Fixed in Ice and Fire (Thank you Alex-the-666!)
