### ISSUE TITLE
Strange console spam even with just dyn trees installed.

### ISSUE THREAD

**Issue by SirAron111** [ferreusveritas/Dynamic-Trees#304]
Strange console spam even with just dyn trees installed.

I get some strange console spam when generating new chunks.

Basically it tells me in the logs like a billion times that it tried to remove the entity falling tree but it was already removed. Only happens when new chunks generate and is especially prominent on servers.

**Comment by Deadlock783** [comment]
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already
> [19:30:26] [Server thread/WARN] [minecraft/WorldServer]: Tried to add entity dynamictrees:falling_tree but it was marked as removed already

**Comment by Deadlock783** [comment]
https://www.dropbox.com/s/eo9m3687r07rf8v/latest.log?dl=0

**Comment by SirAron111** [comment]
Yep that’s exactly what I was talking about. Good I am not the only one with the issue.

**Comment by KiritoSan223** [comment]
I guess nothing ever happened here :D I have the same problem, but every time it occurs all items on the ground are being deleted

**Comment by kierajreed** [comment]
*Move conversation to #365. It's being discussed in more detail there.*
