### ISSUE TITLE
Suggestion: Forest density options.

### ISSUE THREAD

**Issue by SirAron111** [ferreusveritas/Dynamic-Trees#305]
Since the Mod is pretty demanding I think it would be a nice thing to have a better config option to allow deciding a rough amount of tree density.

So you could say set it so less tress generate or for crazy people more. Since every changing block or updating tree in a chunk that is loaded will need chunk re:rendering and data management this could improve playability by a ton for lower end machines/heavy modpacks/servers.

Depending on how the config will be set uo you could make it so a general tree spawn rate divider/multiplier is used or even a biome type specific one (could also lead to some really funny customizability like super tree mountains XD).

But even the simply divider/multipler would already be a life safer.

PS: The Dynamic trees are one of the best things that happened to modded minecraft in terms of improving world visuals. Gj on that Mod.

GZ
SirAron

**Comment by ghost** [comment]
This is implemented with the dynamic trees worldgen.json file.  It's has the power to do everything you mentioned and more.  However it's poorly documented at the moment.  
Here are examples:
https://github.com/ferreusveritas/DynamicTrees/blob/1.12.2/src/main/resources/assets/dynamictrees/worldgen/default.json
https://github.com/the-realest-stu/DynamicTrees-BOP/blob/master/src/main/resources/assets/dynamictreesbop/worldgen/default.json
