### ISSUE TITLE
Option to get more XP with Tinkers Tool Leveling

### ISSUE THREAD

**Issue by rlnt** [ferreusveritas/Dynamic-Trees#307]
**Describe the bug**
When you destroy the bottom block of a dynamic tree with a tinker hatchet, it works like normal and the tree falls and you get the resources. Also there is more durability taken from the hatchet than when you would break a single log. However with Tinkers Tool Leveling, you only get 1XP from that one block you harvested. It would be cool to have an option to get XP for the whole tree. It's also like that with the durability already so why not with the XP?

**To Reproduce**
- craft a TConstruct hatchet
- smack a dynamic tree until it falls
- check the durability and XP values

**Additional context**
I don't see this as an actual bug but it would be a nice feature to have.

**Comment by AllieWade** [comment]
I, too, would love this feature.

**Comment by ghost** [comment]
I don't really understand how this system works.  If someone could explain it more.  Do you basically just get XP for cutting down trees?

**Comment by rlnt** [comment]
> I don't really understand how this system works. If someone could explain it more. Do you basically just get XP for cutting down trees?

Didn't expect to have an issue reopened that is one year old but this would still be cool.
So basically Tinker's Tool Leveling rewards the player for using the tool. All tools that are made with Tinker's Construct collect XP during working with it. It depends on the type of tool of course.
You can level your pickaxe by breaking stone, ores and stuff. So basically what the tool is made for.
Currently you only get 1 XP for the log you chop because you technically only harvest one block but it would be cool if you are rewarded for the whole tree.

**Comment by ghost** [comment]
I see.  We now have a Tinkers Construct add-on mod for DT.  I'll move this issue over to it so it can possibly get this feature added.

**Comment by ghost** [comment]
moved issue to supermassimo/DynamicTrees-ExC#40
