### ISSUE TITLE
Divide by Zero with Optifine

### ISSUE THREAD

**Issue by Edrein** [ferreusveritas/Dynamic-Trees#308]
I'm trying to run Dynamic Trees and Optifine in a modpack, however every time you go to boot up the client you get a divide by zero error.

If I remove Optifine it launches and loads fine. If I remove Dynamic Trees it launches and loads fine. When they are both in the pack the issue occurs.

https://paste.dimdev.org/atimarenab.mccrash

**Comment by kierajreed** [comment]
This is a known bug: #290.
