### ISSUE TITLE
(suggestion) Conquest Reforged Compat

### ISSUE THREAD

**Issue by HiveHD** [ferreusveritas/Dynamic-Trees#312]
A compatibility update for CR would be amazing! or is there any kind of documentation anywhere to guide me on how I can create a compat myself?

Conquest reforged is an incredible aesthetic and immersive overhaul to minecraft. 
But the immersion is quickly broken when you break a tree and get fence or pillar blocks.
Its also painful having to destroy each individual block of a sprawling tree only to leave behind floating logs, leaves and branches (that are actually fence blocks again).

Its also painful early game to destroy the small trees and only get fence blocks that you can't craft a workbench with.

Dynamic trees would literally make this the perfect experience. The trees would look better, the small trees would actually be small trees on not fences with leaves, the big trees would be way better looking with actual connecting branches and logs and having the ability to prune them back using dynamic trees branch cutting would be incredible.

**Comment by kierajreed** [comment]
Sadly, there is no documentation for making addons, but you can see examples [here](https://github.com/ferreusveritas/DynamicTrees-PHC) and [here](https://github.com/the-realest-stu/DynamicTrees-BOP) as well as joining [the discord](https://discord.gg/hn2pGEV) for extra assistance.
