### ISSUE TITLE
Cactus Only Placeable on Vanilla Sand

### ISSUE THREAD

**Issue by Celestial-Vixen** [ferreusveritas/Dynamic-Trees#313]
Cactus Seeds cannot be placed on non-vanilla sands, even those from mods correctly applying the 'sand' oredict tag. 
 MC Version 1.12
Mods Tried: Underground Biomes.

**Comment by kierajreed** [comment]
Even S-N-A-D?


This is probably a quick fix to a check somewhere. Or not, if the placement system is compex.
