### ISSUE TITLE
Suggestion: Tektopia Lumberjack compatibility

### ISSUE THREAD

**Issue by SamuraiShogun1102** [ferreusveritas/Dynamic-Trees#315]
Even since the new villager mod, Tektopia by Tango Tek came out, I wonder if you can make the dynamic trees compatible with tektopia so that the lumberjacks can cut it down, get resources, and replant them.

**Comment by YaibaToKen** [comment]
I have a feeling though that this might have to be done on Tango Tek's side. Either way, I second this suggestion.

**Comment by kierajreed** [comment]
It would require them to be able to:
- Detect Dynamic Trees
- Plant Dynamic Saplings

Both of those are difficult to implement from only one side.

**Comment by YaibaToKen** [comment]
I stand corrected

**Comment by kierajreed** [comment]
It's still quite doable, but it would require TangoTek to help with at least some bits.

**Comment by CoDrie** [comment]
Any updates on this topic? Haven't found any package for now.
