### ISSUE TITLE
Pam's dynamic trees change from type, back to a default tree.

### ISSUE THREAD

**Issue by 2iguys** [ferreusveritas/Dynamic-Trees#316]
**Describe the bug**
When growing pam's harvestcraft trees (dynamic compat installed) they change themselves during the growth stage, from the fruit tree you planted, back to a default tree, whether it be jungle or oak.

**To Reproduce**
1. plant a pams harvestcraft (dynamic tree) seed
2. wait for it to grow
3. observe as it changes from fruit to not fruit tree.

**Screenshots**

**Rendering Glitches**
Are you using Optifine? = no

**Additional context**
if you bone-meal the trees from the seedling till full growth, the issue is not there, it is only during the natural growth of the tree that it transitions out of its fruit varient.

**Crashes**
- Are you running the latest version of Dynamic Trees?(Currently 0.9.5) = YES
- If you are using the DT Biome O' Plenty Add-on do you have the latest version?(Currently 1.4.1e) = YES
- If you are using the DT Thaumcraft Add-on do you have the latest version?(Currently 1.4.1e)
If the above mods are current then please submit a full crash log.  The crash log normally contains the names of mods and their versions.  Don't be that guy who submitted a crash report without first checking that the versions are current.

**Mods List**
If your crash log does not contain a list of mods or you have no crash log then please provide a full list of the mods you are using complete with mod versions.
What version of Forge are you running?(e.g. 1.12.2-14.23.5.2768)
>!
             Modlist
===================
Akashi Tome
AppleSkins
Applied Energistics 2
Baubles
Bibliocraft
Biomes O Plenty
Blood Magic
Botania
Chest Transporter
Chisel-MC
Cooking for Blockheads
Draconic Evolution
Dynamic Trees
Dynamic Trees - Biomes O' Plenty Compat
Dynamic Trees - Pams Harvestcraft Compat
Dynamic Trees - Thaumcraft Compat
Ender IO
Extra Utilities
Extreme Reactors
Farming for Blockheads
Iron Backpacks
Iron Chests
Journeymap
Just Enough Resources (JER)
Mekanism
Mekanism Generators
Mekanism Tools
Open Blocks
Pam's Get All the Seeds
Pam's HarvestCraft
Redstone Flux
RF Tools
RF power
Just Another Snad
Thaumcraft
Thaumatic Inventory Scanning
Thaumic Tinkerer
Thermal Cultivation
Thermal Dynamics
Thermal Expansion
Thermal Foundation
Thermal Innovation
Tinkers Construct
Tinkers' Tool Leveling
VeinMiner

>!        Mod Dependencies
===================
AutoRegLib
BrandonCore
CoFHCore
CoFHWorld
CTM-MC
CodeChickenLib
Mantle
mcjtylib
OpenModsLib
EnderCore

>!CLIENT-SIDE MODS
===================
Not Enough Items
Just Enough Items
HWYLA
Thaumic JEI
WAILA Harvestability

**Comment by ghost** [comment]
Sorry it took so long to get back to you.  I tried several attempts at reproducing this error.  In all tests I was able to produce a mature fruit bearing tree without the use of bonemeal(just time).  None of the trees lost their identity no matter what I tried.  If you are still experiencing the problem with the latest version of Dynamic Trees then please resubmit this issue after running your own tests that have suspect mods temporarily removed in case it's a mod interaction.  If you find a mod interaction issue then I'll likely be able to resolve it.
