### ISSUE TITLE
Broken Texture Vines(?) on certain dynamic trees.

### ISSUE THREAD

**Issue by brisingraerowing** [ferreusveritas/Dynamic-Trees#317]
**Describe the bug**
Some blocks that hang from trees have a broken texture (TOP shows them as vines).

**To Reproduce**
Not sure how to reproduce. It seems to happen wherever trees with vines spawn.

**Screenshots**
![2019-09-16_22 54 26](https://user-images.githubusercontent.com/250409/65007804-36c49f80-d8d5-11e9-88dd-4de59c7a8e62.png)

**Rendering Glitches**
Are you using Optifine? No

**Additional context**
F3 says I'm looking at 'minecraft:air' with direction blockstates listed underneath it.

**Crashes**
- Are you running the latest version of Dynamic Trees? Yes (0.9.5)
- If you are using the DT Biome O' Plenty Add-on do you have the latest version?(Currently 1.4.1e) Yes
- If you are using the DT Thaumcraft Add-on do you have the latest version?(Currently 1.4.1e) N/A

**Mods List**
[Mod List](https://gist.github.com/BrisingrAerowing/ac6a03801239a539b2cce83980dfc116)

**Comment by brisingraerowing** [comment]
It gets even weirder:
![2019-09-16_23 09 38](https://user-images.githubusercontent.com/250409/65008362-185fa380-d8d7-11e9-8e47-2e3b4a2f022f.png)

**Comment by ghost** [comment]
I'm most strongly suspicious that your level.dat file has been corrupted at some point.  To test this make a new separate world and see if you get the same behaviour.

**Comment by brisingraerowing** [comment]
I forgot I had posted this. I ended up having similar issues on multiple worlds without Dynamic Trees installed, and they went away after I updated a bunch of mods.
