### ISSUE TITLE
better foliage

### ISSUE THREAD

**Issue by AlexRover** [ferreusveritas/Dynamic-Trees#32]
![2018-01-04_18 33 41](https://user-images.githubusercontent.com/34899332/34561766-24a1d272-f17e-11e7-8713-cb8ce13f79f2.png)
![2018-01-04_18 33 53](https://user-images.githubusercontent.com/34899332/34561775-2d842f84-f17e-11e7-8ffe-77514eddab59.png)
Hello, and the leaves do not quite understand where they are supposed to grow from

**Comment by ghost** [comment]
What exactly is the problem?  Because I can't tell what you're trying to convey from the screenshots.

**Comment by AlexRover** [comment]
Do not you get confused by oak particles on the spruce leaves? And spruce on birch?)

**Comment by ghost** [comment]
Okay sure.  But I have to wonder how better foliage is deciding how to decorate the leaves at all.  My leaves don't work like that.  If I had to guess I'd say that better foliage is reading the metadata bits 00XX to determine the type of species it is and decorating it with that in mind.  I use those bits to store hydration data for cell automata.  My species bits are on XX00.  Unless better foliage has some kind of API there's absolutely nothing I can do about this.

**Comment by AlexRover** [comment]
it is sad
