### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by lancce-Wolf** [ferreusveritas/Dynamic-Trees#320]
hey everyone,

so, my server randomly crashes with *Exception in server tick loop*
without anything special and it seems like dynamic trees is causing this issue.

**To Reproduce**
It seems like its the world but i cant tell exactly whats causing this.
(crash log says that it has something to do with the event "falling tree")
It happens at total random, most of the time it happens when i log in, but i'm able to play a bit.
Sometimes for just 5 minutes and other times for like an hour or more. but it even crashed in the middle of the night without anyone being online.

Currently running:
- DynamicTrees-1.12.2-0.9.5
- DynamicTreesBOP-1.12.2-1.4.1e
- DynamicTreesPHC-1.12.2-1.4.2.jar
- DynamicTreesTC-1.12.2-1.4.1e

**Mods List**
Its a custom modpack but a mod list is in the crash log. if more information is needed please tell me.
[crash-2019-09-20_16.35.55-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/3636447/crash-2019-09-20_16.35.55-server.txt)
thank you in advance for helping me.

PS: *if this here takes too long i simply gonna wipe the server world.*

**Comment by ghost** [comment]
This should be fixed in the latest DT version.  I know this issue is hopelessly out of date.  Sorry about that.  Life happens.
