### ISSUE TITLE
[Incompatibility] Clearing drop list from HarvestDropsEvent prevents trees from dropping logs

### ISSUE THREAD

**Issue by theishiopian** [ferreusveritas/Dynamic-Trees#321]
Greetings, I am the developer of a mod called Liquid Luck that alters block drops based on the player's luck. I do this using the harvestDropsEvent, and as part of the process I clear the drops list of the event so I can refill it with drops that are calculated in my code. It has recently been brought to my attention that this seems to break your mod's ability to drop logs from fallen trees. I am working on a workaround on my end, but other mods that use HarvestDropsEvent might run into similar issues.

**Comment by ghost** [comment]
Thanks.  If you haven't figured this out by now then drop me a line and maybe we can work it out.
