### ISSUE TITLE
[Suggestion] Configurable Soil Life multiplier

### ISSUE THREAD

**Issue by YaibaToKen** [ferreusveritas/Dynamic-Trees#323]

**Comment by ghost** [comment]
Thank you for the suggestion.  The tree growth is already balanced with the existing soil life in mind and to add an option such as this will only result in improper growth behavior.

**Comment by YaibaToKen** [comment]
I was mostly looking for a simple way to make trees be able to grow (unreasonably) big, in a natural way. However, it having been considered not worth the effort, I respect the decision and appreciate the response.
