### ISSUE TITLE
Server timing out when chopping tree's down

### ISSUE THREAD

**Issue by Wisain** [ferreusveritas/Dynamic-Trees#325]
**Describe the bug**
When you chop tree's down the server can freeze or time everyone out. Then it gets hung up and has to be forcefully restarted. Seems to happen randomly when cutting tree's down. Thought it was just going to fast but now it appears to just happen if a tree is in your way.

**To Reproduce**
Grow or find some of the Dynamic Tree's, cut them down one after the other or just randomly cut them down

**Screenshots**
https://i.imgur.com/DX5NFdU.png

**Rendering Glitches**
No visual issue, tree will fall as normal even if the server freezes

**Additional context**
Using 

**Crashes**
Server is not crashing but rather freezing and timing everyone out. Then it will just stay hung for a while until you force restart it or have a timer to restart it.
https://i.imgur.com/BZhfnrs.png

**Mods List**
Using the current RLCraft pack version 2.6.3
Went ahead and reported this to him as well in case it was a pack issue.

**Comment by ghost** [comment]
Thanks for the report but we'll need a better log of the event, hastebin or similar is preferred.  A picture of the log is as bizarre as it is useless.  Also try upgrading DT to 0.9.6 to see if that corrects the problem.
