### ISSUE TITLE
Server Creating Dynamic Tree Do Not Render

### ISSUE THREAD

**Issue by TheUssLoliChan** [ferreusveritas/Dynamic-Trees#326]
**Describe the bug**
When creating a custom/home server dynamic tree mod does not render in correctly... it only shows the normal minecraft tree's but with the time it takes to mine the tree with the mod.... and still get the wood... but each piece takes the same amount of time.

create a server with the RLCraft, modpack and join the world.... it refuses to load in the mod.... 

psa, i do not write very well....

**Comment by ghost** [comment]
I'm sorry, I don't quite understand what the problem is.  Perhaps a screenshot?

Edit: Did you add the mod to an existing world that already had trees in it?

**Comment by ghost** [comment]
I couldn't parse this problem as it makes little sense to me and no requested clarification was forthcoming.
