### ISSUE TITLE
Suggestion: Maturity scale config

### ISSUE THREAD

**Issue by EightBlade** [ferreusveritas/Dynamic-Trees#328]
So I know that you can use potions and bonemeal to grow a tree past maturity, but would it be possible to increase the default maturity size? That way trees would be bigger on generation.  Could even add a chance to have rare super huge trees?

**Comment by ghost** [comment]
Thank you for the suggestion.  I'll be adding a Potion of Gigas soon that will allow you to convert a tree into it's mega version.
