### ISSUE TITLE
Exception Ticking World

### ISSUE THREAD

**Issue by Shinigami-Apples** [ferreusveritas/Dynamic-Trees#329]
My server and singleplayer world both crash seemingly at random, causing rollback from anywhere between a few minutes and a day, meaning many hours of progress is often lost. 

The crash log comes up with "Exception Ticking World". My partner and I thought it to be Ice and Fire, but after bringing it up with the devs, we were pointed to Dynamic Trees and Electroblob's Wizardry. 

My server runs a slightly backdated version of Forge ( forge-1.12.2-14.23.5.2837 ), so my partner tested it on an up to date version of Forge and the issue still occurred. I'll attach a crash log for both my server and his singleplayer world.

[crash-2019-10-02_18.14.12-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/3683430/crash-2019-10-02_18.14.12-server.txt)
[crash-2019-10-02_14.44.00-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/3683431/crash-2019-10-02_14.44.00-server.txt)

**Comment by ghost** [comment]
I'm sorry to hear you're having a problem like this.  That sucks.    Equally sorry about not replying sooner.
Can you test this again with more recent versions of DT and electrobob's wizardry?  If you can still reproduce the problem I'll take another stab at it.
