### ISSUE TITLE
Fire ticking dynamic tree branches causing server crash

### ISSUE THREAD

**Issue by Shivaxi** [ferreusveritas/Dynamic-Trees#330]
[crash-2019-10-05_00.43.22-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/3693470/crash-2019-10-05_00.43.22-server.txt)

Seems to happen rarely but definitely an issue in the latest Dynamic Trees for 1.12.2

java.lang.StackOverflowError: Exception while ticking a block

**Comment by ghost** [comment]
This was fixed in 1.12.2-0.9.6
