### ISSUE TITLE
Crash when trying to search inventory in creative mode

### ISSUE THREAD

**Issue by Dirandir** [ferreusveritas/Dynamic-Trees#332]
Crash report:

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 10/5/19 6:10 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.block.BlockOldLeaf.func_149691_a(SourceFile:84)
	at com.ferreusveritas.dynamictrees.api.backport.BlockState.getIcon(BlockState.java:89)
	at com.ferreusveritas.dynamictrees.blocks.BlockDynamicLeaves.func_149691_a(BlockDynamicLeaves.java:647)
	at net.minecraft.block.Block.func_149733_h(Block.java:583)
	at net.minecraft.client.renderer.RenderBlocks.func_147745_b(RenderBlocks.java:8242)
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4318)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:255)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.BlockOldLeaf.func_149691_a(SourceFile:84)
	at com.ferreusveritas.dynamictrees.api.backport.BlockState.getIcon(BlockState.java:89)
	at com.ferreusveritas.dynamictrees.blocks.BlockDynamicLeaves.func_149691_a(BlockDynamicLeaves.java:647)
	at net.minecraft.block.Block.func_149733_h(Block.java:583)
	at net.minecraft.client.renderer.RenderBlocks.func_147745_b(RenderBlocks.java:8242)
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4318)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:255)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Dirandir'/474, l='MpServer', x=-66.50, y=70.62, z=246.50]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-60,64,256), Chunk: (at 4,4,0 in -4,16; contains blocks -64,0,256 to -49,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 191 game time, 191 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 108 total; [EntityBat['Bat'/4107, l='MpServer', x=-75.26, y=36.40, z=322.19], EntityBat['Bat'/4109, l='MpServer', x=-74.81, y=38.03, z=318.06], EntityBat['Bat'/4137, l='MpServer', x=-133.52, y=58.57, z=196.48], EntityBat['Bat'/4141, l='MpServer', x=-129.41, y=58.55, z=195.49], EntityBat['Bat'/4167, l='MpServer', x=10.65, y=12.41, z=226.54], EntityBat['Bat'/4169, l='MpServer', x=13.33, y=12.02, z=229.61], EntityFallingBlock['Falling Block'/6256, l='MpServer', x=-159.50, y=46.55, z=318.50], EntityFallingBlock['Falling Block'/6257, l='MpServer', x=-158.50, y=46.55, z=318.50], EntityFallingBlock['Falling Block'/6258, l='MpServer', x=-154.50, y=46.55, z=316.50], EntityFallingBlock['Falling Block'/6267, l='MpServer', x=-84.50, y=25.55, z=220.50], EntityFallingBlock['Falling Block'/6269, l='MpServer', x=-85.50, y=25.55, z=220.50], EntityCreeper['Creeper'/2178, l='MpServer', x=-99.70, y=15.00, z=321.49], EntityZombie['Zombie'/2180, l='MpServer', x=-99.50, y=15.00, z=324.50], EntityZombie['Zombie'/2182, l='MpServer', x=-99.50, y=15.00, z=323.50], EntityZombie['Zombie'/2184, l='MpServer', x=-89.27, y=13.00, z=322.53], EntityZombie['Zombie'/2186, l='MpServer', x=-99.08, y=15.00, z=322.37], EntitySheep['Sheep'/142, l='MpServer', x=-123.75, y=64.00, z=173.69], EntitySheep['Sheep'/144, l='MpServer', x=-120.28, y=63.00, z=168.13], EntitySheep['Sheep'/146, l='MpServer', x=-118.38, y=64.00, z=176.72], EntitySheep['Sheep'/148, l='MpServer', x=-116.56, y=64.00, z=177.84], EntitySheep['Sheep'/150, l='MpServer', x=-113.50, y=64.00, z=188.50], EntitySheep['Sheep'/152, l='MpServer', x=-113.50, y=64.00, z=190.50], EntitySheep['Sheep'/154, l='MpServer', x=-116.50, y=64.00, z=191.50], EntitySheep['Sheep'/156, l='MpServer', x=-117.50, y=64.00, z=187.50], EntitySheep['Sheep'/158, l='MpServer', x=-112.50, y=66.00, z=307.50], EntityFallingBlock['Falling Block'/6303, l='MpServer', x=22.50, y=37.55, z=157.50], EntitySheep['Sheep'/160, l='MpServer', x=-101.97, y=70.00, z=311.03], EntityFallingBlock['Falling Block'/6304, l='MpServer', x=22.50, y=37.55, z=155.50], EntitySheep['Sheep'/162, l='MpServer', x=-109.50, y=67.00, z=302.50], EntitySheep['Sheep'/164, l='MpServer', x=-106.50, y=67.00, z=298.50], EntitySheep['Sheep'/166, l='MpServer', x=-107.19, y=64.00, z=317.78], EntitySheep['Sheep'/168, l='MpServer', x=-111.22, y=63.00, z=318.94], EntitySheep['Sheep'/170, l='MpServer', x=-103.64, y=70.00, z=313.18], EntitySheep['Sheep'/172, l='MpServer', x=-111.59, y=64.00, z=316.44], EntitySheep['Sheep'/237, l='MpServer', x=-58.72, y=67.00, z=244.22], EntitySheep['Sheep'/239, l='MpServer', x=-61.50, y=68.00, z=247.50], EntitySheep['Sheep'/241, l='MpServer', x=-51.16, y=66.00, z=249.13], EntitySheep['Sheep'/243, l='MpServer', x=-52.22, y=66.00, z=246.34], EntityEvilChicken['Chicken'/282, l='MpServer', x=-22.50, y=67.00, z=266.50], EntityEvilChicken['Chicken'/284, l='MpServer', x=-22.50, y=68.00, z=269.50], EntityEvilChicken['Chicken'/286, l='MpServer', x=-22.50, y=69.00, z=272.50], EntityVillager['Villager'/304, l='MpServer', x=7.48, y=64.47, z=199.21], EntityVillager['Villager'/306, l='MpServer', x=7.50, y=65.00, z=195.50], EntityVillager['Villager'/308, l='MpServer', x=2.53, y=64.00, z=212.28], EntityVillager['Villager'/310, l='MpServer', x=0.50, y=65.00, z=204.56], EntityVillager['Villager'/338, l='MpServer', x=8.50, y=65.00, z=221.50], EntitySheep['Sheep'/348, l='MpServer', x=10.06, y=71.00, z=267.09], EntityClientPlayerMP['Dirandir'/474, l='MpServer', x=-66.50, y=70.62, z=246.50], EntityZombie['Zombie'/511, l='MpServer', x=13.50, y=15.00, z=312.50], EntityCreeper['Creeper'/529, l='MpServer', x=-86.50, y=45.00, z=192.50], EntityCreeper['Creeper'/531, l='MpServer', x=-85.50, y=45.00, z=193.50], EntitySkeleton['Skeleton'/641, l='MpServer', x=-105.44, y=37.00, z=240.44], EntitySkeleton['Skeleton'/643, l='MpServer', x=-102.30, y=42.81, z=247.50], EntityCreeper['Creeper'/649, l='MpServer', x=-106.79, y=39.00, z=236.82], EntityWitch['Witch'/655, l='MpServer', x=-139.50, y=49.00, z=218.50], EntityWitch['Witch'/717, l='MpServer', x=-138.50, y=49.00, z=218.50], EntityFallingBlock['Falling Block'/4845, l='MpServer', x=-157.50, y=43.85, z=314.50], EntityFallingBlock['Falling Block'/4846, l='MpServer', x=-157.50, y=43.85, z=315.50], EntityFallingBlock['Falling Block'/4847, l='MpServer', x=-156.50, y=43.85, z=313.50], EntityFallingBlock['Falling Block'/4853, l='MpServer', x=-155.50, y=43.85, z=315.50], EntityFallingBlock['Falling Block'/4865, l='MpServer', x=-142.50, y=43.85, z=267.50], EntityFallingBlock['Falling Block'/4866, l='MpServer', x=-142.50, y=43.85, z=268.50], EntityFallingBlock['Falling Block'/4867, l='MpServer', x=-142.50, y=43.85, z=269.50], EntityFallingBlock['Falling Block'/4870, l='MpServer', x=-142.50, y=43.85, z=270.50], EntityZombie['Zombie'/855, l='MpServer', x=-10.50, y=26.00, z=170.50], EntityZombie['Zombie'/940, l='MpServer', x=-48.50, y=52.00, z=210.50], EntityZombie['Zombie'/945, l='MpServer', x=-44.06, y=51.00, z=216.38], EntitySkeleton['Skeleton'/952, l='MpServer', x=-48.50, y=52.00, z=209.50], EntitySkeleton['Skeleton'/1032, l='MpServer', x=-67.50, y=54.00, z=217.06], EntitySkeleton['Skeleton'/1034, l='MpServer', x=-67.50, y=53.00, z=206.50], EntitySkeleton['Skeleton'/1036, l='MpServer', x=-60.88, y=55.00, z=212.56], EntitySkeleton['Skeleton'/1038, l='MpServer', x=-66.50, y=53.00, z=212.06], EntitySkeleton['Skeleton'/1044, l='MpServer', x=-62.44, y=53.00, z=210.47], EntitySpider['Spider'/3143, l='MpServer', x=-127.50, y=46.00, z=251.50], EntityZombie['Zombie'/1151, l='MpServer', x=-77.50, y=16.00, z=299.50], EntityBat['Bat'/3280, l='MpServer', x=-88.38, y=54.00, z=199.47], EntityBat['Bat'/3282, l='MpServer', x=-88.25, y=54.88, z=199.43], EntityFallingBlock['Falling Block'/5369, l='MpServer', x=22.50, y=33.85, z=157.50], EntityFallingBlock['Falling Block'/5370, l='MpServer', x=23.50, y=34.85, z=156.50], EntityFallingBlock['Falling Block'/5371, l='MpServer', x=22.50, y=33.85, z=155.50], EntitySkeleton['Skeleton'/1526, l='MpServer', x=-109.50, y=26.00, z=292.09], EntityCreeper['Creeper'/1572, l='MpServer', x=-92.50, y=20.00, z=306.50], EntitySkeleton['Skeleton'/1586, l='MpServer', x=-136.50, y=42.00, z=307.94], EntitySpider['Spider'/1588, l='MpServer', x=-136.50, y=42.00, z=306.00], EntityBat['Bat'/3724, l='MpServer', x=-53.97, y=27.82, z=194.79], EntityBat['Bat'/3726, l='MpServer', x=-46.54, y=23.06, z=197.72], EntityBat['Bat'/3728, l='MpServer', x=-88.43, y=45.55, z=190.50], EntitySkeleton['Skeleton'/1684, l='MpServer', x=-108.50, y=39.00, z=238.50], EntitySkeleton['Skeleton'/1688, l='MpServer', x=-106.23, y=39.00, z=235.91], EntitySkeleton['Skeleton'/1692, l='MpServer', x=-111.50, y=39.00, z=244.50], EntitySkeleton['Skeleton'/1700, l='MpServer', x=-112.50, y=39.00, z=243.50], EntitySkeleton['Skeleton'/1704, l='MpServer', x=-117.25, y=38.00, z=244.31], EntityZombie['Zombie'/1790, l='MpServer', x=-126.50, y=44.00, z=240.50], EntityFallingBlock['Falling Block'/5906, l='MpServer', x=-158.50, y=44.71, z=317.50], EntityFallingBlock['Falling Block'/5907, l='MpServer', x=-157.50, y=45.71, z=311.50], EntityFallingBlock['Falling Block'/5908, l='MpServer', x=-157.50, y=45.71, z=312.50], EntityFallingBlock['Falling Block'/5909, l='MpServer', x=-159.50, y=44.71, z=317.50], EntityFallingBlock['Falling Block'/5910, l='MpServer', x=-159.50, y=44.71, z=318.50], EntityFallingBlock['Falling Block'/5911, l='MpServer', x=-158.50, y=44.71, z=318.50], EntityFallingBlock['Falling Block'/5912, l='MpServer', x=-154.50, y=44.71, z=316.50], EntityZombie['Zombie'/1820, l='MpServer', x=-63.31, y=51.00, z=210.69], EntityFallingBlock['Falling Block'/5918, l='MpServer', x=-123.50, y=22.71, z=199.50], EntityCreeper['Creeper'/1872, l='MpServer', x=-142.50, y=46.00, z=219.50], EntityCreeper['Creeper'/1876, l='MpServer', x=-142.50, y=46.00, z=221.50], EntityCreeper['Creeper'/1878, l='MpServer', x=-143.50, y=46.00, z=221.50], EntityFallingBlock['Falling Block'/6040, l='MpServer', x=22.50, y=35.71, z=157.50], EntityFallingBlock['Falling Block'/6041, l='MpServer', x=22.50, y=35.71, z=155.50], EntityCreeper['Creeper'/1952, l='MpServer', x=-16.50, y=34.00, z=295.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1167351104 bytes (1113 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 37 mods loaded, 37 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{1.2.1} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJAAAA	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (gilded-games-util-1.7.10-1.9.jar) 
	UCHIJAAAA	movillages{1.4.2} [Mo' Villages] ([1.7.10]MoVillages-1.4.2.jar) 
	UCHIJAAAA	abyssalcraft{1.9.1.3} [AbyssalCraft] (AbyssalCraft-1.7.10-1.9.1.3-FINAL.jar) 
	UCHIJAAAA	aether{1.7.10-1.6} [Aether II] (aether-1.7.10-1.6.jar) 
	UCHIJAAAA	Aquaculture{1.2.6} [Aquaculture] (Aquaculture-1.7.10-1.2.6.21.jar) 
	UCHIJAAAA	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) 
	UCHIJAAAA	atum{0.6} [Atum] (Atum-1.7.10-0.6.77.jar) 
	UCHIJAAAA	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAAAA	redgear_core{2.2.2} [Red Gear Core] (RedGearCore-1.7.10-2.2.2.jar) 
	UCHIJAAAA	redgear_brewcraft{1.3.3} [Brewcraft] (Brewcraft-1.7.10-1.3.3.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(29oct17).jar) 
	UCHIJAAAA	dynamictrees{1.7.10-0.7.2b} [Dynamic Trees] (DynamicTrees-1.7.10-0.7.2b (1).jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UCHIJAAAA	enhancedportals{3.0.12} [EnhancedPortals] (EnhancedPortals_1.7.10-universal-3.0.12.jar) 
	UCHIJAAAA	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
	UCHIJAAAA	journeymap{5.1.4p1} [JourneyMap] (journeymap-1.7.10-5.1.4p1-unlimited.jar) 
	UCHIJAAAA	locks{1.0.0} [Locks] (Locks-1.0.0.jar) 
	UCHIJAAAA	lotr{Update v35.4 for Minecraft 1.7.10} [The Lord of the Rings Mod] (LOTRMod v35.4.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's+HarvestCraft+1.7.10Lb.jar) 
	UCHIJAAAA	simpleautorun{1.7.10-1.2} [SimpleAutoRun] (simpleautorun-1.7.10-1.2.0.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	thebetweenlands{1.0.6-alpha} [The Betweenlands] (TheBetweenlands-1.0.6-alpha-universal.jar) 
	UCHIJAAAA	erebus{0.4.7} [Erebus] (TheErebus-0.4.7.jar) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.2.1} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.1-172.jar) 
	UCHIJAAAA	ThinkBigCore{1.4} [§5§m===§r §e§lThink Big Core §5§m===§r] (ThinkBigCore-1.4-[1.7.10].jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 425.31' Renderer: 'GeForce GTX 670MX/PCIe/SSE2'
	CoFHCore: -[1.7.10]3.1.4-329
	ThermalFoundation: -[1.7.10]1.2.6-118
	ThermalExpansion: -[1.7.10]4.1.5-248
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.
	ThermalDynamics: -[1.7.10]1.2.1-172
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 670MX/PCIe/SSE2 GL version 4.6.0 NVIDIA 425.31, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by ghost** [comment]
Sorry, 1.7.10 is no longer supported so this will not be investigated.
