### ISSUE TITLE
Trees don't drop items after breakage (SpongeForge server)

### ISSUE THREAD

**Issue by craving-death** [ferreusveritas/Dynamic-Trees#335]
https://github.com/ferreusveritas/DynamicTrees/issues/147

RLCraft server
spongeforge-1.12.2-2838-7.1.7-RC3926
DynamicTrees-1.12.2-0.9.5

Trees dont drop items after breaking and sometimes leave invisible entity there that can crush players if they walk through

**Comment by ghost** [comment]
> In sponge 7.1.3-RC3495 bug don't reproduced.
> Problem solved! =)
