### ISSUE TITLE
Is Dynamic Trees Biome Specific

### ISSUE THREAD

**Issue by TheSexyYeti** [ferreusveritas/Dynamic-Trees#336]
Is Dynamic Trees biome specific?. I only ask because I'm using project: Vibrant Adventure (P:VA) which adds it's own specific biomes. And even though I've disabled all the tree gen from P:VA. There is still issues with world gen. Where instead of generating dynamic trees for Vanilla trees in these new biomes. 

It instead just spawn the default Vanilla trees. If that is not the case then how in the world do I disable vanilla tree gen. I've been googling all day to find out. And all I can find is articles on mod development that replaces vanilla tree gen.

**Comment by ghost** [comment]
Yes, it is biome specific and for good reason.  If it were coded any other way it could generate trees in modded biomes in ways that could break things.  Such as if a modder made a pink puffy tree biome and then dynamic oaks were all over it, ruining the intended aesthetics.  Before you can even set about adding dynamic trees to custom biomes you first need to find out if there's a way to stop the tree generation in the modded biomes.
