### ISSUE TITLE
Dynamic trees crashing game on startup

### ISSUE THREAD

**Issue by FormalPineapple** [ferreusveritas/Dynamic-Trees#341]
https://pastebin.com/0PrG1wRA

**Comment by kierajreed** [comment]
Please use [pastebin](https://pastebin.com/) for error logs and stack traces.

**Comment by FormalPineapple** [comment]
> Please use [pastebin](https://pastebin.com/) for error logs and stack traces.

My bad. There, I posted it

**Comment by kierajreed** [comment]
Duplicate of #290.
