### ISSUE TITLE
Minecraft Failed to Start!

### ISSUE THREAD

**Issue by sambm775** [ferreusveritas/Dynamic-Trees#346]
All is in the title (sadly)
I have around hundred mods used in the same time, maybe one of them is the cause (see the pastebin link below)

[image](https://user-images.githubusercontent.com/53912802/67149148-1ad36580-f2a8-11e9-83c8-bd778408573c.png)

I use OptiFine HD U E3 for Minecraft 1.12.2.

I run the 0.9.5 version of DT
I use also DT Biome O' Plenty Add-on in the last version (1.4.1e)

Crash log : https://pastebin.com/LGk7wip0

I'm using 1.12.2-forge1.12.2-14.23.5.2838)

**Comment by kierajreed** [comment]
Duplicate of #290.
