### ISSUE TITLE
Server crash due to "IndexOutOfBoundsException" in Dynamic Trees.

### ISSUE THREAD

**Issue by archonsd** [ferreusveritas/Dynamic-Trees#349]
1.12.2 Forge
DT 1.12.2-0.9.5

Was just chopping down a Dynamic Oak Tree from the base.  Entire MC server crashed.

Pastebin of Crashlog:  https://pastebin.com/NbgBwkBY

**Comment by ghost** [comment]
Is this reproduceable?

**Comment by archonsd** [comment]
> Is this reproduceable?

I stopped this server and deleted it in early January. (2-3 Mos after that post)

I don't believe I ran into that crash again, but I only played that server for 2-3 weeks, a few hrs a day.

The crash log was pretty explicit, but I don't plan to set up another MC server any time soon, so I can't validate soon.

**Comment by ghost** [comment]
Yeah.  It's explicit. It refers to Minecraft pathfinding which indicates that likely some sort of modded animal entity(or it's supporting functionality) isn't playing nice with an ArrayList in PathWorldListener(namely "navigations") .  The only way a crash like that can happen in the `notifyBlockUpdate` call is if it's modified from another thread.  From what I can tell my mod just happened to be in the way when this happened and thus became part of the backtrace.
