### ISSUE TITLE
[1.12.2] Dynamic Trees Freeze on World Gen

### ISSUE THREAD

**Issue by HorizonsMC** [ferreusveritas/Dynamic-Trees#35]
Using Dynamic Trees and Void Island Control causes dynamic trees to hang when the world generates and freezes the server.

Using Forge 2587 and latest version of both mods.

Turning worldgen=true to false fixes the freeze.

**Comment by ghost** [comment]
I think I know what the problem is.  No ground for the tree to spawn.  I didn't take that into account.  Can you provide a crash log so I have a place to get started?

**Comment by HorizonsMC** [comment]
There isn't any crash log, it just freezes.

**Comment by ghost** [comment]
Oh yeah.  :)  Fixed it.  Hopefully.

**Comment by HorizonsMC** [comment]
It's fixed, ty
