### ISSUE TITLE
Trees from worldpainter not changing to DynamicTrees.

### ISSUE THREAD

**Issue by Realeon** [ferreusveritas/Dynamic-Trees#351]
**Describe the bug**
 When I add trees to my worldpainter map, and then export it to MC, the saplings evolve into vanilla trees instead. I can plant dynamic trees manually though. Thus, when I create worlds in minecraft, the trees are dynamic. I tried to edit the .configs file to force vanilla saplings to become DT saplings. And it only worked if I plant it myself. At first I thought it was a problem with CubicChunks, but as I mentioned earlier when I create worlds in MC with the CubicChunks option enabled, the trees are dynamic.

**Rendering Glitches**
Are you using Optifine? Yes.

'm using forge 14.23.5.2768 for 1.12.2.

**Comment by ghost** [comment]
The option to force vanilla saplings to become DT saplings only occurs when the player physically plants the vanilla sapling by hand.

Edit: I did notice that there's a forge TerrainGen event for when a sapling grows into a tree.  I might be able to leverage it to work how you're asking.
