### ISSUE TITLE
Error: java.io.UTFDataFormatException: malformed input around byte 4

### ISSUE THREAD

**Issue by ZomecGaming** [ferreusveritas/Dynamic-Trees#352]
Here is the crash report. It has more info than I could possibly give. Right now I'm getting constant ctd's.

https://paste.ubuntu.com/p/hDWnnzDtbN/

**Comment by ghost** [comment]
Judging by your crash log it looks like you might somehow have a corrupted region file.  It's very unlikely that this is a dynamic trees problem.
