### ISSUE TITLE
FallingTreeEntity Not being removed?

### ISSUE THREAD

**Issue by ichimo** [ferreusveritas/Dynamic-Trees#353]
I don't really have much of an explanation of what this is, using the tickprofiling mod, using /profile count_entities the amount the entities are just increasing without ever dropping.  I can use a /kill command and get rid of them clearing up lag if it gets bad.

**Comment by ghost** [comment]
I used the F3 menu and it's "E:" section and could not find any evidence that the entity is not removed.

**Comment by ghost** [comment]
This is an old issue and I'm sorry I couldn't get to it sooner.  If you feel that I'm assessing this incorrectly then please open up a fresh issue with more information.
