### ISSUE TITLE
Seeds not implementing IPlantable

### ISSUE THREAD

**Issue by Lordician** [ferreusveritas/Dynamic-Trees#355]
**Describe the bug**
The block placer of Engineer's Decor cannot place the acorns (or well, seeds) of any Dynamic Trees variant. After some research by the owner of Engineer's Decor, it turns out that this is due to the seeds not implementing the IPlantable interface and therefor, it cannot be detected as a plantable item.
Can this be fixed?
Link to Engineer's Decor issue: https://github.com/stfwi/engineers-decor/issues/57

**To Reproduce**
1. put oak acorn in the Factory Block Placer of Engineer's Decor.
2. Apply lever.
3. Pull lever.
4. Watch as it just spits out the item because it does not know how to place/plant the item.

**Mods List**
This issue was found using the following setup:
1.12.2-forge1.12.2-14.23.5.2838
ImmersiveEngineering-0.12-92
engineersdecor-1.12.2-1.0.15-b2
DynamicTrees-1.12.2-0.9.5

**Comment by ghost** [comment]
This is a nice thought and I would like to add this but I can't.  The IPlantable interface provides a function to "getPlant" but it only returns an IBlockState that's meant to be the block that gets planted.  Dynamic trees produces a sapling block that's a tile entity(it holds a reference to the species) so it won't work.  Sorry.
