### ISSUE TITLE
Unable to adjust dynamic trees mining speed?

### ISSUE THREAD

**Issue by JustLiam040** [ferreusveritas/Dynamic-Trees#357]
Unable to adjust dynamic trees log mining time? I am unsure as to whether this is an issue in my configs or simply a feature that does not exist (although i swear i've used it in the past). Basically when mining trees the speed is reduced dependent on the amount of logs above it, i would like to change this so that the bottom log can be mined at regular speed. I am unsure as to whether my config is missing things, or whether i am simply missing it myself; however i would just like to know whether this is a feature and if so where can it be found/done?

Minecraft version: 1.12.2
Forge version: forge-14.23.5.2847

**Comment by kierajreed** [comment]
As seen in the [config class](https://github.com/ferreusveritas/DynamicTrees/blob/d121cade19dbc820ee19701503dc4467c177c9ca/src/main/java/com/ferreusveritas/dynamictrees/ModConfigs.java), there is no option to modify the mining speed of tree blocks. Sorry. If there is enough demand for this feature, however, it might be considered for addition in a later version.
