### ISSUE TITLE
Support for Additional Mods

### ISSUE THREAD

**Issue by kierajreed** [ferreusveritas/Dynamic-Trees#358]
Over time, quite a few requests for compatibility add-ons have been posted. To make it simpler to track all of these requests, they will be grouped here from now on. *While compatibility is never added into Dynamic Trees itself, anyone who is willing can make an add-on to add support for another mod.*

Current requests for support, by adding trees or otherwise:
- Ex Nihilo Creatio (#178)
- TerraFirmaCraft (#223) 
- Natura (#286) 
- Conquest Reforged (#312) 
- TekTopia\* (#315) 
- Forestry (#334) 
- AbyssalCraft (#⁠334) 
- Betweenlands (#⁠334)
- Quark (#338)
- *Real Life* (#369) 
- Advent Of Ascension (#381)
- Biome Bundle (#⁠381)
- Aether II (#391)
<hr>

*: TekTopia is unfortunately not open-source, and this is unlikely to be done unless the developer (TangoTek) releases the source code or does it themselves.

**Comment by Gaelmare** [comment]
A Dynamic Trees TFC-TNG add-on for 1.12.2 is in beta.
Source: https://github.com/Gaelmare/dynamictreestfc
CF: https://www.curseforge.com/minecraft/mc-mods/dynamictreestfc
Love the mod, good clean source. I'll be opening issues for a few questions I have.

**Comment by This-1s-My-Name** [comment]
Compatibility with PrimalCore Ironwood and Yew trees would be dope.

**Comment by supermassimo** [comment]
[Natura compat](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-natura) 
[Quark compat](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-quark#c14) 
[Aether legacy compat](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-the-aether-legacy) (Aether II is in a too unstable development phase to make addons for, for the time being)
The BetweenLands and forestry addons are in the works :)

**Comment by TokcOn** [comment]
Is anyone maked something for terraqueous?

**Comment by supermassimo** [comment]
[Forestry Compat](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-forestryl)
