### ISSUE TITLE
Suggestion: Allow configuration for custom trees.

### ISSUE THREAD

**Issue by UnlimatedStone9** [ferreusveritas/Dynamic-Trees#359]
It would be great if there was a configuration ability to register custom trees.
You would provide the necessary textures for the trees seed, leaves and log, and would select what it considers as a drop (trees tend to drop logs) and the mod would register said tree.
This would allow bypassing mods not having direct DynamicTrees support for generic trees and allows players to add trees that don't even exist at all.
Although these trees probably couldn't replace vanilla-esque trees during world generation, they could perhaps be configured as to what biomes they can generate in, their default growth stage/rarity, etc, and it would be up to players/pack developers to disable other mods trees however possible. (Through that mods config file, etc)

**Comment by kierajreed** [comment]
Not in scope. Ask someone else, maybe they can make a mod for it.
