### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by mmmilord** [ferreusveritas/Dynamic-Trees#362]
https://gist.github.com/mmmilord/63267ee3953444aa63c7b2142cd3b8e5

DynamicTrees-1.12.2-0.9.6.jar
DynamicTreesPHC-1.12.2-1.4.2.jar

**Comment by ghost** [comment]
The crash is caused by the Spark Hammers mod. Specifically [here](https://github.com/thebrightspark/SparksHammers/blob/1.12/src/main/java/brightspark/sparkshammers/worldgen/WorldGenMjolnirShrine.java#L106)
The mod clearly means to use "p" instead of "pos" in the while loop check. Looks like a typo.
