### ISSUE TITLE
When putting blocks of oak wood breaks all the blocks

### ISSUE THREAD

**Issue by PopiiMyPlax** [ferreusveritas/Dynamic-Trees#364]
I build a house with oak, for example, by removing only one block, it destroys all the other blocks together.

Is there any way to disable it?

I want to put blocks of oak wood for example, and that does not destroy the rest of the blocks by removing it with an ax in survival mode.
Without being a planted tree.

**Comment by ghost** [comment]
I don't really understand what you're asking.  Dynamic trees doesn't affect vanilla oak logs.

**Comment by ghost** [comment]
Dynamic Tree's branches are not designed to be used as building material.
