### ISSUE TITLE
Dynamic trees not spawning.

### ISSUE THREAD

**Issue by KotGarfield** [ferreusveritas/Dynamic-Trees#366]
I am using:
Dynamic Trees (0.9.6) 
BoP addon (1.4.1e)
BoP (7.0.1)
Quark (r1.5-176)
Quark oddities 
Optifine
And Ambient sounds
(Forge 14.23.5.2838)
Simply dynamic trees are not spawning. I also tried to config the mod but config is unavaible.

**Comment by ghost** [comment]
I tried recreating the same pack and it worked. The mangrove trees and fake bushes (with one log in the middle) were blocks, but dynamic trees spawned in BoP biomes. (I couldn't actually find any dynamic BoP trees though and only the mangrove swamp for regular trees.
The DT config doesn't run from inside MC. You'll need to go to the config directory if you want to edit it. If it's not there, and it's turned on (it happens, especially with Twitch), you should reinstall DT. Try typing @dynamic in the JEI search box and see if any of the mod items are registered.

**Comment by ghost** [comment]
Not reproducible.
