### ISSUE TITLE
Explosion-based logging operations crashing game

### ISSUE THREAD

**Issue by Hexidecimark** [ferreusveritas/Dynamic-Trees#367]
When a Dynamic Tree is hit by an explosion, it occasionally crashes the game.

Uncertain of exact replication conditions, however, the general problem can be faithfully duplicated by using mods that cause large or frequent explosions. Erroneous effects have been observed given explosions with ICBM and Mrcrayfish's Gun mod.

**Additional context**
Error has occurred in a modpack I have constructed (details below) across multiple users.

**Crashes**
- Are you running the latest version of Dynamic Trees?(Currently 0.9.6)
Yes
- If you are using the DT Biome O' Plenty Add-on do you have the latest version?(Currently 1.4.1e)
Yes

CRASH LOG FROM MOST RECENT INCIDENT:
[crash-2019-11-24_13.27.18-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/3884101/crash-2019-11-24_13.27.18-server.txt)

CONFIG FILE WITH WHICH THE ERROR OCCURRED:
[dynamictrees.txt](https://github.com/ferreusveritas/DynamicTrees/files/3884103/dynamictrees.txt)

**Comment by Hexidecimark** [comment]
[latest.log](https://github.com/ferreusveritas/DynamicTrees/files/3884108/latest.log)
Latest.log from the same incident.

**Comment by kierajreed** [comment]
Please use [pastebin](https://pastebin.com/) for error logs and stack traces.
