### ISSUE TITLE
Cuisine - Serene Seasons - Dynamic Trees

### ISSUE THREAD

**Issue by DcNdrew** [ferreusveritas/Dynamic-Trees#368]
Hi!
I didn't find a Discord server yet or a way to contact, but here is my idea:
Cuisine leaves has ages, Serene Seasons has option to disable aging crops.
Well, if the leaves of Dynamic Trees would have age tag, they can die in some seasons. Winter for example, except spruce.
Or what if Serene Seasons has an option to not kill the crop, but set its age to 0. In that case at the age of 0 Dynamic's leaves should look like empty branches, turned to the connected branch. At spring they can age to 1 (leaves) and 2 (blooms), and in summer or seasons how they are set, to 3 (fruits).

**Comment by kierajreed** [comment]
There is in fact a discord: [invite.](https://discord.gg/hn2pGEV)
