### ISSUE TITLE
[Request]: More tree species

### ISSUE THREAD

**Issue by Blue20Boy17** [ferreusveritas/Dynamic-Trees#369]
I think one thing that'd really make this mod great is completely removing Vanilla trees from Minecraft and adding their real-life variants, like Oak trees will encompass White Oak, Black Oak, Red Oak, Chestnut Oak, Pin Oak, Post Oak, Shingle Oak, etc. And to make them identifiable in game, make their textures like x64 or x128 or x256 so that one can see the difference in bark and leaves. And have like, Tulip Trees, Black Walnut Trees, American Beech, Blue Beech, Red Pine, White Pine, Virginia Pine, Pitch Pine, Paper Birch, Black Birch, Yellow Birch, etc. I think that would make this mod really great. Even greater than it is now.

**Comment by kierajreed** [comment]
This can easily be done as an addon. "Extra Dynamic Trees" or something. I've added it to the list, now if someone wants to, they can go and do it.
