### ISSUE TITLE
Some trees aren't dynamic in Flower Forest

### ISSUE THREAD

**Issue by CalaMariGold** [ferreusveritas/Dynamic-Trees#371]
**Describe the bug**
Some trees aren't dynamic in the flower forest biome.

**To Reproduce**
Install DT. Find a flower forest.

**Comment by ghost** [comment]
What other mods are you running?  Do you have a screenshot?

**Comment by democat3457** [comment]
![image](https://user-images.githubusercontent.com/32407067/114773495-c2621480-9d34-11eb-991d-d69b428e038e.png)
Minecraft's Flower Forest biome has static trees
