### ISSUE TITLE
Realistic cutting mechanics

### ISSUE THREAD

**Issue by Blue20Boy17** [ferreusveritas/Dynamic-Trees#372]
Would it be possible to make trees fall like they do IRL? Like how this video shows a tree falling after using an axe on it? 
https://www.youtube.com/watch?v=nK8h2DmM0Ww 

And after it's on the ground, you have to chop it up?

**Comment by ArkinSolomon** [comment]
I'm sorry, how is this an issue?

**Comment by kierajreed** [comment]
The way it is is the way it's staying. Sorry.
