### ISSUE TITLE
Incompatibility with ConnectedTexturesMod(CTM) and DynamicTrees

### ISSUE THREAD

**Issue by in-tension** [ferreusveritas/Dynamic-Trees#373]
I just wanted to let you guys know that DynamicTrees throws and error and crashes on startup (I think it's during the 4th stage of forge load up, "Mod Initialization: Phase 2"  (or something like that)) if I also have  [ConnectedTexturesMod(CTM)](https://www.curseforge.com/minecraft/mc-mods/ctm)  installed. It's not really an issue for me cause I don't really need CTM but it might be good to put on the mod page under incompatibilities or something.

**Comment by astrononeko** [comment]
To be more clearly here is the problem:

> Caused by: java.lang.UnsupportedOperationException
> at com.google.common.collect.ImmutableCollection.addAll(ImmutableCollection.java:244)
>     at com.ferreusveritas.dynamictrees.client.QuadManipulator.getSpriteUVFromBlockState(QuadManipulator.java:171)
>     at com.ferreusveritas.dynamictrees.client.QuadManipulator.getModelTexture(QuadManipulator.java:139)
>     at com.ferreusveritas.dynamictrees.proxy.ClientProxy.discoverWoodColors(ClientProxy.java:99)
>     at com.ferreusveritas.dynamictrees.proxy.ClientProxy.postInit(ClientProxy.java:85)
>     at com.ferreusveritas.dynamictrees.DynamicTrees.postInit(DynamicTrees.java:58)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
>     at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
>     at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
>     at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
>     at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
>     at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
>     at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
>     at com.google.common.eventbus.EventBus.post(EventBus.java:217)
>     at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
>     at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
>     at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
>     at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
>     at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
>     at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
>     at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
>     at com.google.common.eventbus.EventBus.post(EventBus.java:217)
>     at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
>     at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
>     at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
>     at net.minecraft.client.Minecraft.init(Minecraft.java:535)
>     at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
>     at net.minecraft.client.main.Main.main(SourceFile:123)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by HentaiHamster** [comment]
I have the same exact problem now. Its probably because CTM updated because ive never had this issue before and have used both mods this whole time. And it says the CTM  just updated 11/25/19 so maybe they changed something. 

Edit: just checked out CTM issues page...other people say the issue is with CTM, dynamic trees, and better with mods all installed at the same time. They said reverting to CTM 1.0.1.29 could fix the issue.....trying it out. 

https://github.com/Chisel-Team/ConnectedTexturesMod/issues/118

**Comment by tterrag1098** [comment]
https://github.com/Chisel-Team/ConnectedTexturesMod/issues/116#issuecomment-559615248
