### ISSUE TITLE
CCL Catching a Concurrent Modification Exception Which would cause a client crash

### ISSUE THREAD

**Issue by xElementzx** [ferreusveritas/Dynamic-Trees#376]
**Describe the bug**
Concurrent Modification Exception which would usually cause a client crash, caught by CCL

**To Reproduce**
Unsure, Error occurred upon joining MP Server was not an error the second time joining

**Screenshots**
No Screenshot as no crash occurred due to CCL catching the error
https://gist.github.com/b9533aa33a329b6b52a4d0e512928fa3 Gist of the stacktrace

**Rendering Glitches**
Are you using Optifine? No...

**Additional context**

**Crashes**
- Are you running the latest version of Dynamic Trees?(Currently 0.9.6) No, 0.9.5 from FTB Academy
- If you are using the DT Biome O' Plenty Add-on do you have the latest version?(Currently 1.4.1e) NO, Traverse Addon 1.5

**Mods List**
If your crash log does not contain a list of mods or you have no crash log then please provide a full list of the mods you are using complete with mod versions.
What version of Forge are you running?(e.g. 1.12.2-14.23.5.2768)
Forge 2846
https://gist.github.com/02b112314309251a6d563ad22dd5fe1a - List of all mods

**Comment by ghost** [comment]
Same as #373
