### ISSUE TITLE
crash during worldgen on  a server

### ISSUE THREAD

**Issue by bobodoustaud** [ferreusveritas/Dynamic-Trees#379]
crash report : https://pastebin.com/UM8GuTvt

just generated a tree in the world

modlist is in the crash report

**Comment by ghost** [comment]
Does this happen often? Because the log suggests the server hung for 60 seconds before giving up the ghost.

**Comment by bobodoustaud** [comment]
it happened always but the error was fixed after reinstalling the server.
bad luck?

Le mer. 22 janv. 2020 à 00:45, Ferreus Veritas <notifications@github.com> a
écrit :

**Comment by ghost** [comment]
I'm glad it's resolved at least.

Closed: Can not replicate
