### ISSUE TITLE
[Mod support suggestion] Advent of Ascension, Biome Bundle

### ISSUE THREAD

**Issue by Archilyte** [ferreusveritas/Dynamic-Trees#381]
before yall pin me to the wall with pitchforks, lemme tell ya that people at discord told me to make a issue here.

That said, I would like if anyone willing made a Dynamic Trees support for [Advent of Ascension](https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine) and [Biome Bundle](https://www.curseforge.com/minecraft/mc-mods/biome-bundle)

the latter may already have one, but i am not sure / cant find it.

**Comment by kierajreed** [comment]
I've added it to the list. Whether anyone does it or not is uncertain.
