### ISSUE TITLE
Dynamic trees does not work

### ISSUE THREAD

**Issue by picarouso** [ferreusveritas/Dynamic-Trees#382]
Hi, I have a multiplayer server in aternos, all the other mods works correctly, but the dynamic trees don't generate the trees, it doesn't change them.
In an individual game it does work, and I don't understand it, since the mod is added to the server and in the mod folder, in - 1.12.2.

This is the config from the mod:
# Configuration file

client {
    # Rings of thick trees are rendered using a texture created with an expanded tangram construction technique. Otherwise the ring texture is simply stretched [default: true]
    B:fancyThickRings=true

    # Rooty dirt blocks will mimic the texture of adjacent soil blocks to better match the environment. Otherwise will always default to the most generic block [default: true]
    B:rootyTextureMimicry=true
}

debug {
    # Enable to mark tree spawn locations with wool circles. [default: false]
    B:worldGenDebug=false
}

interaction {
    # Modes: 0=Standard 1 Damage, 1=By Branch/Trunk Thickness, 2=By Tree Volume [range: 0 ~ 2, default: 1]
    I:axeDamageMode=1

    # If enabled players receive reduced fall damage on leaves at the expense of the block(s) destruction [default: true]
    B:canopyCrash=true

    # If enabled the Dirt Bucket will place a dirt block on right-click [default: true]
    B:dirtBucketPlacesDirt=true

    # If enabled then thinner branches can be climbed [default: true]
    B:enableBranchClimbling=true

    # If enabled then trees will harm living entities when falling [default: true]
    B:enableFallingTreeDamage=true

    # If enabled then trees will fall over when harvested [default: true]
    B:enableFallingTrees=true

    # Multiplier for damage incurred by a falling tree [range: 0.0 ~ 100.0, default: 1.0]
    S:fallingTreeDamageMultiplier=1.0

    # If enabled all leaves will be passable [default: false]
    B:isLeavesPassable=false

    # If enabled player movement on leaves will not be enhanced [default: false]
    B:vanillaLeavesCollision=false
}

seeds {
    # The rate at which seeds voluntarily drop from branches [range: 0.0 ~ 1.0, default: 0.0]
    S:dropRate=0.0

    # The minimum forestness that non-forest-like biomes can have. 0 = is not at all a forest, 1 = may as well be a forest. Can be fractional [range: 0.0 ~ 1.0, default: 0.0]
    S:minForestness=0.0

    # If enabled then seeds will only voluntarily plant themselves in forest-like biomes [default: true]
    B:onlyForest=true

    # The rate at which seeds voluntarily plant themselves in their ideal biomes [range: 0.0 ~ 1.0, default: 0.125]
    S:plantRate=0.125

    # Ticks before a seed in the world attempts to plant itself or despawn. 1200 = 1 minute [range: 0 ~ 6000, default: 1200]
    I:timeToLive=1200
}

trees {
    # The chance of a tree on depleted soil to die. 1/256(~0.004) averages to about 1 death every 16 minecraft days [range: 0.0 ~ 1.0, default: 0.0]
    S:diseaseChance=0.0

    # If enabled then sticks will be dropped for partial logs [default: true]
    B:dropSticks=true

    # If enabled apple trees will be generated during worldgen and oak trees will not drop apples [default: true]
    B:enableAppleTrees=true

    # If enabled then certain species trunks will be able to grow wider than a single block [default: true]
    B:enableThickTrees=true

    # Do X growth cycles at once while ignoring (X-1)/X attempts.  Higher numbers can improve client side performance but too high can make trees grow wierd. [range: 1 ~ 8, default: 2]
    I:growthFolding=2

    # Factor that multiplies the rate at which trees grow. Use at own risk [range: 0.0 ~ 16.0, default: 0.5]
    S:growthMultiplier=0.5

    # Factor that multiplies the wood returned from harvesting a tree.  You cheat. [range: 0.0 ~ 128.0, default: 1.0]
    S:harvestMultiplier=1.0

    # The maximum radius of a branch that is allowed to rot away. 8 = Full block size.  Set to 0 to prevent rotting [range: 0 ~ 24, default: 8]
    I:maxBranchRotRadius=8

    # Scales the growth for the environment.  0.5f is nominal. 0.0 trees only grow in their native biome. 1.0 trees grow anywhere like they are in their native biome [range: 0.0 ~ 1.0, default: 0.5]
    S:scaleBiomeGrowthRate=0.5
}

vanilla {
    # Right clicking with a vanilla sapling places a dynamic sapling instead. [default: false]
    B:replaceVanillaSapling=true
}

world {
    # Blacklist of dimension numbers for disabling Dynamic Tree worldgen [default: [7]]
    S:dimensionsBlacklist <
        7
     >

    # Randomly generate podzol under select trees. [default: true]
    B:podzolGen=true

    # World Generation produces Vanilla cactus as well as Dynamic cactus if world gen replacement is enabled. [default: false]
    B:vanillaCactusWorldGen=false

    # World Generation produces Dynamic Trees instead of Vanilla trees. [default: true]
    B:worldGen=true
}

![Sin título](https://user-images.githubusercontent.com/45683797/70925283-45813680-202b-11ea-950d-f86f77655fac.jpg)

Pls help

**Comment by kierajreed** [comment]
Please use [pastebin](https://pastebin.com/) for error logs and stack traces, as well as configs. Thanks.

**Comment by ghost** [comment]
Are you expecting existing already generated Vanilla trees to change to Dynamic Trees?  If that's the case then that isn't how this mod works.
