### ISSUE TITLE
Dynamic Trees doesn't work

### ISSUE THREAD

**Issue by MSFLowYT** [ferreusveritas/Dynamic-Trees#384]
Hi, I need your help, I removed dynamic trees but then I put it again in mod Folder but the trees suddenly don't work because the blocks of the trees are small:
![2019-12-17_14 02 31](https://user-images.githubusercontent.com/58983014/71003592-06a9ba00-20d9-11ea-82b8-be43fea3fd11.png)

I need help, please

**Comment by kierajreed** [comment]
This is a very old issue, the cause of which is still unknown. See #63 for original discussion.
