### ISSUE TITLE
Low Performance

### ISSUE THREAD

**Issue by HeberonYT** [ferreusveritas/Dynamic-Trees#386]
**Describe the bug**
I am using DynamicTrees together with Traverse, and the area where I am established has begun to cause a considerable delay for a few days.
Basically the server takes too long to load the area near my base, there are no mod objects, no farms or redstone systems.
This does not happen if I explore new areas of the map.
The profiler is showing that the cause is DynamicTrees.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/13698597/71121021-2f968180-21a3-11ea-8463-d490864b9f22.png)

**Rendering Glitches**
Are you using Optifine? Yes

**Mods List**
forge-1.12.2-14.23.5.2846
DynamicTrees-1.12.2-0.9.6.jar
Traverse-1.12.2-1.6.0-69.jar
spongeforge-1.12.2-2838-7.1.8-RC3963.jar

**Comment by ghost** [comment]
Strange.  According to your results this occurs when a chunk is unloaded.  Which is a rather straightforward dump of a tiny amount of data that is saved.  I notice that you're using spongeforge which historically has caused unexplained harmful interactions with DT.

**Comment by MagmaSlime123** [comment]
Use normal Forge.
