### ISSUE TITLE
Bug with Ancient Warfare2

### ISSUE THREAD

**Issue by SettingDust** [ferreusveritas/Dynamic-Trees#388]
**Describe the bug**
The trees will drop item after structures been build.
The vanilla trees was not drop items. 
The falling tree is the reason I think.
I have disabled the falling, and its ok.  But I think this is a bug.

**To Reproduce**
1. Add DynamicTrees & Ancient Warfare2
2. Add a world and go

**Screenshots**
![image](https://user-images.githubusercontent.com/19922286/71573113-30bd9c00-2b1d-11ea-85aa-58e8907bc86a.png)
![image](https://user-images.githubusercontent.com/19922286/71573899-0b329180-2b21-11ea-8990-3a184662b9da.png)

**Rendering Glitches**
Are you using Optifine?
Yes

**Additional context**

**Crashes**
- Are you running the latest version of Dynamic Trees?(Currently 0.9.6)
![image](https://user-images.githubusercontent.com/19922286/71573160-5ba7f000-2b1d-11ea-83ff-56449db0382b.png)

**Mods List**
Just the bug of DT & AW2. I dont know where to submit this bug. This or that?
![image](https://user-images.githubusercontent.com/19922286/71573168-6cf0fc80-2b1d-11ea-91e7-85e62c92091a.png)

**Comment by ROMVoid95** [comment]
are you trying to have DynTrees in AW2 structures?

**Comment by ghost** [comment]
This has been fixed
