### ISSUE TITLE
Disabling generation of new dynamic trees

### ISSUE THREAD

**Issue by Bibovsky** [ferreusveritas/Dynamic-Trees#389]
Is there any way to disable generation of new dynamic trees through config files? "Tried to add entity dynamictrees:falling_tree but it was marked as removed already" error kills server tps, but i want to leave generated ones in my world to exist.

**Comment by AlyceOsbourne** [comment]
Yeah there already is, check for something along the lines of "replace vanilla generation" in the cfg, near the bottom I think

**Comment by AlyceOsbourne** [comment]
B:worldGen=true to false

**Comment by Bibovsky** [comment]
missed that line somehow, thanks
