### ISSUE TITLE
Suggestion, Trees have a harder time surviving in Desert, along with cactus being added?

### ISSUE THREAD

**Issue by Kowantify** [ferreusveritas/Dynamic-Trees#39]
Would be cool if there was a slim chance a tree could survive in a desert biome, along with barely being able to throw down trees around it in hopes there is even soil nearby, AND water within atleast a 30 block radius. and cactus would grow the same way as trees and eventually get bigger,

**Comment by ghost** [comment]
Are you suggesting that trees should have a chance to spawn in the desert?  

- Trees don't spawn in the desert.  
- Trees planted in the desert won't grow very tall. 
- Trees can't be planted in sand. 
- Seeds that are dropped in the desert on dirt will have only a very slim chance of planting themselves.  
- I'm not doing anything with waterblock searching to complicate an already complex system. 
- I'm happy with how the cacti grow and I'm not changing it.

In fact i'm not really sure what you are asking.  It sounds like 3 or 4 suggestions but I can't figure out what you're trying to say.

**Comment by Kowantify** [comment]
Sorry, i should have explained better
 - Keep trees from spawning on sand
- Allow trees that are in a desert biome on Dirt/Soil to grow in the desert but at a slower rate and a chance of dying. 
- Referring to one above make a watering can that can help trees grow a little faster and live longer, without having to change water block system as u mentioned. and possibly preventing tree from dying as I mentioned above.
- Allow cacti to have same growing features as trees, as in start small eventually grow to be big cacti.
- Trees that are grown in desert on soil have a chance of spawning new trees around it, but decreased chance it will happen since it is in Desert Biome.

If you don't catch my drift I understand these are multiple suggestions, but would be cool too see implemented. if not no harm done.

**Comment by ghost** [comment]
Okay that does clear it up.

 - Trees already don't spawn on sand
 - Trees growing in a desert do grow slower and don't get as large. Chance of dying is configurable in the config file.
 - Watering cans are outside of project scope
 - Cacti do grow like trees now(start small, progressively get bigger and branch)
 - Trees planted in a desert already do spawn trees around them if there's viable dirt.  With a decreased success rate because it's a desert.

**Comment by Kowantify** [comment]
wtf, you literally already have some suggestions I had I didn't realize it! and for the first one I didn't mean for trees to spawn on sand, I ment as in if I place soil in a desert it would just grow slower but u already have that configd the exact way I mentioned, awesome mod!
