### ISSUE TITLE
crash with growing trees on a skyblock, java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Ethern8ai** [ferreusveritas/Dynamic-Trees#390]
Hello, i tryed to look online for similar bug but it does not seem common, though i am preety sure that it is a simple issue, would anyone have an idea of the issue? is it compatibility? or is it the specs of my computer (also possible)

**Describe the bug**
I am doing tests with dynamic trees on my stable modpack and i planted 9 trees in a circle, game crashed in less then a mintue

**To Reproduce**
growing trees in my modpack

**Crashes**
- running the latest version of Dynamic Trees
[crash-2020-01-11_18.19.43-client.txt]

(https://github.com/ferreusveritas/DynamicTrees/files/4049670/crash-2020-01-11_18.19.43-client.txt)

**Comment by kierajreed** [comment]
Please use [pastebin](https://pastebin.com/) for error logs and stack traces.

**Comment by kierajreed** [comment]
Additionally, please include a mod list.

**Comment by Ethern8ai** [comment]
Hello SkyHawkB, Sorry I thought it would be the easyest way for you :s 
there is the pastebin: https://pastebin.com/T8Yb4zDM
the mod list is inside, i have one that has all the mods of my test pack included the deactivated ones, i can drop it on pastebin if needed.
thanx

**Comment by kierajreed** [comment]
`java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockPlanks$EnumType, values=[acacia, dark_oak]} to oak on block minecraft:leaves2, it is not an allowed value`
Interesing. I'll look into it. Thanks for the assistance.

**Comment by Ethern8ai** [comment]
Well thank you very much for finding my case interesting xD

**Comment by ghost** [comment]
At no point does the backtrace from the crashlog show any dynamic trees calls.  There are two other mods that are called however.  Optifine and Portable Jim's BetterBuildersWands.  As a test try removing the BBW mod and see if you can reproduce the crash with Dynamic Trees.

**Comment by Ethern8ai** [comment]
this is very weird as BBW (lmao) is on my pack for a long time and never caused issues, i will try the test during the week, slow computer and lots of work ^^
thank you very much, i keep you posted!

**Comment by Ethern8ai** [comment]
Thank you very much, i pushed on my test and yet there is no crash, do you have some simple and good study source were i could learn to find those crash sources for my future issues?
very quick and good support, amazing mod, wish you the best!
p.s. still not thinking about a compatibility with forestry? i mean those two mods are ment to fuse ... or at least make a baby xD did you tryed to get in contact with the mod author? maybe he would be interested in a collaboration :)

**Comment by ghost** [comment]
You're welcome.  I'm sorry I don't have any kind of study source.  Over time you just learn what to look for as a programmer and know how to poke around.

**Comment by kierajreed** [comment]
There are some nice shortcuts one can try depending on what exception the log shows. But it's mostly experience as you debug logs for a long time.

**Comment by Ethern8ai** [comment]
thank you very much! i shall hunt the exceptions down :)
good luck with everything!
