### ISSUE TITLE
Aether II compat addon

### ISSUE THREAD

**Issue by AnasterianSunstrider** [ferreusveritas/Dynamic-Trees#391]
Dear creators of Dynamic Trees, I'd like to bring to your attention the Aether II , which is a really popular mod with 3,020,827 downloads (from all versions together) . Please consider creating a compat addon for it. https://www.curseforge.com/minecraft/mc-mods/the-aether-ii

**Comment by kierajreed** [comment]
We do not make addons ourselves, but I will add it to the request list so that whoever does want to make an addon and can, can do it themselves.
