### ISSUE TITLE
Suggestion: Desires & Illnesses

### ISSUE THREAD

**Issue by MegaGamer265** [ferreusveritas/Dynamic-Trees#393]
After a long time without rain trees should die out unless they are near a water source. When there are no trees the chance of rain is pretty much zero so it will be a lot harder plant new trees to increase rain and if there are a lot of trees the chance of rain increases because trees send out chemicals wich can bind the water drops in the air together and it starts to rain wich again increases population of trees and so on. Trees should have illnesses like mushrooms or insects that kill forests and spread but soon after trees should regrow so rain chance wont go down to fast. Thick trees should not remove blocks around them, instead they should grow around them! Tropical trees should be 3x3 blocks thick or more in my opinion and a lot more branches so they are more like this:
![large_jungle-tree-1-16395](https://user-images.githubusercontent.com/47698400/72560683-d60b9a80-38a7-11ea-9278-d929d6498d88.png)
And it would be cool to add cactus fruits!

**Comment by kierajreed** [comment]
Good suggestions, but unfortunately out of scope of this project. I'll remember the cactus fruit idea, though. That'd be a very nice addition.
