### ISSUE TITLE
How goes the updating to modern versions of minecraft?

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [ferreusveritas/Dynamic-Trees#396]
With 1.16 just around the corner I was wondering when we will see my fave tree gen mod in 1.13,1.14,1.15 or 1.16? I realize a LOT changed since 1.12.2. Which support from Forge has been dropped I might add. Been missing this bad for vanilla, BOP and Wild Nature. Thanks.

**Comment by kierajreed** [comment]
Due to ferreus being busy working on other projects ([check it out!](https://playoutworlder.com/)) and no one else wanting to do it, slow. I've been messing around, but it's a lot of code and very hard to do right. It'll get there, but not for a long time unless someone helps out.

**Comment by harrislapiroff** [comment]
Is there an open ticket/branch to track this on @SkyHawkB? I'm not totally sure I can help out, but I'm interested in following progress and *might* be able to dip in. (Totally new to mod dev, but not new to software engineering.)
