### ISSUE TITLE
Dynamic Trees are not generating on "River" biome

### ISSUE THREAD

**Issue by BlackLightTR** [ferreusveritas/Dynamic-Trees#397]
Dynamic Trees are not generating on "River" biome

I was playing with my mod pack when I see a river I noticed trees are normal trees and they belong to river biome somehow. Also, I had streams mod and it doesn't work too.

![2020-01-28_13 56 36](https://user-images.githubusercontent.com/60400977/73288728-92e8ea00-420c-11ea-8967-1b9e3fad6889.png)
![2020-01-28_13 56 39](https://user-images.githubusercontent.com/60400977/73288746-98463480-420c-11ea-98b9-406f81c6618b.png)
 

My mods:
Ice and Fıre
RC Complex
ElectroblolbsWizardary
Mowziesmobs
Forgelin
Bibliocraft
Pam's Harvestcraft
Librarian Lb
Tinkers Construct
Quark
Basemetals
Better Animals Plus
ExtraUtils2
WizardsAnimals
MysticalWorld
NetherEx
Atum
MrCrayFishs Furniture Mod
Optifine
Exotic Birds
Charm
Fishs Undead Rising
Craft Tweaker
Agricraft
Rustic
Mystical Wİldlife
Better Foliage
Mantle
Rex's Additional Structures
Farseek
Libraryex
Advanced Fishing
Streams
Coral Reef

**Comment by ghost** [comment]
Dynamic Trees does not generate trees on the river at all, as it is intended not to.  It also cancels the vanilla generation on rivers using the means devised by the forge API to the furthest extent possible.  You must have another mod that is adding those trees to the rivers.  Try testing by temporarily removing the most suspicious(non-dynamic trees) mods and making a new world.
