### ISSUE TITLE
[Suggestion] Larger (or possibly more realistic) trees?

### ISSUE THREAD

**Issue by kCorki99** [ferreusveritas/Dynamic-Trees#399]
I was wonder if possibly there could be a config option or something like that to make it so that when forest and trees generate, they will naturally generate being around twice there current height. 

I'd like that because in real life, many of these large old growth forests (or virgin forests) would be 30+ meters in height (depending on tree species and local climate of course) 

I mean, the Conifer Forest in BoP already has some pretty realistically sized old growth firs, so it's not a question of height. The Roofed forest already has some pretty wide branches so not that either.

But I could just be underestimating the complexity of having to generate such large branches in three dimensions which is a good possibility 

I just think walking under the canopy of such a large forest with their branches and imposing sizes would be such a cool and immersive feature

Sincerely, Corki

**Comment by sirati** [comment]
i am so for this

**Comment by ghost** [comment]
Thank you for the suggestion.  I intend to add more mega varieties of some existing vanilla species soon.
