### ISSUE TITLE
crash in charging texture

### ISSUE THREAD

**Issue by delbass** [ferreusveritas/Dynamic-Trees#402]
**Describe the bug**
i crash eveyr time one textures is loaded

**To Reproduce**
every time i charge my load

**Screenshots**

**Rendering Glitches**
Are you using Optifine? no

**Additional context**

**Crashes**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  IGCMPatchingLoader (IGCM_v1.2.10_mc1.12.2.jar)
  FirstAid CoreMod (firstaid-core-1.6.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  LoadingPlugin (HardcoreBuoy-1.12-1.1.0.jar)
  LoadingPlugin (BetterWithLib-1.12-1.5.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 2/1/20 2:57 PM
Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
	at net.minecraft.client.renderer.BlockModelRenderer.func_187494_a(BlockModelRenderer.java:210)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187496_a(BlockModelRenderer.java:252)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:109)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:65)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187494_a(BlockModelRenderer.java:210)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187496_a(BlockModelRenderer.java:252)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:109)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:65)

-- Block model being tesselated --
Details:
	Block: dynamictreesbop:leaves_palm[hydro=1,tree=0]
	Block location: World: (1069,75,306), Chunk: (at 13,4,2 in 66,19; contains blocks 1056,0,304 to 1071,255,319), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
	Using AO: false
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)

-- Block being tesselated --
Details:
	Block type: ID #1027 (tile.leaves_palm // dynamictreesbop.blocks.BlockDynamicLeavesPalm // dynamictreesbop:leaves_palm)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (1069,75,306), Chunk: (at 13,4,2 in 66,19; contains blocks 1056,0,304 to 1071,255,319), Region: (2,0; contains chunks 64,0 to 95,31, blocks 1024,0,0 to 1535,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['johndelbass'/209, l='MpServer', x=1214.27, y=80.00, z=400.72]]
	Chunk stats: MultiplayerChunkCache: 588, 588
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-119,64,285), Chunk: (at 9,4,13 in -8,17; contains blocks -128,0,272 to -113,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 125031 game time, 125031 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: ~~ERROR~~ ConcurrentModificationException: null
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:49)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1423949704 bytes (1357 MB) / 3154116608 bytes (3008 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 51 mods loaded, 51 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version           | Source                                             | Signature                                |
	|:------ |:-------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2            | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                  | 9.42              | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCHIJA | forge                | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                      | None                                     |
	| LCHIJA | creativecoredummy    | 1.0.0             | minecraft.jar                                      | None                                     |
	| LCHIJA | firstaidcore         | 1.0.0             | minecraft.jar                                      | None                                     |
	| LCHIJA | biomesoplenty        | 7.0.1.2441        | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar      | None                                     |
	| LCHIJA | craftstudioapi       | 1.0.0             | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| LCHIJA | harvestcraft         | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zf.jar                    | None                                     |
	| LCHIJA | animania             | 1.7.3             | animania-1.12.2-1.7.3.jar                          | None                                     |
	| LCHIJA | antiqueatlas         | 4.5.1             | antiqueatlas-1.12.2-4.5.1.jar                      | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHIJA | antiqueatlasoverlay  | 1.2               | antiqueatlas-1.12.2-4.5.1.jar                      | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCHIJA | applecore            | 3.2.0             | AppleCore-mc1.12.2-3.2.0.jar                       | None                                     |
	| LCHIJA | aquaculture          | 1.6.8             | Aquaculture-1.12.2-1.6.8.jar                       | None                                     |
	| LCHIJA | astikorcarts         | 1.12.2-0.1.2.7    | astikorcarts-1.12.2-0.1.2.7.jar                    | None                                     |
	| LCHIJA | jei                  | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                          | None                                     |
	| LCHIJA | quark                | r1.6-177          | Quark-r1.6-177.jar                                 | None                                     |
	| LCHIJA | autoreglib           | 1.3-32            | AutoRegLib-1.3-32.jar                              | None                                     |
	| LCHIJA | betterwithlib        | ${version}        | BetterWithLib-1.12-1.5.jar                         | None                                     |
	| LCHIJA | ctm                  | MC1.12.2-1.0.1.30 | CTM-MC1.12.2-1.0.1.30.jar                          | None                                     |
	| LCHIJA | immersiveengineering | 0.12-92           | ImmersiveEngineering-0.12-92.jar                   | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | betterwithmods       | 1.12-2.3.20-1027  | BetterWithMods-1.12-2.3.20-1027.jar                | None                                     |
	| LCHIJA | bibliocraft          | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
	| LCHIJA | chameleon            | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| LCHIJA | controlling          | 3.0.6             | Controlling-3.0.6.jar                              | None                                     |
	| LCHIJA | configmod            | v1.0              | coroutil-1.12.1-1.2.36.jar                         | None                                     |
	| LCHIJA | extendedrenderer     | v1.0              | coroutil-1.12.1-1.2.36.jar                         | None                                     |
	| LCHIJA | coroutil             | 1.12.1-1.2.36     | coroutil-1.12.1-1.2.36.jar                         | None                                     |
	| LCHIJA | igcm                 | 1.2.2             | IGCM_v1.2.10_mc1.12.2.jar                          | None                                     |
	| LCHIJA | playerrevive         | 1.0               | PlayerRevive_v1.2.28_mc1.12.2.jar                  | None                                     |
	| LCHIJA | creativecore         | 1.9.9             | CreativeCore_v1.9.90_mc1.12.2.jar                  | None                                     |
	| LCHIJA | customoregen         | 1.12              | Custom-Ore-Generation-Revival-Mod-1.12.2.jar       | None                                     |
	| LCHIJA | dynamictrees         | 1.12.2-0.9.7      | DynamicTrees-1.12.2-0.9.7.jar                      | None                                     |
	| LCHIJA | dynamictreesbop      | 1.12.2-1.4.1e     | DynamicTreesBOP-1.12.2-1.4.1e.jar                  | None                                     |
	| LCHIJA | dynamictreesphc      | 1.12.2-1.4.2      | DynamicTreesPHC-1.12.2-1.4.2.jar                   | None                                     |
	| LCHIJA | engineersdoors       | 0.8.0             | engineers_doors-1.12.2-0.8.0.jar                   | None                                     |
	| LCHIJA | gravestone           | 1.10.2            | gravestone-1.10.2.jar                              | None                                     |
	| LCHIJA | hardcorebuoy         | ${version}        | HardcoreBuoy-1.12-1.1.0.jar                        | None                                     |
	| LCHIJA | immersivecables      | 1.3.2             | ImmersiveCables-1.12.2-1.3.2.jar                   | None                                     |
	| LCHIJA | immersiveposts       | 0.1.5             | ImmersivePosts-0.1.5.jar                           | 0ba8738eadcf158e7fe1452255a73a022fb15feb |
	| LCHIJA | immersivetech        | 1.3.10            | immersivetech-1.12-1.3.10.jar                      | None                                     |
	| LCHIJA | jehc                 | 1.7.0             | just-enough-harvestcraft-1.12.2-1.7.0.jar          | None                                     |
	| LCHIJA | jeresources          | 0.9.2.60          | JustEnoughResources-1.12.2-0.9.2.60.jar            | None                                     |
	| LCHIJA | morpheus             | 1.12.2-3.5.106    | Morpheus-1.12.2-3.5.106.jar                        | None                                     |
	| LCHIJA | mousetweaks          | 2.10              | MouseTweaks-2.10-mc1.12.2.jar                      | None                                     |
	| LCHIJA | spiceoflife          | 1.3.12            | SpiceOfLife-mc1.12-1.3.12.jar                      | None                                     |
	| LCHIJA | storagedrawers       | 1.12.2-5.4.0      | StorageDrawers-1.12.2-5.4.0.jar                    | None                                     |
	| LCHIJA | tramplestopper       | 1.2.0.4           | tramplestopper-1.12.2-1.2.0.5-universal.jar        | None                                     |
	| LCHIJA | weather2             | 1.12.1-2.6.12     | weather2-1.12.1-2.6.12.jar                         | None                                     |
	| LCHIJA | worleycaves          | 1.2.2             | worleycaves-1.2.2.jar                              | None                                     |
	| LCHIJA | firstaid             | 1.6.2             | firstaid-1.6.2.jar                                 | 7904c4e13947c8a616c5f39b26bdeba796500722 |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  
RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  pw.prok.realbench.asm.RBTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
IGCMPatchingLoader (IGCM_v1.2.10_mc1.12.2.jar)
  com.creativemd.igcm.core.IGCMTransformer
FirstAid CoreMod (firstaid-core-1.6.2.jar)
  ichttt.mods.firstaid.common.asm.PotionTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LoadingPlugin (HardcoreBuoy-1.12-1.1.0.jar)
  betterwithmods.core.ClassTransformer
LoadingPlugin (BetterWithLib-1.12-1.5.jar)
  betterwithmods.library.core.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
**Mods List**
If your crash log does not contain a list of mods or you have no crash log then please provide a full list of the mods you are using complete with mod versions.
What version of Forge are you running?(e.g. 1.12.2-14.23.5.2768)

**Comment by ghost** [comment]
Every time you charge your load?  Try narrowing down a few of the mods until you figure out which one is not playing nice with Dynamic Trees.  Also update your mods to the latest to see if that clears it up.

**Comment by ghost** [comment]
This issue is old which is mostly my fault.  Chances are the problem has already been fixed. If this issue persists after testing with my instructions then drop a line and I'll reopen the issue.
