### ISSUE TITLE
TreeHelper.getExactSpecies seem to not working for trees more than 1 block in diameter

### ISSUE THREAD

**Issue by Prunoideae** [ferreusveritas/Dynamic-Trees#407]
**Describe the bug**
I have a modified Thermal Expansion for have it integrated with the DT, but it seems that the function doesn't functioning if the tree is more than 1 block, as the code always report the species as Species.NULLSPECIES.
At first I guess it's because the tree species registered from addons made the check wrong, but it seems that it actually doesn't.
I didn't have the DT modified, it's the newest version on CurseForge.

**To Reproduce**
![image](https://user-images.githubusercontent.com/24620047/74699084-b5ce5300-523a-11ea-8e50-32332eae6092.png)

This is my code for checking valid trees, sorry for I'm not publishing it on Github since I'm quite lazy and the modpack is still on heavy developing.

**Screenshots**
Using it on a single block tree and the result (Vanilla Spruce Tree):
![image](https://user-images.githubusercontent.com/24620047/74699187-0c3b9180-523b-11ea-9102-04bc90add1e9.png)
![image](https://user-images.githubusercontent.com/24620047/74699174-05148380-523b-11ea-9910-79156e1b9722.png)

Using this on a multi block based tree and the result is not found (BOP's Fir Tree):
![image](https://user-images.githubusercontent.com/24620047/74699330-5f154900-523b-11ea-8677-4e89f54614d0.png)
![image](https://user-images.githubusercontent.com/24620047/74699449-ab608900-523b-11ea-978b-3cbe63c08ac7.png)

**Mods List**
Forge 14.23.5.2847
DynamicTrees 0.9.7
Thermal Expansion - Own modified version

I tested the mod in a separate instance so this is all the mods present.

**Comment by ghost** [comment]
Thick trunk were still fairly new when I last worked on them and the getExactSpecies function never really accounted for them properly.  Consider adding this wrapper function to your codebase to work around the problem until I modify the DT codebase.

```
	public static Species getExactSpeciesCustom(IBlockState blockstate, World world, BlockPos pos) {
		if(blockstate.getBlock() instanceof BlockTrunkShell) {
			BlockTrunkShell trunkShell = (BlockTrunkShell)blockstate.getBlock();
			ShellMuse muse = trunkShell.getMuse(world, pos);
			return getExactSpecies(muse.state, world, muse.pos);
		}
		return getExactSpecies(blockstate, world, pos);
	}
```

Hope this helps.
