### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by wincraft64** [ferreusveritas/Dynamic-Trees#409]
It would be very nice if you could update DT to a newer version of Minecraft like 1.14.4 or 1.15.2. Because to play the Mod at this versions is much better. I hope you can

**Comment by kierajreed** [comment]
As I have said in #285, the update is being worked on, but not very actively. In addition, I've talked with the other devs and they have said they want to maintain the 1.12.2 version rather than update at this time, so I'm working alone. Unfortunately, you're going to have to wait, probably for a good while.

**Comment by Cr4fTJuNkiE** [comment]
1.12.2 is dead though. Even abandoned by the Forge team. I understand a lot of mods are on 1.12.2, but NOT prioritizing modern versions of Minecraft is unwise IMHO. This is a "must have" mod for a lot of ppl.

**Comment by ghost** [comment]
1.12.2 and DT is currently used for the most popular modpack that ever existed, RLCraft.  It's only dead when people stop playing it, which will be approximately never.

**Comment by Cr4fTJuNkiE** [comment]
Or if/when RLCraft updates to modern versions of MC. I love DT! It's one of the best tree gen mods ever. We all need it updated! Maybe add some more devs? Wish I knew Java so I could help. Frustrating.Thx.

**Comment by ghost** [comment]
Sure.  I'll just open that fresh box of devs I've been hoarding and add them in. ;-) I haven't turned anyone away who was interesting in porting to newer version.

**Comment by Cr4fTJuNkiE** [comment]
That would be nice if it worked that way wouldn't it. lol So how hard would a port be for a person with zero coding experience? *sigh*

**Comment by kierajreed** [comment]
Very. Dynamic Trees is a complex mod with many things one wouldn't find in simpler mods. I'm in the middle of porting it right now and it's quite hard, even with experience.

**Comment by kierajreed** [comment]
P.S. Unless every mod within RLCraft updates, the pack won't update. Since the pack has so many mods, the likelihood of it ever updating is slim to none, as many mods would need to be dropped or replaced.

**Comment by Cr4fTJuNkiE** [comment]
I know it's been a while, but has there been any progress on the 1.15.2 version? Thanks.

**Comment by kierajreed** [comment]
See #285. No. The devs have been busy working on other projects and no one else has expressed interest in updating this mod.
