### ISSUE TITLE
[Suggestion] Dynamic Cacao Tree

### ISSUE THREAD

**Issue by WrongWeekend** [ferreusveritas/Dynamic-Trees#41]
I think this mod works well in that apple trees are a distinct species rather than grown from oak. However cocoa beans should be treated the same way, with them being grown from a unique tree rather than grown onto jungle trees.

In real life the cocoa tree is smaller and more branching and spindly:

http://bioweb.uwlax.edu/bio203/s2008/boland_kirs/classificationtree.jpg

unlike the tall, straight jungle trees found in the game.

**Comment by ghost** [comment]
Not a bad idea.  I'll put together a strawpoll for the next release to see what others think of it.

**Comment by Deshiba** [comment]
Tripple yes to this

**Comment by ghost** [comment]
https://strawpoll.com/9pd94fyw

**Comment by WrongWeekend** [comment]
I forgot to mention that since cacao/cocoa are different spellings for the same thing, the spelling used for the tree should probably match what is used for the beans (cocoa).

**Comment by nephatrine** [comment]
@WrongWeekend  While they are sometimes used interchangeably, in my experience common usage in English seems to use "cocoa beans" but the plant itself is still usually called "cacao". Other usage has "cocoa" for the processed components and "cacao" for the raw ones. In many people's heads "cocoa" is synonymous with chocolate while "cacao" doesn't necessarily have that connotation and so I think the names should be different.

**Comment by ghost** [comment]
The strawpoll has spoken loudly.  This will be implemented in the near future.  Thanks again for the suggestion.
