### ISSUE TITLE
Odd behavior in player-grown trees

### ISSUE THREAD

**Issue by Jigbashmop** [ferreusveritas/Dynamic-Trees#411]
**Describe the bug**
I replanted some spruce trees and I've noticed they are following some odd growth patterns. Specifically, they grow wider than they do tall.

**To Reproduce**
Steps to reproduce the behavior: Plant a spruce cone and wait.

**Screenshots**
![20200320171342_1](https://user-images.githubusercontent.com/42393677/77207219-3351e100-6acf-11ea-87d5-7a127ff0e871.jpg)

**Additional context**
The problem seems to have started happening after I installed [Better Auto Jump](https://www.curseforge.com/minecraft/mc-mods/better-auto-jump) and [Better Signs](https://www.curseforge.com/minecraft/mc-mods/better-signs), though I can't imagine either of those has anything to do with it. Then again, it's possible I just didn't notice until now.

**Mods List**
 
- Just Enough Items (JEI) (by mezz) v4.15.0.291
- CraftStudio API (by ZeAmateis) v1.0.1.95
- CustomOreGen (by lawremi) v1.8.1
- ConnectedTexturesMod (by tterrag1098) v1.0.1.30
- Blood Arsenal (by Arcaratus) v2.2.2
- Carry On (by Tschipp) v1.12.3
- Guide-API (by TehNut) v2.1.8
- Animus (by TeamDman) v2.1.7
- TickrateChanger (by Guichaguri) v1.0.14
- Realistic Terrain Generation (by WhichOnesPink) v6.1.0.0
- OreLib (by OreCruncher) v3.6.0.1
- Thaumic Augmentation (by TheCodex6824) v1.1.17
- Thaumic Inventory Scanning (Thaumcraft Addon) (by BlayTheNinth) v2.0.10
- SleepingOverhaul (by CosmicDanAU) v1.0.0
- Enchanting With Thaumcraft (by Frostnox) v1.2
- Farseek (by delvr) v2.5
- Sound Filters (by Tmtravlr) v0.12
- Double Doors (by Serilum) v1.2
- Thaumcraft (by Azanor13) v6.1
- LLibrary (by _ForgeUser11902522) v1.7.19
- SwingThroughGrass (by exidex) v1.2.3
- Antique Atlas (by Hunternif) v4.6.3
- Chisel (by tterrag1098) v1.0.1.44
- Unlimited Chisel Works (by asiekierka)
- Inventory Tweaks (by JimeoWan) v0.3.4
- Dynamic Surroundings (by OreCruncher) v3.6.0.2
- Schematica (by Lunatrius) v1.8.0.169
- LunatriusCore (by Lunatrius) v1.2.0.42
- Mantle (by mDiyo) v1.3.3.55
- Blood Magic (by WayofTime) v2.4.3
- No Recipe Book (by Seneschal_Luwin) v1.2.2
- Colytra (by TheIllusiveC4) v1.2.0.4
- Thaumic JEI (by Buuz135) v1.6.0
- CosmicLib (by CosmicDanAU) v0.4.0
- Serene Seasons (by TheAdubbz) v1.2.18
- Dynamic Trees (by ferreusveritas) v0.9.7
- [SBM] Wooden Shears (by BuiltBroken) v0.0.1b8.
- CoFH World (by TeamCoFH) v1.3.1.7
- CreativeCore (by CreativeMD) v1.10.5
- Thaumic Brewing (by daedalus4096) v1.0.2
- LittleTiles (by CreativeMD) v1.5.0
- VE-FluidHandling (by DarkGuardsman) v0.11.0
- Baubles (by Azanor13) v1.5.2
- Better Advancements (by way2muchnoise) v0.1.0.77
- Dynamic Darkness (by githubactions) v0.2.1
- [SBM] Wooden Buckets (by BuiltBroken) v0.2.0
- Wolf Armor and Storage (by satyrnidae) v2.2.3.1798
- Arcane Arteries (by maxish0t) v1.0.0
- Dynamic Trees - Thaumcraft Compat (by mangoose3039) v1.4.1e
- Global GameRules (by GoryMoon) v2.2.7
- Better Auto Jump (by oldjunyi) v1.1.1
- Ice and Fire: Dragons in a whole new light! (by alex1the1666) v1.8.4
- DrCyano's Lootable Bodies (by jriwanek) v2.4.0
- Easy Elytra Takeoff (by Serilum) v1.1
- Better Signs (by Angercraft) v1.0
- Animania (by Purplicious_Cow_) v1.7.3
- Bauble of Undying (by HeckinChloe) v1.0.1
- Fantastic Lib (by laike_endaril) v2.034
- More Overlays (by FeldiM245) v1.15.1
- Nutrition (by WesCook) v4.6.1
- Optifine vHD_U_F5

Using Forge-14.23.5.2847

**Comment by ghost** [comment]
This is bizarre.  Did you find any new information about this problem?

**Comment by ghost** [comment]
Can you try setting your scaleBiomeGrowthRate config option to 1.0 to see if that changes anything?  You're answer may help me to know where to look next.  Also.. what biome is this?  Use F3 debug screen to identify the biome.

**Comment by Jigbashmop** [comment]
Sorry for the late reply. The biome in the original screenshot is Extreme Hills, but I've noticed it happening in the nearby Taiga biome too.
![20200903131531_1](https://user-images.githubusercontent.com/42393677/92146648-04fb6000-ede8-11ea-89f0-d7ac130956d9.jpg)

Changing the config didn't seem to do anything. 
![20200903132535_1](https://user-images.githubusercontent.com/42393677/92147383-17c26480-ede9-11ea-9959-0dcf6b3399a2.jpg)

**Comment by ghost** [comment]
What are you doing with the mod TickrateChanger (by Guichaguri) v1.0.14?  I haven't seen it before and I'm curious if it's involved.

**Comment by Jigbashmop** [comment]
It's a dependency for Sleeping Overhaul by CosmicDanAU.

**Comment by ghost** [comment]
I can't reproduce the problem in a taiga biome with a spruce tree.  They all eventually grow to the proper size.  Are you waiting long enough for them to grow up?  Can you please post your dynamic trees config file?

**Comment by Jigbashmop** [comment]
It's entirely possible it's a fluke with my modlist or something. It's been a few months so I don't really recall much. Here's the config, I don't remember changing anything.

[Config.zip](https://github.com/ferreusveritas/DynamicTrees/files/5196969/Config.zip)

**Comment by ghost** [comment]
It might be, that's what I'm trying to figure out.  You took the time to submit a proper bug report so I'm trying to do my due diligence.

**Comment by ghost** [comment]
I can't reproduce this problem.  I've gone through the modlist you've provided and couldn't find an offender.  It's possible it is some kind of weird mod interaction that is causing this.  If new information about this problem if discovered by you or anyone else I will reopen this issue.  Thanks.
