### ISSUE TITLE
[Compat] No Tree Punching

### ISSUE THREAD

**Issue by GeebsRilie** [ferreusveritas/Dynamic-Trees#414]
I am trying to make dynamic trees work with No Tree Punching. The black list is ore:woodLog. what would i put here for dynamic trees to work with it?

**Comment by Jaboolian** [comment]
RLCraft has both mods working together. You could reference its config files.

**Comment by bdp1312** [comment]
Fixable using craftweaker with following script (forge 1.18, will likely work with other versions)
<tag:blocks:nottreepunching:always_drops>.add(<tag:blocks:dynamictrees:branches>);
<tag:blocks:notreepunching:always_breakable>.add(<tag:blocks:dynamictrees:branches>);
