### ISSUE TITLE
Importing Jo Codes from clipboard?

### ISSUE THREAD

**Issue by Some-Doofus** [ferreusveritas/Dynamic-Trees#415]
Sorry to ask this here, wasn't sure if there was a better place to ask questions.

Is the woodland staff also able to use JoCodes taken from trees in other worlds? On the mod description page you point out that any JoCode pulled with the staff is copied to clipboard, which works fine - I've been collecting the JoCodes for trees I like in a text file to hopefully use later, but I can't figure out how to copy the JoCodes from the text file back onto the woodland staff so I can place the trees I copied earlier. You also mentioned sharing tree models via this method so I assume it's possible somehow, but could you enlighten me how exactly?

Thanks guys, absolutely adore the mod thus far, can't play without it.

**Comment by ghost** [comment]
`/give @p dynamictrees:staff 1 0 {color:"#88FF00",code:"OUiVpPzkbtJ9uSRPbZP",readonly:1,tree:"dynamictrees:birch",maxuses:16,display:{Name:"Frog"}}`

I'm so sorry I didn't answer this earlier.  This issue slid by me unnoticed.

**Comment by Some-Doofus** [comment]
Thanks for the reply. I take it the color, species and display name aso need to be entered manually? Or if you just leave them blank or put "~" does that match the species it's meant to be?

**Comment by ghost** [comment]
Those are optional tags.
`/give @p dynamictrees:staff 1 0 {code:"OUiVpPzkbtJ9uSRPbZP",tree:"dynamictrees:birch"}`
Is the barebones command for getting a JoCode.  I added the other stuff for completeness.  You can change the color of the crystal on the staff as well as limit the number of times it can be used in survival.  This way admins can give away cool trees in staff form.

**Comment by Some-Doofus** [comment]
Oh ok that makes sense. Thanks again for the clarification :)

**Comment by ghost** [comment]
This can now be easily done with the `/dt createstaff` console command.
