### ISSUE TITLE
Some silverwood trees do and some dont

### ISSUE THREAD

**Issue by SyndicateServers** [ferreusveritas/Dynamic-Trees#416]
SOME silverwood and greatwood trees do not spawn in dynamic.
im using DT and the DT thaumcraft

![2020-03-31_19 49 55](https://user-images.githubusercontent.com/42458375/78085174-2d3de900-7388-11ea-9aca-66704148964b.png)

I'm not using optifine

its a modpack I'm building with about 125 different mods, I shut them all off but dynamic trees, DT thaumcraft and thaumcraft and still get the issue.

**Comment by LukaPix** [comment]
This should be at : https://github.com/the-realest-stu/DynamicTrees-TC/issues

**Comment by ghost** [comment]
This was posted in the wrong mod's issues
