### ISSUE TITLE
Cant run on Forge Servers.

### ISSUE THREAD

**Issue by trillo05** [ferreusveritas/Dynamic-Trees#418]
**Describe the bug**
When runned on a forge server, the mod won't load, regular trees will genrate instead an you cant place any blocks from the mod.
when you try to load a world created in singleplayer, where the mod does work, the server "ignores" the mod and replaces all of the od related blocks, such as leaves with air blocks.
.
**To Reproduce**
-create a forge server
-intall mod
-run server

**Screenshots**
t think they're not required as i describe the issue as it is.

**Rendering Glitches**
-Are you using Optifine?
 no (i've tried using it with the mods and it doesnt fix anything)
-Trees (and any of the mod's blocks) won't generate or render when loading a single player world.

**Additional context**

**Crashes**
no crashes. 

**Mods List**
forge 1.12.2-14.3.5.2768 (server mode)
mods in a screenshot.
![image](https://user-images.githubusercontent.com/63746405/79377382-3353ce00-7f21-11ea-9544-9931873a37b5.png)

**Comment by kierajreed** [comment]
What if you use the normal, non-deobf version? Also, what happens if you run a server with just this mod? Will it work then? It's a lot more helpful to have that information for the devs to determine the exact issues.

**Comment by ghost** [comment]
Yes.  Do NOT use the deobf version for gameplay.  That's for developers only.
