### ISSUE TITLE
Lack of tree-specific trunkshell blockstate

### ISSUE THREAD

**Issue by Foreck1** [ferreusveritas/Dynamic-Trees#419]
This is not an issue per se; the problem arises because of every tree that's wider than one block uses `dynamictrees:trunkshell`, but this block has a generic Block state which means that other mods can't target a specific tree shell but has to target **all tree shells**.

Why is this a problem? It's impossible to define a single tree as a whole to be affected by other mod, i.e. not being able to make redwood harvestable with an iron-tier axe only, since to make its shell unbreakable all trees would become unbreakable too.

**Comment by ghost** [comment]
This is an good suggestion.  My only problem is with the existing generic shell blocks in the world, how I would handle them.

**Comment by Foreck1** [comment]
This may be more work than needed, but a system where every tree "sheds" its generic shell to regrow their custom one could be an option. I'm no modder, so I don't know how viable is this.

**Comment by ghost** [comment]
Thank you for this suggestion.  I'll take it into consideration though the problem you are describing is not likely to be something fixable.
