### ISSUE TITLE
Can't move the player

### ISSUE THREAD

**Issue by Kekko961** [ferreusveritas/Dynamic-Trees#42]
Using 0.7.5a, randomly i can't move the player(but i can break block and interact with the world). Only way to solve is by switching to creative, close the world, reopen it but after some variable time(generally a short period) it stops again. I think it depends on dynamictrees because using the same allthemods 3 modified profile without dynamictrees in another world, this doesn't happen. I have the Bop addon too.

**Comment by ghost** [comment]
Are you in leaves by chance?  Could you send a screenshot of it happening?

**Comment by Kekko961** [comment]
No, It happens even inside caves. There aren't any strange things happening, apart the fact that i can't walk(but i can move the visual, i can even break blocks within range)

**Comment by ghost** [comment]
That's bizarre.  I can't think of why this would be happening.  It doesn't sound like lag.  I need to reproduce this so I guess we should start by having you list the mods you use.

**Comment by Kekko961** [comment]
https://imgur.com/a/jRDzZ this is the mod list

**Comment by ghost** [comment]
Oh dear.

**Comment by Kekko961** [comment]
I know, there are lot of mods haha

**Comment by Kekko961** [comment]
I think i know a way to replicate the bug, it happens most of the times when you're in a cave few blocks under a dynamic tree. to get around: switch to creative while stucked, close the game, reopen(journeymap will create a death waypoint but you don't lose stuff, i don't know if it can be useful as information) and switch back to survival and you'll be able to move again. when stucked you can't open the inventory.

**Comment by ghost** [comment]
Unable to replicate.  For this issue it is up to the poster to determine which mod is interacting badly.  When it is found resubmit a new issue citing the specific mod compatibility problem.
