### ISSUE TITLE
Crash when walking through a wooded area, 0.9.7

### ISSUE THREAD

**Issue by democat3457** [ferreusveritas/Dynamic-Trees#421]
Info here: https://github.com/CalaMariGold/Rebirth-Of-The-Night/issues/247

**Crashes**
- Are you running the latest version of Dynamic Trees? Yes
- If you are using the DT Biome O' Plenty Add-on do you have the latest version? Yes

What version of Forge are you running? 1.12.2-14.23.5.2847

**Comment by kierajreed** [comment]
Duplicate of #417.
