### ISSUE TITLE
Dynamic Trees Dimensional Blacklist not working

### ISSUE THREAD

**Issue by SangurianSoul** [ferreusveritas/Dynamic-Trees#422]
Bug
The bug first appeared to me trying to play The Betweenlands mod. It hadnt occurred to me that there might be an issue. However, upon entering the dimension, Dynamic causes "cascading world gen lag" that crashes the server. Oops. So i go to place The Betweenlands Dimension in the Dyncamic Trees black list (ID 20), but it doesnt work. Im stuck in the Betweenlands, because everytime i log in, the cascading world gen lag starts and i crash.

To Reproduce
Dynamic Trees + Betweenlands = Cascading World Gen Lag that crashes server. Blacklisting Betweenlands in Dynamic Config does not stop Dynamic from attempting to do this.

Rendering Glitches
No Optifine

Crashes
-Running MC 1.12.2
- Running latest Dynamic Trees
- Running latest The Betweenlands

Mod List
- Over 70+ mods, all work well together, until right now.

**Comment by ghost** [comment]
May I see the DynamicTrees config file?  And also the entire crash log.

**Comment by SangurianSoul** [comment]
Sure, i apologize, i dont know how to use github well, first is the config, then the crash reports

Also, i am basing this information off of the mountain of text my server command window is spewing before the crash. I may be completely wrong here, but i am certainly no programming wiz. i just barely know enough to run this server for my dad and brothers.

# Configuration file
```
client {
    # Rings of thick trees are rendered using a texture created with an expanded tangram construction technique. Otherwise the ring texture is simply stretched [default: true]
    B:fancyThickRings=true

    # Rooty dirt blocks will mimic the texture of adjacent soil blocks to better match the environment. Otherwise will always default to the most generic block [default: true]
    B:rootyTextureMimicry=true
}


debug {
    # Enable to mark tree spawn locations with wool circles. [default: false]
    B:worldGenDebug=false
}


interaction {
    # Modes: 0=Standard 1 Damage, 1=By Branch/Trunk Thickness, 2=By Tree Volume [range: 0 ~ 2, default: 1]
    I:axeDamageMode=1

    # If enabled players receive reduced fall damage on leaves at the expense of the block(s) destruction [default: true]
    B:canopyCrash=true

    # If enabled the Dirt Bucket will place a dirt block on right-click [default: true]
    B:dirtBucketPlacesDirt=true

    # If enabled then thinner branches can be climbed [default: true]
    B:enableBranchClimbling=true

    # If enabled then trees will harm living entities when falling [default: true]
    B:enableFallingTreeDamage=true

    # If enabled then trees will fall over when harvested [default: true]
    B:enableFallingTrees=true

    # Multiplier for damage incurred by a falling tree [range: 0.0 ~ 100.0, default: 1.0]
    S:fallingTreeDamageMultiplier=1.0

    # If enabled all leaves will be passable [default: false]
    B:isLeavesPassable=false

    # If enabled player movement on leaves will not be enhanced [default: false]
    B:vanillaLeavesCollision=false
}


seeds {
    # The rate at which seeds voluntarily drop from branches [range: 0.0 ~ 1.0, default: 0.0]
    S:dropRate=0.0

    # The minimum forestness that non-forest-like biomes can have. 0 = is not at all a forest, 1 = may as well be a forest. Can be fractional [range: 0.0 ~ 1.0, default: 0.0]
    S:minForestness=0.0

    # If enabled then seeds will only voluntarily plant themselves in forest-like biomes [default: true]
    B:onlyForest=true

    # The rate at which seeds voluntarily plant themselves in their ideal biomes [range: 0.0 ~ 1.0, default: 0.125]
    S:plantRate=0.125

    # Ticks before a seed in the world attempts to plant itself or despawn. 1200 = 1 minute [range: 0 ~ 6000, default: 1200]
    I:timeToLive=1200
}


trees {
    # The chance of a tree on depleted soil to die. 1/256(~0.004) averages to about 1 death every 16 minecraft days [range: 0.0 ~ 1.0, default: 0.0]
    S:diseaseChance=0.0

    # If enabled then sticks will be dropped for partial logs [default: true]
    B:dropSticks=true

    # If enabled apple trees will be generated during worldgen and oak trees will not drop apples [default: true]
    B:enableAppleTrees=true

    # If enabled then certain species trunks will be able to grow wider than a single block [default: true]
    B:enableThickTrees=true

    # Do X growth cycles at once while ignoring (X-1)/X attempts.  Higher numbers can improve client side performance but too high can make trees grow wierd. [range: 1 ~ 8, default: 2]
    I:growthFolding=2

    # Factor that multiplies the rate at which trees grow. Use at own risk [range: 0.0 ~ 16.0, default: 0.5]
    S:growthMultiplier=0.5

    # Factor that multiplies the wood returned from harvesting a tree.  You cheat. [range: 0.0 ~ 128.0, default: 1.0]
    S:harvestMultiplier=1.0

    # The maximum radius of a branch that is allowed to rot away. 8 = Full block size.  Set to 0 to prevent rotting [range: 0 ~ 24, default: 8]
    I:maxBranchRotRadius=8

    # Scales the growth for the environment.  0.5f is nominal. 0.0 trees only grow in their native biome. 1.0 trees grow anywhere like they are in their native biome [range: 0.0 ~ 1.0, default: 0.5]
    S:scaleBiomeGrowthRate=0.5
}


vanilla {
    # Right clicking with a vanilla sapling places a dynamic sapling instead. [default: false]
    B:replaceVanillaSapling=true
}


world {
    # Blacklist of dimension numbers for disabling Dynamic Tree worldgen [default: [7]]
    S:dimensionsBlacklist <
        7
	20
    >

    # Randomly generate podzol under select trees. [default: true]
    B:podzolGen=true

    # World Generation produces Vanilla cactus as well as Dynamic cactus if world gen replacement is enabled. [default: false]
    B:vanillaCactusWorldGen=false

    # World Generation produces Dynamic Trees instead of Vanilla trees. [default: true]
    B:worldGen=true
}
```

---CRASH REPORT---
[crash-2020-05-19_12.46.37-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/4654188/crash-2020-05-19_12.46.37-server.txt)

**Comment by ghost** [comment]
Can you do me a favor and temporarily remove DynamicTrees-TC and DynamicTrees-ExC and rerun your test to see if it crashes and/or tries to run in dim 20?  I'd like to eliminate it as possible suspects.

**Comment by ghost** [comment]
Also try removing the FastLeafDecay mod and do the same test.  Something has installed an ASM handler that's invoking 'net.minecraftforge.fml.common.eventhandler.ASMEventHandler_809_LeafUpdateEventHandler_UpdateNeighbour_NeighborNotifyEvent.invoke` and that's producing infinite recursion.  I suspect it might be FastLeafDecay though I'm not certain.

**Comment by SangurianSoul** [comment]
Sure! ill get back to you this morning!

Okay, test 1: Took out FastLeafDecay; got two crash reports from one crash?
[crash-2020-05-20_09.45.47-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/4657229/crash-2020-05-20_09.45.47-server.txt)
[crash-2020-05-20_09.45.46-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/4657230/crash-2020-05-20_09.45.46-server.txt)

Test 2: Took out Dynamics Add-Ons (in addition to FastLeafDecay); and got this one
[crash-2020-05-20_09.52.26-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/4657255/crash-2020-05-20_09.52.26-server.txt)

Test 3: Now i am confused. i made a brand new server with just Betweenlands and Dynamic Trees. totally fine. So obviously something else is involved... but if you can see anything on your end with a more experienced programmers eye, i would really appreciate it.

Test 4: Totally clean server with all the mods im using. Worked perfectly fine for the Betweenlands that had already loaded from previous test, then once i loaded new chunks, server crashed.
[crash-2020-05-20_13.31.33-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/4658420/crash-2020-05-20_13.31.33-server.txt)
[crash-2020-05-20_13.31.34-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/4658421/crash-2020-05-20_13.31.34-server.txt)

Test 5: I am almost positive its Quark being the offending third party here. i saw an ASM=Quark line or two fly by the screen when i was loading the server again and took quark out. All of my other mods are still present. hopefully its just a setting on Quark that can be changed to play nice? i dont really know what an ASM handler is, so maybe you have some advice?

Test 6: Okay, i turned off the "Greener Grass" in Quarks config, and as far as i can tell, it seems to have fixed the issue. So i dont know what exactly is causing what to do what, Or any of this actually helps you at all. Or if Dynamic didnt really have anything to do with this and i have wrongfully accused it.

So i apologize if i have wasted your time at all. Though i would like to at least try and understand what the problem really is, rather than just constantly throwing darts at a board until something sticks.

**Comment by SangurianSoul** [comment]
So its been a few days and i just haven't played MC at all. Logged on, jumped into the Betweenlands, issues started again.

So i have no idea where to go from here.

**Comment by SangurianSoul** [comment]
I finally figured it out.

It was Auto Ore Dictionary. It was causing huge lag trying to figure out all the ores, which for some reason was effecting Fast Leaf, which was then affecting Dynamic Trees.
