### ISSUE TITLE
Strange Glitch with Dynamic Trees when generating new chunks in a  Biomes o' Plenty multiplayer server world

### ISSUE THREAD

**Issue by TheJessaChannel** [ferreusveritas/Dynamic-Trees#425]
**Describe the bug**
Have a strange problem with Dynamic Trees showing up oddly and sparsely when generating new chunks after having deleted the region files in our multiplayer world. I downloaded the world to regenerate chunks with Chunk Pregenerator in singleplayer. I then upload the world back to the server and this happens:

(_The first screenshot of each biome is how it looks in the singleplayer version, the second how it shows up once transferred to the server_.)

![](https://i.imgur.com/V9ilEpn.png)

![](https://i.imgur.com/TV7vbZm.png)

---

![](https://i.imgur.com/tzVarKT.png)

![](https://i.imgur.com/vp3HJxg.png)

---

![](https://i.imgur.com/LhvEFa7.png)

![](https://i.imgur.com/PMMI6UY.png)

The reason I am not pregenerating right on the server is because I am adding in custom Roguelike Dungeons and for some reason, the dungeons will not generate on the server in an existing world, only in single player. So this method is a workaround for that problem. 

The dungeons do show up when I download the world, delete the regions I want to delete (anything we have already built on), use Chunk Pregenerator to pregenerate regions again and upload back to server.

So now I have great custom dungeons, but all the Dynamic Trees look like that.

**To Reproduce**

1. Download existing world from server, delete unwanted regions.
2. Open world in singleplayer and regenerate chunks with Chunk Pregenerator
3. Upload to server and go to new regions

**Rendering Glitches**
Are you using Optifine?

Yes: OptiFine_1.12.2_HD_U_E3.jar

**Mods List**
AlcatrazCore AlcatrazEscapee alcatrazcore-1.0.4.jar

AppleCore squeek502 AppleCore-mc1.12.2-3.2.0.jar

Arcane Essentials (Electroblob's Wizardry) FavouriteDragon Arcane Essentials-1.0.0-alpha-5.jar

Athenaeum codetaylor athenaeum-1.12.2-1.17.4.jar

ATLCraft Candles Mod _ForgeUser22964140 ATLCraftCandlesMod(MC1.12-Ver1.9).jar

AtomicStryker's Battle Towers atomicstrykergrumpy BattleTowers-1.12.2.jar

AtomicStryker's Infernal Mobs atomicstrykergrumpy InfernalMobs-1.12.2.jar

AutoRegLib Vazkii AutoRegLib-1.3-32.jar

Backpacks! Brad16840 backpacks 1.12.2 - 3.5.8.jar

Baubles Azanor13 Baubles-1.12-1.5.2.jar

Better Animal Models cybercat5555 betteranimals-1.12.2-5.3.0.jar

Better Animals Plus cybercat5555 betteranimalsplus-1.12.2-8.2.0.jar

Better Combat Rebirth SanAndreasP BetterCombat-1.12.2-1.5.6.jar

BiblioCraft Nuchaz BiblioCraft[v2.4.5][MC1.12.2].jar

Biomes O' Plenty Forstride BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar

Biomes o' Plenty Tools undertrox boptools-1.12-0.0.3.0.jar

Bloodmoon Lumien231 Bloodmoon-MC1.12.2-1.5.3.jar

Bookshelf DarkhaxDev Bookshelf-1.12.2-2.3.590.jar

BountifulBaubles Cursed1nferno Bountiful Baubles-1.12.2-0.1.6.jar

Carry On Tschipp CarryOn MC1.12.2 v1.12.3.jar

Ceramics KnightMiner Ceramics-1.12-1.3.7.jar

Charm svenhjol Charm-1.12.2-1.3.6.jar

ChickenShed 1.1x holmraven CSC-1.12-1.0.jar

Chisel tterrag1098 Chisel-MC1.12.2-1.0.2.45.jar

Chisels & Bits AlgorithmX2 chiselsandbits-14.33.jar

CoFH Core TeamCoFH CoFHCore-1.12.2-4.6.3.27-universal.jar

Comforts TheIllusiveC4 comforts-1.12.2-1.4.1.2.jar

ConnectedTexturesMod tterrag1098 CTM-MC1.12.2-1.0.2.31.jar

Cooking for Blockheads BlayTheNinth CookingForBlockheads_1.12.2-6.5.0.jar

CoralReef primetoxinz CoralReef-2.5-1.12.2.jar

CoroUtil Corosus coroutil-1.12.1-1.2.37.jar

CraftTweaker Jaredlll08 CraftTweaker2-1.12-4.1.20.562.jar

Decocraft RazzleberryFox Decocraft-2.6.3_1.12.2.jar

Doggy Talents percivalalb DoggyTalents-1.12.2-1.15.1.5.jar

Doomlike Dungeons JaredBGreat DoomlikeDungeons-1.13.2-MC1.12.2.jar

Dude! Where's my Horse? Noobanidus dwmh-1.12.2-3.1.2.jar

Dungeon Mobs Reborn sunconure11 dungeonmobs-5.8.5-MC1.12.2.jar

Dynamic Trees ferreusveritas DynamicTrees-1.12.2-0.9.7.jar

Dynamic Trees - Biomes O' Plenty Compat mangoose3039 DynamicTreesBOP-1.12.2-1.4.1e.jar

Dynamic Trees - Pam's Harvestcraft Compat ferreusveritas DynamicTreesPHC-1.12.2-1.4.2.jar

Easy Flint whisper_me_good_hentai EasyFlint-1.12.2-1.1.0.jar

Effortless Building Requioss effortlessbuilding-1.12.2-2.16.jar

Electroblob's Wizardry Electroblob ElectroblobsWizardry-4.2.9-MC1.12.2.jar

Entity Spring jglrxavpok entityspring-2.0.1.jar

Familiar Fauna Forstride FamiliarFauna-1.12.2-1.0.11.jar

Farseek delvr Farseek-1.12-2.5.jar

FastFurnace Shadows_of_Fire FastFurnace-1.12.2-1.3.1.jar

FastWorkbench Shadows_of_Fire FastWorkbench-1.12.2-1.7.3.jar

Fence Jumper TheRealp455w0rd fencejumper-1.12-1.0.5.jar

Ferdinand's Flowers c0_0ry Ferdinand's Flowers-1.12.x-1.10.4.1.jar

Grappling Hook Mod yyonne grapplemod-v11.1-1.12.2.jar

Hide Names thislooksfun1 HideNames-1.12.2-1.4.1.jar

Hostile Worlds - Invasions Corosus hostileworlds_invasions-1.12.1-1.1.13.jar

Hunger Overhaul ProgWML6 HungerOverhaul-1.12.2-1.3.3.jenkins148.jar

Ice and Fire: Dragons in a whole new light! alex1the1666 iceandfire-1.8.4.jar

Inspirations KnightMiner Inspirations-1.12.2-0.2.9.jar

Iron Chests ProgWML6 ironchest-1.12.2-7.0.72.847.jar

IvToolkit Ivorforce IvToolkit-1.3.3-1.12.jar

JEI Integration SnowShock35 jeiintegration_1.12.2-1.5.1.36.jar

JourneyMap techbrew journeymap-1.12.2-5.7.1.jar

Just a Few Fish Tmtravlr JustAFewFish-1.7_for_1.12.jar

Just Enough HarvestCraft (JEHC) mrAppleXZ just-enough-harvestcraft-1.12.2-1.7.0.jar

Just Enough Items (JEI) mezz jei_1.12.2-4.15.0.291.jar

Just Enough Resources (JER) way2muchnoise JustEnoughResources-1.12.2-0.9.2.60.jar

Just Sleep modmuss50 JustSleep-1.0.0.1.jar

Level Up! Legacy BeetoGuy Level Up! Legacy-0.15.1-1.12.2.jar

Literal Ascension jamieswhiteshirt_ literalascension-1.12.2-2.0.0.0.jar

LLibrary _ForgeUser11902522 llibrary-1.7.19-1.12.2.jar

Macaw's Bridges sketch_macaw mcw-bridges-1.0.4-mc1.12.2.jar

Magic seeds for Electroblobs Wizardry thetornadotitan SeedsForWizardry 1.0 For MC Forge 1.12.2.jar

Mantle mDiyo Mantle-1.12-1.3.3.55.jar

Mowzie's Mobs bobmowzie mowziesmobs-1.5.4.jar

MrCrayfish's Furniture Mod MrCrayfish furniture-6.3.1-1.12.2.jar

Nature's Compass Chaosyr NaturesCompass-1.12.2-1.8.5.jar

NBTEdit malte0811 NBTEdit-0.7.jar

No Tree Punching AlcatrazEscapee notreepunching-2.0.20.jar

Nomadic Tents skyjay1 NomadicTents-1.12.2-9.5.2.jar

Not Enough Pets AstroTibs NotEnoughPets-1.12.2-v2.1.0.jar

NotEnoughIDs fewizz_ NotEnoughIDs-1.5.4.4.jar

OreLib OreCruncher OreLib-1.12.2-3.6.0.1.jar

Pam's Cookables - Pam's Harvestcraft Addon BloodWorkXGaming pamscookables-1.1.jar

Pam's HarvestCraft pamharvestcraft Pam's HarvestCraft 1.12.2zg.jar

Pirates spectre0987 pirates-0.0.6B.jar

Placebo Shadows_of_Fire Placebo-1.12.2-1.6.0.jar

Potion Rings Shivaxi PotionFingers-r1.0-8.jar

PTRLib RazzleberryFox PTRLib-1.0.4.jar

Quark Vazkii Quark-r1.6-178.jar

RandomPatches TheRandomLabs randompatches-1.12.2-1.21.0.3.jar

Reborn Core modmuss50 RebornCore-1.12.2-3.19.2.522-universal.jar

Redstone Flux TeamCoFH RedstoneFlux-1.12-2.1.0.6-universal.jar

Roguelike Dungeons greymerktv RoguelikeDungeons-1.12.2-1.8.0.jar

Rope Bridge lordcazsius ropebridge-1.12-2.0.7.jar

Rope Ladders Selim_042 RopeLadders-1.12.2-2.0.0.jar

Rough Tweaks Lellson8 roughTweaks0.2.4-1.12.2.jar

Ruins (Structure Spawning System) atomicstrykergrumpy Ruins-1.12.2.jar

Rustic mangoose3039 rustic-1.1.4.jar

Save My Stronghold! YUNGNICKYOUNG savemystronghold-1.12.2-1.0.0.jar

Scaling Health SilentChaos512 ScalingHealth-1.12.2-1.3.42+147.jar

Serene Seasons TheAdubbz SereneSeasons-1.12.2-1.2.18-universal.jar

Shadowfacts' Forgelin ShadowfactsDev Forgelin-1.8.4.jar

Signpost Gollorum signpost-1.12.2-1.08.3.jar

Silent Lib SilentChaos512 SilentLib-1.12.2-3.0.14+168.jar

Simply Arrows DarkhaxDev SimplyArrows-1.12.2-1.0.4.jar

Spartan and Fire cbkovak spartanfire-0.07.jar

Spartan Shields ObliviousSpartan SpartanShields-1.12.2-1.5.4.jar

Spartan Weaponry ObliviousSpartan SpartanWeaponry-1.12.2-beta-1.3.8.jar

Stacksize wwrpg1 stacksize-1.12.2-1.0.jar

Streams delvr Streams-1.12-0.4.8.jar

Switch-Bow White_Draco switchbow-1.5.7.jar

The Disenchanter Mod impelon disenchanter-[1.12]1.6.jar

Tool Belt gigaherz ToolBelt-1.12.2-1.9.12.jar

TrashSlot BlayTheNinth TrashSlot_1.12.2-8.4.10.jar

Trinkets and Baubles XzeroAir Trinkets and Baubles-1.12.2-0.29.2.jar

Tumbleweed konwboj tumbleweed-1.12-0.4.7.jar

VeinMiner Portablejim VeinMiner-1.12-0.38.2.647+b31535a.jar

Watercan codetaylor watercan-1.12.2-1.1.3.jar

Waystones BlayTheNinth Waystones_1.12.2-4.1.0.jar

XP Tome bl4ckscor3 xptome-1.12.2-v1.1.4.jar

YUNG's Better Caves YUNGNICKYOUNG bettercaves-1.12.2-1.6.0.jar

 
 
 
**What version of Forge are you running?(e.g. 1.12.2-14.23.5.2768)**

Forge: forge-1.12.2-14.23.5.2847-universal.jar

**Comment by ghost** [comment]
That's really strange.  I wouldn't expect that to happen and I can't think of a reason that it does.  Have you found out anything new about this?

**Comment by ghost** [comment]
Are you also copying the level.dat file of the server?  Because if you aren't and the block ids are different then you're likely to find yourself in a situation where the leaves are a different id number.  In which case they'll show up as air and the bare trees will try to regrow the leaves with the correct leaves blocks. If I had to guess I'd say that's your problem.

**Comment by ghost** [comment]
This is caused by the level.dat file not being copied over from the single player pregenerator world to the final server world.  If you feel this to be incorrect then provide evidence otherwise and I will reopen the issue.  Thank you for your patience.
