### ISSUE TITLE
[1.12.2][shaders] Sky through block cracks / no block breaking animations / wrong animation side

### ISSUE THREAD

**Issue by ghost** [ferreusveritas/Dynamic-Trees#426]
## Description of Issue
With certain shaders enabled, block breaking animations on certain blocks don't trigger or the sky can be seen through them on the incorrect face of the block. They appear on oak wood for me, but not on things like stone, dirt, etc. so far.

## Steps to Reproduce
1. Enable any shaders (tested with Sildur's Vibrant Extreme & Extreme with VL v1.22 where there's no block breaking animation for oak wood and with SEUS renewed 1.0.1 where you can see the sky through the wood cracks on the wrong cube face) and install dynamic trees 0.9.8.

2. Go punch some oak wood.

## OptiFine Version
1.12.2_HD_U_F5

## F3 Debug Screenshot
https://imgur.com/YdTuOIX

**Comment by LukaPix** [comment]
on Optifine's website under "preview" there's also an F6 version for 1.12.2, you could try that

**Comment by ghost** [comment]
Does this also happen when you break Vanilla chests?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/13294361/92266912-fd05f380-eead-11ea-909f-4dbe6ab2dbef.png)

As you can see in the image there's a deeper issue with Optifine and some models.  This is a vanilla chest being broken in an Optifine modded minecraft.  If it doesn't work with vanilla chests it's highly unlikely that I'll be able to get it working with Dynamic Trees.
