### ISSUE TITLE
Change hardness from other mod

### ISSUE THREAD

**Issue by FOREVEREALIZE** [ferreusveritas/Dynamic-Trees#427]
I would like to know if is there a way to change the 8.0f value from [https://github.com/ferreusveritas/DynamicTrees/blob/1.12.2/src/main/java/com/ferreusveritas/dynamictrees/blocks/BlockBranchBasic.java#L180] to another. Any help would be appreciated.

**Comment by felixgames097** [comment]
### ### ### ### ### ### ### ### hello

**Comment by FOREVEREALIZE** [comment]
solved with mixin
