### ISSUE TITLE
How to get trees looking back to vanilla ones

### ISSUE THREAD

**Issue by Bjorndoesgaming** [ferreusveritas/Dynamic-Trees#428]
Hello, this is my first time typing anything on here so sorry in advance if my message isnt really that good or not enough on here. Im very curious on how i can change the tree textures back to vanilla ones. I like how the trees look but i dont like how they look in builds like my houses i have. I have tried changing in config 'World Generation produces Dynamic Trees instead of Vanilla trees. [default: true]' and i changed it to false but that doesnt seem to work. Any help is appreciated. :)

**Comment by leonbaronick** [comment]
You should still be able to place normal log blocks anyway.

Can you maybe attach a screenshot to better explain what you want to do? The option you changed only changes wheter dynamic trees generate in the world.

**Comment by Bjorndoesgaming** [comment]
I got three screenshots, one is showing how my trees look on my buildings and the others are before and after i have placed a log.
I dont know why it wont allow me to not place vanilla logs.
Ah alright, didnt realize that with that option.
![2020-07-07_16 45 11](https://user-images.githubusercontent.com/67880350/86798866-90b77100-c071-11ea-899b-1337f8f29398.png)
![2020-07-07_16 45 14](https://user-images.githubusercontent.com/67880350/86798868-91e89e00-c071-11ea-8f1e-4e73efa2d28f.png)
![2020-07-07_16 45 02](https://user-images.githubusercontent.com/67880350/86798870-91e89e00-c071-11ea-9799-93c5e4ee349f.png)

**Comment by ghost** [comment]
Dynamic Trees does not round the vanilla logs like that.  That's caused by another mod entirely.

**Comment by Bjorndoesgaming** [comment]
Oh, seriously? I will check which mod it is and come back to tell which it was. I thought Dynamic trees did it because it was a mod along with others i put in and came to my world to see the trees rounded like that. Thanks for the help you two :)

**Comment by WenXin20** [comment]
That's from the mod Better Foliage.  You can turn round logs off in the Better Foliage config.

**Comment by Bjorndoesgaming** [comment]
Ah alright, thanks!

**Comment by Bjorndoesgaming** [comment]
Yep, found the config where i could change the round logs. 👍
