### ISSUE TITLE
[1.12.2] FileNotFoundException megajungle.txt

### ISSUE THREAD

**Issue by leonbaronick** [ferreusveritas/Dynamic-Trees#429]
**Describe the bug**
This is not really a bug, it is just an error message that shows up in the console while launching the game.

[Error message](https://pastebin.com/2XF9wJck)

Seems like the megajungle.txt file is missing in the jar while still being used in the code somewhere or something like that.

**To Reproduce**
Start the game while Dynamic Trees is installed.

**Comment by ghost** [comment]
Yes.  This is an error resulting from my only partial WIP adding of mega sized jungle trees.  In time once I finish the feature this error will go away.
