### ISSUE TITLE
[Suggestion] 1.13 Dynamic Coral

### ISSUE THREAD

**Issue by Deshiba** [ferreusveritas/Dynamic-Trees#43]
I know this is way premature, but I just wanted to get it out there.

Technically Coral is a living underwater tree-like organism. It would be nice if we could get dynamic Coral somewhere in the far future.

**Comment by WrongWeekend** [comment]
While many species of corals (which are actually animals) do have branching patterns they aren't quite extensive or large enough to function like trees individually.

Though having a coral reef expand dynamically as a whole may make an interesting mechanic, if a difficult to achieve one.

**Comment by ghost** [comment]
That's more or less what I was thinking.  But I wanted to give it some thought before I closed it.
