### ISSUE TITLE
Some Trees Aren't Dynamic

### ISSUE THREAD

**Issue by Rage-GitHub** [ferreusveritas/Dynamic-Trees#431]
**Describe the bug**
When creating a new world, I notice some trees aren't dynamic and take a odd shape away from vanilla but use the vanilla blocks and have no Dynamic functionality.

**Screenshots**
https://imgur.com/a/cobwI5z

**Crashes**
- Are you running the latest version of Dynamic Trees?(Currently 0.9.6)
> Yes
- If you are using the DT Biome O' Plenty Add-on do you have the latest version?(Currently 1.4.1e)
> Yes
- If you are using the DT Thaumcraft Add-on do you have the latest version?(Currently 1.4.1e)
> Yes

**Mods List**
https://imgur.com/a/MDQURaD

What version of Forge are you running?(e.g. 1.12.2-14.23.5.2768)
> 1.12.2 (modded) forge-14.23.5.2854

**Comment by Excederus** [comment]
It looks like those trees are spawned in by the mod "Recurrent Complex".
You can probably disable the spawning of trees in that mods config file
