### ISSUE TITLE
Shaders wont add the waving effect to Dynamic Trees!

### ISSUE THREAD

**Issue by Draglorr** [ferreusveritas/Dynamic-Trees#434]
I have been trying to  fix this and i can't seem to figure it out! i personally use SIldurs Enhanced Default! Could i have some help please? i tried adding dynamictrees:leaves to the block>properties folder and it didn't do anything! (1.12.2)

**Comment by KnifeOfDunwall** [comment]
I have the same Problem. i use Chocapic 13 V8

**Comment by ghost** [comment]
Duplicate of #403
