### ISSUE TITLE
Server crash thread after updating your mod

### ISSUE THREAD

**Issue by SeagalKru** [ferreusveritas/Dynamic-Trees#441]
I'll provide a link to the bug report just in case:
https://github.com/odorousrex/DynamicTreesTraverse/issues/15

**Comment by ghost** [comment]
The problem is in the Traverse Add-On.  It's referencing stuff that's been deprecated since Nov 29, 2018 and was finally removed in the latest DT.  We'll see if we can't put together a pull request for Dynamic Trees Traverse to get this resolved.  In the meantime just run the previous DT version.

**Comment by SeagalKru** [comment]
DynamicTrees-1.12.2-0.9.11.jar
The update didn't help.
Crash server again:
[crash-2020-09-07_12.20.45-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/5182259/crash-2020-09-07_12.20.45-server.txt)

**Comment by SeagalKru** [comment]
If Dynamic Trees - Traverse Compat is no longer updated, should it be removed from the build and considered obsolete?
Is there no connection with the developer either?

**Comment by Harleyoc1** [comment]
Dynamic Trees isn’t the problem - it’s purely the Traverse compat that hasn’t been updated since 2018. We are trying to get in contact with the author of it but so far he has ignored/not seen the pull requests ferreus put in all the way back at the end of 2018. It’s not a difficult update and if the author doesn’t reply to our recent messages to perhaps give us control over the project then we will upload an updated version under a separate CurseForge project so the mod can live on.

**Comment by SeagalKru** [comment]
Good. I'll wait! While rolled back to version 0.9.8.

**Comment by SeagalKru** [comment]
Is it too early to upgrade to 0.9.12 (about Traverse)?

**Comment by ghost** [comment]
It's not too early.  You're right on time.  Just download the new version of the traverse add-on here:
https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-traverse

**Comment by SeagalKru** [comment]
Oh how. Now you need to wait for another mod to update:
[crash-2020-09-09_19.08.03-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/5196501/crash-2020-09-09_19.08.03-server.txt)
-----------------------------------------------------------------------------------
Mod dynamictrees (Dynamic Trees) requires [dynamictreestc@[1.12.2-1.4.2,) (Dynamic Trees - Thaumcraft Compat)

P.S.: rolled back from version "DynamicTrees-1.12.2-0.9.12.jar" to version "DynamicTrees-1.12.2-0.9.11.jar".
:)

**Comment by ghost** [comment]
That's in the works.  I hope to have it out today.

**Comment by SeagalKru** [comment]
Ok. Wait. )

**Comment by SeagalKru** [comment]
Great job dear modders! Everything works great! I can survive on my server again! Hooray! ;)

P.S.: Eh! Still with the Dynamic map to figure it out! None of the trees from your mod and additional mods to yours are shown on the online map. Or I didn't figure out how to enable it. Understand ...
