### ISSUE TITLE
[1.12.2-0.9.10] crashes

### ISSUE THREAD

**Issue by xemnes** [ferreusveritas/Dynamic-Trees#442]
just upgraded to the newer version, entered my world and crashed almost immediately during world generation. log seems to point to dynamic trees.
heres the crash log. https://pastebin.com/4cVDJngM

i intend to downgrade for now, the features of this version dont really make any difference to my setup.

**Comment by ghost** [comment]
Fixed.  I'll have an update out on curseforge very soon.
