### ISSUE TITLE
An absolute WTF issue

### ISSUE THREAD

**Issue by Sunconure11** [ferreusveritas/Dynamic-Trees#444]
![Screenshot 2020-09-09 08 07 10](https://user-images.githubusercontent.com/5614902/92597065-d14f8880-f274-11ea-8774-7c8ce501fb5e.png)

Your mod seems to think it requires one of the addons. WTF?

**Comment by LUEZIS** [comment]
Moreover it requires not existing version of addon, there is only 1.4.1e version as most recent.

**Comment by ghost** [comment]
I'll have a 1.4.2 version of the thaumcraft add-on out very soon.  Hopefully today. Sorry for the inconvenience.

**Comment by ghost** [comment]
New Thaumcraft add-on 1.4.2 is now out
https://www.curseforge.com/minecraft/mc-mods/dttc
