### ISSUE TITLE
mod compatibility 

### ISSUE THREAD

**Issue by ImKROMKA** [ferreusveritas/Dynamic-Trees#445]
DynamicTrees mod is incompatible with
Pam's HarvestCraft, errors occur with trees, or rather, tree textures disappear, and trees from the Pam's HarvestCraft mod are not replaced and remain normal, as from Vanilla

**Comment by ghost** [comment]
I run Dynamic trees with Pam's harvestcraft and the Dynamic trees add-on for harvestcraft.  It works great with none of the problems you're mentioning.  Existing vanilla style trees that have already generated don't get replaced with Dynamic versions, that's not how it works.
