### ISSUE TITLE
Compiling failed due some import issue

### ISSUE THREAD

**Issue by fddn** [ferreusveritas/Dynamic-Trees#446]
**Describe the bug**
Compiling process fails due some import issue:
/path/to/DynamicTrees/build/sources/main/java/com/ferreusveritas/dynamictrees/compat/SereneSeasonsAdapter.java:14: error: package sereneseasons.config does not exist        
import sereneseasons.config.BiomeConfig;
                           ^
/path/to/DynamicTrees/build/sources/main/java/com/ferreusveritas/dynamictrees/compat/SereneSeasonsAdapter.java:15: error: package sereneseasons.config does not exist        
import sereneseasons.config.SeasonsConfig;
                           ^
/path/to/DynamicTrees/build/sources/main/java/com/ferreusveritas/dynamictrees/seasons/SeasonProviderSereneSeasons.java:4: error: package sereneseasons.api.season.Season does not exist
import sereneseasons.api.season.Season.SubSeason;
                                      ^
/path/to/DynamicTrees/build/sources/main/java/com/ferreusveritas/dynamictrees/seasons/SeasonProviderSereneSeasons.java:5: error: package sereneseasons.api.season does not exist
import sereneseasons.api.season.SeasonHelper;
                               ^
4 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.

**To Reproduce**
I just ran ./gradlew build under WSL (Ubuntu 18.04).
[gradle.log](https://github.com/ferreusveritas/DynamicTrees/files/5241200/gradle.log)

**Mods List**
Version of Forge 12.2-14.23.5.2768

**Comment by ghost** [comment]
The 1.12.2 maven for serene seasons either doesn't exist or was removed by the maintainer.  So just make a libs directory in the project root and drop in the serene season jar file from curseforge.

**Comment by fddn** [comment]
I'm new in this gradle/maven world, thanks for the tip. I'll try it.
