### ISSUE TITLE
Oak leaves don't drop apples if Apple trees are disabled

### ISSUE THREAD

**Issue by QuantumStatement** [ferreusveritas/Dynamic-Trees#447]
**Describe the bug**
Oak leaves don't drop apples if config parameter `enableAppleTrees` set to `false`.

**To Reproduce**
1. Set `enableAppleTrees` config parameter to `false`
2. Launch game and create new world
3. Chop down several oak trees

**Mods List**
Dynamic Trees 0.9.14
Smooth Font 2.1.2
Forge 1.12.2-14.23.5.2854

**Comment by ghost** [comment]
Do you also have worldgen disabled?

**Comment by QuantumStatement** [comment]
No, worldgen is enabled

**Comment by ghost** [comment]
You have to break the leaves blocks to get apples, like in Vanilla.  Have you tried that?

**Comment by QuantumStatement** [comment]
Absolutely forgot about that. Looks like it works now. Thank you!
