### ISSUE TITLE
Concurrent modification exception during multiple explosions:

### ISSUE THREAD

**Issue by ghost** [ferreusveritas/Dynamic-Trees#448]
**Describe the bug**
 Breaking dynamic trees and pushing tree branches around midair using multiple explosions at once causes crash if there is too many explosion rays being applied.

**To Reproduce**
Plant multiple (near hundreds) vanilla TNT blocks around a patch of dynamic trees and chain-detonate them.  Or download Spartan Weapons and throw multiple dynamite sticks.  Or download Cyclic and use Dynamite IV on the patch of trees.  Or download ICBM mod and ignite multiple explosive blocks.  these modded explosives take less amount of detonations to trigger. This bug is common but doesn't always occur; perform this action again and again until it eventually triggers.  will occur best with very large dynamic trees in bunches.

**Screenshots**
It closes the server before the client crashes, indicating your physics logic is faulting.

**Rendering Glitches**
Optifine is installed.  Required for Vivecraft compatibility of my modpack's development.  Rendering does not fault; physics logic is the issue here.

**Crashes**
forge version 14.23.5.2584 (latest and last)
1.12.2 Dynamic Trees version 0.9.14
1.12.2. Dynamic Trees Biomes o Plenty and Pam's Harvest craft are installed as well (path trace proves this is irrelevant.)

**Mods List**
WARNING: my modpack is extremely large, however you should be able to notice this crash is the fault of dynamic trees alone caused by vanilla explosion physics.

[crash-2020-09-17_13.54.47-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/5245791/crash-2020-09-17_13.54.47-server.txt)

**Comment by ghost** [comment]
I hope to see this fixed soon as Dynamic Trees has helped my modpack stay true to its cause.

**Comment by democat3457** [comment]
https://github.com/ferreusveritas/DynamicTrees/commit/273cb0f17ea92cea124ea810d9aa91566cce7156 this probably didn't actually fix the problem then, because either the set and/or the stream is not concurrent, rather than the map.

**Comment by ghost** [comment]
I think I need to redo the filter algorithm such that it doesn't redefine the entire map object on cleanup.
