### ISSUE TITLE
Optifine issues 

### ISSUE THREAD

**Issue by disastercube** [ferreusveritas/Dynamic-Trees#449]
**Minecraft 1.12.2**
--------------------
When using Optifine with Dynamic Trees an issue with leaves occurs. 
Savana leaves on mod changed trees seem to have the same/similar color of the forest ones (greener). 
The change doesn't really make the game any worse, actually to someone it might seem that there's more natural details, but it would be nice if all leaves could have the same biomes color.

**_Example of leaves on modded trees and natural generated RecurrentComplex trees:_**
![2020-09-21_18 38 32](https://user-images.githubusercontent.com/62697421/93797076-0deb8e80-fc3c-11ea-8325-2ecad2fe2ac4.png)

**Comment by ghost** [comment]
I use optifine and I don't have this problem.
![2020-09-22_09 31 56](https://user-images.githubusercontent.com/13294361/93888943-a0307880-fcb6-11ea-8620-93f81d7beee5.png)
Please reduce your mods to just Optifine and Dynamic Trees and create a test world.  If it does not occur with just those mods then do binary troubleshooting(add half of disabled mods at each testing cycle) with your mods.  If I can't reproduce this there is little chance it will ever be fixed.

**Comment by disastercube** [comment]
The real issue is a combination of **Optifine**, **DynamicTrees** and **Quark**.
-------------
Using both Optifine and DynamicTrees together is completely fine, but adding quark in the mix causes this effect.
When using Quark and Optifine alone the colors are fine as well, all though adding DynamicTrees brakes it.
Also, removing Optifine made the leaves and grass look all the same, but not to its original color, but the greenish one.

**_A world pregenerated with Quark and Optifine alone and adding Dynamic trees after:_**
_**- greener bottom grass block**_
**_- greener leaves_**
![2020-09-23_22 03 17](https://user-images.githubusercontent.com/62697421/94064122-788dfd00-fde9-11ea-9a1f-02a53c8d6045.png)

**_The same world but with Optifine removed  afterwards:_**
_**- everything with the same greener shade**_
![2020-09-23_22 15 25](https://user-images.githubusercontent.com/62697421/94064666-4f21a100-fdea-11ea-8007-a26015dff028.png)

**Comment by ghost** [comment]
**So it's _Closed_.**
