### ISSUE TITLE
[request] Config for Appletree leaves not dropping apples

### ISSUE THREAD

**Issue by DaedalusGame** [ferreusveritas/Dynamic-Trees#45]
I found in my testworld that apple tree leaves drop apples even if there's no visible apples grown on the tree, and I believe this to be an intentional change as all tree leaves appear to use special ids (aka they're not vanilla leaves). Thus I would like to request a config option that limits apple drops to only the visible apple growths that appear underneath the the leaves after some time. While it is a small balance concern to have lots of apples drop from leaves, I mostly would like this for the aesthetic/mechanic of having to harvest the physical apples to get apples instead of just chopping the tree down. Thanks in advance if you can make this happen.

**Comment by ghost** [comment]
I removed apple tree leaves dropping apples in the latest alpha releases.  What version are you running?

**Comment by DaedalusGame** [comment]
ah ok there's a latest alpha version I didn't see. I have tested this and apple trees no longer drop apples from leaves so this is resolved
