### ISSUE TITLE
What are the block´s IDs?

### ISSUE THREAD

**Issue by Tarnia919** [ferreusveritas/Dynamic-Trees#450]
I´ve been loking where the ID´s could be, but I don´t find anything in the Forge page or in these forums, so I´m asking here; because I´d like to fill a Worldpainter map with dynamic trees and, if I don´t have the ID´s, I´ll have to plant every single tree by hand.

**Comment by ghost** [comment]
You can get the block id by using the Minecraft F3 debug screen and looking at a block.  It's a string.
