### ISSUE TITLE
Crash when rendering leaves

### ISSUE THREAD

**Issue by Heli0n** [ferreusveritas/Dynamic-Trees#454]
Me and my friend were trying to play LAN and minecraft crashes when entering a world for this person, who is connecting to host (we tried creating new worlds and it crashes every time, but host is ok)
We have many mods so i'm interested in the main reason of a crash...
There is a piece of a crashlog:

> java.lang.NullPointerException: Tesselating block model
> 	at net.minecraft.world.biome.BiomeColorHelper.func_180285_a(SourceFile:36)
> 	at net.minecraft.world.biome.BiomeColorHelper.func_180287_b(SourceFile:51)
> 	at asmodeuscore.core.handler.ColorBlockHandler.lambda$registerBlockColourHandlers$1(ColorBlockHandler.java:100)
> 	at asmodeuscore.core.handler.ColorBlockHandler$$Lambda$2034/559688256.func_186720_a(Unknown Source)
> 	at net.minecraft.client.renderer.color.BlockColors.func_186724_a(BlockColors.java:185)
> 	at com.ferreusveritas.dynamictrees.blocks.LeavesProperties.foliageColorMultiplier(LeavesProperties.java:149)
> 	at com.ferreusveritas.dynamictrees.blocks.LeavesPropertiesJson.lambda$resolveClient$3(LeavesPropertiesJson.java:319)
> 	at com.ferreusveritas.dynamictrees.blocks.LeavesPropertiesJson$$Lambda$2635/1855543817.func_186720_a(Unknown Source)
> 	at com.ferreusveritas.dynamictrees.blocks.LeavesPropertiesJson.foliageColorMultiplier(LeavesPropertiesJson.java:281)
> 	at com.ferreusveritas.dynamictrees.proxy.ClientProxy.lambda$registerColorHandlers$7(ClientProxy.java:229)
> 	at com.ferreusveritas.dynamictrees.proxy.ClientProxy$$Lambda$2306/920897996.func_186720_a(Unknown Source)
> 	at net.minecraft.client.renderer.color.BlockColors.func_186724_a(BlockColors.java:185)
> 	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:228)
> 	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:116)
> 	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:85)
> 	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:79)
> 	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:58)
> 	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
> 	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:82)
> 	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:328)
> 	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
> 	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at net.minecraft.world.biome.BiomeColorHelper.func_180285_a(SourceFile:36)
> 	at net.minecraft.world.biome.BiomeColorHelper.func_180287_b(SourceFile:51)
> 	at asmodeuscore.core.handler.ColorBlockHandler.lambda$registerBlockColourHandlers$1(ColorBlockHandler.java:100)
> 	at asmodeuscore.core.handler.ColorBlockHandler$$Lambda$2034/559688256.func_186720_a(Unknown Source)
> 	at net.minecraft.client.renderer.color.BlockColors.func_186724_a(BlockColors.java:185)
> 	at com.ferreusveritas.dynamictrees.blocks.LeavesProperties.foliageColorMultiplier(LeavesProperties.java:149)
> 	at com.ferreusveritas.dynamictrees.blocks.LeavesPropertiesJson.lambda$resolveClient$3(LeavesPropertiesJson.java:319)
> 	at com.ferreusveritas.dynamictrees.blocks.LeavesPropertiesJson$$Lambda$2635/1855543817.func_186720_a(Unknown Source)
> 	at com.ferreusveritas.dynamictrees.blocks.LeavesPropertiesJson.foliageColorMultiplier(LeavesPropertiesJson.java:281)
> 	at com.ferreusveritas.dynamictrees.proxy.ClientProxy.lambda$registerColorHandlers$7(ClientProxy.java:229)
> 	at com.ferreusveritas.dynamictrees.proxy.ClientProxy$$Lambda$2306/920897996.func_186720_a(Unknown Source)
> 	at net.minecraft.client.renderer.color.BlockColors.func_186724_a(BlockColors.java:185)
> 	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:228)
> 	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:116)
> 	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:85)
> 
> -- Block model being tesselated --
> Details:
> 	Block: dynamictrees:leaves1[decayable=true,hydro=2,tree=0]
> 	Block location: World: (3829,69,-4768), Chunk: (at 5,4,0 in 239,-298; contains blocks 3824,0,-4768 to 3839,255,-4753), Region: (7,-10; contains chunks 224,-320 to 255,-289, blocks 3584,0,-5120 to 4095,255,-4609)
> 	Using AO: true
> Stacktrace:
> 	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:79)
> 	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:58)
> 
> -- Block being tesselated --
> Details:
> 	Block type: ID #1204 (tile.dynamictrees:leaves1 // com.ferreusveritas.dynamictrees.blocks.BlockDynamicLeaves // dynamictrees:leaves1)
> 	Block data value: 1 / 0x1 / 0b0001
> 	Block location: World: (3829,69,-4768), Chunk: (at 5,4,0 in 239,-298; contains blocks 3824,0,-4768 to 3839,255,-4753), Region: (7,-10; contains chunks 224,-320 to 255,-289, blocks 3584,0,-5120 to 4095,255,-4609)
> Stacktrace:
> 	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
> 	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:82)

**Comment by ghost** [comment]
Looks like the crash is caused by asmodeuscore.  Their mod is closed source so I can't evaluate the reason.

**Comment by Heli0n** [comment]
ok, thanks
