### ISSUE TITLE
Dynamic Trees changes how leaf drops work

### ISSUE THREAD

**Issue by Jomeaga** [ferreusveritas/Dynamic-Trees#455]
**Describe the bug**
Pyrotech adds stick drops to leaves as it disables crafting sticks until later. However it seems that Dynamic Trees makes changes to leaf drops and *mostly* blocks them from dropping.

**To Reproduce**
Pyrotech ONLY - break leaves, almost every other drops a stick.
Pyrotech & Dynamic Trees - break leaves, maybe 1 or 2 sticks from a whole tree.

**Mods List**
forge-14.23.5.2854
Dynamic Trees 0.9.19
Pyrotech  1.4.34

**Comment by Harleyoc1** [comment]
Fixed in recent commit (see PR above). Will be included in next version.
