### ISSUE TITLE
Crash with Underground Biomes 

### ISSUE THREAD

**Issue by PresquePlayed** [ferreusveritas/Dynamic-Trees#458]
**Describe the bug**
The Game crashes on start up due to soil registration with ubc

**To Reproduce**
Install latest dynamic trees version and latest UBC version
curse page: https://www.curseforge.com/minecraft/mc-mods/underground-biomes

**Comment by Harleyoc1** [comment]
This was fixed in [this commit](https://github.com/ferreusveritas/DynamicTrees/commit/64f6df98e00e0ac86be12975be3ead4d3b40faab) and will be included in the next version.
