### ISSUE TITLE
Bushy leaves

### ISSUE THREAD

**Issue by KennyBooy2** [ferreusveritas/Dynamic-Trees#465]
In every mod review for dynamic trees i always see the leaf blocks have leaves on them to make it bushy but i just cant seem to get them to work no matter what. 

Did they use to be a feature but got removed? 

Is it to do with optifine? 

Would really like to fix this cheers.

**Comment by Harleyoc1** [comment]
That’s added by [this mod](https://www.curseforge.com/minecraft/mc-mods/better-foliage).
