### ISSUE TITLE
[Compability Request] GregTech Community Edition Rubber Tree

### ISSUE THREAD

**Issue by HonzaVinCZ** [ferreusveritas/Dynamic-Trees#467]
I'd like to ask you for compability addon for GTCE rubber tree. Unfortunately I don't have any experience in mod making so I have no idea how to make that addon. Please let me know if it could be done, added to to-do or not at all, thank you!

**Comment by Harleyoc1** [comment]
Please see #443 for add-on requests. These shouldn’t be opened here.
