### ISSUE TITLE
[Bug Report] Dyn Trees missing some trees compability

### ISSUE THREAD

**Issue by HonzaVinCZ** [ferreusveritas/Dynamic-Trees#468]
Some BBOP biomes seem like they don't support Dynamic Trees. Happens most noticable in Savanna with acacia trees and with spruce trees overally. All tree gen related mods I use are listed below:

Biome_Bundle_O_Plenty-1.12.2_v1.0
BiomesOPlenty-1.12.2-7.0.1.2444-universal
DynamicTrees-1.12.2-0.9.21
DynamicTreesBOP-1.12.2-1.4.4
DynamicTreesPHC-1.12.2-2.0.5
OpenTerrainGenerator-1.12.2-v9.0
Pam's+HarvestCraft+1.12.2zg

Some screenshots:
![2020-11-23_16 18 00](https://user-images.githubusercontent.com/29098779/99980702-d5d20a80-2da8-11eb-84e4-85d8ae8e54ca.png)
![2020-11-23_16 18 13](https://user-images.githubusercontent.com/29098779/99980711-d8346480-2da8-11eb-8244-ac10c735675d.png)
![2020-11-23_16 20 31](https://user-images.githubusercontent.com/29098779/99980720-da96be80-2da8-11eb-8542-06df75e43e69.png)
![2020-11-23_16 21 36](https://user-images.githubusercontent.com/29098779/99980732-dc608200-2da8-11eb-981f-1e13b40eb618.png)

**Comment by ghost** [comment]
Are you running recurrent complex?  Please list all mods being used as requested.

**Comment by HonzaVinCZ** [comment]
> Are you running recurrent complex? Please list all mods being used as requested.

No, I don't use Recurrent Complex because the same thing does the OTG. I will provide my mod list here later today, I'm not at home now. Only tree I know that isn't supported in my modpack is GTCE Rubber Tree but that's not the problem here. 

The problem I think about are .bo3 objects in OTG which can place already defined trees into the world like schematic. But then I don't understand why it doesn't work only with certain trees.

**Comment by HonzaVinCZ** [comment]
So here is my mod list. Every single mod is up to date checked about five days ago.

AppleSkin-mc1.12-1.0.14
appliedenergistics2-rv6-stable-7
base-1.12.2-3.13.0
bettercaves-1.12.2-2.0.4
Biome_Bundle_O_Plenty-1.12.2_v1.0
BiomesOPlenty-1.12.2-7.0.1.2444-universal
bookworm-1.12.2-2.5.0
CEU-1.12.2-1.0.4.3
CodeChickenLib-1.12.2-3.2.3.358-universal
ContentTweaker-1.12.2-4.9.1
coroutil-1.12.1-1.2.37
CraftTweaker2-1.12-4.1.20.586
CTM-MC1.12.2-1.0.2.31
CustomNPCs_1.12.2-(05Jul20)
DynamicTrees-1.12.2-0.9.21
DynamicTreesBOP-1.12.2-1.4.4
DynamicTreesPHC-1.12.2-2.0.5
ExtraCells-1.12.2-2.6.5
Forgelin-1.8.4
ForgeMultipart-1.12.2-2.6.2.83-universal
furniture-6.3.1-1.12.2
gregtech-1.12.2-1.10.4.574
Hwyla-1.8.26-B41_1.12.2
ICBM-classic-1.12.2-4.0.1b75
ido-1.12.2-1.1.0
inventorysorter-1.12.2-1.13.3+57
ironchest-1.12.2-7.0.72.847
jei_1.12.2-4.16.1.301
journeymap-1.12.2-5.7.1
LagGoggles-1.12.2-5.8-132
LootTweaker-0.2.0+MC1.12.2
malisisadvert-1.12.2-6.1.0-sources
malisiscore-1.12.2-6.5.1
malisisdoors-1.12.2-7.3.0
Mekanism-1.12.2-9.8.3.390
MekanismGenerators-1.12.2-9.8.3.390
mw_2.0-0.4.4.6_mc1.12.2
NaturalFauna+Mod-1.12.2-1.5.1
NPUtils-1.12.2-1.3.21
OpenTerrainGenerator-1.12.2-v9.0
OTG-Core
Pam's+HarvestCraft+1.12.2zg
SoundFilters-0.12.1_for_1.12
TickCentral-2.6
weather2-1.12.1-2.6.12
WorldEdit-CUI-FE3-1.12.2-3.0.8
worldedit-forge-mc1.12.2-6.1.10-dist
zawa-1.12.2-2.0.0

**Comment by Harleyoc1** [comment]
Does it happen when you generate a regular world (as in without the BBOP preset)?

**Comment by HonzaVinCZ** [comment]
> Does it happen when you generate a regular world (as in without the BBOP preset)?

No, there is problem only with BiomeBundle. It have been a while and I realised, BB uses custom trees that are placed into the world like WorldEdit schematic. That is propably the reason why DynTrees can't do anything with them.

**Comment by Harleyoc1** [comment]
Sorry. I forgot to reply to this before. I think you should bring this up with the developers of BBOP instead since this isn't really directly related to us. Please make sure it happens without any other mods present before though since one of the other mods you're using could be causing it.
