### ISSUE TITLE
Bewitchment Elder Tree Crash

### ISSUE THREAD

**Issue by GameDungeon** [ferreusveritas/Dynamic-Trees#470]
**Describe the bug**
If you plant and break a bewitchment elder tree sapling the game crashes. (tested on a server if that has anything to do with it)

**Crashes**
https://hastebin.com/raw/mefaqohedi

**Comment by Harleyoc1** [comment]
Why have you opened this here? There is no evidence it’s being caused by DT.

**Comment by GameDungeon** [comment]
I could be wrong, but I thought it is an issue here. I've not looked into it too hard. It might be an issue with Bewitchments Dynamic trees compat. I don't see why bewitchment would do anything when I destroy a dynamic tree elder tree sapling on a server (because that's the only time I know of when it crashes)

**Comment by Harleyoc1** [comment]
In that case please open this issue on [Bewitchment’s issue tracker](https://github.com/Um-Mitternacht/Bewitchment/issues). Please don’t put bugs with addons on this issue tracker unless you have reason to believe they are specifically caused by something base DT is doing.
