### ISSUE TITLE
Surface roots

### ISSUE THREAD

**Issue by Tavarnarmo** [ferreusveritas/Dynamic-Trees#475]
I have question/issue with mod version 1.12.2-0.9.21 and surface roots - they don't grow with any of dynamic tree species in terrafirmacraft. I used potions from dynamic trees to speed up growth and changed tick speed - could that cause lack of surface roots or was there some change which removed them altogether? Also - can you tell me which tree species can have them, if some species are supposed to have them does this mean that all trees of this species will have them or only some and if species are from another mod (like terrafirmacraft) can they also have them?

**Comment by Harleyoc1** [comment]
Surface roots depend on the species specifically, for example (if I’m remembering right) the mega jungle species has surface roots whereas the common jungle species doesn’t. I don’t think using the speed potion should prevent them from growing. 

I don’t know whether or not the Terrafirmcraft add-on supports them on any trees or if they do on which, but please open any add-on related issues/suggestions on their respective GitHub pages ([here](https://github.com/Gaelmare/dynamictreestfc) is the Terrafirmcraft one).
