### ISSUE TITLE
Critical Things For The Mod

### ISSUE THREAD

**Issue by Judge-GitHub** [ferreusveritas/Dynamic-Trees#476]
You may hate me for doing this or call it abuse, however the mod is still in 1.12.2 (sadly). I know,I know 1.13 changed so many things, but this mod is arguably on of the best mods ever and it is so sad seeing it stay at 1.12.2. You should consider porting it to fabric (because that is the future of modding, forge can't keep up) and update it to the newest version. Again, I know I will be called out for abuse or something, but I just had to say it!. I hope you see this and reconsider your choices! :(

**Comment by Barerock** [comment]
Reconsider his choices? This entire post is derogatory in nature, respect whatever Ferreusveritas wants to do man, geez. Your comment is unnecessary, rude, and incredibly short sighted.

**Comment by democat3457** [comment]
This is like a passive-aggressive post - telling the modder to do something while also trying to express your negative emotions in a restrained manner.

**Comment by Judge-GitHub** [comment]
Lol Imagineeee!! How old are you? 13? If you are offended by my post, bye bye, none mentioned you. How is my post offending.I am literally saying it is the best mod ever. I know the developer doesn't want to update it and in behalf of all the people that want it updated, I tried to tell him to think about it again, however people like you get in the way thinking they do something lol :). Lets see you use better words this time to show us that you are an educated and good person ;). Thank you.
