### ISSUE TITLE
Acorns etc not falling when harvesting trees 1.12.2

### ISSUE THREAD

**Issue by victre151** [ferreusveritas/Dynamic-Trees#477]
Acorns etc used to drop when harvesting trees they just randomly stop doing so today

**Comment by kierajreed** [comment]
What were you doing when this happened? Which mods were you running? We can't do anything about this without additional info.

**Comment by victre151** [comment]
I use a large modpack that I created and was hoping that somone else had
this issue so I wouldn't have to list them all out and I was just chopping
down a ton of trees for building

**Comment by RiverC** [comment]
When we updated to the latest version, we also began to have to this problem. It's not strictly that seeds do not drop, it's that they drop _super rarely_ -- making nearly all trees un-farmable.

For reference, the version we used before we updated (where seed drops were mostly normal) was 0.9.8. I believe the current version is 0.9.21. 

I also did some experiments with seed auto-drop rates and auto-plant in forests, and no tree spread occurs at all. I don't think it is that tree spread doesn't work, it's that seeds don't drop automatically either.

**Comment by victre151** [comment]
Thank you that's most likely the issue

**Comment by RiverC** [comment]
I did a check by keeping all mods the same (except Pam's Dynamic Trees which I had to disable since it is dependent) and I got normal drops until 0.9.11, after which they seem to have disappeared. I hope that helps isolate the change that created the issue.

**Comment by Harleyoc1** [comment]
Do you both have serene seasons installed? A lot of work was done for season compatibility in 0.9.11.

**Comment by victre151** [comment]
I had serene seasons

**Comment by Harleyoc1** [comment]
It may be it’s to do with this - I believe drops are altered depending on the season. I don’t know the details of how it works but I’ll take a look into it.

**Comment by victre151** [comment]
Okay thank you

**Comment by Harleyoc1** [comment]
I believe that rather than an issue this is a misunderstanding of how the season compatibility works. For certain trees in certain biomes the drop rates will be very low for some of the year and the spread rates almost nothing. 

If you want more explanation to how the rates are calculated the numbers can be found [here](https://docs.google.com/spreadsheets/d/17RDJ3T5ZPWuHy1_XVmu3MB-J1JHbGG-QjAuuRkEn2vI/edit#gid=0) as well as a little explanation of the temperate drop chances.

**Comment by RiverC** [comment]
Is there any way to disable this function? I can understand not dropping seeds in the winter, but these values are opaque to the player and looking at the chart it _seems_ like seeds should drop at normal rates during the summer, and early summer was the point at which I was always testing, so I think either I am misunderstanding that graph or there still is something the matter.

I will downgrade our pack to 0.9.9 until I can get some kind of better feedback on this feature.

EDIT: I see I was looking at the graph wrong. Our seasons are pretty long (30 day months) so this isn't a good feature for us. I'll stick with 0.9.9 until there's a way to alter the behavior/disable this function.

**Comment by Harleyoc1** [comment]
There’s not currently a way to disable this, but I may make fully configurable at some point. 

Perhaps as a temporary remedy we could add some config options to disable certain integrations altogether.

**Comment by RiverC** [comment]
Yes, I think the integration right now feels a bit rough and to be honest I had no knowledge that it existed. (I'm sure it was in one of the changelogs, though, curseforge only lets me see the latest changelog so when I updated the pack I didn't see any of that.)

For my part, it introduces another challenge for players that I wasn't expecting and requires re-analyzing and re-balancing the pack. I really thought it was broken! 😆
