### ISSUE TITLE
Dynamic Trees not animated by Shaders

### ISSUE THREAD

**Issue by bl0ke** [ferreusveritas/Dynamic-Trees#48]
I have Millenaire, Dynamic Trees and Shaders installed. Vanilla trees created by the Millenaire villagers are animated by the shaders - that is, the leaf blocks sway in a 'breeze' - but those of DT are not.

**Comment by ghost** [comment]
May I have a link to the "Shaders" mod you are referring to?

**Comment by bl0ke** [comment]
I updated to the latest version, just to be safe:

Sildurs Vibrant Shaders v1.17 Extreme
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1291396-1-6-4-1-12-2-sildurs-shaders-pc-mac-intel

**Comment by ghost** [comment]
What MC version are you using?

**Comment by cadaverous-eris** [comment]
I can confirm this, although I'm not sure why the leaves aren't animated since the animations seem to work on other modded leaves.
Edit: Actually, other modded leaves don't seem to wave after all. Seems like an issue with the shaderpack.
Edit 2: Updating Dynamic Trees has solved the issue for me. The leaves now wave properly.

**Comment by bl0ke** [comment]
Minecraft 1.12.2
Millenaire 6.2.0 Beta 18
Optifine a 12.2 HD U D1

**Comment by cadaverous-eris** [comment]
What version of Dynamic Trees are you using? I was able to solve the issue by updating to version 0.7.3c.
Edit: Updating the mod didn't solve the issue, installing Better Foliage did.

**Comment by cadaverous-eris** [comment]
It seems shaders just don't recognize modded leaves at all, but Better Foliage will fix this. If you don't like Better Foliage, you can install it and then disable the mod using it's in-game options menu and it will still make modded leaves wave.

**Comment by bl0ke** [comment]
Weird, my DT mod file is DynamicTrees-1.12.2-0.7.4.jar.

**Comment by ghost** [comment]
Did the better foliage suggestion resolve your problem?

**Comment by bl0ke** [comment]
Confirmed: BetterFoliage-MC1.12-2.1.10 fixes the issue, thanks.

**Comment by ghost** [comment]
The conclusion here is that Better Foliage adds code to allow modded leaves to sway properly with optifine.  Thanks OctarineNoise!
