### ISSUE TITLE
[Enhancement] Tree tapping like in PHC-addon's maple trees as general, configurable feature ?

### ISSUE THREAD

**Issue by barttraeger** [ferreusveritas/Dynamic-Trees#481]
Love your mod, its awesome, thanks so much for all your work!

I was wondering if some sort of tree-tapping mechanic like in the PHC-addon could be added.
Or simply the possibility to attach blocks like torches to the side of thick enough branches.

Recently I experimented with the mod "Maple Syrup" which adds a treetap attachable to blocks with configurable fluids pouring out over time and really liked the mechanic and possibilities for rubber extraction from jungle trees or pine tar, whatever.
It just has this Stardew Valley-vibe about it that I really like.
I tried to get the mod to work with Dynamic Trees, but unfortunately the tap cannot be attached to any center branches,
regardless of its thickness / metadata of the block.
I guess it could be because of the block property not beeing a "full block" or something, 
but I'm no coder and can only understand so much from browsing the code.

Anyway, with the PHC-addon you pulled this mechanic off quite nicely,
so I was wondering if you could think of a method to get this mod to work
or maybe even implement tree-tapping as a general feature.
Thanks for any input!

**Comment by barttraeger** [comment]
Oh, saw the pinned issue just now, should I better move this to supermassimo/DynamicTrees-ExC#41 ?
Sorry!

**Comment by Harleyoc1** [comment]
Yes, please open this as a new issue in  [supermassimo/DynamicTrees-ExC](https://github.com/supermassimo/DynamicTrees-ExC/issues).
