### ISSUE TITLE
Leaves Generate in Places Occupied by Entities

### ISSUE THREAD

**Issue by TheTedder** [ferreusveritas/Dynamic-Trees#487]
**Description of the bug**
Leaves can generate where the player is standing, causing the player to be inside a leaf block.

**To Reproduce**
Climb on top of a tree and stand directly over the top of the trunk. Break leaf blocks underneath you until you're standing direcly on the trunk. Leaves will eventually generate where you are standing.

**Screenshots**
![image](https://user-images.githubusercontent.com/25165500/107179615-f15eb180-69a4-11eb-874c-6a046303dd66.png)

**Mods List**
![image](https://user-images.githubusercontent.com/25165500/107179769-5914fc80-69a5-11eb-90f5-f5e0b58cbd65.png)

**Comment by supermassimo** [comment]
What would be the issue with this?

**Comment by Harleyoc1** [comment]
As said above we don't really see this as an issue. If you really want we could add a config option but I don't think it's worth it. I'll close for now but feel free to re-open if you are passionate about a config option.
