### ISSUE TITLE
Where can I find the default config file?

### ISSUE THREAD

**Issue by relsqui** [ferreusveritas/Dynamic-Trees#489]
I've installed dynamic trees through a custom modpack, testing it both locally and on a server, and the config file for it generated empty in both places. (I didn't actually know there were configuration options until I saw #382, but the formatting there means I can't really copy/paste from it.) Is there somewhere I can find a clean copy of the default config so I can edit it? (I just need to turn off the slow fall, makes me queasy!) Thanks.

**Comment by relsqui** [comment]
Aha, disregard -- I was looking in the `config/dynamictrees/` directory but I see now there are also loose config files in the parent directory.

**Comment by TeiBri** [comment]
PLEASE! Where are you finf a congfig file?? Where is parent directory!!?? I dont understand sorry.. D: Please help! Im using 1.16.5 dynamic trees.
