### ISSUE TITLE
Matthock Integration Tinkers Construct

### ISSUE THREAD

**Issue by murban-git** [ferreusveritas/Dynamic-Trees#490]
**Describe the bug**
Mattocks from Tinkers Construct do not take Damage acording to "I:axeDamageMode=2"

**To Reproduce**
1. Install Tinkers Contruct & Dynamic Tree
2. Get a Mathock
3. Chop a tree

**Additional Info**
Hatches, Lumberaxe are working fine

**Forge Version**
1.12.2-14.23.5.2855

**Comment by Harleyoc1** [comment]
Do you mean it works on the other axe damage modes or is that just the only one you’ve tested it on?

**Comment by murban-git** [comment]
I tested:
hatch, lumber axe and mattock (All Iron from JEI)

hatch was ok (damage was calculated Properly)
lumber axe was ok (damage was calculated Properly)
mattock did only take 1 dmg.
I had the axe dmg mode set to 2 in the config file. ( should get dmg according to droped wood)

I realized that Problem in my modpack with an mattock out of wood and stone.
I tested it with only Tinkers Construct and dynamic Tree's to remove other possible errors from other mods.

(I had JEI and Optifine included, should not do anything to it)

**Comment by Harleyoc1** [comment]
For whatever reason Tinker’s mattock doesn’t have the tool class `axe` so we weren’t applying the damage properly. They probably have a good reason for not setting this, and it’s simple enough for us to just add a check for `mattock` anyway.

**Comment by murban-git** [comment]
Dose this mean you are fixing it?
I ask because Bug is closed and I don't see a PR for this ticket?

**Comment by Harleyoc1** [comment]
I already fixed it in a commit to 1.12, it will be included in the next update.
