### ISSUE TITLE
Could not resolve all files for configuration ':compileClasspath'.

### ISSUE THREAD

**Issue by Eleshz** [ferreusveritas/Dynamic-Trees#495]
I am trying to follow the compile instructions but when I run 'gradle build'
[Tree mod.txt](https://github.com/ferreusveritas/DynamicTrees/files/6013786/Tree.mod.txt)
 it gets me:  Could not resolve net.minecraftforge:forge:1.16.5-36.0.42_mapped_snapshot_20201028-1.16.3.
  Required by:
      project :
   > Could not resolve net.minecraftforge:forge:1.16.5-36.0.42_mapped_snapshot_20201028-1.16.3.
      > Could not get resource 'https://maven.tehnut.info/net/minecraftforge/forge/1.16.5-36.0.42_mapped_snapshot_20201028-1.16.3/forge-1.16.5-36.0.42_mapped_snapshot_20201028-1.16.3.pom'.
         > Could not GET 'https://maven.tehnut.info/net/minecraftforge/forge/1.16.5-36.0.42_mapped_snapshot_20201028-1.16.3/forge-1.16.5-36.0.42_mapped_snapshot_20201028-1.16.3.pom'. Received status code 403 from server: Forbidden
??????????????????????????????????????????????????????? What do I do??

**Comment by Harleyoc1** [comment]
The error message seems to suggest you don’t have JDK installed: `java.lang.IllegalStateException: Could not find tools.jar. Please check that C:\Program Files\Java\jre1.8.0_281 contains a valid JDK installation.`

**Comment by Harleyoc1** [comment]
I’m going to close this because it’s not really an issue on our end. If you need further help then do ask but it seems like the only problem is you don’t have JDK installed.

**Comment by Eleshz** [comment]
Thank you.
