### ISSUE TITLE
Mod causes server crash, creating TickNextTick issue.

### ISSUE THREAD

**Issue by m4tustechna** [ferreusveritas/Dynamic-Trees#496]
At some points, when rendering new chunks. Server crashes, giving out java.lang.IllegalStateException: TickNextTick list out of synch

I'm using latest version of dynamictrees. Same with Forge. 2855

here's crash report from server. It just disconnects from normal Minecraft Client
[crash-2021-02-23_11.58.55-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/6028486/crash-2021-02-23_11.58.55-server.txt)

**Comment by Harleyoc1** [comment]
I see you’re running other mods, why are you reporting this here? I see no proof it’s being caused by dynamic trees...

**Comment by HariboTer** [comment]
ThutCore is notorious for causing this kind of crash in 1.12.2. It is most likely the cause of the problem.

**Comment by Harleyoc1** [comment]
Thanks for mentioning. This shouldn’t have been opened here anyway since there’s no mention of DT in the stack trace.
