### ISSUE TITLE
[1.16.5] Beta server crash w/ forge 36.0.22

### ISSUE THREAD

**Issue by MrKashew** [ferreusveritas/Dynamic-Trees#498]
crashes with latest beta release
https://gist.github.com/MrKashew/dc92252f7863e9a00a0515562701a308
https://gist.github.com/MrKashew/0877e4f5a2df0588824381115eaafeba

**Comment by Harleyoc1** [comment]
I don't see why these methods/classes don't exist for you. Despite the fact that they're not classes added by Forge it would be worth trying to update Forge to the latest version.

**Comment by darvld** [comment]
I know this isn't the proper place to ask, but I couldn't find anywhere else to do it: How can I use the 1.16 version of this mod? Every download link I've found on the Internet so far is for the 1.12 version. I am unable to compile from source, so is there a way to do it without having to download the source code and compiling?

**Comment by Harleyoc1** [comment]
You should be able to compile from source via the instructions in the readme but we also put download links to the beta in the discord, though we also stress that it should be used for testing only because it's unfinished and unstable.

**Comment by MrKashew** [comment]
updated to forge 36.0.42, here is the new server crash
https://gist.github.com/MrKashew/0b97463937572951977d9a2010b613ef

**Comment by Harleyoc1** [comment]
Ah are you running on a dedicated server? Literally just noticed that class is client-side only, will be a simple fix. 

By the way for future you should state if you're running on a dedicated server in the issue description.

**Comment by Harleyoc1** [comment]
Forgot to say that this has been fixed on the custom tree data branch.

**Comment by MrKashew** [comment]
@Harleyoc1 is the custom tree data branch in a stable playable state (should I compile and test on my server or wait for the changes to be checked out to main 1.16 branch)

**Comment by Harleyoc1** [comment]
I wouldn't call it stable but neither is the main 1.16 branch. Playable? Probably. It still needs a lot of work and testing so someone using it might actually help, and since you're already prepared to test the 1.16 branch I'd say you'd be fine running this. Also note that you'd need to build the branch on DT plus too if you’re using that, as the old one won't work.

**Comment by MrKashew** [comment]
@Harleyoc1 havent been able to build on that branch, is this a me problem / am i doing it wrong? tried building custom tree data branch
