### ISSUE TITLE
When are you going to add support for newer versions?

### ISSUE THREAD

**Issue by PessiPanto** [ferreusveritas/Dynamic-Trees#499]
I would absolutely LOVE it if you could make this compatible with the latest version. This is an absolutely essential mod!! Everyone’s migrating to the newest version, and while it itself adds a lot of good stuff, there are so many other amazing new mods I consider essential as well that are only available on these versions now, with the developers saying that they don’t ever plan on backporting, or that it’s impossible to do. So do you have plans of eventually porting this mod to the newest version?

**Comment by Harleyoc1** [comment]
All it takes is looking in the branches of the project or even the project board. Do not open issues asking for newer versions, especially when they're already being worked on.
