### ISSUE TITLE
Cascading chunk loading (lag)

### ISSUE THREAD

**Issue by redxef** [ferreusveritas/Dynamic-Trees#50]
It seems like the mod causes an extreme amount of chunks being loaded in bigger forests.
Here is a warning message from my game log (These messages keep popping up when the server can't keep up.):

    [03:04:21] [Server thread/WARN] [FML]: Dynamic Trees loaded a new chunk (11, -39  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

I think the warning from forge says more or less everything there is to say.

**Comment by ghost** [comment]
I'll work on a fix for this during the next dev cycle.  It's a pretty harmless error since the cases when this occurs is infrequent and doesn't really cause true cascading chunk loading.

**Comment by redxef** [comment]
Then I've hit this case in my first world using this mod. Bad luck indeed (Took longer than 20 minutes to load, at which point I decided to stop the server).

Thanks for the reply and awesome mod!

**Comment by ghost** [comment]
I've made some bug fixes to my SimpleVoxelMap class that seem to have fixed this..  I've been flying through the world for nearly half an hour and I have not seen the lag warning.  I'm calling it fixed in dev.
