### ISSUE TITLE
1.12.2 trees do not drop logs

### ISSUE THREAD

**Issue by SuzuChen** [ferreusveritas/Dynamic-Trees#500]
copping down trees drop only seeds, and no logs or even sticks at all. Dunno how to fix it or what causes a problem... my mod pack is huge, but maybe anyone knows what mod can be an issue? or maybe I changed something in the config file so it broke down?
<img width="1005" alt="Снимок экрана 2021-03-09 в 02 05 02" src="https://user-images.githubusercontent.com/80288152/110393594-deaacb80-807b-11eb-9bc4-8fdeb27abf62.png">
<img width="999" alt="Снимок экрана 2021-03-09 в 02 05 31" src="https://user-images.githubusercontent.com/80288152/110393627-f1250500-807b-11eb-8353-8689f1225694.png">
<img width="998" alt="Снимок экрана 2021-03-09 в 02 05 58" src="https://user-images.githubusercontent.com/80288152/110393656-ff732100-807b-11eb-8581-21c921483724.png">
<img width="996" alt="Снимок экрана 2021-03-09 в 02 06 22" src="https://user-images.githubusercontent.com/80288152/110393683-0d28a680-807c-11eb-8da1-36d3bf09668e.png">
<img width="997" alt="Снимок экрана 2021-03-09 в 02 06 37" src="https://user-images.githubusercontent.com/80288152/110393716-16197800-807c-11eb-91ba-20f34e22be7b.png">
<img width="993" alt="Снимок экрана 2021-03-09 в 02 07 04" src="https://user-images.githubusercontent.com/80288152/110393755-26315780-807c-11eb-9ffe-2c19018192a3.png">
<img width="997" alt="Снимок экрана 2021-03-09 в 02 07 22" src="https://user-images.githubusercontent.com/80288152/110393776-30535600-807c-11eb-9e4c-ecfdd1212cfd.png">

**Comment by SuzuChen** [comment]
help will be super helpful! I will be in debt

**Comment by Harleyoc1** [comment]
Could you send your config file since you seem to suggest you have changed it? There is a harvest multiplier so the only thing I can think of that might be causing this (if it being caused by the config) is that you've changed that to 0 or simply set it too low.

**Comment by SuzuChen** [comment]
Configuration file

client {
    # Rings of thick trees are rendered using a texture created with an expanded tangram construction technique. Otherwise the ring texture is simply stretched [default: true]
    B:fancyThickRings=true
}


debug {
    # Enable to mark tree spawn locations with wool circles. [default: false]
    B:worldGenDebug=false
}


integration {
    # If enabled, fruit production rates will be multiplied based on the current season (requires serene seasons). [default: true]
    B:enableSeasonalFruitProductionFactor=true

    # If enabled, growth rates will be multiplied based on the current season (requires serene seasons). [default: true]
    B:enableSeasonalGrowthFactor=true

    # If enabled, seed drop rates will be multiplied based on the current season (requires serene seasons). [default: true]
    B:enableSeasonalSeedDropFactor=true
}


interaction {
    # Modes: 0=Standard 1 Damage, 1=By Branch/Trunk Thickness, 2=By Tree Volume [range: 0 ~ 2, default: 1]
    I:axeDamageMode=0

    # If enabled players receive reduced fall damage on leaves at the expense of the block(s) destruction [default: true]
    B:canopyCrash=true

    # If enabled the Dirt Bucket will place a dirt block on right-click [default: true]
    B:dirtBucketPlacesDirt=true

    # If enabled then an alternate(non-vanilla) snow layer block will be used on top of leaves [default: false]
    B:enableAltLeavesSnow=false

    # If enabled then thinner branches can be climbed [default: true]
    B:enableBranchClimbling=true

    # If enabled then trees will harm living entities when falling [default: true]
    B:enableFallingTreeDamage=true

    # If enabled then trees will fall over when harvested [default: true]
    B:enableFallingTrees=true

    # Multiplier for damage incurred by a falling tree [range: 0.0 ~ 100.0, default: 1.0]
    S:fallingTreeDamageMultiplier=1.0

    # If enabled all leaves will be passable [default: false]
    B:isLeavesPassable=false

    # If enabled player movement on leaves will not be enhanced [default: false]
    B:vanillaLeavesCollision=false
}


seeds {
    # The rate at which seeds voluntarily drop from branches [range: 0.0 ~ 1.0, default: 0.0]
    S:dropRate=0.0

    # The minimum forestness that non-forest-like biomes can have. 0 = is not at all a forest, 1 = may as well be a forest. Can be fractional [range: 0.0 ~ 1.0, default: 0.0]
    S:minForestness=0.0

    # If enabled then seeds will only voluntarily plant themselves in forest-like biomes [default: true]
    B:onlyForest=true

    # The rate at which seeds voluntarily plant themselves in their ideal biomes [range: 0.0 ~ 1.0, default: 0.125]
    S:plantRate=0.125

    # Ticks before a seed in the world attempts to plant itself or despawn. 1200 = 1 minute [range: 0 ~ 6000, default: 1200]
    I:timeToLive=1200
}


trees {
    # The chance of a tree on depleted soil to die. 1/256(~0.004) averages to about 1 death every 16 minecraft days [range: 0.0 ~ 1.0, default: 0.0]
    S:diseaseChance=0.0

    # If enabled then sticks will be dropped for partial logs [default: true]
    B:dropSticks=true

    # If enabled apple trees will be generated during worldgen and oak trees will not drop apples [default: true]
    B:enableAppleTrees=true

    # Do X growth cycles at once while ignoring (X-1)/X attempts.  Higher numbers can improve client side performance but too high can make trees grow weird. [range: 1 ~ 8, default: 2]
    I:growthFolding=2

    # Factor that multiplies the rate at which trees grow. Use at own risk [range: 0.0 ~ 16.0, default: 0.5]
    S:growthMultiplier=0.5

    # Factor that multiplies the wood returned from harvesting a tree.  You cheat. [range: 0.0 ~ 128.0, default: 1.0]
    S:harvestMultiplier=1.0

    # The maximum radius of a branch that is allowed to rot away. 8 = Full block size.  Set to 0 to prevent rotting [range: 0 ~ 24, default: 8]
    I:maxBranchRotRadius=8

    # Maximum harvesting hardness that can be calculated. Regardless of tree thickness. [range: 1.0 ~ 200.0, default: 20.0]
    S:maxTreeHardness=20.0

    # Scales the growth for the environment.  0.5f is nominal. 0.0 trees only grow in their native biome. 1.0 trees grow anywhere like they are in their native biome [range: 0.0 ~ 1.0, default: 0.5]
    S:scaleBiomeGrowthRate=0.5
}


vanilla {
    # Right clicking with a vanilla sapling places a dynamic sapling instead. [default: false]
    B:replaceVanillaSapling=false
}


world {
    # Blacklist of dimension numbers for disabling Dynamic Tree worldgen [default: [7]]
    S:dimensionsBlacklist <
        7
     >

    # Randomly generate podzol under select trees. [default: true]
    B:podzolGen=true

    # Generate giant mushrooms in roofed forests. [default: true]
    B:roofedForestMushroomGen=true

    # World Generation produces Vanilla cactus as well as Dynamic cactus if world gen replacement is enabled. [default: false]
    B:vanillaCactusWorldGen=false

    # World Generation produces Dynamic Trees instead of Vanilla trees. [default: true]
    B:worldGen=true
}

**Comment by SuzuChen** [comment]
this one used rn (I deleted the old one- I changed axe mode, climbing on branches to false, and passable leaves to true), but it still is not working properly

**Comment by SuzuChen** [comment]
I'm on mac btw, if that makes any difference (I don't know) but even when I  deleted all configs- this "no log drop"-thing still exists

**Comment by Harleyoc1** [comment]
No it shouldn't do, especially since I'm also on MacOS and cannot recreate this issue. Your harvest multiplier is definitely on 1.0 so it must somehow be a mod incompatibility, though I can't see how another mod could interrupt this. Perhaps you could try installing Hwyla to see if the log drops are actually being calculated correctly (like in [this image](https://cdn.discordapp.com/attachments/732380610953478194/800813899540332565/unknown.png))?

**Comment by Harleyoc1** [comment]
Also a screenshot of your mod list isn't exceptionally helpful. First of all I can't use cmd + F to test if you have a certain mod installed that could be causing it, instead I have to look through the list. But more importantly if I wanted to test this out myself I would have to manually download all of the mods on the pack which is a rather dull task. If you are using the pack through a launcher an export would be appreciated.

**Comment by SuzuChen** [comment]
Ok, I'm using my own private pack so I can only give a google drive link (only mods/configs and resources so the main menu won't look  ugly) (using a lot of textures and stuff from the big variety of resource packs and stuff... :v)

**Comment by Harleyoc1** [comment]
That would be great. If I am able to reproduce your issue I might at least be able to narrow down what's causing it. 

By the way, if you could cut down a few trees and then check the logs to make sure no exceptions are being thrown (or just send me your logs), that would also be a good thing to check. Also, I assume the trees are not dropping sticks either?

One other thing - have you gotten log drops working without any other mods installed? I don't expect this kind of issue would be caused by hardware weirdness but that's also worth a try just to be 150% sure.

**Comment by SuzuChen** [comment]
https://drive.google.com/file/d/1Z_ab5xAv5_0M0Ve9xTPp1J_R76RuAy12/view?usp=sharing
nope, no sticks either, only seeds :c
gonna try without  any mods installed too

**Comment by SuzuChen** [comment]
without any mods- everything works fine
![2021-03-17_02 52 29](https://user-images.githubusercontent.com/80288152/111394559-06c5aa80-86cc-11eb-968a-094738952697.png)
![2021-03-17_02 52 47](https://user-images.githubusercontent.com/80288152/111394577-0fb67c00-86cc-11eb-8fe6-eea3ed340d05.png)

**Comment by Harleyoc1** [comment]
OK that confirms it's definitely a mod incompatibility at least. As mentioned above could you send me your logs too just in case there are any exceptions/warnings being thrown there?

**Comment by SuzuChen** [comment]
https://drive.google.com/file/d/1VlTE9FJ2W8JIM9Dwk0kZ1NKjM7fAD1jR/view?usp=sharing
logs

**Comment by SuzuChen** [comment]
what u mean by exceptions/warnings? o.o

**Comment by Harleyoc1** [comment]
Just wanted to make sure it wasn't throwing any errors (would've helped a lot), but it doesn't appear to be anyway (at least from your latest log files).

**Comment by SuzuChen** [comment]
ok, I will try to install all mods back 1 by 1 and find what's causing it and reach back to you... (may take some time, with this many of them, but still xd)

**Comment by SuzuChen** [comment]
ok, one mod found- "gardenstuff-1.12-2.1.1"

**Comment by SuzuChen** [comment]
second "liquid luck" 1.12.2

**Comment by SuzuChen** [comment]
and  it's done)

**Comment by Harleyoc1** [comment]
What? So is it garden stuff that's causing it or liquid luck?

**Comment by SuzuChen** [comment]
Both. 2 mods out f 220+ mods

**Comment by Harleyoc1** [comment]
How did you come to the conclusion that both are causing it? Does it only happen if both are installed?

**Comment by Harleyoc1** [comment]
I just tried installing both of these mods (both separately and at the same time) and logs were still dropped, so it must be something else causing it.

**Comment by SuzuChen** [comment]
I tried installing mods 1 by 1 (leaving the mods that work perfectly with it), creating a new world each time, and breaking the tree, to see if the logs/sticks will drop. For me with these mods, they did not drop,  dunno why. Maybe they conflict with something else in my mod pack, so it breaks logs drops (some sort of chain reaction between mods), but I think it's not really possible

**Comment by democat3457** [comment]
ohgod a three-way mod conflict
