### ISSUE TITLE
Server Crash (RLCraft) 0.9.7 - 1.12.2

### ISSUE THREAD

**Issue by nicholasrobertm** [ferreusveritas/Dynamic-Trees#501]
On version 0.9.7 in MC 1.12.2 using the rlcraft pack.
Forge 1.12.2-14.23.5.2838

**Describe the bug**
Not entirely sure of the cause, but when a player went into a specific area (apparently with a dragon den) it was crashing the server. I was able to find this https://www.curseforge.com/minecraft/modpacks/rlcraft/issues/179

Which mentioned issues with fire and dynamic trees previously but from what I've seen all of these issues are supposed to be patched

Here is a full copy of the server log from one of the times this crashed things
https://gist.github.com/nicholasrobertm/c52492acef67c61809e8d61d61854f16

**To Reproduce**
Visit area with affected tree

**Screenshots**
n/a

**Rendering Glitches**
n/a

**Crashes**
- Are you running the latest version of Dynamic Trees? (Currently 0.9.22)
- If you are using the DT Biome O' Plenty Add-on do you have the latest version? (Currently 1.4.2)
- If you are using the DT Thaumcraft Add-on do you have the latest version? (Currently 1.4.4)

Not updated to latest but obvs would be interested if this was something fixed in a newer version. Shivaxi doesn't seem to wish to update the pack but I'd be happy to build it from source to attempt to back-port a patch

**Comment by Harleyoc1** [comment]
I have no idea (this is a very old version) but can't you just enable editing on the pack and update it manually to the latest version?

**Comment by nicholasrobertm** [comment]
> 
> 
> I have no idea (this is a very old version) but can't you just enable editing on the pack and update it manually to the latest version?

Unfortunately no, that would require the pack dev (Shivaxi) to update the pack which they're not doing (Ice and Fire mod is in a similar situation where it's pretty out of date).

https://www.curseforge.com/minecraft/modpacks/rlcraft

**Comment by Harleyoc1** [comment]
Well I'm afraid unless you are willing to update the pack yourself (which should be relatively easy to do anyway) you're on your own. As the template states we don't support old versions as it would be wasting effort on something that might've already been fixed.

**Comment by democat3457** [comment]
(i.e., update the mod on your local instance)

**Comment by Harleyoc1** [comment]
Yep. Launchers should allow you to do it through the interface (I know CurseForge does at least where you can go into the profile settings and enable content management for the profile and then it's as simple as clicking the update button next to DT).

**Comment by Harleyoc1** [comment]
To be honest if Shivaxi is no longer maintaining RLCraft I'm surprised no one has taken over the project or started a fork seeing how popular it is.

**Comment by nicholasrobertm** [comment]
yep understandable you wouldn't wanna support the older versions. I didn't see it before but did find he is apparently updating the pack https://streamlabs.com/Shivaxi/feed/45538459_looking_at_title_submissions_for_rlcraft so I'll report this to him and see if he'll patch the version
