### ISSUE TITLE
Black/Pink cubes on jungle and swap trees.

### ISSUE THREAD

**Issue by Zeltrax** [ferreusveritas/Dynamic-Trees#502]
Hello,

Got a mod pack I've made and usually I've never had this issue before but when I use dynamic trees these black/pink blocks appear on these trees and they grow. It seems like they are vines but when you inspect them it says Minecraft:air.

At first I thought it was Biomes O Plenty so I removed reloaded the world and tried again and they still appeared. Then I tried removing Dynamic trees and now they don't appear anymore.

I've made this kind of modpack in the past so I don't know if the newer version of dynamictrees conflicts.

![problem](https://user-images.githubusercontent.com/8917813/112058088-0dcc3d00-8b52-11eb-8b8b-bb75a61c1ce7.png)
![mods](https://user-images.githubusercontent.com/8917813/112058090-0efd6a00-8b52-11eb-84ba-18092a87a72a.PNG)

**Comment by Harleyoc1** [comment]
Please find the registry name of the block by looking at the F3 screen whilst focussing on the block.

**Comment by Zeltrax** [comment]
I can't seem to see it unless its the minecraft:air Do you want me to supply a log aswell?

![problem2](https://user-images.githubusercontent.com/8917813/112068206-59d2ae00-8b61-11eb-8713-94309b39a4b4.png)

**Comment by Harleyoc1** [comment]
Well that's very obscure. And yes, please send a log as there might be some helpful rendering exceptions that might provide some indication of what's going on there.

**Comment by Zeltrax** [comment]
Here is the log's the weird thing is when you load out of save and go back in its gone but then they start to appear out of thin air either attached to the ground or to trees or they just float. But as soon and I stop using dynamic trees they never appear.


[latest.log](https://github.com/ferreusveritas/DynamicTrees/files/6185809/latest.log)
[debug.log](https://github.com/ferreusveritas/DynamicTrees/files/6185810/debug.log)

**Comment by Harleyoc1** [comment]
Unfortunately can't see anything instructive in there at first glance. You might have to try to find out which other mod is causing it (assuming of course that it doesn't happen with only DT installed). First perhaps try checking all of your mods and Forge is up to date, just in case.

**Comment by Zeltrax** [comment]
Yeah checked sadly all mods are upto date. Another weird thing is I tried making a dedicated server with the mods and the issue doesn't happen so I'm guessing its client side. Will need to check one by one to see which mod is causing it.

**Comment by FrostNovaTV** [comment]
This also happened to me, I checked and the error block are vines.

**Comment by rai-en** [comment]
This incompatibility is with JurassiCraft. 

World w/ Dynamic Trees + JurassiCraft:
![2021-06-14_15 15 18](https://user-images.githubusercontent.com/50001839/121954845-d3bfa100-cd24-11eb-989e-18e35426597d.png)

After removing JC:
![2021-06-14_15 16 10](https://user-images.githubusercontent.com/50001839/121954883-e043f980-cd24-11eb-929d-050d2bf22cbe.png)

Re-created world w/ Dynamic Trees and w/o JurassiCraft:
![2021-06-14_15 21 58](https://user-images.githubusercontent.com/50001839/121954917-ee921580-cd24-11eb-82b8-9be3c5d9a3b6.png)

Re-created world w/ JC and w/o DT:
![2021-06-14_15 31 07](https://user-images.githubusercontent.com/50001839/121955579-bf2fd880-cd25-11eb-8fdc-d7edffce55fb.png)

**Comment by Harleyoc1** [comment]
I looked into this and found the cause. JC is replacing the vine block with their own for whatever reason. Since our vines generation feature references the vanilla vines directly from code it's trying to spawn an unregistered block. It's a simple fix, we just need to get the vine block directly from the registry instead of from code (we shouldn't have to, ideally JC would redirect the code to their own vine block).
