### ISSUE TITLE
Vanilla appearance trees

### ISSUE THREAD

**Issue by Ti0Luke** [ferreusveritas/Dynamic-Trees#505]
The trees are not changing visually (like branches for example), although items from the mod appear. I don't know what is causing the mod not to work, I have already erased and replaced it and nothing. Any help please?
I'm using other mods, but none that change the trees.

**Comment by democat3457** [comment]
version, logs, and which trees

**Comment by democat3457** [comment]
and also are you creating a new world

**Comment by Ti0Luke** [comment]
> version, logs, and which trees

Okay. I'm not sure where you get these logs from, but I think these are the ones I'm going to attach along with the mods. I use TLauncher and I tried to create other worlds to see, it didn't work in any of them. The curious thing is that a friend created a server with the same mod pack and on his server the mod worked normally. (The trees I say are literally ALL trees, from savannah, pines, etc. As I said, the trees have the usual look and are not dropping items from Dynamic Trees, although I can use them in creative mode.).

-mods:
![image](https://user-images.githubusercontent.com/82247831/114278681-4cde0780-9a07-11eb-89ab-10dd29660576.png)

-log (Sorry, this is the first time I’ve done this so I’m not sure how to do it, but I imagine that’s it):
[optionsof.txt](https://github.com/ferreusveritas/DynamicTrees/files/6290363/optionsof.txt)
[optionsshaders.txt](https://github.com/ferreusveritas/DynamicTrees/files/6290364/optionsshaders.txt)
[options.txt](https://github.com/ferreusveritas/DynamicTrees/files/6290365/options.txt)

Edit.: I think I found the log, I'll attach :v
[2021-04-10-4.log.gz](https://github.com/ferreusveritas/DynamicTrees/files/6290403/2021-04-10-4.log.gz)

**Comment by Harleyoc1** [comment]
You didn't answer the second question - you are creating a new world or loading new chunks in an existing one, correct?

**Comment by Ti0Luke** [comment]
> You didn't answer the second question - you are creating a new world or loading new chunks in an existing one, correct?

I tested both options (I even put it in the creative and flew a good distance to see if works).

**Comment by Harleyoc1** [comment]
Oh sorry you did actually mention that you created new worlds in that comment, my bad.

**Comment by Harleyoc1** [comment]
Could you try generating a world with only DT installed just to make sure it is a mod compatibility issue?

**Comment by Ti0Luke** [comment]
> Could you try generating a world with only DT installed just to make sure it is a mod compatibility issue?

I tested 2 things: 
1- Create a new ModPack only with DT and it worked OK!
2- Disable all the Mods of this ModPack and leave only the DT and it didn't work.
Did it bug? Impossible to be imcompatible if I disabled them all :v

**Comment by Harleyoc1** [comment]
Hmm. That's weird. Perhaps check that world gen is turned on in the config on the original modpack? I can't think of anything else that would cause that...

**Comment by Ti0Luke** [comment]
> Hmm. That's weird. Perhaps check that world gen is turned on in the config on the original modpack? I can't think of anything else that would cause that...

Well, I created the same modpack again and it worked (???).
I didn't understand anything, but it worked lol
Ty so much guys, I think its just a bug or something like that.
