### ISSUE TITLE
Add a way to disable the new leaves on palm trees, banana trees, etc.

### ISSUE THREAD

**Issue by Orvngex** [ferreusveritas/Dynamic-Trees#506]
**Is your feature request related to a problem? Please describe.**
The new leaves on palm, banana, and other trees are just ugly to me. They simply don't fit in.

**Describe the solution you'd like**
I would like to have a config option to just use normal leaves on all trees.

**Comment by Harleyoc1** [comment]
Base DT does not add any Palms, they are add-on only content, please open this [here](https://github.com/supermassimo/DynamicTrees-ExC/issues) instead.
