### ISSUE TITLE
Dynamic trees not spreading in 1.16.5

### ISSUE THREAD

**Issue by Csquaredaap** [ferreusveritas/Dynamic-Trees#507]
Hi so I threw some of the seeds on the ground and they disappear after a short amount of time but they don't actually plant.... Am I missing something?

**Comment by Harleyoc1** [comment]
That's not how spreading works... They can naturally drop from a tree and plant themselves into the ground - not from a player dropping them on the ground. If you want to plant a new tree yourself, you can right click the ground with a seed like you would with a vanilla sapling.

**Comment by Harleyoc1** [comment]
To amend my previous statement: seeds do have a **chance** to plant themselves if you drop them on the ground **AND** they land in a forest biome (if the `seedOnlyForest` config option is disabled you can override the latter).
