### ISSUE TITLE
mods.toml missing metadata for modid nul

### ISSUE THREAD

**Issue by Cbrock03** [ferreusveritas/Dynamic-Trees#509]
mods.toml missing metadata for modid nul

i install this mod and am immediately met with this error message on game startup

**Comment by democat3457** [comment]
are you sure its a dynamictrees error

**Comment by Cbrock03** [comment]
yes, i recreated the error multipe times but adding and removing it form my mod lists

**Comment by Harleyoc1** [comment]
You have entirely ignored the issue template and not given sufficient details. How are we supposed to help if you haven't even told us what version you're trying to run or a crash report?

**Comment by Inkquill256** [comment]
I'm having the same issue on the 1.16.5 version
Crash Report: 
[crash-2021-04-25_21.58.16-fml.txt](https://github.com/ferreusveritas/DynamicTrees/files/6373995/crash-2021-04-25_21.58.16-fml.txt)

**Comment by Cbrock03** [comment]
sorry im new to minecraft modding, im running 1.16.5, latest version of forge, and optifine. 
[crash-2021-04-25_21.58.16-fml.txt](https://github.com/ferreusveritas/DynamicTrees/files/6378202/crash-2021-04-25_21.58.16-fml.txt)

**Comment by Harleyoc1** [comment]
Your problem is that you're trying to run the 1.12 version in 1.16. If you want to run 1.16 there is a beta download on our Discord.

**Comment by Harleyoc1** [comment]
If you look at the file name it is `DynamicTrees-1.12.2-0.9.23.jar`. The bit in the middle is describing the Minecraft version it runs on, in this case 1.12.2.

**Comment by Harleyoc1** [comment]
Then the last section is the Dynamic Trees version, which is in this case 0.9.23. And for future reference you should also include this in bug reports.

**Comment by Inkquill256** [comment]
Okay thank you so much!
