### ISSUE TITLE
excuse me, wtf?

### ISSUE THREAD

**Issue by Blunder-G** [ferreusveritas/Dynamic-Trees#513]
This is not a bug report. I just wanted to convey the feeling of happiness I had when I saw the update of the most legendary mod in the world to you, the dear mod maker. What you did was bringing tears to my eyes. Mowzies Mobs, Tinker's Construct, Twilight Forest, Dynamic Trees, Better Foliege... I think apocalypse is approaching

THANK YOU SO MUCH FOR THIS ABSOLUTELY **FANTASTIC** MOD :)

**Comment by Harleyoc1** [comment]
We appreciate it... but please please please do not open this as a bug report. Our [discord](https://discord.gg/A4FCBS3) is great for this sort of thing.
