### ISSUE TITLE
Support for "Oh The Biomes you'll Go" mod

### ISSUE THREAD

**Issue by Izuny** [ferreusveritas/Dynamic-Trees#514]
Title, basically.

Please add support for this biome mod, currently only "vanilla" trees fall down, anything generated by other mods will not.

Thank you

**Comment by Harleyoc1** [comment]
#443.

**Comment by Harleyoc1** [comment]
Also an add-on is already in development [here](https://github.com/supermassimo/DynamicTrees-BYG).
