### ISSUE TITLE
server caught in tick loop 1.16.5 crash DynamicTrees-1.16.5-0.10.0-Beta6

### ISSUE THREAD

**Issue by Ajw2003** [ferreusveritas/Dynamic-Trees#515]
[crash-2021-05-03_22.32.38-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/6418779/crash-2021-05-03_22.32.38-server.txt)

crashed using DynamicTrees-1.16.5-0.10.0-Beta6 and forge 1.16.5 36.1.13

server caught in tick loop

**Comment by Harleyoc1** [comment]
Fixed in 531085e547ea655bbd83462317c646e6a9fff5a1.
