### ISSUE TITLE
[1.16.5 Bug] Vanilla trees spawn in villages

### ISSUE THREAD

**Issue by Dradon7** [ferreusveritas/Dynamic-Trees#518]
**Describe the bug**
Plains villages (and possibly other villages, I just haven't checked) have vanilla trees as a part of their generation (probably because the NBT files for a village include trees)

**To Reproduce**
Run Dynamic Trees 0.10.0. Go find a plains village. Look at the trees. They're vanilla.

**Additional context**
Village NBT files inlcude vanilla trees. I'm not sure how you'd replace them, though I suppose you could write a datapack to replace them. The only problem with this solution is that any other mod that ALSO overwrites those same village structures would be incompatible

**Crashes**
The game didn't crash

**Mods List**
forge 36.1.13
dynamic trees 0.10.0

**Comment by Dradon7** [comment]
I should note that most trees are still dynamic, as far as I can tell, this issue is isolated to village generation

**Comment by Harleyoc1** [comment]
> probably because the NBT files for a village include trees

Exactly that. This happens because the trees are part of the village structure files. 

At some point I plan on manually edit the structure files to incorporate them or adding a config option to just prevent their generation altogether.

**Comment by Harleyoc1** [comment]
Fixed in the next beta.
