### ISSUE TITLE
Missing pics in the wiki

### ISSUE THREAD

**Issue by xieve** [ferreusveritas/Dynamic-Trees#52]
There are many pictures just missing in the wiki, idk exactly why or if it's a problem caused by my browser/my internet connection but if I copy the link location it just says "https://github.com/ferreusveritas/DynamicTrees/wiki" which is weird. Now missing are all the pictures on the JoCodes page and every picture below the first row of the table [here](https://github.com/ferreusveritas/DynamicTrees/wiki/World-generation#decide-tree-locations-with-a-stipling-algorithm).

System: Arch Linux
Browser: Firefox 59.0 (64-bit)

**Comment by ghost** [comment]
The wiki isn't finished.  I work on it when I have time which seems to be never.
