### ISSUE TITLE
1.16.5 Some jungle trees are genetically vanilla style

### ISSUE THREAD

**Issue by ghost** [ferreusveritas/Dynamic-Trees#522]
**Describe the bug**
Hi, I made a new world and faced the fact that some trees still remain in vanilla style.

**Screenshots**
![Screenshot_5](https://user-images.githubusercontent.com/36424845/117171001-2a0afd00-add3-11eb-971f-848060112f0b.png)

**Mods List**
DynamicTrees-1.16.5-0.10.0-Beta7.jar
DynamicTreesPlus-1.16.5-0.1.0-Beta7.jar
DynamicTreesQuark-1.16.5-2.0.1.jar
TerraForged-1.16.4-0.2.9.jar

**Comment by Harleyoc1** [comment]
I'm pretty sure this is being caused by Terraforged. Terraforged does not have a compatibility add-on yet but I plan on making one in the future. 

Feel free to re-open if you see this happening without Terraforged, but I very much doubt it is.
