### ISSUE TITLE
Im playing on server 1.16.5 with Create and trees are invincible Idk is it a funcion or bug

### ISSUE THREAD

**Issue by tequ2000** [ferreusveritas/Dynamic-Trees#523]
**Rules (Read this first!)**
This is just a template to help you post a useful issue.  Erase these rules and any irrelevant categories and content as you see fit. 

- Only submit issues related to the latest version of the mod for the currently supported version of Minecraft (which is currently 1.12.2 and 1.16.5).
- When referring to software versions always use the actual version number and never "latest".

If you are opening this **for any other reason** than to report a bug, it will be closed without explanation! For feature requests, use the feature request template. 

**Describe the bug**

**To Reproduce**

**Screenshots**

**Rendering Glitches**
Are you using OptiFine (or any equivalent mods that mess with rendering)?

**Additional context**

**Crashes**
- Are you running the latest version of Dynamic Trees? (Currently 0.9.22)
- If you are using the DT Biome O' Plenty Add-on do you have the latest version? (Currently 1.4.2)
- If you are using the DT Thaumcraft Add-on do you have the latest version? (Currently 1.4.4)

If the above mods are current then please submit a full crash log. The crash log normally contains the names of mods and their versions. Don't be that guy who submitted a crash report without first checking that the versions are current.

**Mods List**
If your crash log does not contain a list of mods or you have no crash log then please provide a full list of the mods you are using complete with mod versions.
What version of Forge are you running? (e.g. 1.12.2-14.23.5.2768)

**Comment by Harleyoc1** [comment]
Are you on beta 7?

**Comment by Harleyoc1** [comment]
I'm going to close this as this should be fixed on beta 7. Please re-open it if it still occurs after updating (don't forget to update both server and client).
