### ISSUE TITLE
what if the bottom blocks of the trees were unbreakeable?

### ISSUE THREAD

**Issue by ekiplier** [ferreusveritas/Dynamic-Trees#524]
It would only disappear over a long period of time or it could be removed with TNT. That way deforestation is actually something to take into account in gameplay

Also realism

**Comment by democat3457** [comment]
like a stump

**Comment by ekiplier** [comment]
> like a stump

Exactly! It would be really cool imo. And you could add a toggle in the configs in case some people think it's too intrusive.

I think players are left too unpunished for wiping out entire forests

**Comment by Ultrasquid9** [comment]
if this was a thing, it would most definitely need to be disabled by default.

**Comment by ekiplier** [comment]
Sure. Still a cool feature imo

**Comment by Harleyoc1** [comment]
We are not adding this. Making blocks unbreakable like this even by configuration will just end up causing all sorts of problems. 

Also, our goal isn't to add punishment to removing trees, it's to make them realistic. If anything, features that aim to punish the player for removing trees should be in an add-on instead.
