### ISSUE TITLE
1.16.5 Crash

### ISSUE THREAD

**Issue by Tunaey** [ferreusveritas/Dynamic-Trees#528]
Whenever I load in a world it crashes after exploring a bit. I've attached the crash log below. 

[latest.log](https://github.com/ferreusveritas/DynamicTrees/files/6447524/latest.log)

**Comment by Harleyoc1** [comment]
That's strange. Logs seem to suggest there are no biomes for the type `river` of which there should be at least two (in vanilla). My best guess is another mod you have is (for some reason) removing these from the biome dictionary.
