### ISSUE TITLE
Dynamic Trees for a forge server that is port forwarded 

### ISSUE THREAD

**Issue by AnonymousCrossOG** [ferreusveritas/Dynamic-Trees#529]
So Previously I have been using forge 1.12.2 with dynamic trees and I just recently made a 1.12.2 Minecraft forge server that is port forwarded I was wondering why when I put all the mods I have including dynamic trees they don't work in my server but they did on my lan  server with my friend

**Comment by Harleyoc1** [comment]
You must be setting up your server wrong in some way. This isn't the right place to ask for help setting up a Forge server.
