### ISSUE TITLE
[1.16.5] Vanilla trees still generates

### ISSUE THREAD

**Issue by QuantumStatement** [ferreusveritas/Dynamic-Trees#531]
**Describe the bug**
Vanilla trees still generates alongside dynamic trees

**To Reproduce**
1. Create new world

**Screenshots**
0.10.0-Beta9
![2021-05-10_12 02 50](https://user-images.githubusercontent.com/35406698/117637606-a19dab00-b18a-11eb-97cf-9feea2074eda.png)

0.10.0-Beta8 (same world)
![2021-05-10_12 14 29](https://user-images.githubusercontent.com/35406698/117637762-cdb92c00-b18a-11eb-92e5-81286ad10420.png)

**Additional context**
[logs.zip](https://github.com/ferreusveritas/DynamicTrees/files/6451088/logs.zip)

**Mods List**
DynamicTrees 0.10.0-Beta9
Forge 36.1.16

**Comment by Harleyoc1** [comment]
This was 100% a mistake on my part. I'll push a new beta later today.
