### ISSUE TITLE
Vanilla tress spawn alongside dynamic trees

### ISSUE THREAD

**Issue by BonsaiBaggins** [ferreusveritas/Dynamic-Trees#532]
Using Minecraft version 1.16.5 with Forge version 36.1.16 and Dynamic trees version 0.10.0-Beta9 (no other mods).

Regular vanilla dark oak, oak, and birch trees are spawning alongside dynamic trees. There seems to be an even split.

Steps to reproduce:
- Install dynamic trees version 0.10.0-Beta9
- Generate new world using "-5419139379499429564" as seed
- View trees in and around dark oak forest at spawn

![image](https://user-images.githubusercontent.com/83957413/117654905-7ea2e380-b1ea-11eb-9b08-c864a295f3f4.png)
![image](https://user-images.githubusercontent.com/83957413/117655031-a72add80-b1ea-11eb-8ac9-47578f3af595.png)
![image](https://user-images.githubusercontent.com/83957413/117655092-bad64400-b1ea-11eb-9e55-1f997a82eb59.png)
![image](https://user-images.githubusercontent.com/83957413/117655230-e5c09800-b1ea-11eb-8a17-ac9b3b12bffc.png)

**Comment by NerChick** [comment]
fine for me
![image](https://user-images.githubusercontent.com/66223024/117656548-28f61900-b1a1-11eb-95f0-e0f37e4ea79c.png)

**Comment by BonsaiBaggins** [comment]
Well I'm not sure how, but I seem to have fixed the issue on my end. It initially occurred on an overwolf curseforge instance with some other mods, but after removing all other mods and even completely reinstalling Minecraft, forge and dynamic trees it kept generating the same way. It wasn't until I restarted my PC, reinstalled, generated a new world and flew to a dark forest biome that the issue stopped. I can now use the mentioned seed without getting vanilla trees. Confused but happy with the outcome

**Comment by Harleyoc1** [comment]
This is a duplicate of #531 anyway. It **was** a problem in beta 9 and was fixed in beta 10.
