### ISSUE TITLE
Optifine colormaps feature not showing up when tree falls.

### ISSUE THREAD

**Issue by NerChick** [ferreusveritas/Dynamic-Trees#533]
version - 1.16.5 0.10.0beta9
When breaking tree with resourcepack with optifine colormaps feature not showing up.
![image](https://user-images.githubusercontent.com/66223024/117655187-6b1e5b00-b19f-11eb-9412-9448bb52ec6e.png)
![image](https://user-images.githubusercontent.com/66223024/117655201-6e194b80-b19f-11eb-9364-2fd9e3c05d2c.png)

**Comment by NerChick** [comment]
I think its cause falling tree is an entity, but it would be cool if you could fix this

**Comment by Harleyoc1** [comment]
Could you confirm it happens on the latest beta still? Some separate changes were made but I'm not confident that it would've fixed this.

**Comment by Harleyoc1** [comment]
@NerChick do you mind sending me the colour map you're using so I can use it in testing to fix this?
