### ISSUE TITLE
cannot load mod 1.16.5

### ISSUE THREAD

**Issue by kittylegitcheck** [ferreusveritas/Dynamic-Trees#534]
cannot load mod: smth not found for modid null. 
Ik it is this mod (on newest 1.16.5 version) cause when I removed It all started to work.
[crash-2021-05-11_09.12.11-fml.txt](https://github.com/ferreusveritas/DynamicTrees/files/6457415/crash-2021-05-11_09.12.11-fml.txt)
edit: oldest 1.16.5 mod version: 
![image](https://user-images.githubusercontent.com/79789524/117779415-f4389f00-b23e-11eb-90be-7b34d51bfcfe.png)

[crash-2021-05-11_09.54.26-fml.txt](https://github.com/ferreusveritas/DynamicTrees/files/6457433/crash-2021-05-11_09.54.26-fml.txt)

**Comment by Ana-avos** [comment]
I am getting the same thing no matter what modpack I drop this into for 1.16.5. I also cannot find anything on google to fix it

**Comment by Harleyoc1** [comment]
The first error was because you were loading the 1.12.2 file on 1.16.5. You need to make sure you're running the file with 1.16.5 in the name. 

The second is because you're running an outdated version of Dynamic Trees Plus. Update **both** DT and DT+ to their latest versions.
