### ISSUE TITLE
Cannot Uninstall Mod Properly

### ISSUE THREAD

**Issue by SortarKris** [ferreusveritas/Dynamic-Trees#539]
I have removed the mod and all it's addons, including their config files, but the trees are still round and bone meal still doesn't work.
(I am using 1.12.2)

**Comment by Harleyoc1** [comment]
This mod doesn't even make trees round... Are you sure you're not talking about Better Foliage's round logs feature (by the way if it is you can turn it off in their config).

**Comment by Harleyoc1** [comment]
Also if you have properly removed the jar file from your `/mods` folder it's literally impossible for our blocks to still be in your world.
