### ISSUE TITLE
Crash while exploring

### ISSUE THREAD

**Issue by lebanni** [ferreusveritas/Dynamic-Trees#543]
DynamicTrees-1.16.5-0.10.0-Beta12.jar
DynamicTreesPlus-1.16.5-0.1.0-Beta8.jar
forge-1.16.5-36.1.18.jar

[crash-2021-05-18_20.44.35-server.txt](https://github.com/ferreusveritas/DynamicTrees/files/6503603/crash-2021-05-18_20.44.35-server.txt)

**Comment by Harleyoc1** [comment]
This should be fixed now anyway.
