### ISSUE TITLE
Destroyed Dynamic Trees (by several structures) (1.12.2)

### ISSUE THREAD

**Issue by KenyMylankca** [ferreusveritas/Dynamic-Trees#544]
![2021-05-19_19 11 40](https://user-images.githubusercontent.com/41585837/118847324-4b411280-b8d6-11eb-8fc6-fce6b05cb515.png)
look at that poor birch dynamic tree... it didn't deserve that. and also see that dynamic rubber tree of tech reborn!! even in the meteor!!!
that meteor is from applied energistics.
 can you fix this? thanks!

**Comment by Harleyoc1** [comment]
#440 We are aware of this problem but as far as we can tell there is nothing we can do on our side to rectify this without something being done on AE2's side too, or an explicit add-on (though that would not be ideal).

**Comment by KenyMylankca** [comment]
oh thats so sad :(

**Comment by KenyMylankca** [comment]
but how can that dynamic rubber tree survives but the vanilla dynamic tree? there should be something about it...

**Comment by Harleyoc1** [comment]
Hmm. Yeah that is weird. DT's addons all use the same world gen so there's no reason why a tree from one add-on should survive like that.

**Comment by KenyMylankca** [comment]
it looks like tech reborn knows how to plant trees well by being compatible with other mods structures, then the DT addon just replaces it so it survives. maybe DT should handle the tree generation better or something... idk

**Comment by Harleyoc1** [comment]
It’s not. As I said DT’s addons use the same algorithm as DT does.

**Comment by KenyMylankca** [comment]
then there's no way for that rubber tree to survive..

**Comment by Harleyoc1** [comment]
And yet it did. Which should be informative to this issue.

**Comment by KenyMylankca** [comment]
i will investigate this. ill seek for other trees from other addons to see if they survive too. and from which mods. maybe helpful..

**Comment by Harleyoc1** [comment]
Trust me. All of the addons are using DT's spawning algorithm's (except TFC, I believe).

**Comment by Harleyoc1** [comment]
I have spoken to @supermassimo who had a similar reaction to me on this ("wtf").

**Comment by KenyMylankca** [comment]
ok then. i will do anything helpful as debugging etc. just tell me..

**Comment by KenyMylankca** [comment]
![2021-05-29_15 40 22](https://user-images.githubusercontent.com/41585837/120070648-3c0b5300-c094-11eb-8fa4-6f3933eee8cf.png)
...
