### ISSUE TITLE
Issue with some other mods...

### ISSUE THREAD

**Issue by ghost** [ferreusveritas/Dynamic-Trees#545]
ok, so I don't know if this is a known bug, but if you have other mods/plugins installed, that can break an entire tree by just breaking on block (example: Mekanism's Atomic Disassembler), it just spams particles everywhere and caused a crash/lags of the server I play on.

**Comment by ghost** [comment]
This is the 1.16.5 version btw.

**Comment by Harleyoc1** [comment]
Send the crash report from the Minecraft folder `/crash-reports`.

**Comment by Harleyoc1** [comment]
If you or anyone else is able to provide a crash/logs for this please do comment.
