### ISSUE TITLE
Mods.toml error while launching mineraft

### ISSUE THREAD

**Issue by Minecrafter1609** [ferreusveritas/Dynamic-Trees#547]
There is a nasty bug i have encountered in the latest 1.16.5 version of dynamic trees where if i try to launch minecrat, it shows "mods.toml missing metadata for modid null"
I browsed on the web for its solution and i found other people have also encountered this bug and the only solution to it as  of now is to 'delete' the mod
![2021-05-21](https://user-images.githubusercontent.com/84562912/119100757-ebfa1400-ba35-11eb-9aea-ce90057ba6a2.png)

I will request the devs of this mod to kindly fix the issue as its really irritating
Also, is there anyone else playing on 1.16.5 version experiencing the same issue?

**Comment by Harleyoc1** [comment]
Download [this](https://www.curseforge.com/minecraft/mc-mods/dynamictrees/files/3313858) file. You want the one with `1.16.5` in the name, not `1.12.2`.
