### ISSUE TITLE
Mass block ragdoll with the Physics Mod causing mass lag

### ISSUE THREAD

**Issue by PierreBorine** [ferreusveritas/Dynamic-Trees#552]
**Bug description**
When installing Dynamic Trees with the Physics Mod (who make blocks having a "ragdoll" physics when broke), trees starts dropping leaves ragdolls, wich cause massive lags and crash in big forests. Also when a tree is cut down, all tree's leaves ragdoll themelfs, wich, cause big laggs too.

**Screenshots**
Here, the physic of oak leaves is turned off
![Capture](https://user-images.githubusercontent.com/85021467/120070569-77555400-c08b-11eb-80b1-09debf5426a0.JPG)
Trees making a lot of ragdolls when broken
![2021-05-29_14 33 03](https://user-images.githubusercontent.com/85021467/120070572-791f1780-c08b-11eb-92be-891c00af73e6.png)

**Mods List**
-Forge 36.1.13
-Dinamic Trees 1.16.5 0.10.0 Beta12
-Physics Mods 1.16.5 1.3.4(for forge) / https://www.curseforge.com/minecraft/mc-mods/physics-mod

I hope i'm clear, its hard to talk abouts thoses things in english for me.

**Comment by Harleyoc1** [comment]
What exactly do you expect us to do about this? Their oak leaves rule clearly must target `minecraft:oak_leaves` instead of `dynamictrees:oak_leaves`. You should see if they allow you to define rules for modded blocks.

**Comment by PierreBorine** [comment]
they do have rules for modded blocks but there is no rules for dynamic trees at all

**Comment by Harleyoc1** [comment]
Surely you can add a custom one?

**Comment by PierreBorine** [comment]
here is a view of the configs file without any other mods than Dynamic Trees and The Physics Mod: https://pastebin.com/TgEQaj4R
I will try to add the "dynamictrees:oak_leaves" you said

**Comment by Harleyoc1** [comment]
Looks like you want to add `..., dynamictrees:oak_leaves, 0, ...` (the `...` just means the rest of the list, don't actually put ...).

**Comment by PierreBorine** [comment]
I tried, that dosen't work, they don't even show up in the settings in game.

**Comment by PierreBorine** [comment]
I should probably look for the Physics Mod support for that

**Comment by Harleyoc1** [comment]
Can you show me how you added it?

**Comment by Harleyoc1** [comment]
But yes this is unrelated to DT.

**Comment by PierreBorine** [comment]
here is how i added it: https://pastebin.com/7aHetgjL
i'll go check that, thanks you anyway :)

**Comment by Harleyoc1** [comment]
Yeah I can't see what's wrong with that so I'd ask the Physics mod for help.
