### ISSUE TITLE
1.16.5 Crash Upon Mass Tree Destruction

### ISSUE THREAD

**Issue by ghost** [ferreusveritas/Dynamic-Trees#553]
DELETED

**Comment by Cfgaar** [comment]
Having a similar issue with one of my users. Tested on both their laptop and the PC running the server. Any chance the trees involved in your problem include dark oak?

**Comment by Harleyoc1** [comment]
The crash link has expired, but I think this was the same as #620 which should be fixed (though note not yet released).
