### ISSUE TITLE
Placeholder texture (purple and black) in root block.

### ISSUE THREAD

**Issue by Yurkiis** [ferreusveritas/Dynamic-Trees#556]
The root block is with a placeholder texture instead of the normal dirt texutre. What is causing this problem is the Default 3D texture pack, is there a way to use it without causing this issue? 

![image](https://user-images.githubusercontent.com/85118026/120206916-27e56400-c202-11eb-87e3-73aeaebb0ac2.png)

I know this is a trivial/too specific question, it's just that really like the texutre pack and the dynamic trees mod, i want to have both of them running at the same time. Sorry if i'm bothering.

**Comment by Harleyoc1** [comment]
This isn't directly an issue with DT. You need to work out how to edit a multipart model properly to allow for this. Assuming that's possible there are many places to ask for help in doing so - but an issue tracker isn't the place.
