### ISSUE TITLE
oak leaves spread on top of the crimson trees

### ISSUE THREAD

**Issue by Umuthoper** [ferreusveritas/Dynamic-Trees#557]
![Minecraft_ 1 16 5 - Singleplayer 1 06 2021 12_20_20](https://user-images.githubusercontent.com/68096354/120299848-11a7d880-c2d4-11eb-818b-a5c2c7d8d437.png)

**Comment by Harleyoc1** [comment]
DT version? Context?

**Comment by Harleyoc1** [comment]
I'm unable to reproduce this and you've chosen to ignore the issue template that would've given some more context. If you are still having this issue please re-open it **with context**.
