### ISSUE TITLE
Birch tree leaves are bugged while using serene seasons

### ISSUE THREAD

**Issue by GabePss** [ferreusveritas/Dynamic-Trees#561]
While using _Serene Seasons_, every type of tree leaves work as intended (changing colors depending on the season), but for some reason, when a birch tree from _Dynamic Trees_ is spawned (by world-gen or by a player placing a sapling) it's leaves won't change colors, but if the birch tree's leaves block is collected by shears and placed down, it will change it's color according to the season.

I have tested in creative by getting the leaves block from the birch dynamic tree with the mouse scroll click(middle click) to see if there was a "new" leaf block in the tree, but when getting it that way and placing the block down, it would still change colors while the tree's one wouldn't. 

The mod list is as follows:

> Dynamic Trees 1.16.5 - 0.10 Beta 14

> Dynamic Trees+ 1.16.5 - 0.1.0 Beta 8 (pretty sure i have tested without it aswell, but I will leave it here in case it changed something)

> Serene Seasons 1.16.5 - 4.0.1.91   (most recent up to date for 1.16.5)

> Minecraft 1.16.5 (using MC loader)

> Forge 36.1.0

(I have been playing with more mods, but i created a fresh new instance with only those in order to see if it was a mod conflict or something, again, leaving here just in case it helps in any way)

**Comment by Harleyoc1** [comment]
Fixed. Will be included in beta 15.
