### ISSUE TITLE
Terraforged World Type Generates Vanilla Trees

### ISSUE THREAD

**Issue by takeshipoggies** [ferreusveritas/Dynamic-Trees#562]
**Describe the bug**
minecraft version: 1.16.5

So, I tried loading a world with both Terraforged and Biomes o' Plenty installed. 
I have dynamic trees+ installed too but I don't think that's causing the issue.
As the title says, I ran a Terraforged World Type, not Vanilla, nor Bo'P type.

**To Reproduce**
Steps to reproduce the behavior: Just load a terraforged world type, I only see vanilla trees everytime.

**Screenshots**
there's not much to explain, it's just that trees are vanilla, not dynamic.
I'll provide screenshots if you really need, but I gotta find another way tho (key shortcut doesn't work nor 3rd party programs at the moment).

**Rendering Glitches**
I'm using Optifine U G8 for 1.16.5 to use SEUS / BSL shaders.

**Crash**
Game didn't crash, but FYI:
- I'm running the latest version of DT for 1.16.5
- Bo'P addon is not compatible for 1.16.5 yet.

**Mods List**
Forge is version 36.1.0

the mods I have installed:
AppleSkin,
AE2,
Atum 2 (the sand dimension),
YUNG's better caves/mineshafts/strongholds,
betterEnd,
Biomes o' Plenty,
create,
curious,
decorative blocks,
dynamic suroundings,
dynamic trees/trees+/terraforged addon (Bo'P addon is not available for 1.16 yet),
endergetic expansion,
HWYLA,
immersive engineeing/petroleum,
infernal expansion,
ironchest,
item physics,
JEI/JER,
modernXL,
morewaterlogging,
mousetweaks,
mystical agriculture/agradditions,
neat,
optifine U G8,
oreexcavation,
pam's 2 core + crops + trees + food extended,
platforms,
projectE,
quark,
subterranean wilderness,
tinker's construct (no add-ons),
terraforged,
Thermal mods (foundation, expansion, innovation, locomotion),
waystones
+ the respective libraries:
abnormals core, autoreglib, cofh core, creative core, cucumber, mantle, shetiphiancore, statement, titanium, YUNGs API.

**EDIT**
I checked and it seems to work for some (vanilla) trees but some don't.
Idk if this is related to Bo'P and it will be automatically fixed when the addon comes out for 1.16 o it's another issue, I'll leave this here just to be sure.

**Comment by Harleyoc1** [comment]
See #443 for suggesting add-ons (bop add-on hasn't updated to 1.16 yet), see a list of the current add-ons on the CurseForge page (there is an add-on that works for TerraForged biomes, but it still won't work for BOP).
