### ISSUE TITLE
Configuration in 1.16.5

### ISSUE THREAD

**Issue by allethargic** [ferreusveritas/Dynamic-Trees#563]
Some config options which I remember where in 1.12.2 aren't listed in config files in newer version. Are functions like "miltuply loot from trees" unavailable for 1.16.5?

**Comment by Harleyoc1** [comment]
Yes but server configurations are now world-based. This means you need to change the options in `saves/[world]/serverconfig/dynamictrees-server.toml` instead of in the normal config directory.

**Comment by Harleyoc1** [comment]
By the way, you can also move this file to `/defaultconfigs` in the root MC directory in order to have them copy over to that location automatically when creating new worlds.

**Comment by allethargic** [comment]
Giant thanks to you!
