### ISSUE TITLE
TFC and Dynamic Trees falling tree crash 1.12

### ISSUE THREAD

**Issue by Tavarnarmo** [ferreusveritas/Dynamic-Trees#565]
Hello, I play terrafirmacraft with 9.23 version of Dynamic Trees and in all of my worlds every time when dynamic trees tree is either burning or cut down there is a crash, crash report here https://gist.github.com/Tavarnarmo/84ce3b4cb539d84d9e32fd4d03217026. Already reported this on TFC github because it started happening exactly after update to newest version of it but they think that it isn't TFC so went here.

**Comment by Harleyoc1** [comment]
If you could narrow this down to the mods causing it that would be great as I can't reproduce this with only DT and TFC.

**Comment by Tavarnarmo** [comment]
I think that this was because of this mod [(https://www.curseforge.com/minecraft/mc-mods/sneedasm](url)) After removing it issue went away.

**Comment by Harleyoc1** [comment]
Ah right, looks like it has already been reported (LoliKingdom/LoliASM#17) to them and the author has a fix in mind for a future release. As a temporary workaround you can also disable `squashBakedQuads` in their config if you still want to use it now.

**Comment by Rongmario** [comment]
Ah seems like it was a config issue all along, insert

`com.ferreusveritas.dynamictrees.client.QuadManipulator`
and
`com.ferreusveritas.dynamictrees.models.bakedmodels.BakedModelBlockBranchCactus`

in `classesThatCallBakedQuadCtor` of the config, and it'll work fine.
