### ISSUE TITLE
Sapling cannot grow into a tree

### ISSUE THREAD

**Issue by oOBoomberOo** [ferreusveritas/Dynamic-Trees#566]
**Describe the bug**
After planting a sapling, it will pop off after some time and can never grow into a full tree.

This bug **does not** occurs when using bone meal to directly grow the tree.

**To Reproduce**
1. find a suitable area
2. plant a sapling
3. wait a bit (you can use `/gamerule randomTickSpeed` to speed things up)

**Additional context**
Saplings from dynamic tree's addons **do not** have this issue, it seems to only be affecting sapling from the main mod.

**Mods List**
- [dynamic-trees-1.16.5-0.10.0-beta15](https://www.curseforge.com/minecraft/mc-mods/dynamictrees/files/3343711)
- [dynamic-trees-plus-1.16.5-0.1.0-beta9](https://www.curseforge.com/minecraft/mc-mods/dynamictreesplus/files/3343850)
- [dynamic-trees-natures-aura-1.16.5-1.2.2](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-natures-aura/files/3308472)
- [dynamic-trees-quark-1.16.5-2.0.4](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-quark/files/3331311)
- [dynamic-trees-traverse-1.16.5-2.2.0](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-traverse/files/3330267)

Forge Version: 1.16.5-36.1.25

**Comment by beezlee** [comment]
Is the tree being planted in a place with a clear sky view above it?

**Comment by oOBoomberOo** [comment]
Yes, and given that the addons sapling was able to grow under the same condition I don't think this is the issue.

**Comment by oOBoomberOo** [comment]
Figure out the issue, this is due to an interaction with the [better-weather](https://www.curseforge.com/minecraft/mc-mods/better-weather/files/3197360) mod.

That mod seems to change the biome humidity and temperature so extreme that the tree wasn't able to grow. I managed to plant an oak tree by setting the season to mid-summer.
