### ISSUE TITLE
Cactus not rendering/crashing clients

### ISSUE THREAD

**Issue by Serifina** [ferreusveritas/Dynamic-Trees#567]
Dynamic Cactus fails to render, with the error "CCL caught an exception rendering a block. See log for details." appearing in chat. Error from the log:
https://gist.github.com/Serifina/ff3031ca960e836964167c946485f005

The cactus is still present. The hitbox can be found, and it can be broken safely in creative. If you try to break it in survival, however, the client crashes, with this crash report:
https://gist.github.com/Serifina/d89661e3ba62e39224d8a47a7a5510a3

Optifine is not present. (I never use it.)

Dynamic Trees version: 1.16.5-0.10.0-Beta15
Dynamic Trees Plus version: 1.16.5-0.1.0-Beta8

Forge Version: 1.16.5-36.1.16

**Comment by Harleyoc1** [comment]
This is a DT+ related issue. You should be reporting it there. Anyway I believe this is caused by you using an outdated version of DT+, try updating to beta 9 and then if it still occurs please open a new issue in the DT+ issue tracker.
