### ISSUE TITLE
Base Age/ Max Age of Dynamic Trees

### ISSUE THREAD

**Issue by autumnly24** [ferreusveritas/Dynamic-Trees#568]
Would it be possible to add a modifier that allows you to change the base age and max age of the trees?
Basically allowing people to choose how big the trees can grow and start as.

If you want some explanation for how this would be useful and improve this mod, it would allow people to create massive forests, new growth looking forests, etc. There would also obviously have to be a limit on how big the trees are, maybe capping out around 24 blocks?

Thanks for reading my suggestion, it'd be incredibly useful for a server I plan on running in the future.

**Comment by Harleyoc1** [comment]
Trees of that size simply aren't possible without major changes to how we handle thick trees. We do plan on doing this in the future but it's not a simple change. 

As for configuring the max ages and such you can actually already sort of do this yourself to individual species using tree packs. If you change the `soil_longevity` key, such as is done for thick trees like the [mega spruce](https://github.com/ferreusveritas/DynamicTrees/blob/1.16.5/src/main/resources/trees/dynamictrees/species/mega_spruce.json). However I'm not entirely sure what you mean by "base age", please explain this.
