### ISSUE TITLE
Game crashes connecting to server trying to load cactus branches. 

### ISSUE THREAD

**Issue by Kratos-Lee520** [ferreusveritas/Dynamic-Trees#569]
- Use a paste site like [Gist](https://gist.github.com) or [Pastebin](https://pastebin.com) to dump any logs or crash reports. 

**Describe the bug**
I crash connecting to my 1.16.5 forge server (version ) which has spawn next to a desert, so I just crash ever time I load in server. Updated both client and server from the Beta 8 Dynamic Trees to the Beta 9 and it fixed the issue. 

**To Reproduce**
Load into a server with dynamic trees (version 1.16.5-0.10.0-Beta16) and dynamic trees plus (version 1.16.5-0.1.0-Beta8)

**Rendering Glitches**
I do have Optifine version 1.16.5_HD_U_G8.

**Crashes**
- I am running the latest version of Dynamic Trees and Trees+.

**Pastbin Link**
https://pastebin.com/0mTJR1JY

**Comment by Harleyoc1** [comment]
DT+ Beta 8 is not the latest version. You need to update to DT+ Beta 9.

**Comment by democat3457** [comment]
they also literally said they updated to beta 9 and it fixed the issue - what was the point of opening this anyway if it's already fixed

**Comment by Harleyoc1** [comment]
Oh yeah. Literally the only thing beta 9 was released for was to be compatible with the changes made in DT beta 15 so this is expected behaviour.

**Comment by Harleyoc1** [comment]
So your issue is basically similar to saying “Forge for 1.16.4 does not load on 1.16.5, but when I update to Forge for 1.16.5 it works”.
