### ISSUE TITLE
1.14 support

### ISSUE THREAD

**Issue by aMinecraftPlay** [ferreusveritas/Dynamic-Trees#572]
I'm trying to make a Realistic Minecraft, and all the mods and recourse packs are using version 1.14. The reason I want this mod in my mod pack is to make the trees fall realistically. None of the other mods recreated the same effect, so I decided to use this one. If the team releases a 1.14 version, it would be a big help.

I have tried force running it, but it crashed. I don't know any other thing to try, so I'm asking for this version.

If you find any mod that replicates the effect, or release a version of this mod that only has the falling tree effect, please inform me.

**Comment by Harleyoc1** [comment]
We are not back porting to other versions. Either use 1.12 or update to 1.16.5.

**Comment by aMinecraftPlay** [comment]
are there any realistic texture packs for 1.12 then?

**Comment by Harleyoc1** [comment]
I imagine there are tons for both versions but I don't know of any specific ones.

**Comment by aMinecraftPlay** [comment]
I was thinking urban recourse pack, but it was not for 1.12, so if you can give me any _mods_ that make the tree fall, that could also help. Or like I said in the question, would it be possible to make a version of the mod with only the falling effect?

**Comment by Harleyoc1** [comment]
No. If you’re so keen on using this resourcepack specifically why not just port it yourself? 

Anyway, I’m sorry but this is not a search engine. Do your own research.

**Comment by aMinecraftPlay** [comment]
Ok thank you!
