### ISSUE TITLE
ConcurrentModificationException while loading world with mohist server

### ISSUE THREAD

**Issue by DPurple** [ferreusveritas/Dynamic-Trees#578]
**Describe the bug**
throws ConcurrentModificationException while using mohist server which likely using a multi-threaded chunk loader 

**To Reproduce**
Get a mohist server https://github.com/MohistMC/Mohist and installed
Put DynamicTrees 1.16.5 into mods directory and boot server

**Additional context**
I replaced HashMap into java.util.concurrent.ConcurrentHashMap in UniversalPoissonDiscProvider.java at line 19, it likely fixed the problem, but not further tested...

**Crashes**
https://pastebin.com/Dqe7bX1W

I'm using
DynamicTrees 0.10.0-Beta12 in 1.16.5
mohist version 1.16.5-679
which come wtih forge 1.16.5 - 36.1.32

**Comment by DPurple** [comment]
here what I tried:
https://pastebin.com/5FZRn6LV

**Comment by Harleyoc1** [comment]
Please make sure you are also on the latest version. Beta 12 is quite old now. 

I'm guessing they're making chunk data loading asynchronous? The change you made seems like it should be sufficient enough, feel free to open a PR.

**Comment by DPurple** [comment]
Opps sorry, I just use the version which provided by the template
I'm using beta17 (confirmed), code tested by fresh clone from github branch 1.16.5
