### ISSUE TITLE
[Mod compatibilit] With Biomes o' plenty

### ISSUE THREAD

**Issue by Jummit** [ferreusveritas/Dynamic-Trees#58]
Currently you cant place saplings on biomes o' plenty's grass blocks like sandy grass or grass from specific biomes. When the tree grows and the roots are placed it should still use the old root block. Could this be made possible or are there issues with that?

**Comment by ghost** [comment]
Are you using the Dynamic Trees - Biomes O' Plenty add-on mod?  If not then install it because I believe it makes that stuff work.

**Comment by ghost** [comment]
BoP add-on for dynamic trees is required to do this.
