### ISSUE TITLE
cactus grow strange

### ISSUE THREAD

**Issue by Filgas08** [ferreusveritas/Dynamic-Trees#583]
cactuses grow without branches connection:
![2021-07-01_14 49 40](https://user-images.githubusercontent.com/47673040/124127224-c3752900-da7b-11eb-8b12-3183f71e8149.png)
this is a really annoying problem so please help.

**Comment by Harleyoc1** [comment]
This is a Sodium issue. Refer to spoorn/sodium-forge#17.
