### ISSUE TITLE
Biomes O' Plenty compatibility

### ISSUE THREAD

**Issue by iimNumix** [ferreusveritas/Dynamic-Trees#584]
I'm attempting to create a modpack for me and my friends and I do not know how to fix a problem. My problem is coming up with Dynamic Trees. The modpack is in 1.16.5 and the problem only occurs when Biomes O' Plenty is in the pack. The game will come up with an error after loading the game to the menu so it isn't a world generation thing. I made sure to also install the Dynamic Trees addon that makes it compatible with BOP. I've tried installing different versions of the addon mod since that mod is the problem. I've attached the crash report here as well. 

[crash-2021-07-01_18.58.35-fml.txt](https://github.com/ferreusveritas/DynamicTrees/files/6751171/crash-2021-07-01_18.58.35-fml.txt)

**Comment by iimNumix** [comment]
If you need anything else please let me know.

**Comment by Harleyoc1** [comment]
Update to DT beta 17.
