### ISSUE TITLE
Shader Crash

### ISSUE THREAD

**Issue by HeroMotion677** [ferreusveritas/Dynamic-Trees#587]
Version: 1.16.5 - 0.10.0 - Beta

Issue/How to reproduce: When switching from no shader to any shader or vice versa via optifine it crashes. Crash log states its a rendering issue with Dynamic Trees.

Crash Log
https://pastebin.com/XfYgvCX8

**Comment by Harleyoc1** [comment]
This is NOT caused by DT, it's caused by DT+. Please open it in the [DT+ issue tracker](https://github.com/supermassimo/DynamicTreesPlus/issues).
