### ISSUE TITLE
game crashing while cutting down trees, can't re enter world without crashing

### ISSUE THREAD

**Issue by frogmenace** [ferreusveritas/Dynamic-Trees#589]
**Describe the bug**
game crashed while cutting down trees, save will not reopen

**To Reproduce**
not sure, i was in the middle of clearing a forest and it just crashed and my save will not open anymore without crashing.

**Rendering Glitches**
optifine installed

here's my crashlog >>
https://pastebin.com/7ZyJbd0H

**Comment by Harleyoc1** [comment]
Same issue was experienced by someone before, #546. It was determined to be Building Gadget's problem, not ours. I suggest you make sure you're on their latest version and if not look into making a report on their end.
