### ISSUE TITLE
[Suggestion] Natura Compatibility

### ISSUE THREAD

**Issue by jefferyrlc** [ferreusveritas/Dynamic-Trees#59]
Would like to see an addon adding support for trees added by the Natura mod.

**Comment by ghost** [comment]
Yes, that would be nice, but I'm not going to do it.

**Comment by xFirefalconx** [comment]
I hope this is the correct thread, I had problems finding a place to ask. Minecraft Version 1.16.5.
I was wondering whether there could be a possibility to add "Rich Soil" from "Farmer's Delight" to the blocks a tree can grow on. Not requesting the textures to change or be applied, just that a tree can accept it as a growing place, like some sort of whitelist where that block is added as well. I hope this is possible.
