### ISSUE TITLE
Missing Textures Compatibly Issue with SpaxPurebdcraft

### ISSUE THREAD

**Issue by IchigoGames** [ferreusveritas/Dynamic-Trees#590]
**Feature request rules**
1.16.5

**Is your feature request related to a problem? Please describe.**
Yes this mod does not work well with SpaxPurebdcraft
![image](https://user-images.githubusercontent.com/11888162/125023582-cb693600-e044-11eb-9ef5-c839e7442895.png)
![image](https://user-images.githubusercontent.com/11888162/125023857-534f4000-e045-11eb-8505-8fd49c2e5715.png)

**Describe the solution you'd like**
a option in the config to turn off the extra textures added to dirt under tree aka the roots i think that is the reason for spax not knowing what to do with it and it showing the missing Textures 

**Describe alternatives you've considered**
Support for spax ? Or just make it Normal grass under trees

**Comment by IchigoGames** [comment]
theres allways a off chance this is a optfine issue i dont think it is but i need to do more testing to be sure.

**Comment by Harleyoc1** [comment]
We can't be expected to provide support for specific incompatible changes resource packs are making. You'll need to manually change the resource pack to be compatible.

**Comment by Harleyoc1** [comment]
I imagine they are doing something unorthodox with their model files, I can't see why it would be necessary though so hopefully should be easy to fix.

**Comment by IchigoGames** [comment]
well im not removing the grass texture in my resource pack mabey i can remove the pointless roots

**Comment by Harleyoc1** [comment]
That's not what I was saying. You shouldn't have to remove the grass texture.

**Comment by IchigoGames** [comment]
the block wont even brake like dirt or grass unless you remove the tree on top you sure its considered a type of grass block by mc  ?

**Comment by IchigoGames** [comment]
if its not that might be why resource pack is not working

**Comment by Harleyoc1** [comment]
Yeah that's absolutely the reason why... It's a "rooty grass" block. 

Please send me the model Json for the grass block in that resource pack, I would like to see what they might be doing to break things.

**Comment by IchigoGames** [comment]
sure https://www.dropbox.com/s/nyxoufffi05ar82/Model%20for%20grass%20block.zip?dl=0 its in this zip

**Comment by IchigoGames** [comment]
https://www.dropbox.com/s/bmdv606b66dgam4/texture%20for%20grass%20block.zip?dl=0 in case you want to look at textures

**Comment by Harleyoc1** [comment]
> sure https://www.dropbox.com/s/nyxoufffi05ar82/Model%20for%20grass%20block.zip?dl=0 its in this zip

What the heck? They are using textures but not specifying where the model should get them from... Honestly no clue how it even works in the first place. If you add this to specify the textures like in the vanilla model it should work: 

`grass_block.json`
```json
    ...
    "textures": {
        "particle": "block/dirt",
        "bottom": "block/dirt",
        "top": "block/grass_block_top",
        "side": "block/grass_block_side",
        "overlay": "block/grass_block_side_overlay"
    },
    ...
```

**Comment by IchigoGames** [comment]
could be its located some where else in the resource pack https://www.dropbox.com/s/i8gkad9rcfmry4d/PureBDcraft%20%2064x%20MC116.zip?dl=0

**Comment by IchigoGames** [comment]
ok ill give that a try

**Comment by WenXin20** [comment]
The blockstates folder shows where the grass_block is getting it's model from. It looks like it's getting it from the `models/blocks/_bdc` folder.

**Comment by IchigoGames** [comment]
just wondering but what does it do the grass under the trees is it just grass with roots on it if so why does waila say its fertile ?

**Comment by IchigoGames** [comment]
if it was just a grass texture blocks with a overlay of roots on it i dont think any resource pack would have a issue with it.

**Comment by Harleyoc1** [comment]
The rooty block is a tile entity that stores the tree's data. This includes its specific Species for non-common species (like the apple oak for example), and its fertility. 

The fertility runs out over time and when the tree runs out of fertility it stops growing (it has fully matured, in other words). FYI you can also re-fertilise a tree by applying bone meal.

**Comment by Harleyoc1** [comment]
Also that is exactly what it is, it takes the grass block model and applies a root texture overlay. However it seems that multipart models aren't fully compatible with the way some resource packs work. In this case it seems that the grass block actually also uses a multipart that doesn't even reference the grass block model in the models folder (seems to me someone must have just left that half-finished file there by accident). My guess is that removing it entirely should work, as long as it's not referenced anywhere else.

**Comment by IchigoGames** [comment]
the  grass block mode in the resource pack or in the mod ?

**Comment by IchigoGames** [comment]
looks like its only a issue with grass 
![image](https://user-images.githubusercontent.com/11888162/125838946-df200010-4067-4e0f-826a-ecff7a55eec4.png)

**Comment by Harleyoc1** [comment]
Ah yes I forgot to respond. It was the grass block model in the mod, I can see you worked out. As I said it wasn’t in use and invalid, so I’m guessing someone just left it in; you should inform them as this will happen in any mod that uses the grass block model, like we do.

**Comment by IchigoGames** [comment]
i downloaded a new version of spax it looks like they fixed it 
![image](https://user-images.githubusercontent.com/11888162/126052446-9094a91e-804a-4028-b8e4-a96fb74bf58a.png)

**Comment by IchigoGames** [comment]
i downloaded a new version of spax and it looks like they fixed it.
![image](https://user-images.githubusercontent.com/11888162/126052480-eb237a15-451f-482b-8a9f-805f3a405ee1.png)
