### ISSUE TITLE
[1.16.5] Possible bug with giant trees

### ISSUE THREAD

**Issue by antibang** [ferreusveritas/Dynamic-Trees#591]
**Describe the bug**
Uh, I'm not even 100% sure this is a Dynamic Trees problem, but the other day when I was terraforming with WorldEdit, there were some... problems? I was creating spheres with a brush and I was noticing it was being offset a random number of blocks in any direction. I was assuming it was just grass I didn't see or something, but I moved onto a new project the other day and when I started using the smoothing brush from WorldEdit, there were these holes that formed where l used it and they don't smooth over. In both of these scenarios, I had mass removed dynamic trees from the Giant Spruce Taiga biome. I hadn't terraformed in that biome since I added DT and it's the only one I've noticed those problems with. It seems like these "holes" used to be where the trees were. The first scenario happened on a single player world and the second was on my server.

The holes:

![2021-07-09_04 05 03](https://user-images.githubusercontent.com/79492924/125058982-717e6580-e070-11eb-824b-da1ce1e5731c.jpg)

**Mods List**
https://pastebin.com/X9RGTnjF

Forge 1.16.5-36.1.10

**Comment by Harleyoc1** [comment]
How did you "mass remove" the trees? I fear if you used commands to clear all the branches world edit would've done it in a way that leaves the "trunk shell" blocks (blocks around the centre trunk that are simply meant to provide a collision box for a thick trunk). I suggest you clear all `dynamictrees:trunk_shell` blocks in that same area and in the future use `/dt purgetrees [chunkX] [chunkZ] [chunkRadius]` in future to properly clean up all tree-related blocks.

**Comment by antibang** [comment]
_Oh, god,_ thank you so much lol yeah, I removed them using WorldEdit. Having used it for as long as I have, I should’ve known it was something like that! Holes are no more :)
