### ISSUE TITLE
[1.16] Crash when enabling shaders

### ISSUE THREAD

**Issue by CactusDuud** [ferreusveritas/Dynamic-Trees#595]
Game crashed when enabling Complementary Shaders and resource packs

1. Open game with Dynamic Trees
2. Apply Complimentary Shaders
3. Apply a resource pack (I'm not sure what about them causes the crash)
3. Crash

[Crash report](https://gist.github.com/CactusDuud/2c24d2b44cc67ee67e3f97e9bea576cc)

**Mods List**
Forge 36.1.32
Dynamic Trees Beta17
Complimentary Shaders v.4.1
Stay True 1.16

**Comment by Harleyoc1** [comment]
It's unclear why Forge reckons this is related to us due to the stack trace not even mentioning any of our classes.
