### ISSUE TITLE
[crash] server crash when loading dynamic trees - Beta18/19

### ISSUE THREAD

**Issue by Seth0067** [ferreusveritas/Dynamic-Trees#597]
[Link to server latest](https://gist.github.com/Seth0067/afe71540b70f7ef18376e4de07891dfa)

DESCRIPTION
Using latest Dynamic Trees Beta 18 and Beta 19 (also using sister mods for quark, boP, traverse, extra, atum, forbidden arcanus, natures aura, terraforged) my server is crashing when terraforged is generating dynamic trees. I have posted in their Github about this and they let me know that it looks like a dyn trees issue.

Server world will just not load at all now. Even after deprecating the recent updates.

TO REPRODUCE
[Server zip is here](url) if you want to look directly. 
1) unzip server and run using .bat file (you may need to edit java version based on your local java install)

OPTIFINE
using optifine g7 for 1.16

VERSION
DynamicTrees-1.16.5-0.10.0-Beta19.jar
DynamicTreesAtum-1.16.5-1.1.1.jar
DynamicTreesBOP-1.16.5-2.0.5.jar
DynamicTreesForbiddenArcanus-1.16.5-1.1.2.jar
DynamicTreesNaturesAura-1.16.5-1.2.4.jar
DynamicTreesPlus-1.16.5-0.1.0-Beta10.jar
DynamicTreesQuark-1.16.5-2.1.0.jar
DynamicTreesTerraForged-1.16.5-1.0.0.jar
DynamicTreesTraverse-1.16.5-2.2.2.jar

FORGE VERSION
forge-1.16.5-36.1.65.jar

**Comment by Harleyoc1** [comment]
Could you send the crash with beta 18 to verify it is the same?

**Comment by Seth0067** [comment]
[HERE](https://gist.github.com/Seth0067/25cb40c95a477c20f262402c2b1b665f)

**Comment by XxInvictus** [comment]
I have had this issue on both BETA18 and BETA19 also, attaching crash log. I had one crash on BETA19, then downgraded back and it seemed to be okay, but now I have had another crash on BETA 18.
[DT_CRASH_2.log](https://github.com/ferreusveritas/DynamicTrees/files/6873506/DT_CRASH_2.log)
[DT_CRASH_1.log](https://github.com/ferreusveritas/DynamicTrees/files/6873507/DT_CRASH_1.log)

**Comment by Harleyoc1** [comment]
Don't worry I know what is causing this. Will fix and put out a new beta now.

**Comment by Harleyoc1** [comment]
Should be fixed in beta 20.

**Comment by Seth0067** [comment]
thanks @Harleyoc1 - will look out for it!
