### ISSUE TITLE
[Suggestion] Integration

### ISSUE THREAD

**Issue by Preminenc3** [ferreusveritas/Dynamic-Trees#6]
First of all amazing mod I have been waiting for something like this for years great job keep up the great work.

Integration with Natura and Biomes O' Plenty mods (trees and soil).
Integration with Tough As Nails for seasons.

**Comment by Deshiba** [comment]
The project scope states the following:
- "To provide advanced growing versions of **vanilla** trees."

But it also includes:
- "Provide interfaces for other mod developers to expand the mod with add-ons, new trees, effects, mobs and other things. "
- "To achieve compatibility with other popular mods when appropriate." 

I wouldn't expect this mod author to go to the lengths of supporting all the mods that add wood out there. But anyone could make a plug-in to bridge this mod and BOP.

**Comment by ferreusveritas** [comment]
Well said Deshiba.  I'm currently working on an API that should make adding trees a trivial matter.
After that we'll see who wants to take up the task of BOP bridging.  After all, I'm a busy fella, it probably won't be me.
