### ISSUE TITLE
Trees hardly ever drop seeds

### ISSUE THREAD

**Issue by Pikamochzo** [ferreusveritas/Dynamic-Trees#608]
**Description**
Trees very rarely drop seeds

**To Reproduce**

1. Cut down a tree

- Dynamic Trees: 1.16.5-0.10.0-Beta24
- Forge: 36.1.62
- OS: Windows 10 home

**Comment by Harleyoc1** [comment]
Do you have a seasons mod installed?

**Comment by Pikamochzo** [comment]
Do Serene Seasons affect seed dropping?

**Comment by Harleyoc1** [comment]
Yes it does. Please refer to [this spreadsheet](https://docs.google.com/spreadsheets/d/17RDJ3T5ZPWuHy1_XVmu3MB-J1JHbGG-QjAuuRkEn2vI/edit#gid=0) for information on how seasons affect dynamic trees. 

You can turn this off in the config under the integration category if you wish.

**Comment by TeiBri** [comment]
> Yes it does. Please refer to [this spreadsheet](https://docs.google.com/spreadsheets/d/17RDJ3T5ZPWuHy1_XVmu3MB-J1JHbGG-QjAuuRkEn2vI/edit#gid=0) for information on how seasons affect dynamic trees.
> 
> You can turn this off in the config under the integration category if you wish.

please. Where is config???? It isnt in config folder in.minecraft so WHERE IS IT? I see only common.toml with some text and client.toml where is nothing. Im using 1.16.5 so please help me.

**Comment by Harleyoc1** [comment]
@TeiBri 
Most of DT's config options (including this one) is in the server config. Forge's server configs are admittedly a little unintuitive at first, so here is where to find them: 

Singleplayer: `saves/[world]/serverconfig/dynamictrees-server.toml`
Dedicated: `[world]/serverconfig/dynamictrees-server.toml` relative to the server folder

**Comment by TeiBri** [comment]
> @TeiBri Most of DT's config options (including this one) is in the server config. Forge's server configs are admittedly a little unintuitive at first, so here is where to find them:
> 
> Singleplayer: `saves/[world]/serverconfig/dynamictrees-server.toml` Dedicated: `[world]/serverconfig/dynamictrees-server.toml` relative to the server folder

OMG!!!!!!! Thank you so much!!!!! You are amazing!!!! TYSM <3
