### ISSUE TITLE
Cocoa Tree Species

### ISSUE THREAD

**Issue by Pikamochzo** [ferreusveritas/Dynamic-Trees#609]
Since jungle tree is actually cocoa tree, why is it grown from "jungle pod"?

In my opinion, jungle trees should be grown from cocoa beans.

Maybe, it would have to be germinated in some ways, to prevent unwanted planting.

**Comment by Harleyoc1** [comment]
Thanks for the suggestion! 

We're actually planning on separating the Jungle species out into itself (without cocoa) and a new cocoa species, like how the apple trees are a species of oak trees. I'll keep this thread open for discussion of such a change.

**Comment by supermassimo** [comment]
Done
