### ISSUE TITLE
growing corals

### ISSUE THREAD

**Issue by Pikamochzo** [ferreusveritas/Dynamic-Trees#610]
In minecraft, coral blocks are nonrenewable, while in normal life they do grow.

In my opinion, they should be growable like in dynamic trees/dynamic trees plus.

Maybe, to propagate them, you would have to pick up some polyps/cuttings, and to make them hard to obtain, maybe instead of needing silk touch pickaxe, they would must be in just right conditions to grow (or rather not die), like 13+ light level or being planted on sand.
It's difficult to say how would growing corals look like. I mean, tube, brain, bubble, fire and horn corals look differently. In my opinion, tube corals would grow up hollow inside, brain corals would be short, but really thick with really small polyps, bubble corals would be similar to brain corals, but with much more visible polyps, fire corals would be really branched in a vertical plane (y and z) and thin, almost like sea fans, and horn corals would be less branched than fire corals, but much thicker than them and branched in all directions.

**Comment by Harleyoc1** [comment]
These are not trees and therefore out of scope for DT. Please re-open this on the [DT+ tracker](https://github.com/supermassimo/DynamicTreesPlus/issues) as it doesn't belong here.
