### ISSUE TITLE
Crash with Hardcore item stages 

### ISSUE THREAD

**Issue by pibblepower** [ferreusveritas/Dynamic-Trees#611]
When I load the latest version of the mod (I tried downgrading, same results) with hardcore item stages (and the required parent mods) the game crashes on startup. This is only with hardcore item stages, the rest of the aforementioned parent mods load fine with dynamic trees. to reproduce the issue, load the game with the minimum required mods as detailed in the crash report.
[crash-2021-08-12_17.33.40-client.txt](https://github.com/ferreusveritas/DynamicTrees/files/6978731/crash-2021-08-12_17.33.40-client.txt)

**Comment by Harleyoc1** [comment]
I can't see how we are directly causing this from first glance. I suggest you open it in their issue tracker too.
