### ISSUE TITLE
leaves dont sway

### ISSUE THREAD

**Issue by legobatmanza** [ferreusveritas/Dynamic-Trees#615]
**Description**
leaves don't sway in the wind with shaders on

**To Reproduce**
Steps to reproduce the behavior: put on any shaders and look at one of the trees and you can see it doesn't sway
**Screenshots**
![2021-08-20_20 54 48](https://user-images.githubusercontent.com/87773711/130305470-404e8e63-e68e-4962-8322-790b907fb55b.png)

**Rendering Glitches**
I'm using optifine (for the shaders)

**Additional context**
the leaves don't sway like if you put them down yourself they just sit there

**Crashes**
If you are crashing **you must include a crash report**. The aforementioned [rules](#rules) apply when attaching crash reports.

**Mods List**

**Versions**

- Dynamic Trees: beta 24
- Forge: 36.2.2
- OS: windows 11

**Comment by Harleyoc1** [comment]
OptiFine doesn't allow for for us to do this. There's simply nothing we can do. You need to see how it's done for the shader pack you're using an add the leaves blocks from Dynamic Trees manually (same reg name as the vanilla ones but with namespace `dynamictrees`).
