### ISSUE TITLE
Trunk shells aren't destroyed properly when cutting down a tree on a server

### ISSUE THREAD

**Issue by Wilevar** [ferreusveritas/Dynamic-Trees#616]
**Description**
Blocks occupied by large trees leave data in the resulting "air" blocks, that prevents the placement of certain multi-block objects, like doors. When attempting to do so, the client crashes and we get the below crash report.

This seems to mainly be the case with the outer edges of a 3x3 tree. The dead center and occasionally some spots are fine. See screenshot.

**To Reproduce**
Chop down a large tree, try to place a door where it stood. This is happening on a server world, haven't yet tested it in single player.

**Screenshots**
[Amulet Map Editor Screenshot (Imgur)](https://imgur.com/Eex5QjO)
[In-Game Screenshot (Same Area) ](https://i.imgur.com/6yQZGOg.png)
In the linked image, you'll see a number of "Missing Texture" objects that are hollow 3x3 pillars near a pond. All of the Dark Oak trees on that level were chopped down (See reference image from in-game). Trees that hadn't grown to more than 1 block width didn't leave any residual data.

**Additional context**
First noticed on DynamicTrees-1.16.5-0.10.0-Beta18, updating to Beta24 did not remove the issue. Placing normal blocks in these spaces that take up one block each doesn't seem to be any issue. Likely restricted to blocks/entities that take up multiple spaces. I don't know that it matters, but tree falling animation is turned off.

**Crashes**
[Pastebin Crash Report](https://pastebin.com/cF6RWHUW)

**Versions**
Include relevant versions below. If this issue relates to add-ons then include their versions too.

- Dynamic Trees: DynamicTrees-1.16.5-0.10.0-Beta18 & Beta24
- Forge: 1.16.5-forge-36.2.0
- OS: Windows 10 Home 21H1

**Comment by Harleyoc1** [comment]
Odd.. Seems it's failing to clean up the trunk shell blocks (the outer blocks of a thick tree).

**Comment by Harleyoc1** [comment]
How are you destroying the tree? (just making sure this isn't a tool from another mod messing with things)

**Comment by Wilevar** [comment]
I've seen the issue both breaking it down with Botania Manasteel axe, Silent gear hatchet, and breaking it down in creative mode with an empty hand.

I don't have tree-chopper or the like installed, and I don't _believe_ I have any mods that directly alter the tree chopping itself, but the modlist is in the crash report. Of the mods I can think of that might be affecting trees at all, I have:
- Project MMO (gives experience for breaking down wood/trees), 
- Better Foliage (makes normal logs round, but doesn't change dynamic tree trunks, and adds extra cards to leaves),
- Dynamic Trees BOP, Quark, and Dynamic Trees +,

Additionally, Minecolonies builders and woodcutters see the shells and end up needing to chop them down one block at a time.

I can do some stand-alone testing and add mods back in to see if it's a conflict, server-side only, etc.

**Comment by Wilevar** [comment]
I've tested in Single Player and not been able to reproduce the issue through a few different tests with all the mods I currently have loaded, which is leading me to believe it's a server communication issue.

In single player, I've tested:
- Manasteel Axe, Iron Axe, Silent Gear Hatchet, and an empty hand, both in survival mode and creative.
- Breaking down 3x3 and 1x1 Dark Oak and Giant Fir at the base, leaving 1 block stump, and at the root.
- Up-close, and using extended reach through Project MMO Building level increase.

None of those scenarios have reproduced the issue in single player, so it must be something different between it running SSP and SMP.

**Comment by Harleyoc1** [comment]
That makes a lot more sense as I found it rather shocking that I have never noticed this in the past (I don't test on servers too often; evidently I should).

**Comment by Wilevar** [comment]
I'm going to do some tests on the server to see if I can pinpoint it. The good news is that the shells don't seem to persist indefinitely. Making enough nearby block changes seems to clear them, particularly if you break down/build over the ground the tree was growing from.
