### ISSUE TITLE
Incompatible with AdvancedRocketry

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [ferreusveritas/Dynamic-Trees#62]
https://github.com/zmaster587/AdvancedRocketry/issues/1271

**Comment by ghost** [comment]
This should be fixed in the dev version 0.7.7

**Comment by ErdbeerbaerLP** [comment]
and where is this dev version? i dont find an download link

**Comment by ghost** [comment]
This is the dev version.  On github.  You have to build it yourself or wait.  It's not even alpha yet so it's not gonna be on curseforge.
