### ISSUE TITLE
Standart trees at pre generated area

### ISSUE THREAD

**Issue by KostromDan** [ferreusveritas/Dynamic-Trees#621]
- Dynamic Trees: lastest
- Forge: lastest
- Java:  8 64bit
- OS: win10 64bit
At seed -5975729189679230037 with terraforged in area that generates when world creating no dynamic trees only standart trees.
Demonstration: https://youtu.be/lDvZqRJe_pE

**Comment by Harleyoc1** [comment]
This happens in biomes added by TerraForged. I have an add-on you can download [here](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-terraforged) to fix it.
