### ISSUE TITLE
Cut down trees dont drop seeds

### ISSUE THREAD

**Issue by KorsonKeisyr** [ferreusveritas/Dynamic-Trees#623]
When i cut down trees they dont drop seeds. So i cant replant them...

Im running the latest version of forge for 1.12.2 as of the curse forge launcher

**Comment by KorsonKeisyr** [comment]
Allow me to articulate my issue better.
I just came fron TFC with dynamic trees, and each oak tree i cut down dropped at least AN oak acorn. But usually each tree dropped about half a dozen acorns.

Now im playing vanilla dybamic trees and im lucky TO see AN oak acorn. I cut down nine trees and only got one acorn. That seems a little off, even in unmodded minecraft each oak tree drops at least an sapling.

**Comment by Harleyoc1** [comment]
Please refer to #477 if you are running Serene Seasons.

**Comment by KorsonKeisyr** [comment]
Thank you for assisting me.
