### ISSUE TITLE
Erros al borrar el mod los arboles desaparecen en vez de dejarlos en vanilla

### ISSUE THREAD

**Issue by Alxrl123** [ferreusveritas/Dynamic-Trees#624]
Hola lo que pasa con el mod es que al principio todo funciona bien los arboles caen y sueltan sus ítems, pero al borrar el mod todos los arboles desaparecen en vez de dejarlos en vanilla y eso es un gran problema ya que luego me puedo quedar sin madera y me preocupa eso, si por favor podrían lanzar un parche para que deje de ocurrir eso por favor lo agradecería muchísimo, además estoy usando forge y optifine en la versión 1.16.5 del juego gracias.

**Comment by Harleyoc1** [comment]
There is nothing we can really do about this, especially considering that when you remove the mod our code is no longer running at all. In general removing mods that add blocks is not advised at all. 

If for whatever reason you do have to remove it, an alternative is to use an external tool to replace Dynamic Trees' branches and leaves with the corresponding logs, or to repopulate the chunks with vanilla trees. I can't advise on any such tools but I know that they do exist. 
<br>

No hablo español, así que aquí está la traducción de Google Translate:

No hay nada que realmente podamos hacer con esto, especialmente considerando que cuando elimine el mod, nuestro código ya no está funcionando en absoluto. En general, eliminar los mods que agregan bloques no se recomiendan en absoluto.

Si por alguna razón tiene que eliminarlo, una alternativa es usar una herramienta externa para reemplazar las ramas y hojas de los árboles dinámicos con los registros correspondientes, o para repoblar los trozos con los árboles de vainilla. No puedo avisar sobre ninguna herramienta, pero sé que sí existen.

**Comment by Alxrl123** [comment]
Ok y que herramienta me recomienda usar?

**Comment by Alxrl123** [comment]
Además de otros errores como se ve en esta captura de pantalla: 
![Captura de pantalla (389)](https://user-images.githubusercontent.com/90623569/133321805-f9c844c0-691d-416b-970a-cd72b465710d.png)

**Comment by Alxrl123** [comment]
La sombra marca como si el árbol AUN estuviera ahí y genera turbas hostiles y las capas de nieve flotando es MUY molesto la verdad

**Comment by Harleyoc1** [comment]
Una vez más, Google Translate ha traducido esto, así que mis disculpas si no se puede leer.

Como dije, no puedo recomendar ninguna herramienta ya que yo mismo no he usado ninguna. La eliminación del mod no puede y no será oficialmente compatible.

Te sugeriré que hables con `@Alzurana` sobre nuestro Discord que logró convertir un mundo sin árboles dinámicos, tal vez te puedan ayudar con lo que es esencialmente el efecto opuesto (aunque no hay guarnatees, es posible que no puedan o no quieran ayudar) .

**Comment by Alxrl123** [comment]
Ah ok me podrías pasar su discord? por favor o esta en la pagina de curseforge?
