### ISSUE TITLE
1.12.2 Compatibility with Serene Seasons? Please!

### ISSUE THREAD

**Issue by ghost** [ferreusveritas/Dynamic-Trees#626]
Could we potentially get a Compat option with Serene Seasons 1.12.2? Other crops and things are affected by the seasons, but not Dynamic Trees. Any chance that we could allow players to config whether trees can grow during the winter?

### Ideas

- No tree growth during Winter seasons (or allow customization)

- No Fruit growth (for fruit trees) during Winter seasons (or customized season choices).

**Comment by Harleyoc1** [comment]
We already provide compatibility with Serene Seasons. See [this spreadsheet](https://docs.google.com/spreadsheets/d/17RDJ3T5ZPWuHy1_XVmu3MB-J1JHbGG-QjAuuRkEn2vI/edit#gid=0) for details on which rates are affected and the magnitude of each across the seasons.
