### ISSUE TITLE
After removing this mod and readding it 

### ISSUE THREAD

**Issue by ShabyDaby** [ferreusveritas/Dynamic-Trees#63]
something like that is happening 
![2018-05-02_20 01 54](https://user-images.githubusercontent.com/38922252/39540867-4423522e-4e44-11e8-8467-1bc296e5dc79.png)

**Comment by ghost** [comment]
Are those leaves blocks?
Also.. Forge and Dynamic Trees version number?

**Comment by ShabyDaby** [comment]
Version of mod - DynamicTrees-1.12.2-0.7.6
Version of Forge - 1.12.2-forge1.12.2-14.23.3.2669

It does leaves a holes in ground where a roots was

**Comment by ghost** [comment]
Thanks for the version information.  The holes in the ground are to be expected if you remove the mod.  But those blocks in the sky are what concern me.  What are they?

**Comment by ShabyDaby** [comment]
![2018-05-03_23 49 10](https://user-images.githubusercontent.com/38922252/39604480-a485901c-4f2c-11e8-91b9-3c15432b57c5.png)

**Comment by ghost** [comment]
I can't understand what you're trying to communicate to me.  You're not answering my question.

**Comment by ShabyDaby** [comment]
oh, those blocks on the sky are the branches(Dynamic Spruce Tree) left after readding mod they are on every single place where dynamic tree was under hole where roots was

**Comment by ghost** [comment]
This does indeed happen.  I have no idea how to resolve this.  My suggestion is to refrain from removing, playing, and re-adding the mod.  This doesn't seem to affect all of the trees in the world, only those that were loaded during the missing mod play.  Even then it's only a small selection of the loaded trees apparently at random.  Though proximity does seems to be a factor.

**Comment by ShabyDaby** [comment]
Actually it was affecting whole world for me but now i have no this map anymore

**Comment by ghost** [comment]
If anyone has any suggestions as to why this is happening I would be very appreciative.

**Comment by madtomic** [comment]
I suggest you to regen your world as you already mess up by adding and removing the mod. There is no solution to clean up or fix what is broken.

**Comment by ghost** [comment]
I meant suggestions to prevent it.  Your suggestion is like curing the disease by killing the patient.

**Comment by madtomic** [comment]
No, my suggestion is don’t get sick in the first place. Like, don’t use the mod at all if you plan to remove it afterward and readding. Expects weird things to happen.

**Comment by Deshiba** [comment]
@madtomic That's not a real solution to the problem. The problem is that this shouldn't be happening. Avoiding the situation is not a solution.

**Comment by naqaden** [comment]
In case this wasn't already observed - this bug doesn't just bring branch nodes back. For me it brought back all the leaves and the DT soil right where they used to be. Forge doesn't replace missing mod blocks with air, but with dummy blocks which are functionally air while retaining their old IDs.

In my experience, after reloading a mod that has been previously removed, it will get all new registry IDs, leaving dummy IDs alone. I think DT is getting all its original IDs back, but the blocks are missing their old data so we get these weird 'skeletons' of former trees.
