### ISSUE TITLE
generateDirtBucketRecipes config setting not respected at first

### ISSUE THREAD

**Issue by copygirl** [ferreusveritas/Dynamic-Trees#630]
### Description
When setting `generateDirtBucketRecipes` to `false`, the setting is ignored until `/reload` is run once. I have a hunch that the world config is loaded only after the recipes are already registered.

### To Reproduce
- Create a new instance with Forge and DT
- Create the config file for DT in `defaultconfigs`
- Set `generateDirtBucketRecipes` to `false`
- Start game, generate new world.
- Dirt bucket recipes are enabled (see screenshot)
- Type `/reload`
- Dirt bucket recipes are correctly disabled
- When rejoining the world, they are again enabled
- Restarting the game does not change behavior

### Screenshots
![image](https://user-images.githubusercontent.com/272586/135731892-a8eaa2e0-66db-44a1-b39c-86406aae31ae.png)

### Mods List
[25 mods](https://gist.github.com/copygirl/5a8421902d73ab0d1efa4f0aa9079754)
The modpack is also on [GitHub](https://github.com/copygirl/slime-skies).
(Also reproducible with just DT.)

### Versions
- Dynamic Trees: `1.16.5-0.10.0-Beta24`
- Forge: `36.2.2`
- Java: `1.8.0_292`
- OS: `Arch Linux`

**Comment by Harleyoc1** [comment]
> When setting `generateDirtBucketRecipes` to `false`, the setting is ignored until `/reload` is run once. I have a hunch that the world config is loaded only after the recipes are already registered.

Yeah. The world config is probably not loaded until after datapack loading. I've come up with two potential solutions: 

1. Put the option in the common config. Downside is that you can no longer enable/disable them per world. 
2. Put the option in both the common and server config. Use the common config when server config has not loaded yet (assuming that is possible with config interfaces provided by Forge).  

Which do you think is the best solution for your use-case? I can't see a real use for this option outside of changing recipes in bulk for a modpack, so perhaps the former is sufficient.

**Comment by copygirl** [comment]
I find the per-world config more annoying than useful.

As a modpack creator, it creates more headache than necessary. First of all the settings are in an odd place, only generated when you create a world. Then, say you find an issue with a config setting that can cause the game to crash. When you fix it, you have no way of updating the already-created per-world server config - at least not without the use of a mod.

Per-world config could perhaps be done with gamerules? That would at least work for simple options. Not sure if gamerules are available before the recipes are loaded either, though. I would definitely not put the setting in two places, with one only loaded in specific circumstances.

**Comment by Harleyoc1** [comment]
Yeah. That was meant as more of a workaround solution in case anyone was adamant about having per-world configs, but I guess it doesn’t really solve that problem for per-world configs anyway thinking on it again. I’ll go ahead with the first solution.

**Comment by copygirl** [comment]
Interestingly enough, the inability to change this setting basically causes my modpack to crash when I removed all the recipes from the game using KubeJS. I had to build a custom version of Dynamic Trees which moved it over to common config.

**Comment by Harleyoc1** [comment]
OK. Apologies for my lack of promptness on such a simple change, I've just been busy recently. Feel free to submit a PR for it if you'd like.
