### ISSUE TITLE
Dynamic trees crash with optifine 1.16.5

### ISSUE THREAD

**Issue by superwizzman** [ferreusveritas/Dynamic-Trees#631]
Hi, I just added dynamic trees and when I load a new shader, or putting no shaders my game crash and when i remove dynamic trees it doesn't happend. I found it had some problem in the crash log.

Crash log: https://gist.github.com/Harleyoc1/60546cab02671a2a2bfb26ce7aa7fd3e

**Comment by dkmk100** [comment]
this si still an issue, happened to me yesterday.

**Comment by Harleyoc1** [comment]
Moved to supermassimo/DynamicTreesPlus#8 as this issue seems to be caused by the cactus branch models.
