### ISSUE TITLE
The standard minecraft biomes have a mix of dynamic trees and normal trees in my pack

### ISSUE THREAD

**Issue by Mr-Syntax** [ferreusveritas/Dynamic-Trees#632]
if you download this pack https://www.curseforge.com/minecraft/modpacks/chosencraft

and go to a biome like the dark forest, not all trees will be dynamic trees :-/

**Comment by Harleyoc1** [comment]
This is a mod compatibility issue. Not a lot we can do without knowing what mod is causing it. Unfortunately your best bet is to attempt to guess which is causing it or go through all of them (most ideally in a smart way such as by splitting the mod list in half, testing, and so on).

**Comment by Harleyoc1** [comment]
Once you do find out what is causing it please do share it here. It's possible whichever mod is causing it allows it to be turned off in the config; if not though then it will need to be diverted to #443 (or you can potentially use our Json systems to cancel the features).

**Comment by Mr-Syntax** [comment]
okay fair enough, i have this other issue in the same pack tho.

if you use that pack and go to an illager for from illagers+ then there will sometimes be branches hanging from the air that were suppose to be removed but didnt get

**Comment by Mr-Syntax** [comment]
will post if i find the mod incompability on the other one tho
