### ISSUE TITLE
Cacti rendering as at floating unconnected blocks until hit, then revert to connected objects

### ISSUE THREAD

**Issue by Morabert** [ferreusveritas/Dynamic-Trees#633]
Started Doing This after I installed Obfuscate, is doing it even after I took it out
![2021-10-24_03 43 51](https://user-images.githubusercontent.com/36409264/138576821-fa7e1165-e1c1-4d94-8548-8d7b192ca2a8.png)
![2021-10-24_03 44 41](https://user-images.githubusercontent.com/36409264/138576822-3c8ee72b-226d-4c02-9c5e-63b55739b703.png)

![Da List](https://user-images.githubusercontent.com/36409264/138576825-8807bc0e-f696-4845-b640-7596778ba634.JPG)

- Dynamic Trees: DT, DT BoP & DT +
- Forge: 1.16.5
- Java: JDK 17
- OS: Win 10

**Comment by Harleyoc1** [comment]
Has been reported multiple times on DT+ repo (supermassimo/DynamicTreesPlus#6, supermassimo/DynamicTreesPlus#1). All are an incompatibility with Sodium Reforged.
