### ISSUE TITLE
Tried to create a EntityFallingTree with no branch blocks [crash]

### ISSUE THREAD

**Issue by SheepPeepMeep** [ferreusveritas/Dynamic-Trees#634]
**Description:**
This issue has only occurred recently and spams the console and eventually crashes multiple times a day (snippet link below). The server has been running this world since 10/16 and started getting this crash about a week ago. Supposedly it might be from a tree without branches trying to fall. No other mod seem responsible since it ran perfectly fine in single player and before the crash started.
https://gist.github.com/SheepPeepMeep/017f035a52831bfae749e1775f77fc7d

Also since the start of the server, we had issues with Pam's Harvest redbud and spooky tree crashing the server. Client side, this did not happen while on the server, we had to remove these two mods to even get the server to boot. I'm not sure if this would affect the crash stated above.

**To Reproduce:**
Unsure other than it only crashes on the server and not on single player or LAN.

**Crash Report:**
https://gist.github.com/SheepPeepMeep/9e8d412f8051b5b7c98c17db2b90d2f7

**Versions:**
- DynamicTrees-1.12.2-0.9.25
- DynamicTreesPHC-1.12.2-2.0.5
- DynamicTreesPamTrees-1.12.2-1.0.5
- PamsRedbudTree1.12.2b (client only)
- Pam's Spooky Tree 1.12.2a (client only)
- Forge: 14.23.5.2855
- Java: 1.8.0_271
- OS: Linux (amd64) version 4.15.0-136-generic

**Comment by Harleyoc1** [comment]
My best guess is that another mod is, somehow and for some reason, forcibly removing the branch blocks before the "future break" system has a chance to do it properly. Is there some particular modded tool you or your players might be using to cut down trees or something?
