### ISSUE TITLE
Leaves implementation unrecognizable as item by crafttweaker, and ex nihilo sequentia.

### ISSUE THREAD

**Issue by malice936** [ferreusveritas/Dynamic-Trees#635]
**Description**
As the title says the leaves of all dynamic trees from vanilla to modded in 1.16.5, presumably across all versions do not have an item implementation, which is causing issues when attempting to add crook recipes as well as potentially other issues.

**To Reproduce**
Install the mod, and attempt to use "/give playername dynamictrees:oak_leaves"

**Versions**
Include relevant versions below. If this issue relates to add-ons then include their versions too.

- Dynamic Trees: 0.10.0-Beta25
- Forge: 36.2.8
- Java: 1.8.0_301
- OS: Windows 10

**Comment by Harleyoc1** [comment]
An item should not be necessary for the leaves, they're only meant as a stand-in block for dynamic tree "multi blocks". Surely recipes like the crook using blocks should require a block name, not an item name?
