### ISSUE TITLE
Leaves Decaying and Re-appearing

### ISSUE THREAD

**Issue by madartist0** [ferreusveritas/Dynamic-Trees#637]
Im not sure if this is a glitch, because I don't know if it's intended behavior or not: https://youtu.be/MUCwqNZIlP0 I dont know how to explain it, but here's a quick video of what it looks like (with the random tick speed turned up to 3000)

Here's the mod list I'm using:
  [✔️] abnormals_core-1.16.5-3.3.0
  [✔️] AI-Improvements-1.16.2-0.3.0
  [✔️] alexsmobs-1.12.1
  [✔️] AmbientSounds_v3.1.9_mc1.16.5
  [✔️] appleskin-forge-mc1.16.x-2.1.0
  [✔️] AutoRegLib-1.6-49 (1)
  [✔️] BetterDungeons-1.16.4-1.2.1
  [✔️] betterendforge-1.16.5-1.6.3
  [✔️] BetterStrongholds-1.16.4-1.2.1
  [✔️] BiomesOPlenty-1.16.5-13.1.0.482-universal
  [✔️] catalogue-1.3.0-1.16.5
  [✔️] citadel-1.8.1-1.16.5 (1)
  [✔️] Clumps-6.0.0.27
  [✔️] configured-1.2.0-1.16.3
  [✔️] create-mc1.16.5_v0.3.2f
  [✔️] CreativeCore_v2.2.1_mc1.16.5
  [✔️] DynamicTrees-1.16.5-0.10.0-Beta25
  [✔️] DynamicTreesBOP-1.16.5-2.0.6
  [✔️] DynamicTreesPlus-1.16.5-0.1.0-Beta10
  [✔️] DynamicTreesQuark-1.16.5-2.1.0
  [✔️] DynamicTreesTerraForged-1.16.5-1.0.0
  [✔️] endergetic-1.16.4-3.0.0 (1)
  [✔️] entityculling-1.3.0
  [✔️] extcaves-2.4
  [✔️] FarmersDelight-1.16.5-0.5.0
  [✔️] FastSuite-1.16.4-1.1.1
  [✔️] ferritecore-2.1.0-forge
  [✔️] flywheel-1.16-0.2.4
  [✔️] Hwyla-forge-1.10.11-B78_1.16.2
  [✔️] infernal-expansion-2.3.2
  [✔️] jei-1.16.5-7.7.1.126
  [✔️] lazydfu-0.1.3
  [✔️] nethers_delight-2.1
  [✔️] OptiFine_1.16.5_HD_U_G8
  [✔️] Patchouli-1.16.4-53.2 (1)
  [✔️] Placebo-1.16.5-4.6.0
  [✔️] Quark-r2.4-319
  [✔️] RawOre
  [✔️] shutupexperimentalsettings-1.0.3
  [✔️] steampowered-1.16.5-1.1.7b
  [✔️] TerraForged-1.16.5-0.2.13
  [✔️] unnamedanimalmod-1.0.2
  [✔️] untamedwilds-1.16.5-1.4.1
  [✔️] YungsApi-1.16.4-Forge-13

**Comment by Harleyoc1** [comment]
This is not a glitch it's just a consequence of how the cellular automata stuff works. The decaying/reappearing isn't harmful or noticeable under normal circumstances.

**Comment by madartist0** [comment]
Thank you for the reply, like I said I didn't know if this was intentional. It is, however, very noticeable under "normal circumstances (RTS=3)", thats why I opened this thread. I noticed it and to demonstrate it for the video I turned up the RTS.

> This is not a glitch it's just a consequence of how the cellular automata stuff works. The decaying/reappearing isn't harmful or noticeable under normal circumstances.
