### ISSUE TITLE
[1.12.2]  PizzaCraft, Growthcraft CE and Fossils and Archeology Revival compat 

### ISSUE THREAD

**Issue by aks746** [ferreusveritas/Dynamic-Trees#641]
Hello! It would be great to see addons for [PizzaCraft](https://www.curseforge.com/minecraft/mc-mods/pizzacraft) (olive trees), [Growthcraft CE](https://www.curseforge.com/minecraft/mc-mods/growthcraft-community-edition) (apple tree) and [Fossils and Archeology Revival](https://www.curseforge.com/minecraft/mc-mods/fossils) (calamites, palaeoraphe tree). I hope you find time for this someday. And thanks for the wonderful mod!

**Comment by Harleyoc1** [comment]
#443
