### ISSUE TITLE
Disable/Change the TreeChop mechanic

### ISSUE THREAD

**Issue by Verayon** [ferreusveritas/Dynamic-Trees#642]
It is possible to disable only the tree chop mechanic?

i like this mod because of the appearance of the trees but i would wanna use other mod for change the way the tree fall

**Comment by Harleyoc1** [comment]
Yes, you can disable falling trees in the config (server config in 1.16+). Keep in mind other mods that change the way that tree falls may not work with DT; it's up to them to add support if necessary.
