### ISSUE TITLE
crash apon boot

### ISSUE THREAD

**Issue by Ai-Kiwi** [ferreusveritas/Dynamic-Trees#648]
**Description**
whenever I try to boot my server it crash's. 

**To Reproduce**
I'm not really sure I guess copy my mods?

**Screenshots**

**Rendering Glitches**
sodium (magnesium port)

**Additional context**

**Crashes**
[debug.log](https://github.com/DynamicTreesTeam/DynamicTrees/files/7866680/debug.log)
[latest.log](https://github.com/DynamicTreesTeam/DynamicTrees/files/7866681/latest.log)

**Mods List**
https://pastebin.com/aLdyCaSv

**Versions**
- Dynamic Trees: DynamicTrees-1.16.5-0.10.0-Beta27
- Forge: forge-1.16.5-36.2.20
- Java: jdk-11.0.13
- OS: windows 10 (19043.1466)

**Comment by Hemlock32** [comment]
Last update caused this same problem for me. Can't launch my private server at all now.

**Comment by Corbi** [comment]
Same here.

**Comment by Harleyoc1** [comment]
Hmm, seems to be calling a client only method. Weird thing is that we always called this, including on the version before latest. Nothing changed there. Not sure why it worked before.

**Comment by Harleyoc1** [comment]
Fixed in 8835c25525ba5c70e4f27e0ae20ce0c868a00e81 (was meant to be split into two commits). Beta 28 will be released shortly.
