### ISSUE TITLE
Cascading worldgen lag. [Server Log]

### ISSUE THREAD

**Issue by Elvyria** [ferreusveritas/Dynamic-Trees#65]
Forge: 14.23.3.2655
Mods: Dynamic Trees: 0.7.6 (nothing more)
After launching clear forge server i see this message when i generate world or just fly around: 
"Dynamic Trees loaded a new chunk [x, y] in dimension 0 (overworld) while populating chunk [x±1, y±1], causing cascading worldgen lag. Please report this to the mod's issue tracker"
More info: https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/
![image](https://user-images.githubusercontent.com/2061234/39677207-a55c8540-517f-11e8-81b4-2a0bb14bc671.png)

**Comment by Elvyria** [comment]
Duplicate of Issue #50

**Comment by ghost** [comment]
I'm still working on a fix for this.  I thought I fixed it in the dev version(0.7.7) but it's still happening.  I understand the nature of the problem it's just taking a while to get all of the little generation things to behave.

**Comment by ghost** [comment]
Should be fixed now.  Issues like this are a constant battle.
