### ISSUE TITLE
Support For Additional Mods (1.12.2)

### ISSUE THREAD

**Issue by supermassimo** [ferreusveritas/Dynamic-Trees#652]
To make it easier for everyone, I will be compiling all mod compat suggestions for 1.12.2 on this post going forward.
From now on all 1.12.2 mod support suggestion should go as replies to this post.
For 1.16.5 suggestions, please refer to the [1.16.5 suggestion list](https://github.com/supermassimo/DynamicTrees-ExC/issues/59).
Suggestions from the [discord server](https://discord.gg/83qcpkY) will also be added here.

**Please please please include how many trees a mod adds when suggesting**

> DO NOT suggest the following types of mods as they will not be considered:
>  - OTG mods
>  - Mods without a public source (such as MCreator mods)

Those in **bold** were considered and/or are being worked on.
When a mod is finished and published, it is removed from this list.

The stars are a rough estimate of how likely it is for me (subjectively, anyone is free to pick any!) to choose that mod.
It is based on how popular the mod is, how many trees it has, how unique these are and how interesting I find them.
**0 stars just means i do not know enough about the mod, not that i do not like it**.

- ★★★★☆[**AbyssalCraft**](https://www.curseforge.com/minecraft/mc-mods/abyssalcraft) (2 trees)
- ★★☆☆☆[Advent Of Ascension](https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine) (20 trees)
- ★★★☆☆[**Aether II**](https://www.curseforge.com/minecraft/mc-mods/the-aether-ii) (11 trees)
- ★☆☆☆☆[Ice and Fire](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons) (1 log)
- ★★★☆☆[Environs](https://www.curseforge.com/minecraft/mc-mods/environs) (8 trees)
- ★★★★☆[Redwoods](https://www.curseforge.com/minecraft/mc-mods/redwoods) (1 tree)
- ★☆☆☆☆[Wild Nature](https://www.curseforge.com/minecraft/mc-mods/wildnature) (a bjillion trees)
- ★☆☆☆☆[Binnie's Trees](https://www.curseforge.com/minecraft/mc-mods/binnies-mods) (a bjillion trees)
- ★★★☆☆[Better with Addons](https://www.curseforge.com/minecraft/mc-mods/better-with-addons) (3 trees)
- ★★★☆☆[Fossils and Archeology](https://www.curseforge.com/minecraft/mc-mods/fossils) (4 trees)
- ★★☆☆☆[Simply Tea](https://www.curseforge.com/minecraft/mc-mods/simply-tea) (1 tree)
- ★★☆☆☆[Divine RPG](https://www.curseforge.com/minecraft/mc-mods/official-divinerpg) (11 trees)
- ★★☆☆☆[Novam Terram](https://www.curseforge.com/minecraft/mc-mods/novam-terram) (59 trees)
- ☆☆☆☆☆[Auxiliary Biomes](https://www.curseforge.com/minecraft/mc-mods/auxiliary-biomes) (2 biomes)
- ☆☆☆☆☆[Wizardry Mod](https://www.curseforge.com/minecraft/mc-mods/wizardry-mod) (1 tree)
- ☆☆☆☆☆[Gaia Dimension](https://www.curseforge.com/minecraft/mc-mods/gaia-dimension) (9 trees)
- ★★★★☆[Project Vibrant Journeys](https://www.curseforge.com/minecraft/mc-mods/project-vibrant-journeys) (16 trees)
- ★★★☆☆[Spooky Biomes](https://www.curseforge.com/minecraft/mc-mods/spooky-biomes) (4 trees)
- ★★★☆☆[Primal Core](https://www.curseforge.com/minecraft/mc-mods/primalcore) (3 trees)
- ★★★☆☆[**The Erebus**](https://www.curseforge.com/minecraft/mc-mods/primalcore) (8 trees)
- ☆☆☆☆☆[Calculator](https://www.curseforge.com/minecraft/mc-mods/calculator) (4 trees)
- ★★★☆☆[The Aurorian](https://www.curseforge.com/minecraft/mc-mods/the-aurorian) (2 trees)
- ★☆☆☆☆[Stygan End](https://www.curseforge.com/minecraft/mc-mods/stygian-end-biome-expansion) (1 tree)
- ★☆☆☆☆[Rainbow Oak Trees](https://www.curseforge.com/minecraft/mc-mods/rainbow-oak-trees) (1 tree)
- ☆☆☆☆☆[Growthcraft](https://www.curseforge.com/minecraft/mc-mods/growthcraft-community-edition) (3 trees)
- ☆☆☆☆☆[Mo' Creatures](https://www.curseforge.com/minecraft/mc-mods/mo-creatures) (2 trees)
- ☆☆☆☆☆[More Biomes XL](https://www.curseforge.com/minecraft/mc-mods/morebiomesxl) (3 trees)
- ☆☆☆☆☆[The Midnight](https://www.curseforge.com/minecraft/mc-mods/the-midnight) (5 trees)
- ☆☆☆☆☆[Chinjunfu](https://www.curseforge.com/minecraft/mc-mods/chinjufumod) (4 trees)
- ★★★☆☆[Biodiversity Hotspot](https://www.curseforge.com/minecraft/mc-mods/ani-mod-biodiversity-hotspot) (1 tree)
- ★★★★☆[Tropicraft](https://www.curseforge.com/minecraft/mc-mods/tropicraft) (6 trees)
- ☆☆☆☆☆[Glacidus](https://www.curseforge.com/minecraft/mc-mods/glacidus) (2 trees)
- ★★☆☆☆[Blue Skies](https://www.curseforge.com/minecraft/mc-mods/blue-skies) (4 trees)
- ☆☆☆☆☆[Journey into the Light](https://www.curseforge.com/minecraft/mc-mods/journey-into-the-light-mod) (13 trees)
- ★★☆☆☆[Warriors Path](https://www.curseforge.com/minecraft/mc-mods/warriors-path) (2 trees)
- ★★★★★[Misty World](https://www.curseforge.com/minecraft/mc-mods/misty-world) (13 trees)
- ★★★★☆[Beasts](https://www.curseforge.com/minecraft/mc-mods/beasts) (1 tree)
- ★★★☆☆[Tofucraft](https://www.curseforge.com/minecraft/mc-mods/tofucraftreload) (2 trees)
- ☆☆☆☆☆[Prodigy Tech](https://www.curseforge.com/minecraft/mc-mods/prodigy-tech) (1 tree)
- ★★★★☆[Zoesteria](https://www.curseforge.com/minecraft/mc-mods/zoesteria) (8 trees)
- ☆☆☆☆☆[Explorercraft](https://www.curseforge.com/minecraft/mc-mods/explorercraft-worldexpansion) (5 trees)
- ☆☆☆☆☆[Natural Pledge](https://www.curseforge.com/minecraft/mc-mods/natural-pledge) (28 trees)
- ☆☆☆☆☆[The Creeping Nether](https://www.curseforge.com/minecraft/mc-mods/the-creeping-nether) (1 tree)
- ☆☆☆☆☆[Dartcraft](https://www.curseforge.com/minecraft/mc-mods/dartcraft-reloaded) (1 tree)
- ★☆☆☆☆[Oh The Biomes You'll Go](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)  (45 trees)
- ☆☆☆☆☆[Prehistoric Trees](https://www.curseforge.com/minecraft/mc-mods/prehistoric-trees) (8 trees)
- ☆☆☆☆☆[Greg Tech Community Edition](https://www.curseforge.com/minecraft/mc-mods/gregtechce) (1 tree)
- ★★★☆☆[Nethercraft Classic](https://www.curseforge.com/minecraft/mc-mods/nethercraft-classic) (1 tree)
- ☆☆☆☆☆[Tirphycraft](https://www.curseforge.com/minecraft/mc-mods/tirphycraft) (3 trees)
- ☆☆☆☆☆[Pokecube AIO](https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi) (12 trees)
- ★★★★☆[Terraqueous](https://www.curseforge.com/minecraft/mc-mods/terraqueous) (10 trees)
- ★★★★☆[EvilCraft](https://www.curseforge.com/minecraft/mc-mods/evilcraft) (1 tree)
- ★★★★☆[Douglas Forest](https://www.curseforge.com/minecraft/mc-mods/douglas-forest) (3 trees)
- ★★☆☆☆[Apricon Trees](https://www.curseforge.com/minecraft/mc-mods/apricorn-tree-farm)
- ★★★★☆[Ancient Spellcraft](https://www.curseforge.com/minecraft/mc-mods/ancient-spellcraft) (1 tree)
- ☆☆☆☆☆[Kathairis](https://www.curseforge.com/minecraft/mc-mods/beta-kathairis) (many trees)
- ★★★☆☆[Wasteland Reborn](https://www.curseforge.com/minecraft/mc-mods/wasteland-reborn) (1 tree)
- ☆☆☆☆☆[Jurassic World Reborn](https://www.curseforge.com/minecraft/mc-mods/jurassic-world-reborn-mod) (5 trees)
- ☆☆☆☆☆[Immersive intelligence](https://www.curseforge.com/minecraft/mc-mods/immersive-intelligence) (1 tree)
- ☆☆☆☆☆[Potato Power Craft](https://www.curseforge.com/minecraft/mc-mods/potato-power-craft) (1 tree, 1 dimension)
- ☆☆☆☆☆[Into the Maelstorm](https://www.curseforge.com/minecraft/mc-mods/into-the-maelstrom) (3 trees)
- ☆☆☆☆☆[Scape and Run: Parasites](https://www.curseforge.com/minecraft/mc-mods/scape-and-run-parasites) (1 tree, 3 variants)
- ☆☆☆☆☆[Rusticated Fruit](https://www.curseforge.com/minecraft/mc-mods/rusticated-fruit) (3 trees)

If you continuously suggest mods that are already in the list multiple times, you will be blocked from participating in this discussion.

**Comment by joe-vettek** [comment]
https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-for-sakura

**Comment by braypanda** [comment]
I was wondering if it would be possible for you to make a compat with Primal Core. It adds 2 trees, and it has a cool mechanic where you can strip bark off trees. Idk how hard it would be to make the strip part, or if it’s important for anyone else. So if not, that’s cool. Thanks!

**Comment by mewj** [comment]
https://www.curseforge.com/minecraft/mc-mods/rusticated-fruit

Planting the tree seeds from this mod grows normal trees instead of dynamic ones. I tried fixing this issue by changing the recipe output using CraftTweaker but it doesn't appear to be compatible, even though the mod it's dependent on, Rustic, is.

**Comment by LUEZIS** [comment]
Mod suggestion: Rusticated Fruit (Rustic addon)
https://www.curseforge.com/minecraft/mc-mods/rusticated-fruit
3 trees included:
- peach tree
![image](https://user-images.githubusercontent.com/40040593/167411060-6479bf30-ffd4-4785-adcd-ccef2591993d.png)
- persimmon tree
![image](https://user-images.githubusercontent.com/40040593/167411090-40b72420-4aa3-494b-b675-0df89061969c.png)
- pear tree
![image](https://user-images.githubusercontent.com/40040593/167411126-55760ac3-cc04-4510-91cc-ffade7eae460.png)
The mod is compatible with BoP fruit types.

**Comment by stealthusk** [comment]
Dynamic Trees for Oh The Biomes You'll Go for 1.12.2?
https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/all?filter-game-version=2020709689%3A6756

Please?

**Comment by stealthusk** [comment]
Dynamic Trees for Recurrent Complex Trees? (I think not possible)
https://www.curseforge.com/minecraft/mc-mods/recurrent-complex

**Comment by Harleyoc1** [comment]
> Dynamic Trees for Oh The Biomes You'll Go for 1.12.2? https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/all?filter-game-version=2020709689%3A6756
> 
> Please?

BYG in 1.12 was never truly finished and known to be very buggy. Aside from that it is too much work when not many people actually play it in that version. As such we have no plans for a back port.

**Comment by Harleyoc1** [comment]
> Dynamic Trees for Recurrent Complex Trees? (I think not possible)
> https://www.curseforge.com/minecraft/mc-mods/recurrent-complex

There isn't really much need for this. The tree structures it adds can be disabled in their config.

**Comment by Joshua444454** [comment]
Add support for Project:Vibrant Journeys

**Comment by Lonelyxiya** [comment]
How do I disable Swamp Oak and Blossoming spawning in the Quark configuration?
