### ISSUE TITLE
Support for Additional Mods (1.16.5)

### ISSUE THREAD

**Issue by supermassimo** [ferreusveritas/Dynamic-Trees#653]
With Dynamic Trees for 1.16 being released, the door to 1.16 mod compatibility opens.
Following the same rules as the [1.12 suggestion list](https://github.com/supermassimo/DynamicTrees-ExC/issues/41), comment under this post 1.16 mods that could have Dynamic Trees compatibility.
Suggestions from the [discord server](https://discord.gg/83qcpkY) will also be added here.

**Please please please include how many trees a mod adds when suggesting**

> DO NOT suggest the following types of mods as they will not be considered:
>  - Mods without a public source (such as MCreator mods)

Those in **bold** were considered and/or are being worked on.
When a mod is finished and published, it is removed from this list.

The stars are a rough estimate of how likely it is for me (subjectively, anyone is free to pick any!) to choose that mod.
It is based on how popular the mod is, how many trees it has, how unique these are and how interesting I find them.
**0 stars just means i do not know enough about the mod, not that i do not like it**.

**Update from 1.12:** (add-ons from 1.12 that have yet to be updated)
- **★★★★★[Integrated Dynamics](https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics) (1 tree)**
- **★★★★★[Mystical World](https://www.curseforge.com/minecraft/mc-mods/mystical-world) (1 tree)**
- ★★★★☆[Tech Reborn](https://www.curseforge.com/minecraft/mc-mods/techreborn) (1 tree)
- **★★★★★[Pam’s HarvestCraft 2](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-trees) (49 trees)**
- ★★★★★[The Twilight Forest](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest) (8 trees)
- ★★★★★[The Aether](https://www.curseforge.com/minecraft/mc-mods/the-aether) (3 trees)
- **★★★★★[Tinker's Construct](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct) (3 trees)**
- ★★★★☆[Fruit Trees (port of Cuisine)](https://www.curseforge.com/minecraft/mc-mods/fruit-trees) (9 trees)
- ★★★★☆[Forestry](https://www.curseforge.com/minecraft/mc-mods/forestry) (35 trees)

**New addons:**
- ★★★★☆[Pokecube AIO](https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi) (17 trees)
- ★★★☆☆[Druidcraft](https://www.curseforge.com/minecraft/mc-mods/druidcraft) (2 trees)
- ★★★☆☆[Ars Nouveau](https://www.curseforge.com/minecraft/mc-mods/ars-nouveau) (4 trees)
- **★★★★☆[Atmospheric](https://www.curseforge.com/minecraft/mc-mods/atmospheric) (6 trees)**
- ★★★★☆[Architect's Palette](https://www.curseforge.com/minecraft/mc-mods/architects-palette) (1 tree)
- ★★★☆☆[Better End Forge](https://www.curseforge.com/minecraft/mc-mods/betterend-forge-port) (7 trees, 1 cactus)
- ★★☆☆☆[Croptopia](https://www.curseforge.com/minecraft/mc-mods/croptopia-fabric) (26 trees)
- ★☆☆☆☆[Simply Tea](https://www.curseforge.com/minecraft/mc-mods/simply-tea) (1 tree)
- ★★☆☆☆[Enhanced Mushrooms](https://www.curseforge.com/minecraft/mc-mods/enhanced-mushrooms) (2 mushrooms)
- ★★★☆☆[Greek Fantasy](https://www.curseforge.com/minecraft/mc-mods/greek-fantasy)  (1 tree)
- ★★☆☆☆[Silent Gear](https://www.curseforge.com/minecraft/mc-mods/silent-gear) (1 tree)
- ★★★☆☆[Rediscovered](https://www.curseforge.com/minecraft/mc-mods/rediscovered) (1 tree)
- ★★★☆☆[Premium Wood](https://www.curseforge.com/minecraft/mc-mods/premium-wood) (7 trees)
- ★★★☆☆[Simple Farming](https://www.curseforge.com/minecraft/mc-mods/simple-farming) (9 trees)
- ★★☆☆☆[Tofucraft](https://www.curseforge.com/minecraft/mc-mods/tofucraftreload) (2 trees)
- ★★★★☆[Terra Incognita](https://www.curseforge.com/minecraft/mc-mods/terraincognita) (2 trees)
- ★★★☆☆[Explorercraft](https://www.curseforge.com/minecraft/mc-mods/explorercraft-worldexpansion) (3 trees)
- **★★★★☆[Environmental](https://www.curseforge.com/minecraft/mc-mods/environmental) (6 trees)**
- ★★★★★[Omni](https://www.curseforge.com/minecraft/mc-mods/omni) (4 biomes, 1 cactus)
- ★★★☆☆[The Endergetic Expansion](https://www.curseforge.com/minecraft/mc-mods/endergetic) (1 tree)
- ★★★★★[Desolation](https://www.curseforge.com/minecraft/mc-mods/desolation-forge) (1 tree)
- ★☆☆☆☆[Ice and Fire](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons) (3 branches)
- ★★★☆☆[Ex Nihilo: Sequentia](https://www.curseforge.com/minecraft/mc-mods/ex-nihilo-sequentia) (1 tree (not yet implemented))
- ★★★★☆[Fruitful](https://www.curseforge.com/minecraft/mc-mods/fruitful) (1 tree)
- ★★★☆☆[Bayou Blues](https://www.curseforge.com/minecraft/mc-mods/bayou-blues) (1 tree)
- ★★★☆☆[Abundance](https://www.curseforge.com/minecraft/mc-mods/abundance) (2 trees)
- ★★★★☆[Better Badlands](https://www.curseforge.com/minecraft/mc-mods/better-badlands) (1 tree, 1 cactus)
- ★★★☆☆[The Outer End](https://www.curseforge.com/minecraft/mc-mods/the-outer-end) (1 tree)
- ★★★☆☆[Outvoted](https://www.curseforge.com/minecraft/mc-mods/outvoted) (2 trees)
- ★★★★☆[Alex's Mobs](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs) (1 tree for missing banana drops)
- ★★☆☆☆[Ultra Amplified Dimension](https://www.curseforge.com/minecraft/mc-mods/ultra-amplified-mod) (1 cactus, dimensional world gen)
- ★★★☆☆[Terra World Generator](https://www.curseforge.com/minecraft/mc-mods/terra-world-generator) (world gen, possibly new species)
- ★★★☆☆[Infernal Expansion](https://www.curseforge.com/minecraft/mc-mods/infernal-expansion) (1 fungus)
- ★★☆☆☆[Caves & Cliffs backport](https://www.curseforge.com/minecraft/mc-mods/caves-and-cliffs-backport) (1 tree)
- ★★☆☆☆[Darker Depths](https://www.curseforge.com/minecraft/mc-mods/darker-depths) (1 tree)
- ★★★★★[Maiden's Marvelous Materials](https://www.curseforge.com/minecraft/mc-mods/maidens-marvelous-materials) (8 trees)
- ★★★☆☆[The Undergarden](https://www.curseforge.com/minecraft/mc-mods/the-undergarden) (2 trees, 1 fungus, 4 mushroom)
- ★★★★☆[Malum](https://www.curseforge.com/minecraft/mc-mods/malum) (1 tree)
- ★★★☆☆[Apple Trees Revived](https://www.curseforge.com/minecraft/mc-mods/apple-trees-revived) (2 trees)
- ★★★☆☆[Treemendous](https://www.curseforge.com/minecraft/mc-mods/treemendous) (25 trees)
- ★☆☆☆☆[Lord of the Rings Mod Renewed](https://www.curseforge.com/minecraft/mc-mods/the-lord-of-the-rings-mod-renewed) (a lot of trees)
- ★★★★☆[Better Default Biomes](https://www.curseforge.com/minecraft/mc-mods/better-default-biomes) (2 trees)
- ★★★☆☆[Occultism](https://www.curseforge.com/minecraft/mc-mods/occultism) (2 trees)
- ★★★★☆[More Minecarts](https://www.curseforge.com/minecraft/mc-mods/more-minecarts) (1 cactus)
- ★☆☆☆☆[Chaos Awakens](https://www.curseforge.com/minecraft/mc-mods/chaos-awakens) (3 trees)
- ★★☆☆☆[Unnamed Animal Mod](https://www.curseforge.com/minecraft/mc-mods/unnamed-animal-mod) (1 tree)
- ★★☆☆☆[Werewolves - Become a Beast!](https://www.curseforge.com/minecraft/mc-mods/werewolves-become-a-beast) (2 trees)
- ★★★★☆[Tropicraft](https://www.curseforge.com/minecraft/mc-mods/tropicraft) (6 trees)
- ★★★★★[Water Source](https://www.curseforge.com/minecraft/mc-mods/water-source) (1 tree)
- ★★★☆☆[Horticulture](https://www.curseforge.com/minecraft/mc-mods/horticulture) (4 trees)
- ★★★★☆[Blue Skies](https://www.curseforge.com/minecraft/mc-mods/blue-skies) (7 trees)
- ★★★★☆[Feywild](https://www.curseforge.com/minecraft/mc-mods/feywild) (4 trees)
- ★★★★☆[Charcoal Pit](https://www.curseforge.com/minecraft/mc-mods/charcoal-pit) (6 trees)
- ★★★☆☆[Advanced Rocketry](https://www.curseforge.com/minecraft/mc-mods/advanced-rocketry) (3 trees)
- ★★☆☆☆[Advent of Ascension](https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine) (29 trees)
- ★★★☆☆[Spheric](https://www.curseforge.com/minecraft/mc-mods/spheric) (3 trees)
- ★★★★☆[Hal's Exploration Mod](https://www.curseforge.com/minecraft/mc-mods/hals-exploration-mod) (1 tree)
- ☆☆☆☆☆[Twist](https://www.curseforge.com/minecraft/mc-mods/twist) (2 trees)
- ☆☆☆☆☆[World of Wonder](https://www.curseforge.com/minecraft/mc-mods/world-of-wonder) (2 trees)
- ☆☆☆☆☆[Terrestria Reforged](https://www.curseforge.com/minecraft/mc-mods/terrestria-reforged) (5 trees, 1 mushroom)
- ☆☆☆☆☆[Better Nether Reforged](https://www.curseforge.com/minecraft/mc-mods/betternether-reforged) (13 trees, 1 cactus)
- ☆☆☆☆☆[Wilder Wilds](https://www.curseforge.com/minecraft/mc-mods/wilder-wilds) (world gen)
- ☆☆☆☆☆[Prehistoric Fauna](https://www.curseforge.com/minecraft/mc-mods/prehistoric-fauna) (7 trees)
- ☆☆☆☆☆[Primal Winter](https://www.curseforge.com/minecraft/mc-mods/primal-winter) (6 trees)
- ☆☆☆☆☆[Project Rankine](https://www.curseforge.com/minecraft/mc-mods/project-rankine) (8 trees)
- ☆☆☆☆☆[Corundum Meadows](https://www.curseforge.com/minecraft/mc-mods/corundum-meadows) (2 trees)
- ☆☆☆☆☆[Dregora](https://www.curseforge.com/minecraft/mc-mods/dregora) (245+ biomes)

**Comment by 4193883-eng** [comment]
Please make compability with Oh the biomes you`ll go

**Comment by slaymisi** [comment]
please more abnormals and aurora support

**Comment by Kabinet0** [comment]
Perhaps the [Betweenlands](https://www.curseforge.com/minecraft/mc-mods/angry-pixel-the-betweenlands-mod)?

**Comment by supermassimo** [comment]
> Perhaps the [Betweenlands](https://www.curseforge.com/minecraft/mc-mods/angry-pixel-the-betweenlands-mod)?

The betweenlands is not on 1.16?

**Comment by KentaButcher** [comment]
[https://www.curseforge.com/minecraft/mc-mods/corundum-meadows](url)

Corundum Meadows will be amazing to be supported

**Comment by CodeNameAki** [comment]
dregora 

[https://www.curseforge.com/minecraft/mc-mods/dregora](url)

**Comment by Kabinet0** [comment]
Project: Vibrant Journeys

https://www.curseforge.com/minecraft/mc-mods/project-vibrant-journeys

**Comment by Skulgan** [comment]
https://www.curseforge.com/minecraft/mc-mods/pixelmon

Pixelmon has officially updated to 1.16. With it, they phased out the cute abricot bushlike trees for actual, MC style trees. Please consider adding Dynamic Trees support for them! There are quite a few, but they all follow the same body plan, so it shouldn't be too difficult to make an addon for.

**Comment by TheeMrCheeky** [comment]
With as popular as [Ars Nouveau](https://www.curseforge.com/minecraft/mc-mods/ars-nouveau) is becoming I think it would be cool to see a dynamic trees version

**Comment by resistancelion** [comment]
+1 for Undergarden;
How about [Industrial Reborn](https://beta.curseforge.com/minecraft/mc-mods/industrial-reborn)? It uses the same Rubber Tree as EUC, IC2/IC2 Classic, so might be little bit less of work
