### ISSUE TITLE
Rendering issues with Sodium Forge ports

### ISSUE THREAD

**Issue by HarroldSaxon** [ferreusveritas/Dynamic-Trees#658]
Roots do not properly render with Magnesium installed. They appear as disconnected cubes of various sizes. Branches work normally and as intended. 

**To Reproduce**
-Install dynamic trees and Magnesium
-load a world
-find a tree with roots

**Screenshots**
will add some once I get a chance, in a few hours time. 

**Rendering Glitches**
Incompatibility with Magnesium.

**Additional context**
I’m sure you have better things to do than support yet another performance mod, but thought I’d at least let you know about this in case it is an easy fix for compatibility. 

-Magnesium 1.5
- Dynamic Trees: 1.16.5-0.10.0-Beta30
- Forge: 1.16 36.2.20
- Java: 8 Update 321
- OS: win8.1

**Comment by UK-IN-US** [comment]
I would like to add that this issue also affects the cacti from Dynamic Trees +.
Windows 10
Dynamic Trees 1.16.5-0.10.0-Beta32
Dynamic Trees Plus 1.16.5-0.1.0-Beta11
Magnesium v1.5
Sulfuric 1.0

![2022-02-15_23 47 15](https://user-images.githubusercontent.com/47405051/154219330-2d55b6b4-12f0-49df-b238-5569cc0276da.png)

Interestingly, though, when cut down the model for the falling animation renders correctly.
![2022-02-15_23 47 19](https://user-images.githubusercontent.com/47405051/154219417-8eab107d-f887-4f7c-96f2-c4c4a6126f90.png)

I have quite a few other mods installed at the moment, so I can't definitively say it's Magnesium.
Sorry I can't be of more help.

**Comment by UK-IN-US** [comment]
![2022-02-16_00 23 41](https://user-images.githubusercontent.com/47405051/154224697-83658c14-fed7-41fd-a6d4-0dd813af830a.png)
Issue is present with tree roots from Dynamic Trees for BYG.  Still searching for a vanilla tree with roots to document.

**Comment by UK-IN-US** [comment]
![2022-02-16_00 26 33](https://user-images.githubusercontent.com/47405051/154224980-f0487368-dd01-4330-b154-5ec6307239bf.png)
Issue also present with vanilla trees.

**Comment by nc5432** [comment]
This same issue happens with the Rubidium mod installed, except that it applies to branches and the upper part of trees as well.

**Comment by NeoSunSoar** [comment]
With Rubidium it also causes some trees to not render properly, only rendering a handful of leaves and branches. This will also sometimes occur way up into the sky with just random groups of leaves hanging attached to nothing.
![2022-06-01_22 57 45](https://user-images.githubusercontent.com/106568438/171550391-13fcde86-26af-491a-a9e8-84be6484e8a3.png)
![2022-06-01_23 02 02](https://user-images.githubusercontent.com/106568438/171550545-c61b3182-208f-4b2d-81e8-aa89de457849.png)

**Comment by rjulib00** [comment]
> With Rubidium it also causes some trees to not render properly, only rendering a handful of leaves and branches. This will also sometimes occur way up into the sky with just random groups of leaves hanging attached to nothing. ![2022-06-01_22 57 45](https://user-images.githubusercontent.com/106568438/171550391-13fcde86-26af-491a-a9e8-84be6484e8a3.png) ![2022-06-01_23 02 02](https://user-images.githubusercontent.com/106568438/171550545-c61b3182-208f-4b2d-81e8-aa89de457849.png)

this happens cause of cave biome api

**Comment by Harleyoc1** [comment]
> this happens cause of cave biome api

It's possible but there's definitely a rendering issue there too.

**Comment by Harleyoc1** [comment]
This should be fixed in the next beta.
