### ISSUE TITLE
[1.12.2] Couple rooty soil bugs

### ISSUE THREAD

**Issue by DevTimur** [ferreusveritas/Dynamic-Trees#66]
version DynamicTrees-1.12.2-0.7.6

Rooty dirt and Rooty sand is VERY hard to break using any tool.

2 rooty dirts next to each other combine into some buggy block
https://i.imgur.com/u1QXiUQ.png
Probably because of Connected textures mod

**Comment by ghost** [comment]
Rooty dirt and sand is supposed to be that way to prevent the player from sidestepping the harvesting mechanic.

Don't post more than one issue in a single github issue.

**Comment by DevTimur** [comment]
Ok, sure.
I just thought both this issues about Rooty soil, so i posted them together.

What about texture glitch?

**Comment by ghost** [comment]
Yeah.  It's probably CTM like you said.
