### ISSUE TITLE
Possible bug/crash

### ISSUE THREAD

**Issue by TheeMrCheeky** [ferreusveritas/Dynamic-Trees#661]
- Dynamic Trees: 1.16.5-0.10.0-Beta30.jar (Have the latest plus version installed as well)
- Forge: 36.2.22
- Java: 1.8.0.321
- OS: W1
[crash-2022-01-25_04.33.30-server.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/7932387/crash-2022-01-25_04.33.30-server.txt)
I don't fully understand crash reports so maybe its just a mod conflicts just now it crashes and breaking any part of the tree minus the leaves only tested it on oak trees

**Comment by Harleyoc1** [comment]
Project MMO needs an update for our recent refactors. Looks like it has already been fixed by Harmonised7/project_mmo#50, though doesn't seem to have been released on CF yet so you'll have to wait until then or temporarily downgrade DT to <= beta 25.
