### ISSUE TITLE
what is the latest version of dynamic trees in 1.12.2 that uses forge 14.23.5.2859

### ISSUE THREAD

**Issue by ghost** [ferreusveritas/Dynamic-Trees#665]
i'd just bring my modpack up to 2860 but the other mods need 2859

**Comment by ghost** [comment]
never mind I tested it and its 0.9.25

**Comment by Harleyoc1** [comment]
Are you really certain they need 2859? There's literally one minor change in 2860 that shouldn't be breaking for any mods.
