### ISSUE TITLE
Dynamic Trees not Recognized

### ISSUE THREAD

**Issue by Inkquill256** [ferreusveritas/Dynamic-Trees#666]
I updated Dynamic Trees to the latest 1.16.5 version, but Minecraft kept crashing. It cannot seem to recognize this version. 

DynamicTrees-1.16.5-0.10.0-Beta31.jar
Java Build 1.8.0_321-b07
Windows 11
[crash-2022-01-28_10.56.31-fml.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/7960533/crash-2022-01-28_10.56.31-fml.txt)

**Comment by Harleyoc1** [comment]
```	
Failure message: Mod dynamictreesplus requires dynamictrees 0.10.0 or above
		Currently, dynamictrees is not installed
```

**Comment by Inkquill256** [comment]
Dynamic Trees was installed. For some reason, it's not being recognized.

**Comment by Harleyoc1** [comment]
Well according to Forge it isn't. I would suggest you confirm it is placed in the correct mod folder and if you're certain make sure Forge is updated as the only other possibility I can think of is that it's a Forge issue.

**Comment by Inkquill256** [comment]
Okay
