### ISSUE TITLE
Crash Client Side when tree is falling

### ISSUE THREAD

**Issue by Toscanphoenix-de** [ferreusveritas/Dynamic-Trees#667]
**Description**
When we chop a tree ( seems on happening just on a few like Jacade, Those bamboo-looking like trees and oak with BoP or BYG (Didn't tested more) ), the client crashes. Server is still fine. 

As I don't know which dynamic trees mod cause the problem, I thought going here is the best.

**Reproduced**
Chopped on different trees. (Funny is, if you cut of the leaves, you can chop down the trees without problems.)

**Rendering Glitches**
Using Optifine and it happend. Played without and still happens. 

**Crashes**
Copied the crashlog into pastebin 
https://pastebin.com/2UzjEsw8

**Mods List**
All mods are attached in the log

**Versions**

- Dynamic Trees: 0.10.0
- DT BoP: 2.0.8
- DT BYG: 1.0.0
- DT Quark: 2.1.1
- Forge: 36.2.23
- Java:  1.16.5
- OS: Windows 11 64-Bit

**Comment by Toscanphoenix-de** [comment]
Additional Comment: 
If one player cuts off a branch, only the game of the player who puncehd the branch get crashed

**Comment by DaddyP1G** [comment]
This happens with any tree that has multiple leaves type.  So any flowering tree or orchard tree.

**Comment by Toscanphoenix-de** [comment]
> This happens with any tree that has multiple leaves type.  So any flowering tree or orchard tree.

So nothing I can do, besides don't chop them?

**Comment by Toscanphoenix-de** [comment]
It is fixed i the todays update as I see. 
Think it was the 0.10.0.0-beta32
