### ISSUE TITLE
[Suggestion] Cacti seed/block drop

### ISSUE THREAD

**Issue by DevTimur** [ferreusveritas/Dynamic-Trees#67]
If short, i think cacti should drop less seeds and more blocks. Dynamic cacti looks huge, and when they drop 1 block, it's wierd. Also, they drop about 3 seeds every time, wich is too much for cacti. I think it should guarantee drop 1 seed, and +1 for every growth milestone (Not sure how much it should be)

**Comment by ghost** [comment]
I'll look into the seed drop issue because that does seem a bit high.  However this issue seems to conflict with issue #68 where you claim that it drops too many cactus blocks.  I'm hoping for some clarification.
