### ISSUE TITLE
Improper tool_type for trunk_shell block?

### ISSUE THREAD

**Issue by Darkorg69** [ferreusveritas/Dynamic-Trees#673]
**Description**
dynamictrees:trunk_shell block doesn't have a proper tool type assosiated with it.
https://github.com/Darkorg69/BetterPunching/issues/4

**Screenshots**
- See the referenced issue.

**Comment by Harleyoc1** [comment]
Seems to be invalid: [reference](https://github.com/Darkorg69/BetterPunching/issues/4#issuecomment-1068217633)
