### ISSUE TITLE
Add the function to modify the density of trees.

### ISSUE THREAD

**Issue by Lemonmito** [ferreusveritas/Dynamic-Trees#679]
I found that dynamictrees has a much higher density of trees than vanilla. Since I have betterfoliage when I walk into a forest with a high density of dynamic trees, my framerate drops significantly and I would like to add the ability to modify the density of trees.

**Comment by Harleyoc1** [comment]
You can actually already do this. The trees folder in your MC directory can be populated with all the same resources as DT and add-ons add. 

For changing the density you would want to override the default biome populators. I would recommend inspecting the [default populator](https://github.com/DynamicTreesTeam/DynamicTrees/blob/develop/1.16.5/src/main/resources/trees/dynamictrees/world_gen/default.json) to see how the density is configured for each biome by default. Place a `default.json` file in the same relative directory to the trees folder and play around with the `density` values for each biome.

**Comment by Harleyoc1** [comment]
Oh, and by the way that applies to 1.16. If you're on 1.12 it is effectively the same file but goes in the `config/dynamictrees` folder instead.

**Comment by Lemonmito** [comment]
> You can actually already do this. The trees folder in your MC directory can be populated with all the same resources as DT and add-ons add.
> 
> For changing the density you would want to override the default biome populators. I would recommend inspecting the [default populator](https://github.com/DynamicTreesTeam/DynamicTrees/blob/develop/1.16.5/src/main/resources/trees/dynamictrees/world_gen/default.json) to see how the density is configured for each biome by default. Place a `default.json` file in the same relative directory to the trees folder and play around with the `density` values for each biome.

Thank you very much.
But I still have some questions.
Does this mean I need to modify the jar file for the mod? I am a Modpack maker and need to upload to CurseForge, so if I need to change the JAR file, CurseForge would not allow me to upload Modpack :(

**Comment by Harleyoc1** [comment]
No, it can all be done from the `trees` folder under the relevant MC directory (same directory where the `config`, `mods`, etc folders are). Any entries will override the values assigned in base DT (and any add-ons). IIRC CurseForge allows you to add additional files to exports so you should be able to include the `trees` folder.

**Comment by Lemonmito** [comment]
> No, it can all be done from the `trees` folder under the relevant MC directory (same directory where the `config`, `mods`, etc folders are). Any entries will override the values assigned in base DT (and any add-ons). IIRC CurseForge allows you to add additional files to exports so you should be able to include the `trees` folder.

Really grateful to you!
