### ISSUE TITLE
Texture overlapping error

### ISSUE THREAD

**Issue by MexicanHomie** [ferreusveritas/Dynamic-Trees#684]
I'm using DynamicTrees-1.16.5-0.10.0-Beta33.jar with some other mods and I have this issue with the textures overlapping or missin in the edges of the top and bottom, I was wondering if you had seen this before and perhaps help me fix it, maybe is a setting or a specific mod.

I'm not using any of the Incompatible Mods indicated in the Curse Forge page. (Applied Energistics 2, Tree Chopper, Liquid Luck or Cave Biomes API)

If you do not follow these basic rules we may well close the issue without explanation.

This are some vanilla blocks that have the issue but any type of dynamic block like the mod Add-Ons also have this issue.
![Oak Log](https://user-images.githubusercontent.com/103147319/162066483-bcd190d9-7188-4b41-9c47-06771b11df38.png)
![Hay Bale](https://user-images.githubusercontent.com/103147319/162066488-39a6a4a4-c5e4-4c35-a0d5-126adbfaaf8f.png)

I'm not using OptiFine but instead a combination of mods like Sulfuric, BetterFoliage, DynamicLightsReforged, Magnesium_extras, among others.

The game doesn't crash, is just a visual bug/conflict.

- Dynamic Trees: 1.16.5-0.10.0-Beta33.jar
- Forge: 36.2.20
- CurseForge: v. 0.194.2.1
- Java: Version 8 Update 321 (build 1.8.0_321-b07)
- OS: Windows 10 version 20H2

**Comment by Harleyoc1** [comment]
Dynamic Trees does not change blocks in this way. IIRC that is Better Foliage.
