### ISSUE TITLE
Rooty farmland texture is messed up

### ISSUE THREAD

**Issue by carrotbane2** [ferreusveritas/Dynamic-Trees#686]
Version is DynamicTrees-1.16.5-0.10.0-Beta33.jar.

To reproduce: till dirt, place acorn, use bonemeal on young tree. The farmland underneath is turned into dynamictrees:rooty_farmland, but it uses the "missing" texture (purple/black squares).

I am not using Optifine, shaders, resource packs or anything else that changes textures.

Also, as an aside: when I tried to run this mod alongside Realistic Block Physics, it crashed, and the crash log mentioned this specific block (rooty farmland).

Modlist:
alchemistry-1.16.5-1.jar
alib-1.16.4-1.jar
chemlib-1.16.5-2.jar
curios-forge-1.16.5-4.0.5.3.jar
DynamicTrees-1.16.5-0.10.0-Beta33.jar
FarmersDelight-1.16.5-0.5.5.jar
geckolib-forge-1.16.5-3.0.66.jar
GeneticAnimals-0_6_40.jar
jei-1.16.5-7.7.1.152.jar
RealisticExplosionPhysics-1.16.5-1.0.0.jar
ThrowableExplosives-1.16.5-1.2.0.jar

**Comment by Harleyoc1** [comment]
Should be fixed in the next beta.
