### ISSUE TITLE
Game crashing when making Terraforged worlds.

### ISSUE THREAD

**Issue by Chann3l-Chas3r** [ferreusveritas/Dynamic-Trees#689]
When attempting to generate a new world the game crashes and I get the exit code -1. Steps to reproduce the behavior: It happens when I try to make a new world using Terraforged. Everything _should_ be compatible, I have the mod that makes the two compatible and I'm 95% certain I've got the right versions of all 3 mods, but the crash reports says something about there being an issue with generating the bushes? I am not using Optifine.

**CRASH REPORT**:
https://gist.github.com/Chann3l-Chas3r/5d48a9cf9fec0e37c2d4652ae349faf6

**VERSIONS**:
- Dynamic Trees: 1.16.5-0.10.0-Beta27
- Forge: 1.16.5-forge-36.2.34
- Java: 8.0.3330.2
- OS: Windows 10

**Comment by Harleyoc1** [comment]
I'm fairly certain this issue has already been resolved. Please update to the latest version of DT and try again.
