### ISSUE TITLE
All trees drop 1 log.  DynamicTrees-1.12.2-0.7.7a Forge 14.23.3.2679

### ISSUE THREAD

**Issue by renadi** [ferreusveritas/Dynamic-Trees#69]
After updating Rustic and adding in the TC compat mod I had to update Dynamic Trees to the next version. 
 I realized all trees were only dropping one log, I changed the configs to be at 7 times multiplier and it still only drops one, I downgraded back to 0.7.6 a tree drops on average 32-64 logs. changing multiplier back to one I get 3-8 logs on average.

**Comment by renadi** [comment]
I tested setting gain multiplier to 50 and get roughly 6-12 per tree

**Comment by ghost** [comment]
What was the deal?  Why did you close this issue?

**Comment by renadi** [comment]
Oops, that was an accident.
