### ISSUE TITLE
Client and server crash, v.1.12.2.

### ISSUE THREAD

**Issue by SeagalKru** [ferreusveritas/Dynamic-Trees#690]
After updating your mod from "DynamicTrees-1.12.2-0.9.27.jar" to "DynamicTrees-1.12.2-0.9.28.jar", both server and client crash.
The crash log file is attached.
[crash-2022-05-29_13.53.06-server.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/8793176/crash-2022-05-29_13.53.06-server.txt)
[crash-2022-05-29_13.53.50-client.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/8793177/crash-2022-05-29_13.53.50-client.txt)

**Comment by festro** [comment]
Getting the same here, version 0.9.27 works fine though.

**Comment by SeagalKru** [comment]
Yes.
The previous version "DynamicTrees-1.12.2-0.9.27.jar" works fine.

**Comment by DaftHunk** [comment]
Same here

**Comment by SeagalKru** [comment]
(Google translation)

Released mod updates "DynamicTrees-1.12.2-0.9.29.jar" and "DynamicTreesPHC-1.12.2-2.0.6.jar" fixed the crash problem: the server and the client start. There are no crashes.
Thanks to the developers for the hard work!

I'm closing the topic!
