### ISSUE TITLE
Feature Request 1.16.5: Cave/underground growth config possibility

### ISSUE THREAD

**Issue by xFirefalconx** [ferreusveritas/Dynamic-Trees#694]
**Is your feature request related to a problem? Please describe.**
I'm often building large farms in self-made caves/buildings underground. However, Dynamic Trees seem to need sky light in order to grow, my recent attempts were in vain as the tree first grew one bit and then disappeared. The tree I tried was a BoP tree called "red maple samara". If this is bugged without me knowing, my sincere apologies. 

**Describe the solution you'd like**
I would love to have a config file option to disable the skylight check and instead check for general block light level around the tree base. Maybe also a tooltip to tell which is the general growth conditions for a Dynamic Tree, as I can't see one currently. 

**Describe alternatives you've considered**
Probably search for a mod that makes minecraft ignore skylight for general crop growth? There is none, at least. Or never build my farms underground aka being limited in that regard.

**Comment by Harleyoc1** [comment]
We have been discussing this change and are going to be undoing it. Unfortunately the impact of such a config option is that if the player placed any light sources on the ground it would affect the growth of nearby leaves, effectively ruining the design of the growth. 

We are however discussing alternative solutions, such as a block that emits artificial sky light (would be a separate mod as it is out of scope for DT itself).

**Comment by ghost** [comment]
Here's a workaround for this:
https://www.curseforge.com/minecraft/mc-mods/skylight-lanterns

With the lanterns this mod provides you can grow trees underground.
