### ISSUE TITLE
Feature Request 1.16.5- Disabling Seeds Config

### ISSUE THREAD

**Issue by JustLiam040** [ferreusveritas/Dynamic-Trees#695]
I am using Dynamic trees however wish to use them purely for world gen, I would like all other trees to be vanilla without the hassle of having to manually craft each sapling.

Is there any possibility of adding a config that allows me to disable the drops of acorns/seeds completely when destroying a tree.
Alongside this I think adding a config option to increase the drop rate of saplings would be ideal if this was possible.

**Comment by Harleyoc1** [comment]
You can now modify the universal seed drop rate by setting the new `leavesSeedDropRate` option. It can be set to `0.0` to disable seeds dropping altogether. The option is in the server config which is located at the following directories: 

Singleplayer: `saves/[world]/serverconfig/dynamictrees-server.toml`
Dedicated Server: `[world]/serverconfig/dynamictrees-server.toml` relative to the server folder
