### ISSUE TITLE
Incompatibility crash between Dynamic Trees and Optifine

### ISSUE THREAD

**Issue by TYTheBeast** [ferreusveritas/Dynamic-Trees#696]
**Description**
A crash with Dynamic Trees and Optifine as the culprits occurs.

**To Reproduce**
_Unknown_; the crash occured on a world that was generated with the Terraformed mod, but that was then uninstalled, and with Optifine shaders. The crash occured while loading the Continuum Graphics 2.0.4 shaderpack.

**Rendering Glitches**
_Are you using OptiFine (or any equivalent mods that mess with rendering)?_
Yes.

**Crashes**
[Not Enough Crashes generated report](https://bytebin.lucko.me/LotfFXJOFw)

All versions are included within the crash report.

_please note that i'm simply submitting this crash report on behalf of a friend and i'm happy with this report being closed with no explanation, i am simply hoping to provide a crash report and contribute to bugs being fixed_ :)

**Comment by Harleyoc1** [comment]
This is an issue with DT+: DynamicTreesTeam/DynamicTrees#8
