### ISSUE TITLE
Spruce cone model error

### ISSUE THREAD

**Issue by 623667595** [ferreusveritas/Dynamic-Trees#698]
![image](https://user-images.githubusercontent.com/88877796/173768133-8b9e9230-e953-4e16-a337-e229c2f94c35.png)
1.12.2 forge 2860  DynamicTrees-1.12.2-0.9.29

**Comment by Harleyoc1** [comment]
The model file hasn't changed recently and I notice you have a resource pack enabled. It is most likely something to do with the resource pack, please try disabling it and see if the issue persists. If it doesn't please tell me the name of the resource pack and I'll try and see what's causing it.

**Comment by 623667595** [comment]
> 模型文件最近没有更改，我注意到您启用了资源包。这很可能与资源包有关，请尝试禁用它，看看问题是否仍然存在。如果不是，请告诉我资源包的名称，我会尝试看看是什么原因造成的。

It has been found that it is a resource pack problem. Thank you
