### ISSUE TITLE
1.12.2-0.7.7 Crash

### ISSUE THREAD

**Issue by iobiarg** [ferreusveritas/Dynamic-Trees#70]
HI, i'm trying to use Rustic and the Addons for Dynamic trees and both requieres the Dynamic Trees 1.12.2-0.7.7 version witch i know it's an alpha, but is causing my game to crash on lauch... since i'm not a programmer i'm not able to figure out what's going on besides the error in dynamictreesbop

[crash-2018-05-08_12.34.40-client.txt](https://github.com/ferreusveritas/DynamicTrees/files/1984662/crash-2018-05-08_12.34.40-client.txt)

It would be really helpfull if you could give me a hand with this.
Sorry for my bad English, it isn't my native language.

**Comment by ghost** [comment]
Update dynamictreesbop to version [1.1.0a](https://minecraft.curseforge.com/projects/dtbop/files)
Also you should update Dynamic Trees again since I just fixed a major bug a few minutes ago.
