### ISSUE TITLE
Serene Seasons Foliage not working

### ISSUE THREAD

**Issue by dani31c** [ferreusveritas/Dynamic-Trees#701]
**Rules (Read this first!)**
This is just a template to help you post a useful issue.  Erase these rules and any irrelevant categories and content as you see fit.

- Only submit issues related to the latest version of the mod for the Minecraft version specified by the template.
- When referring to versions always use the actual version number; never "latest".
- Inlude all version in the [version](#versions) section.
- Use a paste site, preferably [Gist](https://gist.github.com), to dump any logs or crash reports.
- Do not open bug reports for add-ons! These should be reported to their respective issue trackers.
- Do not use this template for feature requests, there's a separate template for that.

If you do not follow these basic rules we may well close the issue without explanation.

**Description**

**To Reproduce**

**Screenshots**

**Rendering Glitches**
Are you using OptiFine (or any equivalent mods that mess with rendering)?

**Additional Context**

**Crashes**
If you are crashing **you must include a crash report**. The aforementioned [rules](#rules) apply when attaching crash reports.

**Mods List**
If your crash log does not contain a list of mods or you have no crash log then please provide a full list of the mods you are using complete with mod versions, preferably on a paste site if you're running with more than 10 mods.

**Versions**
Include relevant versions below. If this issue relates to add-ons then include their versions too.

- Dynamic Trees: (1.12.2 Latest)
- Forge: 2860
- Java: 8
- OS: Windows 10

Whenever dynamic trees and serene are installed, foliage wont work

**Comment by Harleyoc1** [comment]
This is nowhere near enough info. Please don't ignore the template, or at the very least state what "won't work" actually means.

**Comment by dani31c** [comment]
Oh sorry, ill explain here.

I made a 1.12.2 server using the latest version of Serene Seasons and DynamicTrees, however, trees dont seem to follow the season's folliage, it stays static.

Steps to reproduce:
1. Make a Forge 1.12.2-2860 server.
2. Install Dynamic Trees and Serene's
3. Change seasons to see no change

I didn't tale any screenshots, but I clearly saw these normal pine trees with the same darkish green color while snowing, where it should have changed foliage.

My mod list includes TexFix, Optifine, Vanillafix, BetterFPS, Phosphor, Born in a Barn, Appleskin, Hwyla, JEI, Foamfix, Particle culling, Entity culling, Serene and dynamic trees. All of these on latest versions with fast settings.

Also, as told before, dynamic trees on its latest, aswell Java and Forge. The OS was Windows 11 actually when playing, and Ubuntu 20.04 for the server.

**Comment by dani31c** [comment]
I also think snow wouldnt stay on top of trees, but even after some trees were chopped, that empty area wouldnt get snow again.

**Comment by dani31c** [comment]
Btw the initial issue is for the addons for like, BOP

**Comment by Harleyoc1** [comment]
> Btw the initial issue is for the addons for like, BOP

So it works on the vanilla tree leaves, but not on add-ons? If so can you confirm this isn't also an issue for the regular leaves of those respective mods.

**Comment by Harleyoc1** [comment]
> I didn't tale any screenshots, but I clearly saw these normal pine trees with the same darkish green color while snowing, where it should have changed foliage.

Also wouldn't that be intentional? Pine trees are evergreen.

**Comment by dani31c** [comment]
Yes, I just found out, as oak trees did change, however I havent seen any BOP leaves change so far, ill give it another check today and confirm that atleast some trees do work?

**Comment by dani31c** [comment]
Seems to be an issue with BOP.

**Comment by Harleyoc1** [comment]
So to be clear... This is an issue with BOP itself, not the add-on?

**Comment by dani31c** [comment]
That's why a BOP addon exists?

**Comment by Harleyoc1** [comment]
What? DT and its BOP add-on are nothing to do with serene seasons. They change the foliage of leaves on their own.

**Comment by dani31c** [comment]
Oh okay then. may I know why it works without DT?

**Comment by Harleyoc1** [comment]
Well that is what I was asking - do the leaves foliage colours definitely work on the regular BOP leaves?

**Comment by dani31c** [comment]
Yes, it is made by the same guys and has compatibility with certain biomes
