### ISSUE TITLE
Floating lava on trees

### ISSUE THREAD

**Issue by EicheBrutal** [ferreusveritas/Dynamic-Trees#707]
I'm having a weird bug with floating lava over trees, which stand near by lavablocks. It also accours when i interact with lava using a bucket.
It doesn't seem to actually burn the trees nor does it crash my game.

My modpack is simular to RLCraft, however i'm also using Dynamic Trees for BOP.
I just hope it's not bc my forge version, i cant update that since it would completly break my modpack.

Is there a known way to solve this problem?
Did i miss something in the configs?

Forge 14.23.5.2855
Optifine HD U G5

Dynamic Trees 0.9.19
Dynamic TreesBOP 1.4.4
Dynamic TreesTraverse 2.1

**Comment by Harleyoc1** [comment]
I'm going to mark this as mod incompatibility as it's not likely caused by DT.
