### ISSUE TITLE
Normal vanilla trees still spawning as well as dynamic trees

### ISSUE THREAD

**Issue by soupfan** [ferreusveritas/Dynamic-Trees#719]
In all of my worlds vanilla trees are still spawning alongside dynamic trees, seemingly only in vanilla biomes, not Biomes O' Plenty biomes (I also have the BOP DT addon) The only advice I found was that a mod may be interfering but I tried several times with no other mods on new worlds and the issue still occurs.

Example of the issue:
![2022-09-07_16 31 28](https://user-images.githubusercontent.com/112960977/188920274-dc6f6448-d06d-4d70-b865-fccede113539.png)

**Comment by moninformateur** [comment]
Edit: **Nevermind, this is Terralith's fault.**

I confirm I notice the same behavior, on 1.18.2. Also using BOP Dynamic Trees addon. 

[Modlist](https://pastebin.com/AAZbNgQy)

Here are a few F3 screenshots, tested on a "Quark-less" world. Teralith Worlgen.

![Base Profile Screenshot 2022 09 26 - 12 31 58 54](https://user-images.githubusercontent.com/79221061/192334182-fa61ed4b-62a2-4e3d-9cec-3ec9747b6566.png)

![Base Profile Screenshot 2022 09 26 - 12 31 46 29](https://user-images.githubusercontent.com/79221061/192334208-d5bdd953-d046-4307-8544-5104f8ccea04.png)

![Base Profile Screenshot 2022 09 26 - 12 37 24 48](https://user-images.githubusercontent.com/79221061/192334329-fae2d054-68b3-4a2f-b943-6e874e65c841.png)
