### ISSUE TITLE
Crashing when chopping down tree

### ISSUE THREAD

**Issue by TheeMrCheeky** [ferreusveritas/Dynamic-Trees#720]
**Description**
Game crashes when chopping down (oak tree in forest) in survival but not creative (haven't tested other trees) ALSO In the badlands the trees spawn in 80% normal minecraft trees and occasionally a dynamics tree here and there.

**Crashes**
[crash-2022-09-10_14.40.09-server.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/9541188/crash-2022-09-10_14.40.09-server.txt)

**Mods List**
[Mods List.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/9541206/Mods.List.txt)

~ Minecraft Version: 1.16.5
- Dynamic Trees:  DynamicTrees-1.16.5-0.10.0-Beta34.jar
- Forge: 36.2.39
- Java: Latest Version I guess ( I always update java when there is a update)
- OS: Windows 11

**Comment by Harleyoc1** [comment]
This is being caused by PMMO. It appears they will need an update to support the latest beta.
