### ISSUE TITLE
My game crashed

### ISSUE THREAD

**Issue by mapyDayton22** [ferreusveritas/Dynamic-Trees#721]
![image](https://user-images.githubusercontent.com/40726888/189533359-91d79736-d4fd-4cda-87bc-fce5640b9395.png)

**Comment by Harleyoc1** [comment]
DT doesn't use Mixin so not sure how that's happened... Anyway for us to do anything you need to fill out the information in the template properly, and we need you to send the crash report file.

**Comment by Harleyoc1** [comment]
#724 seems to be the same issue so I'm going to close this one in favour of that one since the author put more details on there.
