### ISSUE TITLE
Compat issue between Dynamic Trees and CTOV MC 1.18.2

### ISSUE THREAD

**Issue by Flugel3** [ferreusveritas/Dynamic-Trees#723]
**Description**
Basically, tree break house... Villager becomes homeless.

**To Reproduce**
Have ChoiceTheorem's Overhauled Village and Dynamic Trees, do /locate command to find a CTOV Village and teleport to it, preferably in a denser forest to more clearly see the issue.

**Screenshots**
![2022-09-11_18 54 50](https://user-images.githubusercontent.com/78325529/189552559-6bbadd57-971e-46c5-a55b-d997d0b170ac.png)
![2022-09-11_18 54 46](https://user-images.githubusercontent.com/78325529/189552561-3458c299-c854-4e8b-913a-c17944b1a360.png)
![2022-09-11_18 54 33](https://user-images.githubusercontent.com/78325529/189552565-fc3e899e-5ebf-46ff-abc3-65caf3d38a74.png)

**Rendering Glitches**
No

**Additional Info**
This issue has been reported in both githubs.

**Versions**

- Dynamic Trees: 0.11.0-Alpha2
- Dynamic Trees +: 0.1.0-Alpha1
- Dynamic Trees BOP: 3.0.0-ALPHA1
- ChoiceTheorem's Overhauled Village: v2-9-1
- MC: 1.18.2
- Forge: 40.1.74

**Comment by Harleyoc1** [comment]
This should be fixed once the recent updates to the 1.16.5 version are ported to 1.18.
