### ISSUE TITLE
1 Missing Tree Texture 

### ISSUE THREAD

**Issue by Charbri** [ferreusveritas/Dynamic-Trees#727]
[](url)
![Missing Texture](https://user-images.githubusercontent.com/114490039/192650524-2171431d-fb9f-4b1f-82be-92de68ef786c.jpg)
![Active_Resource Packs](https://user-images.githubusercontent.com/114490039/192652128-c7287f5c-4124-49f4-b5b6-416d6711c79f.jpg)

I Am using Dynamic trees in my Curse Forge modpack and it seems like its missing a texture for only 1 type of tree which uses the charred branch block. I dont know if it's a mod conflict thing or something else but i have no clue on how to resolve it.  Its not a very big deal as it doesnt really effect my being able to play the modpack but itd be great to fix it as it kind of ruins the vibe of the game. :)

Minecraft Version: 1.18.2

Mods in Modpack: 
torohealth-1.18-forge-2.jar
Towns-and-Towers-1.18.2-1.6.0.jar
transparent-4.1.0+1.18.2-forge.jar
trashcans-1.0.15-forge-mc1.18.jar
TravelersBackpack-1.18.2-7.1.10.jar
tumbleweed-1.18-0.4.12.jar
twilightforest-1.18.2-4.1.1423-universal.jar
VisualWorkbench-v3.3.0-1.18.2-Forge.jar
waystones-forge-1.18.2-10.1.0.jar
Xaeros_Minimap_22.14.1_Forge_1.18.2.jar
XaerosWorldMap_1.27.0_Forge_1.18.2.jar
YungsApi-1.18.2-Forge-2.0.8.jar
YungsBetterMineshafts-1.18.2-Forge-2.2.jar
YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar
zmedievalmusic-1.18.2-1.4.jar
AI-Improvements-1.18.2-0.5.0.jar
alexsmobs-1.18.6.jar
AmbientEnvironment-forge-1.18.2-7.0+19.jar
AmbientSounds_FORGE_v5.0.16_mc1.18.2.jar
appleskin-forge-mc1.18.2-2.4.1.jar
Aquaculture-1.18.2-2.3.8.jar
architectury-4.9.84-forge.jar
autoplant-1.18.2-1.0.0.jar
AutoRegLib-1.7-53.jar
balm-3.2.0+0.jar
betteranimalmodels-1.18.2-5.6.0-forge.jar
betteranimalsplus-1.18.2-11.0.5-forge.jar
betterbiomeblend-1.18.2-1.3.5-forge.jar
BetterF3-1.2.5-Forge-1.18.2.jar
BiomesOPlenty-1.18.2-16.0.0.109-universal.jar
blockui-1.18.2-0.0.62-ALPHA.jar
blueprint-1.18.2-5.5.0.jar
Bookshelf-Forge-1.18.2-13.2.50.jar
Botania-1.18.2-435.jar
carryon-1.18.2-1.17.0.8.jar
cfm-7.0.0-pre29-1.18.2.jar
ChunkAnimator-1.18.2-1.3.4.jar
citadel-1.11.3-1.18.2.jar
cloth-config-6.4.90-forge.jar
Clumps-forge-1.18.2-8.0.0+15.jar
cofh_core-1.18.2-1.6.4.21.jar
collective-1.18.2-4.69.jar
corail_woodcutter-1.18.2-2.3.7.jar
Craftable Horse Armour  Saddle-1.18-1.8-Forge.jar
CreativeCore_FORGE_v2.6.15_mc1.18.2.jar
Croptopia-1.18.2-FORGE-2.1.0.jar
curios-forge-1.18.2-5.0.7.1.jar
DarkPaintings-Forge-1.18.2-10.0.3.jar
DoggyTalents-1.18.2-2.5.0.jar
domum_ornamentum-1.18.2-1.0.50-ALPHA-universal.jar
dtcroptopia-1.0.0.jar
DungeonsArise-1.18.2-2.1.50d-beta.jar
dynamic_asset_generator-forge-1.18.2-0.6.3.jar
dynamiclights-1.18.6.jar
DynamicTrees-1.18.2-0.11.0-Alpha2.jar
DynamicTreesBOP-1.18.2-3.0.0-ALPHA1.jar
DynamicTreesPlus-1.18.2-0.1.0-Alpha1.jar
EarthMobs-1.18.2-1.1.2.jar
EasyMagic-v3.3.0-1.18.2-Forge.jar
ecologics-forge-1.18.2-1.7.10.jar
EnchantmentDescriptions-Forge-1.18.2-10.0.9.jar
exoticbirds-1.18.2-1.8.0.jar
expandability-6.0.0.jar
Fallingleaves-1.18.2-1.3.2.jar
FarmersDelight-1.18.2-1.2.0.jar
FarmersRespite-1.18.2-1.3.0.jar
FastFurnace-1.18.2-6.0.3.jar
feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.jar
fireflies-1.2.jar
flowerseeds-1.18.2-3.0.1.jar
forge-1.18.2-40.1.80-installer.jar
ForgeEndertech-1.18.2-9.0.5.0-build.1061.jar
forgivingvoid-forge-1.18.1-6.0.1.jar
geckolib-forge-1.18-3.0.39.jar
goodall-1.0.2-forge.jar
ImmersiveEngineering-1.18.2-8.2.2-154.jar
InventoryProfilesNext-forge-1.18.2-1.8.0.jar
ironfurnaces-1.18.2-3.3.1.jar
jei-1.18.2-9.7.1.255.jar
JustEnoughResources-1.18.2-0.14.1.171.jar
Kiwi-1.18.2-forge-6.1.3.jar
kotlinforforge-3.7.1-obf.jar
libIPN-forge-1.18.2-1.0.0.jar
Mantle-1.18.2-1.9.27.jar
mcw-bridges-2.0.4-mc1.18.2forge.jar
mcw-doors-1.0.7-mc1.18.2.jar
mcw-fences-1.0.6-mc1.18.2.jar
mcw-trapdoors-1.0.7-mc1.18.2.jar
minecolonies-1.18.2-1.0.1048-BETA.jar
modnametooltip-1.18.1-1.18.0.jar
More Babies-forge-1.18.1-0.5.2.jar
morevillagers-forge-1.18.2-3.3.2.jar
mowziesmobs-1.5.29.jar
multi-piston-1.18.2-1.2.15-ALPHA.jar
mysticalworld-1.18.2-0.4.7.28.jar
Natural Decoration v.1.0.9.jar
naturalist-forge-1.1.1-1.18.2.jar
NaturesCompass-1.18.2-1.9.7-forge.jar
netherportalfix-forge-1.18-9.0.0.jar
NethersDelight-1.18.2-2.2.0.jar
notenoughanimations-forge-1.6.0-mc1.18.2.jar
Obscuria's Essentials 3.2.0 (Forge 1.18.2).jar
Obscuria's Tooltips 1.4.1 (1.18.2).jar
Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.4.jar
OreExcavation-1.10.162.jar
Paintings-forge-1.18.2-9.1.2.1.jar
Patchouli-1.18.2-71.1.jar
Placebo-1.18.2-6.6.4.jar
PuzzlesLib-v3.3.5-1.18.2-Forge.jar
Quark-3.2-358.jar
QuarkOddities-1.18.jar
refinedstorage-1.10.3.jar
Regrowth-1.18.2-1.40.0.31.jar
replanter-forge-1.3.jar
repurposed_structures_forge-5.1.14+1.18.2.jar
Rex's-AdditionalStructures-1.18.2-(v.3.1.1).jar
sapience-1.18.2-1.0.0.jar
selene-1.18.2-1.17.9.jar
Serene Seasons-1.18.2-7.0.0.13.jar
shutupexperimentalsettings-1.0.5.jar
sophisticatedbackpacks-1.18.2-3.18.29.718.jar
sophisticatedcore-1.18.2-0.5.12.129.jar
structurize-1.18.2-1.0.424-ALPHA.jar
supermartijn642corelib-1.0.19-forge-mc1.18.jar
supplementaries-1.18.2-1.5.7.jar
swingthroughgrass-1.18.2-1.9.0.jar
TConstruct-1.18.2-3.5.2.40.jar
TerraBlender-forge-1.18.2-1.2.0.126.jar
The_Wild_Update_Mod_V1.3_Minecraft_1.18.jar
thermal_cultivation-1.18.2-1.6.3.11.jar
thermal_foundation-1.18.2-1.6.3.28.jar
tombstone-7.5.3-1.18.2.jar

**Comment by Harleyoc1** [comment]
This is likely an issue on whichever add-on is adding the charred tree as it is not a tree Dynamic Trees adds by default. Please find out which mod it is (if memory serves it is mystical world - but check) and report it to them.
