### ISSUE TITLE
[Bug] Bonemealing unripe apples does nothing.

### ISSUE THREAD

**Issue by Deshiba** [ferreusveritas/Dynamic-Trees#73]
# Current behavior
Currently you can use bonemeal on unripe apples. However apples don't advance a stage when this is done.

# Expected behavior
I'd expect to be able to use bonemeal at all, or to have it advance a growth stage.
Admittedly this is learned behaviour from other mods (primarily Pam's). However if using bonemeal on fruit is not a thing in this, then it shouldn't consume my bonemeal.

# Screenshots
![2018-05-12_12 35 03](https://user-images.githubusercontent.com/10565800/39956486-9c6d2ed8-55e1-11e8-8ac3-c514e8e88272.png)

And in survival, you can see it decreases my bonemeal stack but doesn't affect the apple growth (sorry for the apple visibility being lacking, I hope you get the gist though).
![2018-05-12_12 40 27](https://user-images.githubusercontent.com/10565800/39956493-b8250344-55e1-11e8-88e3-441095d0b87d.png)
![2018-05-12_12 40 29](https://user-images.githubusercontent.com/10565800/39956494-ba3b70f0-55e1-11e8-904b-6c980a90f4e9.png)

**Comment by Deshiba** [comment]
Minecraft version 1.12.2 (Latest release)
Forge version 14.23.3.2655 (Latest stable release) 
Dynamic Trees version 1.12.2-0.7.6 (Latest release on CF)


For sake op completion, tested on  Alpha 1.12.2-0.7.7c as well, this behaviour is unchanged.
![2018-05-12_12 51 09](https://user-images.githubusercontent.com/10565800/39956558-537d56ec-55e3-11e8-9bf2-0371ebe38162.png)

**Comment by ghost** [comment]
Oh..   Thanks for reporting that. Somehow I never noticed it was doing that.  I'll have it fixed before the next alpha version

**Comment by ghost** [comment]
Fixed in dev.
