### ISSUE TITLE
Apple trees crash other player on LAN (1.16.5)

### ISSUE THREAD

**Issue by Cryptillian** [ferreusveritas/Dynamic-Trees#732]
**Describe the bug**
While my friend plays on my world through a LAN connection he crashes every time he looks directly at apples on apple trees. I do not have this issue myself.

**To Reproduce**
Open LAN server with another player with Hamachi, have them look directly at an apple on an apple tree. Only temporary fix seems to be to chop down the tree so they can rejoin.

**Rendering Glitches**
Are you using OptiFine (or any equivalent mods that mess with rendering)?
Yes we both use OptiFine 1.16.5

**Additional context**
We run a lot of mods (as shown in crash report) and are using Hamachi to connect as a LAN server in case that is relevant.

**Crashes**
Versions:
- DynamicTrees-1.16.5-0.10.0
- Biomes O' Plenty 1.16.5-13.1.0.488
- DynamicTrees BOP 1.16.5-2.0.9
- Forge: 1.16.5-36.2.39

Full mod list available in crash report below.

Crash Report: https://pastebin.com/5gKruDES

**Comment by Veylyn** [comment]
I've had this same issue in 1.18.2. It appears to be some interaction with WAILA/Jade. Disabling Jade fixes the bug, but a fix for the issue would be appreciated

**Comment by Harleyoc1** [comment]
I think I know the cause of this, I'll release a patch ASAP. In the mean time it should work if the person joining the server starts a single player world at least once after game launch.
