### ISSUE TITLE
Updated DynamicTrees and now has a loading error during start up

### ISSUE THREAD

**Issue by SylvanFauna** [ferreusveritas/Dynamic-Trees#736]
**Describe the bug**
Updated Dynamic Trees to DynamicTrees-1.16.5-0.10.2 from DynamicTrees-1.16.5-0.10.0-Beta33
Now game crashes during set up

**Crashes**
[Crash log](https://gist.github.com/SylvanFauna/2ca70391e3c727252a1c79a9df22d9d4)

**Mods List**
Mods and Forge in crash report

**Comment by Harleyoc1** [comment]
This is an issue on Cave Biomes API's end. They haven't updated their Mixins for a change made a few months ago.

**Comment by SylvanFauna** [comment]
Copy, thank you for getting back to me!
