### ISSUE TITLE
Just updated, now world will not load

### ISSUE THREAD

**Issue by ghost** [ferreusveritas/Dynamic-Trees#737]
I just updated the mod. Now Minecraft will launch but the world will not load. Issue seems to be with core mod. Will launch Minecraft, but wont load world.
See logs below. Thanks! This mod is maybe the best ever!

[crash-2022-11-29_17.29.05-fml.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/10118333/crash-2022-11-29_17.29.05-fml.txt)
[latest.log](https://github.com/DynamicTreesTeam/DynamicTrees/files/10118334/latest.log)
![image](https://user-images.githubusercontent.com/101782179/204678954-2be25619-ba91-4aa5-a313-d57a536edef9.png)

**Comment by caniplzjustlogin4godsakesthistakesforev** [comment]
The same error also happens with Dynamic Trees 18.2-0.11.0-Beta3, link to latest.log:
[latest.log](https://github.com/DynamicTreesTeam/DynamicTrees/files/10231986/latest.log)

**Comment by Harleyoc1** [comment]
Should be fixed in beta 5.
