### ISSUE TITLE
Temprate rainforest biomes used oaks instead of rewoofs and firs?

### ISSUE THREAD

**Issue by GhostHollowKnight** [ferreusveritas/Dynamic-Trees#738]
When I go to the temprate rainforest  biome it uses oaks shaped like firs and redwoods but not redwoods is there a way to fix this it looks bad and too unrealistic (what conifer has leafs it makes no sense?)

**Comment by Ceimnithe** [comment]
Yeah I'm having a similar issue. 1.18.2, version 0.11.0-Beta6. In jungle biomes, the jungle trees are replaced with dark oak.
