### ISSUE TITLE
Dynamic trees crashing when breaking any tree.

### ISSUE THREAD

**Issue by Monikette** [ferreusveritas/Dynamic-Trees#739]
My very first post here, so excuse if format isn`t correct :)

**Describe the bug**
Dynamic trees crashes **when breaking any tree** with-Exception in server tick loop java.lang.NoSuchMethodError: 

**To Reproduce**
Install **Project MMO** [https://www.curseforge.com/minecraft/mc-mods/project-mmo](url) and
break any tree.

**Screenshots**
None, full crash log here: [https://pastebin.com/EBGz8zpz](url)

**Rendering Glitches**
No render glitches

**Additional context**
After some testing, **project MMO seems to be the culprit**, as once removed mod works just fine with no crashes.

**Versions:**
 - Minecraft: 1.16.5
 - Loader: Forge-36.2.39
 - Dynamic trees: Latest for said version

**Comment by Harleyoc1** [comment]
This appears to be on their end, I think they're calling a method we removed or changed the signature of during the beta. Please open the issue on their tracker.

**Comment by Monikette** [comment]
Okay will do :)
