### ISSUE TITLE
[Feature Request]Apple trees dropping apples.

### ISSUE THREAD

**Issue by Deshiba** [ferreusveritas/Dynamic-Trees#74]
I'd love it if the apple trees would drop their apples when they are ripe and unpicked after a period of time. This feature would have 3 purposes.
1. Realism. Real trees drop their apples.
2. Automatic farming. 
3. Apple tree spreading like the other trees in this mod do.

The third feature might sound strange, Apple trees are random in other forests due to animal droppings. However there is an apple tree forest in [Tien Shan](https://en.wikipedia.org/wiki/Tian_Shan#Ecology) which houses a lot of wild apples.

**Comment by ghost** [comment]
If/when I get season integration I will make the apples fall off in early fall.  Otherwise having the apples fall off randomly sounds like a bad idea.

**Comment by Deshiba** [comment]
Cool, thanks for the response.
