### ISSUE TITLE
[1.18.2] Mystical World Charred Wood tree Dynamic Tree has Missing Texture  

### ISSUE THREAD

**Issue by caniplzjustlogin4godsakesthistakesforev** [ferreusveritas/Dynamic-Trees#742]
Attached are screen shots and a log file  incase it is helpful, (note that it will have a crash report in it because another mod causes a fatal error when saving the world, this is unrelated)
   This happens with or without rubidium.
Images 
[https://drive.google.com/drive/folders/1UFMhCkbTqB3NTgyRws-5Zg8_f6Su_Lef?usp=sharing](url)
and if helpful: latest.log
[latest.log](https://github.com/DynamicTreesTeam/DynamicTrees/files/10272708/latest.log)

**Comment by Harleyoc1** [comment]
Dynamic trees does not add support for other mods in itself. I believe DT support for Mystical World is built-in (on their end) so please report it to the Mystical World devs.
