### ISSUE TITLE
When starting minecraft, Dynamic trees fails to load

### ISSUE THREAD

**Issue by hudsonrockes** [ferreusveritas/Dynamic-Trees#745]
**Describe the bug**
org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4] {re:classloading}

**To Reproduce**
Unknown, it just started happening

**Additional context**

**Crashes**
[Crash Report](https://pastebin.com/ETU0qRnF)

What version of Forge are you running? (e.g. 1.12.2-14.23.5.2768)
forge-1.16.5-36.2.35

**Comment by Harleyoc1** [comment]
Not caused by DT - see #743.
