### ISSUE TITLE
[1.18.2] 2 minutes after joining a world, crashed.

### ISSUE THREAD

**Issue by itsdinkd** [ferreusveritas/Dynamic-Trees#746]
**Describe the bug**
No idea how to describe the bug. Crashed after witch was throwing potions at me

**To Reproduce**
I went into my modpack, AQM3, with Dynamic Trees and Dynamic Trees Plus added.
Join existing world
summoned a witch and was letting it throw potions at me (for another mod test)
crashed 5 seconds later

**Additional context**

**Crashes**
DynamicTrees-1.18.2-0.11.0-Beta5.jar
https://gist.github.com/itsdinkd/a9ac7ebd686c252ec64537eb73e78dd9

**Comment by hammertater** [comment]
This is my bad, I used a Dynamic Trees non-API class in my compat code without doing any safety checks. So, some refactoring in newer versions of Dynamic Trees broke the compatibility. I'll get it fixed on my end. See https://github.com/hammertater/treechop/issues/159 for a temporary fix.

Also, I think the fact that witches were throwing potions is just coincidental.
