### ISSUE TITLE
Any Branch Not Modifiable With Off-Hand  In Creative Mode

### ISSUE THREAD

**Issue by Pedrinho2015** [ferreusveritas/Dynamic-Trees#749]
**Feature request rules**
This is just a template to help you post a useful issue.  Erase these rules and any irrelevant categories and content as you see fit.

- Only submit issues related to the latest version of the mod for the currently supported version of Minecraft (which is currently 1.12.2 and 1.16.5).
- When referring to software versions always use the actual version number and never "latest".
- Do not request support for other mods (that should be done [here](https://github.com/ferreusveritas/DynamicTrees/issues/443)) or ports to other versions.
- Make sure feature requests come under the project scope. The details of this can be found on the [CurseForge page](https://www.curseforge.com/minecraft/mc-mods/dynamictrees).

If you are opening this **for any other reason** than to request a new feature, it will be closed without explanation! For bug reports, use the bug report template.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Pedrinho2015** [comment]
Branch Only Modifiable With Debug ### Stick_

**Comment by Harleyoc1** [comment]
I'm not sure what you mean by this? The branch is not meant to be modified in any other way?

**Comment by Pedrinho2015** [comment]
I Did A Wrong Name

**Comment by Pedrinho2015** [comment]
Name: Any Branch Not Modifable With Main Hand In Creative Mode

**Comment by Pedrinho2015** [comment]
I Did A Mistake Spelling ಠ⁠_⁠ಠ

**Comment by Pedrinho2015** [comment]
Probably No Debug Stick In 1.12.2 ._.

**Comment by Pedrinho2015** [comment]
**Misspelled**

**Comment by Pedrinho2015** [comment]
### **_sgsgsgsgsgsgsgsgsgsgsgsgsggsgsgsg_**

**Comment by Pedrinho2015** [comment]
### 

> 

- [ ] [_**ghhybdcrdfbrcsggrfhyerhrbfbthcdrdfgybdchhsbsrdghntbdsrcffdfgbhcfhgdfghhrcdybdgbhhcfydgbhcfhdbghfgrdffgdbhgbdbhbgdgbhbffdrdgvhffdgvhcfvvdvgbcfhdbhcfggdggbhcfndgbhhffdbhfgdbbghnffddvgbnffffvbgnvfdbbnvfggbgggdbnfbvvg**_](hhvcrfgbhhgbdcrfvhhsfbhhvgsdfchvbhsdffchbhygsrsedhyyyfrdghgbhdgsddbfgsdfdrbhggbhgdcfbgghgdbhffdgbhbgbhbvvfbfgfb)

**Comment by Harleyoc1** [comment]
> Probably No Debug Stick In 1.12.2 ._.

I'm still confused. Is this your issue? The debug stick is a vanilla item, not added by DT. I'm not sure exactly when it was added. If it doesn't exist in the version you're playing with you can set the `radius` blockstate using `/setblock`.
