### ISSUE TITLE
Dynamic Trees Failed to load

### ISSUE THREAD

**Issue by TheG1234** [ferreusveritas/Dynamic-Trees#752]
**Rules (Read this first!)**
This is just a template to help you post a useful issue.  Erase these rules and any irrelevant categories and content as you see fit. 

- Only submit issues related to the latest version of the mod for the currently supported version of Minecraft (which is currently 1.12.2 and 1.16.5).
- When referring to software versions always use the actual version number and never "latest".
- Use a paste site like [Gist](https://gist.github.com) or [Pastebin](https://pastebin.com) to dump any logs or crash reports. 

If you are opening this **for any other reason** than to report a bug, it will be closed without explanation! For feature requests, use the feature request template. **Do not** open bug reports for add-ons! These should be reported to their respective issue trackers. 

**Describe the bug**

**To Reproduce**

**Screenshots**

**Rendering Glitches**
Are you using OptiFine (or any equivalent mods that mess with rendering)?

**Additional context**

**Crashes**
- Are you running the latest version of Dynamic Trees? (Currently 0.9.23 in 1.12.2 or 0.10.0-Beta12 in 1.16.5)
- If you are using the DT Biome O' Plenty Add-on do you have the latest version? (Currently 1.4.2)
- If you are using the DT Thaumcraft Add-on do you have the latest version? (Currently 1.4.4)

If the above mods are current then please submit a full crash log. The crash log normally contains the names of mods and their versions. Don't be that guy who submitted a crash report without first checking that the versions are current.

Also, **do not** paste the crash report into the issue body! Use a paste site like [Gist](https://gist.github.com) or [Pastebin](https://pastebin.com).

**Mods List**
If your crash log does not contain a list of mods or you have no crash log then please provide a full list of the mods you are using complete with mod versions.
What version of Forge are you running? (e.g. 1.12.2-14.23.5.2768)

**Comment by Harleyoc1** [comment]
This is not enough info. You need to follow the template or at the very least post a crash report.
