### ISSUE TITLE
DT+ 1.18.2 forge 40.1.0 incompatibility 

### ISSUE THREAD

**Issue by twylightproto** [ferreusveritas/Dynamic-Trees#754]
Can there please be support for 40.1.0 please?

**Comment by Harleyoc1** [comment]
It is compatible? What is the problem because both DT and DT+ should work with Forge 40.1+?

**Comment by twylightproto** [comment]
no, i think its 40.1.51/41 or something

**Comment by Harleyoc1** [comment]
You think what is? Again I'm going to need you to explain what the incompatibility actually is. If it's a crash you need to send the crash report.

**Comment by twylightproto** [comment]
forge just says it's like incompatible, on the screen for incompatible mods

**Comment by Harleyoc1** [comment]
Just realised you're saying this is DT+ which is for some reason set to 40.1.51+. For future reference issues for DT+ need to be opened in its repository: [DynamicTreesTeam/DynamicTreesPlus](https://github.com/DynamicTreesTeam/DynamicTreesPlus). Anyway I don't really this being an issue, can you not just update Forge?
