### ISSUE TITLE
Dynamic Trees Mod loading error has occurred

### ISSUE THREAD

**Issue by Taishiokogaji** [ferreusveritas/Dynamic-Trees#755]
Hi, i was wondering if anyone can help me read this crash report to see what is going on. I know that it has to do with Dynamic trees but idk what other mods is making it crash.

Minecraft Ver: 1.16.5
Forge: 36.2.34
[crash-2023-02-20_16.30.33-fml.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/10788546/crash-2023-02-20_16.30.33-fml.txt)

**Comment by Harleyoc1** [comment]
Not caused by DT - see #743.
