### ISSUE TITLE
1.18.2 trees are not spawning

### ISSUE THREAD

**Issue by steverie119** [ferreusveritas/Dynamic-Trees#756]
i have been looking for a solution on the web for this issue and havent found any solution

              i have been having the same issue, namely spruce and dark oak trees

_Originally posted by @steverie119 in https://github.com/DynamicTreesTeam/DynamicTrees/issues/717#issuecomment-1445540284_

**Comment by steverie119** [comment]
it happens with BOP

**Comment by Harleyoc1** [comment]
Duplicate of #717

**Comment by Harleyoc1** [comment]
Please keep comments to the original issue. So is this an issue with BOP? Do you have the add-on installed and if so does it happen if the add-on is not installed?

**Comment by steverie119** [comment]
it worked for initial generation then to seemed to have broke again
