### ISSUE TITLE
Cutting the tree at it's base will fell the entire tree

### ISSUE THREAD

**Issue by DTX3** [ferreusveritas/Dynamic-Trees#757]
Version: 1.18.2 -0.11.0-Beta7

**Describe the bug**
When cutting the tree at the base, it doesn't take down the entire tree. 

**To Reproduce**
Cut the base of the tree with an axe

**Screenshots**
![image](https://user-images.githubusercontent.com/59918994/222269657-ccc9d225-e9c8-4f65-a3e2-4a0fc7dbabe6.png)

What version of Forge are you running? 40.2.0

**Comment by Harleyoc1** [comment]
That isn't a dynamic tree...

Note that if you add this mod to your worlds vanilla trees are not converted in chunks that were already generated. If this was generated after installing DT it may be that a worldgen mod you have installed is incompatible.
