### ISSUE TITLE
Tree Generation Issues on Server Reload (18.2)

### ISSUE THREAD

**Issue by Meshinator69** [ferreusveritas/Dynamic-Trees#759]
**Describe the bug**
World Generation happens normally with only BOP, Terrablender, Dynamic Trees (BOP DT, and DT+), until I reload the server once. (And I am shutting it down gracefully.) 

I have isolated so far is, world gen is normal, until a single server reload/reset. Then:

1) If Dynamic Trees + is installed, the no trees bug happens in many biomes (Savanna, Taiga, Forest etc) 
2) If Dynamic Trees + is NOT present, the Dark Forest Trees filling the Savanna happens instead. 

Regardless if DT+ is installed or not installed, Maple Woods, Snowy Maple Woods, and Wooded Wasteland do not spawn trees at all. 

**To Reproduce**
Generate a world, go to a Savanna (if DT+ is not installed) or any forested biome (forest, taiga, savanna etc) if DT+ is installed, restart the dedicated server, and then the issue will be there, trees will be gone (or incorrect species) It should be noted it never crashes - when this happens, and the biomes are still tagged correctly in game.

**Comment by Meshinator69** [comment]
Also - when I say the trees disappear, I mean from newly generated chunks, it does not affect previously generated chunks.

**Comment by SpaceTruckinn** [comment]
I'm running into this also. Same thing with maple woods, sometimes happens on savanna. Starting a single biome world in maple woods also yields a treeless maple woods.

**Comment by SpaceTruckinn** [comment]
**I figured out the issues with certain BOP biomes not generating any trees:** 
in `(mod jar)\trees\dtbop\world_gen\default.json` several biomes do not have generation code blocks and a few have incorrect biome names. Ex. snowy maple woods in the json is called 'snowy_maple_forest', changing forest to woods fixed the trees not generating in that biome. Regular maple woods was missing a generation code block entirely, duplicating the snowy variant's code block and changing the biome name to just `maple_woods` fixed the issue and trees are now generating in regular maple woods.

For the main issue where trees quit generating after reloading a world, it seems to only be happening with vanilla biomes. I'm digging through to try and figure this out also, can't play the game with this bug and can't go back to ugly vanilla trees. Is any DT generation data stored in save files? Maybe inconsistencies with tree type names there also.

(below) Joruneymap export showing a test world I made in a single biome Old Growth Pine world. Clearly visible border showing where trees quit generating after closing the game and reloading the save.
![here is a journeymap](https://i.imgur.com/VoZfaO9.png)

**Comment by optionalduck** [comment]
Noticed the same behavior. I was trying to set up a small server with my friend to play together and so I pre rendered a ton of chunks on creation of the new save hopefully we can stay within it until a fix comes out .

 I am using dynamic tress plus and the quark compatibility mods also, I was able to re create it in a single player single biome forest world 
![2023-04-24_22 00 21](https://user-images.githubusercontent.com/34895401/234157080-be52a84a-fdfe-4b77-b3d4-b4c481c4fb9f.png)
![2023-04-24_22 01 45](https://user-images.githubusercontent.com/34895401/234157083-c3ae5098-4325-4ce9-adca-174f0b94029b.png)
