### ISSUE TITLE
Dynamic Branches useless

### ISSUE THREAD

**Issue by shootHug** [ferreusveritas/Dynamic-Trees#76]
Dynamic  branches are useless for building, only good for burning. 
- branches placeable like cobblestone- walls
- thin branches always drop Sticks
- change Itemname to Oak / Spruce... Branch
- branches lie on the ground, instead of flying
thx for your work, really enjoy playing!

**Comment by ghost** [comment]
- branches are not for building structures except trees and are only obtainable in creative mode.
- thin branches are supposed to drop sticks
- no.  branches are part a tree so a branch should always be in a tree.  Thus the name is correct.
- no they don't.  that doesn't make any sense.

**Comment by shootHug** [comment]
sorry, i used the mod 'chop down' which dropped a lot of them.
I think this would be a nice addition.
