### ISSUE TITLE
Doesn't harm some animals

### ISSUE THREAD

**Issue by Ashwinaaaaaaahdt** [ferreusveritas/Dynamic-Trees#764]
When a tree falls and the player is standing where the tree falls it would harm the player 
But the same function doesn't apply to the other entities like enderman or chicken or any other entities 

Minecraft version:1.16.5
Forge version:36

**Comment by Harleyoc1** [comment]
It's certainly supposed to and I have tested this before. Are you sure their hit box should definitely be hit in their position at the time the tree falls?

**Comment by Ashwinaaaaaaahdt** [comment]
> It's certainly supposed to and I have tested this before. Are you sure their hitbox should be hit in their position at the time the tree falls?

If the top of the tree falls on them
they remain unharmed
