### ISSUE TITLE
DynamicTrees-1.18.2 Beta8 breaking water shader with SEUS Renewed. 

### ISSUE THREAD

**Issue by CoDroStyle** [ferreusveritas/Dynamic-Trees#768]
**Describe the bug**
When loading world the water shader is broken when using SEUS Reviewed 1.0.1. 

The current full release Optifine version for 1.18.2 is OptiFine HD U H7 which requires Forge 40.0.24.
Dynamic trees for 1.18.2 requires minimum forge 40.1.0 or it will fail to load.

In order too use DynamicTrees 1.18.2 with Optifine we are required to use one of the Optifine previews that support forge 40.1+
I have tried:
- H8pre1
- H9pre1/2/3
All of them have the same issue where the water shader is broken & Dynamic trees does not work. (Vanilla trees).

**To Reproduce**
Install forge-1.18.2-40.1.85
Install OptiFine_1.18.2_HD_U_H9_pre2
Add to Mods folder
- OptiFine_1.18.2_HD_U_H9_pre2
- DynamicTrees-1.18.2-0.11.0-Beta8.jar 

<< Launch forge-1.18.2-40.1.85 game >>

**Rendering Glitches**
YES

**Mods List**
- forge-1.18.2-40.1.85
- OptiFine_1.18.2_HD_U_H9_pre2
- DynamicTrees-1.18.2-0.11.0-Beta8.jar
-Patrix - 1.18 - 64x Resource pack

**Comment by Harleyoc1** [comment]
Assuming the water shader is broken regardless of whether DT is installed or not on those preview versions of OptiFine, it needs to be reported to either Seus or OptiFine as that's not our issue and there's not really anything we can do about that.
