### ISSUE TITLE
leaves instantly regrow.

### ISSUE THREAD

**Issue by Shane371** [ferreusveritas/Dynamic-Trees#77]
Any way to slow down or stop leafs from instantly growing back? On its own its fine but can cause some minor hilarity with other mods. Like primals breaking leaves for sticks or packs that use leaves to get X. (water, seeds ect)

**Comment by GottJammern** [comment]
I am interested in this as well, if only to sculpt for aesthetics.

**Comment by ghost** [comment]
Not really any way to do that. No.  If fake air blocks were put into place when a leaves block was broken then a player could just replace the fake air with any block, break it and get it back to normal air where leaves could spawn.  Trees can't be sculpted, they will grow where they can.  Sorry.
