### ISSUE TITLE
No drops when breaking trees.

### ISSUE THREAD

**Issue by Moonively210** [ferreusveritas/Dynamic-Trees#772]
Whenever I break a tree, I get nothing from it. Could this bug be because I have the TreeFalling mod by rakambda? I assume that it is but I'd like to be sure.

**Comment by chisaato** [comment]
+1 I also meet this problem.

**Comment by chisaato** [comment]
![image](https://user-images.githubusercontent.com/17796830/233745187-512b76b9-d549-4f88-b185-b94fe247c7ed.png)

Translate: 
SNEAK_DISABLE disable mod when sneaking
SNEAK_ENABLE enable mod when sneaking
IGNORE always enable and ignore sneaking

Here  is an workaround. Hold Shift to disable TreeFalling. then DynamicTrees can work well.

In config `fallingtree.json` . 

```json
{
  "sneakMode": "SNEAK_DISABLE",
}
```

**Comment by Moonively210** [comment]
Thank you, this helped out.

**Comment by chisaato** [comment]
or add dynamic trees blocks to fallingtrees balcklist. then you can cut trees without holding shift.

**Comment by Harleyoc1** [comment]
Closing this issue since it's related to mod compatibility with something not really made to be used with DT (dynamic trees already fall when chopped) and it seems there's a fix regardless.
