### ISSUE TITLE
1.18.2 Dynamic trees don't drop seeds on growth and they despawn instead of planting themselves.

### ISSUE THREAD

**Issue by xFirefalconx** [ferreusveritas/Dynamic-Trees#774]
DynamicTrees-1.18.2-0.11.0-Beta10.1

**Describe the bug**
Trees don't drop seeds without destroying part of them. The dropped seeds from destruction, or dropped from the inventory don't generate new saplings, they just despawn. Tested with tick speed 400 and lower.
https://gist.github.com/xFirefalconx/3040dd022a16e09373214e5323402fa0 latest log, it might not be helpful at all. 

**To Reproduce**
Steps to reproduce the behavior: You can download my old modpack version and upgrade Dynamic Trees to the 0.11.0-Beta10.1 as you see fit. Might make things faster, Name is "Royal Equines:Petrified Magic".
Ingame, you find a biome with vanilla trees by opening the creative inventory, picking a nature's compass, navigate to any that includes dynamic trees. Press teleport and then pick a chunk spawner, place it, right click on it. If that's too many steps, use the command "/execute in chunkbychunk:skychunkgeneration run teleport ~ ~ ~", find the biome, etc.
Within the biome:
Observation 1: The tree biomes are not fully habitated with trees, there is a large field with just empty grass space. Is this intentional so they can expand until that area is filled? 
Observation 2:  There are no seed drops. Wait as long as you wish, there will be none. Maybe it's not yet implemented, but I remember it being a feature in past versions. If that's the case, my apologies, then mark this as "Beta, WIP" and ignore the rest.
Observation 3: When seeds get dropped from the inventory or by destroying parts of the existing trees, they don't plant themselves. Drop a stack, just to be sure. 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/106652912/233872818-d6540879-1505-485a-9f24-f26546dd4893.png)

**Additional context**
Maybe there is a gamerule I am not aware of or a missing setting. 

**Mods List**
What version of Forge are you running? 40.2.0

Disclaimer: Not all of these mods are involved in the bug, maybe not even any other than dynamic trees itself, maybe additionally Chunk by Chunk within the CBC generated world map. Maybe it's caused by Chunk by Chunk because the player starts in a different dimension, or by the mod that plants forests with vanilla saplings, or that sort. 
As I'm working on my modpack update, I will include all currently loaded mods, though. The list... might change. I also have mods in there that I deactivated, I don't list them here. Let me know if you need any extra info, I can also fetch you a new latest.log from startup only if you need that in any case.

VariantCraftingTables-1.18.2-1.7.0_1
VendingMachine-1.18.2-1.0.8
verdure-1.18.2-1.1.3a
villagebellrecipe-1.18.2-3.0
village-employment-1.18.2-1.5.1
villagernames-1.18.2-5.2
VillagersRespawn-1.18.1-1.39.0.5
villagertools-1.18-1.0.2
villagespawnpoint-1.18.2-4.0
waystone_towers-1.18.2-FORGE-1.0.9
waystones-forge-1.18.2-10.2.0
weaponleveling-1.18.2-1.4.3
WhatTheBucket-Forge-1.18.2-4.0.2
wildberries-1.1.2[forge-1.18.2]
wooltostring-forge-1.18.2-1.0.1
workers-1.18.2-1.5.2
XPFromHarvest-1.18.2-1.2.2
xptome-1.18.2-2.1.7
(Forge)SimpleMango-1.18.2-1.2.0
3dskinlayers-forge-1.5.2-mc1.18.2
AbsolutelyUnbreakable1.18.2-2.0.1-1.18.2
adaptive_performance_tweaks_core_1.18.2-3.20.1
adaptive_performance_tweaks_player_1.18.2-3.18.0
AkashicTome-1.5-20
anviltooltipmod-MC1.18.2-1.0.0
appleskin-forge-mc1.18.2-2.4.1
architectury-4.11.90-forge
areas-1.18.2-4.3
ArtisticCraft v0.16.1-1.18.2
astikorcarts-1.18.2-1.1.2
atmospheric-1.18.2-4.0.0
autoplant-1.18.2-1.0.0
AutoRegLib-1.7-53
BadMobs-1.18.2-13.01
balm-3.2.6
bamboo2-1.18.1_0.4
BambooEverything-forge-1.3.8-build.45+mc1.18.2
Barsita-1.18.2-1.0.2
BeeFix-1.18-1.0.7
beehive-tooltips-forge-1.4.2
Beekeeper-1.18.2-1.0.5
benched-1.2.2-forge-mc1.18
Better Fishing Rods 1.0.0 - 1.18.2
BetterAdvancements-1.18.2-0.2.0.146
betterbeaconplacement-1.18.2-3.1
BetterBeekeeping-1.18.2-1.2.0
BetterCompatibilityChecker-1.1.21-build.48+mc1.18.2
betterconduitplacement-1.18.2-3.0
BetterCrates-1.18.2-1.0.0
betterfoliage-3.1.4
betterfpsdist-1.18.2-1.5
BetterLogs-1.18.2-(3.0)
bettersafebed-1.18-forge-a
betterspawnercontrol-1.18.2-4.0
bettertaskbar-forge-mc1.18.2-mc1.19.2-1.5.1
BetterThirdPerson-Forge-1.18.2-1.9.0
BetterTitleScreen-1.18-1.12.0
bettervillage-forge-1.18.2-3.1.0
Beyond-Earth-1.18.2-6.2
BiomesOPlenty-1.18.2-16.0.0.109-universal
biomespawnpoint-1.18.2-2.0
blueprint-1.18.2-5.5.0
Book Fishing 1.0.0 - 1.18.2
Bookshelf-Forge-1.18.2-13.2.53
BorderlessWindow-1.18-1.4.0
brb-1.18.2-forge-1.5.6
burgermod-2.8.0-1.18.2
canary-mc1.18.2-0.1.6
carryon-1.18.2-1.17.0.8
cell-lever-1.18-3.0.0.1
cherryblossomgrotto-0.4.6-v1.18.2
Chimes-1.1.2-1.18.2
ChinjufuMod[1.18.2]6.2.4
chipped-forge-1.18.2-2.0.1
ChiselsBits-forge-1.18.2-1.2.116-universal
ChunkByChunk-forge-1.18.2-1.13.2
chunkloaders-1.2.3-forge-mc1.18
citadel-1.11.3-1.18.2
citydecor-1.1.1
cloth-config-6.4.90-forge
Clumps-forge-1.18.2-8.0.0+17
cobbled_paths-forge-0.1.7
CobbleForDays-1.5.1
collective-1.18.2-6.53
configured-2.0.1-1.18.2
connectedglass-1.1.6-forge-mc1.18
Controlling-forge-1.18.2-9.0+22
cookingforblockheads-forge-1.18.2-12.2.0
Copper Armory Remastered 1.2.1 1.18.2
corn_delight-1.0.6-1.18.2
CraftPresence-2.0.0-rc.2+1.18.2
Crated_Vanilla_Foods_1.1-1.18.2
create_food-1.18.2
create-1.18.2-0.5.0.i
creeperconfetti-3.11
crittersandcompanions-1.18.2-1.0.2
Croptopia-1.18.2-FORGE-2.1.0
croptopia-chocolaterie-1.1
CTM-1.18.2-1.1.5+5
Curses_and_magic_1.9_1.18.2
CustomLAN-1.18.1-18.1.2
deepslate_dubble003
Dessertv1.3
DiagonalFences-v3.1.0-1.18.2
Disenchanting-forge-1.18.2-2.2.2
drippyloadingscreen_forge_2.1.4_MC_1.18.2
DungeonCrawl-1.18.2-2.3.12
durabilitytooltip-1.1.4-forge-mc1.18
DynamicSurroundings-5.0.0.4
DynamicTrees-1.18.2-0.11.0-Beta10.1
DynamicTreesBOP-1.18.2-3.0.0-Beta3
DynamicTreesPlus-1.18.2-0.2.0-Beta4
DynamicTreesQuark-1.18.2-2.2.3
EnchantmentDescriptions-Forge-1.18.2-10.0.12
EnderBags-1.18.1-8.0.0
ExNihiloSequentia-1.18.2-20221113-044349
exoticbirds-1.18.2-1.8.0
ExplorersCompass-1.18.2-1.3.0-forge
ExtendedItemInformation-4.0.2-1.18.2
fancymenu_forge_2.14.3_MC_1.18.2
fantasyfurniture-1.18.2-3.14.0
FarmersDelight-1.18.2-1.2.0
FarmersRespite-1.18.2-1.3.0
farmingforblockheads-forge-1.18.2-10.0.2
FastLeafDecay-28
Fastload-Reforged-2.6.9+1.18.2
FemaleVillagers-1.18.2-1.5a
ferritecore-4.2.2-forge
flytre_lib-1.18.2-1.8.2-forge
flywheel-forge-1.18.2-0.6.8.a
fm_animation_maker_1.2.0
forgivingvoid-forge-1.18.1-6.0.1
FramedBlocks-5.11.4
FruitTrees-1.18.2-forge-5.0.1
ftbbackups2-forge-1.18.2-1.0.18
GameMenuModOption-1.18-Forge-1.14.2
geckolib-forge-1.18-3.0.57
guardvillagers-1.18.2.1.4.3
HammerLib-1.18.2-18.2.16
hauntedharvest-1.18.2-1.7.7
hedgehog-1.18.2-1.1.0
hexerei-0.2.2
hole_filler_mod_1.2.5-mc_1.18.1-forge
honeyexpansion-1.1.1
horse_colors-1.18.2-1.8.0
IBICF-1.4.0-build.8+mc1.18.2
InfoDataPack-1.18.1-2.0.2.8
itemcollectors-1.1.7-forge-mc1.18
ItemLocks-Forge-1.18.2-1.3
Jade-1.18.2-forge-5.2.6
jei-1.18.2-9.7.1.255
JEIEnchantmentInfo-1.17.1-2.0.0
journeymap-1.18.2-5.9.5-forge
JustEnoughResources-1.18.2-0.14.1.171
keepmysoiltilled-1.18.2-2.0
kingvillager-1.10
Kiwi-1.18.2-forge-6.1.3
kleeslabs-forge-1.18.2-11.1.1
konkrete_forge_1.6.0_MC_1.18-1.18.2
largemeals-1.18.2-2.0
lazydfu-1.0-1.18+
Level-One-MC1.18.2-v1.6.0
libraryferret-forge-1.18.2-4.0.0
little_geode 1.18.2-1.3.0
majrusz-library-1.18.2-3.3.0
majruszs-accessories-1.18.2-1.1.4
manascore-1.18.2-1.0.2.0
ManyIdeasChristmas-1.18.2-1.0.0
ManyIdeasCore-1.18.2-1.4.1
ManyIdeasDoors-1.18.2-1.2.0
ManyIdeasHalloween-1.18.2-1.0.0
mcw-bridges-2.0.7-mc1.18.2forge
mcw-doors-1.0.9forge-mc1.18.2
mcw-fences-1.0.7-mc1.18.2forge
mcwfencesbop-1.18.2-1.4
mcw-roofs-2.2.3-mc1.18.2forge
mcw-windows-2.1.1-mc1.18.2forge
MemorySweep-1.18.2-0.8
merenc-forge-1.18.x-v1.9
minecard-1.18.2-0.3.0
mmlib-1.2.0-1.18.2
MobCatcher-Forge-1.18.2-1.1.6
modernfix-mc1.18.2-2.3.2
modnametooltip-1.18.1-1.18.0
MoreCrashInfo-2.3.1
MoreMobGriefingOptions-1.18.2-2.0.1
moreoverlays-1.20.11-mc1.18.2
MouseTweaks-forge-mc1.18-2.21
movingelevators-1.3.12-forge-mc1.18
Multiplayer-Server-Pause-1.18-Forge-1.1.0
Mushroom_Villager1.18.2beta
NaturalDecorMod_1.18.2_V0.1.5
NaturesCompass-1.18.2-1.9.7-forge
Netherited-forge-1.18.2-1.2.1
netherportalfix-forge-1.18.2-9.0.1
nocubes_better_fletching_table_1.0.0_forge_1.18.2
nocube's_better_frogs_1.0.0_forge_1.18.2
nocube's_better_smoker_1.0.0_forge_1.18.2
nocube's_villagers_sell_animals_1.2.0_forge_1.18.2
oculus-1.5.2
oculus-flywheel-compat-1.18.2-0.1.8-BETA
Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.7
OpenLoader-Forge-1.18.2-12.0.1
overweightfarming-1.18.2-1.6.0-forge
passiveendermen-1.18.2-4.2
Patchouli-1.18.2-71.1
Pehkui-3.7.3+1.18.2-forge
pettransfer-1.18.2
Placebo-1.18.2-6.6.6
player-animation-lib-forge-1.0.2+1.18
polylib-forge-1801.0.2-build.13
polymorph-forge-1.18.2-0.46
PriorityTarget-Forge-1.18.2-2.0.2
productivevillagers-1.0.6
projectsavethepets-3.1.0-old.1.18+2022.10af157d70.forge
PuzzlesLib-v3.3.6-1.18.2-Forge
Quark-3.2-358
QuarkOddities-1.18
Random_mailbox_1.0.0_1.18.2
randomvillagenames-1.18.2-3.2
randomworldname-2.1
realisticroads-v2
RecipesLibrary-1.18.2-2.0.0
RedstoneExtras-1.18-1.0.11
Regrowth-1.18.2-1.40.31.1
Roads-1.18.1-1.4.0
rubidium-0.5.6
SaveSettings-1.0.0
SBM-Jukebox-1.18-1.0.4
seamless_loading_screen-1.18-3.0.0
seasonhud-1.18.2-1.4.10
selene-1.18.2-1.17.9
Serene Seasons-1.18.2-7.0.0.13
sereneseasonfix-1.18.2-1.0.6
SereneShrubbery-1.18.2-1.4.0
SHAB (1.18.2) V1.1.1
sit-1.18.2-1.3.3
skylightlanterns-1.18.2-1.0.0
smarterfarmers-1.18.2-1.6.0
smoothboot(reloaded)-mc1.18.2-0.0.2
SnowRealMagic-1.18.2-forge-4.2.4
snowyspirit-1.18.2-1.3.2
so_many_enchants-1.8.0 (1.18)
SoL-Carrot-1.18.1-1.12.0
sootychimneys-1.18.2-1.0.0l
sophisticatedbackpacks-1.18.2-3.18.44.814
sophisticatedcore-1.18.2-0.5.48.244
sophisticatedstorage-1.18.2-0.6.25.324
spells_and_shields-1.18.2-1.10.2-LEGACY
starlight-1.0.2+forge.546ae87
StructureCompass-1.18.2-1.3.2
supermartijn642configlib-1.1.6-forge-mc1.18
supermartijn642corelib-1.1.7-forge-mc1.18
supplementaries-1.18.2-1.5.16
swingthroughgrass-1.18.2-1.9.1
Teerth's Traffic Control 4.0.0
TerraBlender-forge-1.18.2-1.2.0.126
TexelsPaintings-forge-1.18.2-5.1.0
Tips-Forge-1.18.2-5.0.11
Toasty Coins 1.1
torchmaster-18.1.0
towns_and_towers_forge-1.10.0.1+1.18.2
Traffic_Plus_1.3.0_1.18.2
UniversalEnchants-v3.0.6-1.18.2-Forge
unordinary_basics-1.18.2-1.0.1.4
untamedwilds-1.18.2-2.3.0

**Comment by Harleyoc1** [comment]
You're misunderstanding how these mechanics work. To address your observations:

1. The trees only drop randomly in biomes with a high forestness<sup>1</sup>.
2. Seeds have a very rare chance<sup>2</sup> to drop 'voluntarily' (randomly without player intervention).
3. By default, and also based on biome suitability, seeds have a 1/6 chance<sup>3</sup> per tick to plant themselves once dropped on the ground.

Hope this clears things up.

<sup>1</sup> Configurable via [biome database populator](https://github.com/DynamicTreesTeam/DynamicTrees/wiki/Tree-Packs:-World-Generation).
<sup>2</sup> Configurable via `voluntarySeedDropRate`  in the server config.
<sup>3</sup> Configurable via `seedPlantRate` in the server config.
