### ISSUE TITLE
1.16.5 Crash on Start

### ISSUE THREAD

**Issue by Amber9572** [ferreusveritas/Dynamic-Trees#776]
I am switching back from 1.18.2 to 1.16.5 and am checking my setup for crashes and got one with base Dynamic Trees. The crash is on start, before getting to the splash screen. I hopefully added the crash and screenshot correctly. I don't have Optifine, (Don't think it could effect this crashing, but its in the list, so there you go). Oh, the crash log will say I'm behind on updates by one version, but I've tried with the most recent update too, I was just checking to see if it was an incompatibility with other mods or something. I do have Biomes o' Plenty and Terraforged but I don't have a 1.16 save game made yet. Forge Version is 36.2.39, and I don't know if it effeects anything, but I'm using ATLauncher with a custom Instance

[crash-2023-04-24_23.20.55-fml.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/11316147/crash-2023-04-24_23.20.55-fml.txt)
![Screenshot (38)](https://user-images.githubusercontent.com/55097977/234167647-f0e531fc-6d7e-4e6c-9d48-920d6f69649b.png)

**Comment by Amber9572** [comment]
I found AN incompatibility/ies, CaveBiomeAPI and Caves & Cliffs Backport. I dunno which mod is interfering with which, though.

**Comment by Harleyoc1** [comment]
Yes, this is an issue on CaveBiomesAPI's end (https://github.com/DynamicTreesTeam/DynamicTrees/issues/743).
