### ISSUE TITLE
Mod Incompatability with Hostile Villages - 1.18.2

### ISSUE THREAD

**Issue by Waterspark63** [ferreusveritas/Dynamic-Trees#777]
I had tried to add Dynamic Trees to my modpack, and after some debugging, I have found that Dynamic Trees and Hostile Villages are not compatible, here's the log with the error for the two mods. This is 1.18.2, using forge 40.2.0. The null issue at the very end is a separate thing, possibly with forge/mc itself after asking a discord for troubleshooting support, it is unrelated to the mod incompatibilities.
[latest.log](https://github.com/DynamicTreesTeam/DynamicTrees/files/11357515/latest.log)

**Comment by Harleyoc1** [comment]
I just thought of a temporary workaround for this - set `cancelVanillaVillageTrees` to `false` in the common config (located at `config/dynamictrees-common.toml`).

The only problem is that vanilla trees will spawn in villages (unless Hostile Villages also removes these - I'm unsure of what it changes).

**Comment by Waterspark63** [comment]
Sorry for the late reply, but that does fix it for the moment, thank you!
