### ISSUE TITLE
Adding a description/tutorial on how to use default.json worldgen config file to Curseforge's description.

### ISSUE THREAD

**Issue by VOLKOUL** [ferreusveritas/Dynamic-Trees#778]
Heyyy!

So I wanted to make some biomes keep the vanilla tree gen and after quite a bit of searching I came across [this](https://github.com/DynamicTreesTeam/DynamicTrees/issues/270#issuecomment-506459346) post. Apparently it's the _only_ mention I could find that explains how it's possible for me to edit worldgen.
(or maybe I'm just blind idk :P) (there was also something about a tree canceller? but I couldn't find it again)

Anyways, I think that it would be really helpful for modders if such a mention/reference was present on the main Dynamic Trees page of Curseforge or another website if there is one! 

So yeah, that's pretty much it)

**Comment by Harleyoc1** [comment]
There is actually documentation on the Wiki [here](https://github.com/DynamicTreesTeam/DynamicTrees/wiki/Tree-Packs:-World-Generation), under the new tree packs section (which the worldgen file is now a part of as of 1.16.5+). Although yes, we should definitely add a mention/link to this on the CF page, thanks for the suggestion!
