### ISSUE TITLE
upgrade

### ISSUE THREAD

**Issue by MrH1616** [ferreusveritas/Dynamic-Trees#779]
I do not want to sound like some ungrateful Minecraft player bossing you and your team around, I love your mod, and it's so immersive and made so well, I have a 1.18.2 server with it installed, but my favorite server with 1.19 exclusive mods can't run it, so I'm asking if you guys can upgrade it to 1.19.3 and if you can't I'm wondering if you can in the future because of dependency issues right now or something if you guys find time can you respond so I can know what's going on with one of my favorite Minecraft mods

**Comment by Harleyoc1** [comment]
Simply a fact of a lot of work goes into porting and maintaining this mod, and we're all busy people. We'll get around to porting at some point, though I can't speak for how long it will take.
