### ISSUE TITLE
Cant place potions on trees.

### ISSUE THREAD

**Issue by geneangela** [ferreusveritas/Dynamic-Trees#780]
Right clicking the base/root of the tree does not work at all.

![image](https://github.com/DynamicTreesTeam/DynamicTrees/assets/50388370/7c89e846-2be8-416f-9e3c-bca908d5f0d6)

**Comment by Harleyoc1** [comment]
The potion being used in the screenshot is the potion of gigas - this will only work on trees that have a mega variant (spruce and jungle only by default). I may add this to the tooltip to avoid future confusion.
