### ISSUE TITLE
Crash 1.19.2 when i click on create a new world

### ISSUE THREAD

**Issue by Thysium** [ferreusveritas/Dynamic-Trees#783]
Minecraft 1.19.2
Forge : 43.2.11
Dynamic Trees : DynamicTrees-1.19.2-1.1.0-BETA1

Hello, my game crashes with Dynamic Trees when i click on create a new world.

https://pastebin.com/LiGfiaYw

**Comment by Harleyoc1** [comment]
Could you confirm whether this is still an issue for you on the latest beta please? I haven't been able to reproduce it.

**Comment by Harleyoc1** [comment]
Since there's been no further reports of this I'm going to assume this fixed. If you (or anyone else) encounters this on the latest 1.19.2 version please do feel free to comment and we can re-open it.
