### ISSUE TITLE
branch inside of solid block cause server crash

### ISSUE THREAD

**Issue by albert1000000** [ferreusveritas/Dynamic-Trees#789]
_Only submit issues related to the latest version of the mod for the currently supported version of Minecraft (which is currently 1.12.2 and 1.16.5)._
This is for 1.18.2, for documentation purposes and I really want to support this mod going into later versions.

_**Describe the bug**_
Multiplayer server crash, including crash log.  Restarting the server there is no problem and the offending dynamic tree is gone.

_**To Reproduce**_
A branch from dynamic trees exists inside of a stone block on the side of the mountain.  cutting down the tree leaves the branch.  cutting the leftover branch crashes the server.  It is of note that the axe in question has the chainsaw enchantment from apotheosis which only should affect regular trees, but as that is significant I want to include that information.

_**Screenshots**_
server log available only for now

_**Rendering Glitches**_
none

_**Additional context**_
none

_**Crashes**_
Are you running the latest version of Dynamic Trees?
1.0.3 for 1.18.2
Attaching crash report
[crash-2023-07-03_08.07.17-server.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/11938935/crash-2023-07-03_08.07.17-server.txt)

_**Mods List**_
see crash report

**Comment by Harleyoc1** [comment]
The crash report says you are running 1.0.2, is this still an issue on 1.0.3? Regardless I'm confused by how a branch would generate inside stone?
