### ISSUE TITLE
Update Breaks BoP addon

### ISSUE THREAD

**Issue by malice936** [ferreusveritas/Dynamic-Trees#79]
[https://pastebin.com/rPq6nKZx](https://pastebin.com/rPq6nKZx)
Crash for reference seems you removed something that the addons were using thus breaking them, pretty sure this would affect the thaumcraft addon as well I just don't have greatwoods or silverwoods planted in my world.

**Comment by ghost** [comment]
Yes.  Bop Add-On should be along sometime today.
