### ISSUE TITLE
Fabric port?

### ISSUE THREAD

**Issue by vadim-a-yegorov** [ferreusveritas/Dynamic-Trees#790]
Would be great to see 1.18.2 Fabric port, is it planned?

**Comment by Proxwian** [comment]
Только во влажных мечтах.

**Comment by Harleyoc1** [comment]
I'm afraid not. It will be staying Forge for the time being.

**Comment by BioTechproject27** [comment]
Awh man, a fabric or even quilt port would be pretty cool. Especially for newer versions.
This is such a great mod!!
