### ISSUE TITLE
Got `java.lang.IllegalArgumentException: Cannot get property EnumProperty{name=coredir, clazz=class com.ferreusveritas.dynamictrees.util.CoordUtils$Surround, values=[N, NW, W, SW, S, SE, E, NE]} as it does not exist in Block{minecraft:deepslate}` when calling `state.getDestroySpeed` of a `BlockWithDynamicHardness$DynamicHardnessBlockState` object.

### ISSUE THREAD

**Issue by isning** [ferreusveritas/Dynamic-Trees#792]
Minecraft Version: 1.19.2

**Describe the bug**
Got `java.lang.IllegalArgumentException: Cannot get property EnumProperty{name=coredir, clazz=class com.ferreusveritas.dynamictrees.util.CoordUtils$Surround, values=[N, NW, W, SW, S, SE, E, NE]} as it does not exist in Block{minecraft:deepslate}` when calling `state.getDestroySpeed` of a `BlockWithDynamicHardness$DynamicHardnessBlockState` object.

Log is here: https://paste.myself5.de/vexayixeqa.md

**To Reproduce**
Install Weather2 and DynamicTrees mod onto server and generate a storm near a tree(Maybe?) by `/weather2 summon tornado_f4`

**Rendering Glitches**
Weather2
But this seems to be not related to rendering, because this is an server-side error

- Are you running the latest version of Dynamic Trees? 1.1.0-BETA3 for 1.19.2
- If you are using the DT Biome O' Plenty Add-on do you have the latest version? Yes, I ported it by myself

**Mods List**
What version of Forge are you running? 1.19.2-43.2.17
BOP version: 17.1.1.162
Weather2(Ported to 1.19.2 by myself: https://github.com/Corosauce/weather2/pull/583)
DynamicTrees-BOP(Ported by myself: https://github.com/DynamicTreesTeam/DynamicTrees-BOP/pull/101)
DynamicTrees-Quark(Ported by myself: https://github.com/DynamicTreesTeam/DynamicTrees-Quark/pull/7)

**Comment by Harleyoc1** [comment]
[This](https://github.com/ISNing/weather2/blob/66df05c57519a9332a3f0751ac3a7ee964c1aba3/src/main/java/weather2/util/WeatherUtil.java#L201) is the line causing issue (part of Weather 2). The hardness of DT branches is position/state dependent and it is passing the zero BlockPos.
