### ISSUE TITLE
Warning: Tried to create a EntityFallingTree with no branch blocks. This shouldn't be possible.

### ISSUE THREAD

**Issue by iMord0** [ferreusveritas/Dynamic-Trees#793]
I get error from the title all over the logs. - It causes lags or server crash.
Version I'm running - DynamicTrees-1.12.2-0.9.29.jar using MC Forge 1.12.2 - 14.23.5.2860

**To Reproduce**
Just cut any tree

**Additional context**
These logs are from RLCraft server (Release v2.9.3)

Example log output:
> [20:41:16] [Server thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.entities.EntityFallingTree:setData:101]: Warning: Tried to create a EntityFallingTree with no branch blocks. This shouldn't be possible.
> [20:41:16] [Server thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.entities.EntityFallingTree:setData:102]: java.lang.Exception
> [20:41:16] [Server thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.entities.EntityFallingTree:setData:102]:     at com.ferreusveritas.dynamictrees.entities.EntityFallingTree.setData(EntityFallingTree.java:102)
> [20:41:16] [Server thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.entities.EntityFallingTree:setData:102]:     at com.ferreusveritas.dynamictrees.entities.EntityFallingTree.dropTree(EntityFallingTree.java:483)
> [20:41:16] [Server thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.entities.EntityFallingTree:setData:102]:     at com.ferreusveritas.dynamictrees.blocks.BlockBranch.futureBreak(BlockBranch.java:432)
> [20:41:16] [Server thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.entities.EntityFallingTree:setData:102]:     at com.ferreusveritas.dynamictrees.event.FutureBreak.process(FutureBreak.java:47)
> [20:41:16] [Server thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.entities.EntityFallingTree:setData:102]:     at com.ferreusveritas.dynamictrees.event.CommonEventHandler.onWorldTick(CommonEventHandler.java:21)
> [20:41:16] [Server thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.entities.EntityFallingTree:setData:102]:     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_938_CommonEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
> [20:41:16] [Server thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.entities.EntityFallingTree:setData:102]:     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> [20:41:16] [Server thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.entities.EntityFallingTree:setData:102]:     at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
> [20:41:16] [Server thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.entities.EntityFallingTree:setData:102]:     at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
> [20:41:16] [Server thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.entities.EntityFallingTree:setData:102]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752)
> [20:41:16] [Server thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.entities.EntityFallingTree:setData:102]:     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
> [20:41:16] [Server thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.entities.EntityFallingTree:setData:102]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
> [20:41:16] [Server thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.entities.EntityFallingTree:setData:102]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
> [20:41:16] [Server thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.entities.EntityFallingTree:setData:102]:     at java.lang.Thread.run(Thread.java:750)

**Comment by Harleyoc1** [comment]
As with my reply in #634 when this was previously reported, this is most likely a mod incompatibility. If it's possible for you to narrow down to the other mod in question we may be able to come to a solution.

**Comment by iMord0** [comment]
I would bet on these 2 then:
- dynamictreesdefiledlands-1.12.2-1.0.0.jar
- DynamicTreesTraverse-1.12.2-2.1.jar

Did you encounter them before or are you sure which one or both are incompatible?
Thanks a lot for any insight

**Comment by Harleyoc1** [comment]
No, I've not had this issue myself before, and I have no clue if it's one of those add-ons causing it. I am just familiar from the previous report of the same kind. 

My best guess at the time that was reported was that something was messing with the way breaks work. Are you aware of what kind of tree was being fell when this happened. Perhaps a certain modded tool was used or something that could be doing it's own tree breaking which is incompatible?
