### ISSUE TITLE
Incompatibility with ModernFix's dynamic resources optimization

### ISSUE THREAD

**Issue by embeddedt** [ferreusveritas/Dynamic-Trees#795]
If ModernFix is installed, and its dynamic resources optimization is manually enabled by a user, Dynamic Trees will crash due to its models not being baked. The reason this occurs is because of how your model bake event handler is implemented:

https://github.com/DynamicTreesTeam/DynamicTrees/blob/8c8caee03809e851eaf9e20569521b8bd7461e73/src/main/java/com/ferreusveritas/dynamictrees/event/handler/BakedModelEventHandler.java#L40-L41

This code assumes that every model in the game was loaded at startup, which is true in vanilla, but not when this optimization is enabled. The optimization is designed to work correctly with models using the vanilla system or the Forge custom model loader system, however, it cannot work with an event handler designed like yours. Since ModernFix only constructs model instances and bakes models when they are actually needed in gameplay, the `INSTANCES` global list is never populated, causing none of the models to actually get initialized. This later leads to a NullPointerException when the model needs to return quads.

This was reported to me and reproduced on 1.19.2, however, it may also affect 1.16.5/1.18.2 if they use the same model code. I should note that dynamic resources is not on by default, for compatibility reasons, but I do recommend it to players looking to reduce loading times further and significantly improve memory usage.

For reference, I recently fixed a similar issue in Bumblezone by modifying the code to do the model initialization inside the constructor instead of deferring it to the `BakingCompleted` handler: https://github.com/TelepathicGrunt/Bumblezone/commit/ce1be46e9c6f8b8b3b52dd350354370718e7f974. This matches how vanilla and most other models are designed, and fixes the issue.

**Comment by Mystifyed** [comment]
Could this be fixed in 1.18.2 as well? Thank you.

**Comment by Mystifyed** [comment]
Are there any plans to backport this to 1.18.2?
