### ISSUE TITLE
Add tree models for mature azaleas

### ISSUE THREAD

**Issue by Rocketcat19** [ferreusveritas/Dynamic-Trees#798]
The azalea will grow up as azalea trees, but they still use vanilla tree models. Can you add tree models for mature azaleas?

**Comment by Harleyoc1** [comment]
I'm not sure what you mean by this?

**Comment by Rocketcat19** [comment]
Uh, its a little embarrassing. Maybe the expression is not very clear, I'll try to show it in pictures intead.
![2023-08-08_00 53 03](https://github.com/DynamicTreesTeam/DynamicTrees/assets/113609599/1c58a4fc-e029-4279-b5b2-a2c312e0f79f)
And this is naturally generated.
![2023-08-08_00 53 59](https://github.com/DynamicTreesTeam/DynamicTrees/assets/113609599/72bf292d-9b10-40b5-8f2d-476332a87c10)

**Comment by Harleyoc1** [comment]
I'm sorry but I'm still confused... What are you expecting the dynamic version to look like?

**Comment by Rocketcat19** [comment]
The second one. It looks better.

**Comment by Harleyoc1** [comment]
Ah, I think you're confused by the sapling. Dynamic Trees adds its own seed items which act as a replacement for normal saplings - you need to use these instead to grow the dynamic version. The item is dropped by the dynamic tree's leaves when broken or can be found in the dynamic trees creative tab. 

Also, in case you're interested there is a config option that causes all regular saplings to be replaced with dynamic ones. It is found in `config/dynamictrees-common.toml` in your MC directory - search for `replaceVanillaSapling` and set to `true` if you want to enable this.

**Comment by Rocketcat19** [comment]
Thank you for your answer. I initially thought of replacing the azalea saplings alone, because only they can generate naturally. But if this is a feature, maybe I don't have to do that.^-^

**Comment by Harleyoc1** [comment]
We decided not to replace the naturally generating ones since they act as a decorational block in their own right. Don't forget you can always use the dirt bucket to exchange saplings for their seed equivalents, and vice versa.
