### ISSUE TITLE
[7.7e]Crash on Loading when updated, no problem with 7.6

### ISSUE THREAD

**Issue by GottJammern** [ferreusveritas/Dynamic-Trees#80]
As title. The game loads fine with 7.6, but if I update to 7.7e and load it crashs with the attached log.

[Minecraft Dynamic Trees Crash.txt](https://github.com/ferreusveritas/DynamicTrees/files/2029198/Minecraft.Dynamic.Trees.Crash.txt)

**Comment by ghost** [comment]
Update Dynamic Trees Biomes O' Plenty compat mod.
