### ISSUE TITLE
(non-critical) (1.19.2) Weird server error

### ISSUE THREAD

**Issue by vgrynch** [ferreusveritas/Dynamic-Trees#801]
Hi!

This does not cause server crashes or visual malfunctioning (at least not observed yet), so it's not a top priority but...

My server log is cluttered with a strange error (followed by a stack trace, which is of no interest as it is related to MC world generation):

`Unknown registry key in ResourceKey[minecraft:root / minecraft:worldgen/structure_pool_element]: minecraft:tree_pool_element`

All traces lead to this mod, where I see "tree_pool_element" is registered in the sources. The first suspicious thing is the "minecraft" namespace. The second - where it is used or defined as a structure? Do you build something in this mod as structures? It looks to me as either some leftover code or missing namespace in the definition.

Please, fix it.

Thanks!

**Comment by Harleyoc1** [comment]
I'm guessing the tree pool element isn't registered, but I'm not getting this message in the logs. Can you send me your full logs, I'm guessing some other mod is sending this message but would be nice to confirm.

**Comment by vgrynch** [comment]
Unfortunately, there are not any traces or crashes to identify it. Just tons of above messages. Right now, it does not appear because I turned world generation off. Possibly you are right and some other mod modifies something in a way that it appears.

Just as a precaution, I would simply recommend reviewing the code around the "tree_pool_element" (or possibly operating it) and re-check if the namespace is always included.

No other ideas...
