### ISSUE TITLE
[Suggestion] The Axes

### ISSUE THREAD

**Issue by MrErilio** [ferreusveritas/Dynamic-Trees#81]
Hello, really well done for your work I love this mod.
But I noticed a point that I find unfortunate, the Ax, it is well too cheat now, only 1 durability even for the tree that gives 10 of wood, 131 guilty tree with just the stone ax :(

I think that the ideal would be that the ax is damaged according to the number of wood recover in the tree! And that would be a lot less cheating. :)

Sorry for my rough english, I use a translator.

**Comment by Deshiba** [comment]
This has been requested in #56. Dev has a config option so you could compile the current source or wait for a release on curseforge.

**Comment by ghost** [comment]
Or you could just get the beta from curseforge.  No need to build from source for this feature.

**Comment by ghost** [comment]
Not an issue in the latest version.
