### ISSUE TITLE
[Server thread/ERROR] [net.minecraft.stats.ServerRecipeBook/]: Tried to load unrecognized recipe

### ISSUE THREAD

**Issue by Minebrah** [ferreusveritas/Dynamic-Trees#810]
DynamicTrees-1.19.2-1.1.0-BETA9

Log spam trying to load multiple unrecognized recipes.

https://gist.github.com/Minebrah/7f3567de1b4ed935ca0236d7cbab81ea

**Comment by DAIZEE-MAE** [comment]
still an issue
