### ISSUE TITLE
[BUG] dynamictrees:dendro_potion recipe turns any item in the game into a DT potion

### ISSUE THREAD

**Issue by Nycto97** [ferreusveritas/Dynamic-Trees#819]
**Describe the bug**
The brewing recipe for `dynamictrees:dendro_potion` accepts all items/blocks from the game as input, effectively meaning you can brew this potion with any item/block registered to the game, both vanilla and modded.

Also, JEI showing wrong information about what the recipe will actually accept.

MineColonies is not really related, but I keep it listed because in their Alchemist tab, you can see all the pages.

**To Reproduce**
(UPDATED)
1. Open brewing stand GUI
2. Insert Blaze Powder, charcoal on the top and literally any item/block at the bottom
3. Get the Biochar Base Potion (dynamictrees:dendro_potion) in return

(OLD)
~~1. Have (MineColonies + required dependencies +) Dynamic Trees + JEI installed~~
~~2. Launch client~~
~~3. Join a world (singleplayer or multiplayer)~~
~~4. Open JEI GUI~~
~~5. Right-click (or hover and 'U') any item~~
~~6. Go to Alchemist tab~~
~~7. Left-click the dynamictrees:dendro_potion~~
~~8. Go to Alchemist tab~~
~~9. See all the pages with recipes~~

**Screenshots**
![image](https://github.com/DynamicTreesTeam/DynamicTrees/assets/83367226/cababbd9-da07-4b9f-9aa3-6c4d7e83a425)

Input:
![image](https://github.com/DynamicTreesTeam/DynamicTrees/assets/83367226/eb00e1b4-9c21-4f23-96a5-24057a100406)

Output
![image](https://github.com/DynamicTreesTeam/DynamicTrees/assets/83367226/f94b9f2c-0486-46e1-90a8-8351d93bbd3c)

**Rendering Glitches**
Not related, running game only with mods listed below

**Additional information**
- https://github.com/ldtteam/minecolonies/issues/9522#issuecomment-1780704549

**Mods List**
![image](https://github.com/DynamicTreesTeam/DynamicTrees/assets/83367226/06ea7b76-e1df-4e87-8943-f3d5d1d5fe6c)

**Forge version**
1.19.2-43.3.2

**Comment by ghost** [comment]
This is no BUG in general.
There is simply no logic behind or in the brewing system of DynamicTrees since 1.16.5

I've patched some logic in but need more infos about the potion use.

BIOCHAR only the base potion for all other
DEPLETION, GIGAS, BURGEONING, FERTILITY, PERSISTENCE, HARVEST and DENUDING based on BIOCHAR and no dynamic use now or planed
TRANSFORM based on BIOCHAR and the only potion used dynamic including addons??
