### ISSUE TITLE
can we plez get an update to 1.20.1 atlest

### ISSUE THREAD

**Issue by VodzGaming** [ferreusveritas/Dynamic-Trees#828]
can we plez get an update to 1.20.1 atlest

**Comment by Exzept1on** [comment]
true

**Comment by TorkumaTigburr** [comment]
Pleeeease!!! I would love to see this get updated for 1.20.1!

**Comment by wedgebert** [comment]
I've built the 1.20.X branch and am using in a 1.20.1 game now. It _mostly_ seems to work. Just not sure if the trees are actually spreading or not.

An official update would be nice though, since then maybe the compatibility mods will get updated too (like Terralith or Biomes 'O Plenty)
