### ISSUE TITLE
Missing textures for biome o plenty redwood tree compat

### ISSUE THREAD

**Issue by KnightedPear** [ferreusveritas/Dynamic-Trees#829]
I am using oculus, on version 1.19.2,modrinth mods are linked

[Create 1.0.0.zip](https://github.com/DynamicTreesTeam/DynamicTrees/files/13834262/Create.1.0.0.zip)

![image_2024-01-04_133516093](https://github.com/DynamicTreesTeam/DynamicTrees/assets/155671267/8cf330de-471c-4162-a99b-99581c031812)

as the title says the textures for the roots of the redwood trees are missing.

**Comment by Rythiq** [comment]
did you ever find a way to fix this?
i have the same issue

**Comment by Elmanujaaj** [comment]
Hello! I had the same problem, what I did to solve it was delete the "dynamic trees plus" mod

**Comment by supermassimo** [comment]
fixed
