### ISSUE TITLE
Crash (It seems to be related to honeycombs (?))

### ISSUE THREAD

**Issue by Jandri555** [ferreusveritas/Dynamic-Trees#839]
**Describe the bug**
Crashes randomly, for no apparent reason, but in the logs I think bees are always mentioned.
Minecraft 1.20.1
Forge 47.2.0

**Additional context**

[latest.log](https://github.com/DynamicTreesTeam/DynamicTrees/files/14058191/latest.log)

[Full](https://pastebin.com/USvcjxjM)

**Comment by supermassimo** [comment]
was fixed
