### ISSUE TITLE
cascading worldgen lag

### ISSUE THREAD

**Issue by jusitnboggs** [ferreusveritas/Dynamic-Trees#84]
30.05 19:07:00 [Server] Server thread/WARN [FML]: Dynamic Trees loaded a new chunk [-22, -8] in dimension 0 (overworld) while populating chunk [-21, -9], causing cascading worldgen lag.
30.05 19:07:00 [Server] Server thread/WARN [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

What other info can I give?

**Comment by ghost** [comment]
I stamp these out as I encounter them.  Sadly this doesn't produce a crash and thus no crash log.  Without a crash log I can't tell where the error is. You can however tell me what kind of biome this occurred in.  That might help me to reproduce it.

**Comment by jusitnboggs** [comment]
Forest biome

**Comment by jusitnboggs** [comment]
idk if these logs will be helpful or not
[debug (2).txt](https://github.com/ferreusveritas/DynamicTrees/files/2056369/debug.2.txt)
[latest (2).txt](https://github.com/ferreusveritas/DynamicTrees/files/2056370/latest.2.txt)

**Comment by ghost** [comment]
Thanks.  Also.  You're using the most up to date version of Dynamic Trees?  0.7.7e is the latest.
If you're using Dynamic Trees BoP compat then make sure you're up to date with that too.

Edit:  Looks like you're using the latest according to your debug logs.

**Comment by ghost** [comment]
Unfortunately this issue is non-productive
