### ISSUE TITLE
crash when launching

### ISSUE THREAD

**Issue by SmellyBozoAce** [ferreusveritas/Dynamic-Trees#840]
when I launch the game on 1.20.1 forge 47.1.3 it crashes before title screen. https://pastebin.com/d5zJf0N8

**Comment by davidromrell** [comment]
issue with modernfix or supermartijn642corelib

**Comment by supermassimo** [comment]
Please confirm if this still happens on latest beta

**Comment by supermassimo** [comment]
Duplicate of https://github.com/DynamicTreesTeam/DynamicTrees/issues/844
