### ISSUE TITLE
Trees disappearing when I try to harvest them (1.19.2)

### ISSUE THREAD

**Issue by Yowakaza** [ferreusveritas/Dynamic-Trees#843]
**Rules (Read this first!)**
This is just a template to help you post a useful issue.  Erase these rules and any irrelevant categories and content as you see fit. 

Basically everytime I try to mine a tree with an axe the tree just disappears. I cannot figure out how to look up and solve this issue.

What version of Forge are you running? (e.g. 1.12.2-14.23.5.2768)

- Forge 43.2.14

**Comment by Summerly56** [comment]
Hello, I have this issue too on forge 1.19.2. Is there any fix?

**Comment by supermassimo** [comment]
Please include latest log

**Comment by supermassimo** [comment]
This is an incompatibility with a tree felling mod, like Tree Harvester or similar
