### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by lanwoodall423** [ferreusveritas/Dynamic-Trees#845]
**Describe the bug**
Crash on launch

**To Reproduce**
Install Dynamic Trees
Install other mods
launch

Dynamic Trees Beta 2 
NeoForge 47.1.78

[crash-2024-01-30_10.38.14-client.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/14100701/crash-2024-01-30_10.38.14-client.txt)

**Comment by FF101UALviv** [comment]
[crash-2024-03-27_18.47.30-client.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/14776690/crash-2024-03-27_18.47.30-client.txt)
and me

**Comment by davidromrell** [comment]
watut-forge-1.19.2-1.0.14.jar is issue for @FF101UALviv 
mixininheaven-mc1.17.1-1.20-v0.0.1-hotfix.jar is issue for @lanwoodall423

**Comment by supermassimo** [comment]
crash unrelated to dynamic trees
