### ISSUE TITLE
Worldgen lag with "Tried to access a block entity before it was created. MutableBlockPos"

### ISSUE THREAD

**Issue by Runburner** [ferreusveritas/Dynamic-Trees#850]
Mod Version: 1.19.2-1.2.0-BETA1
Minecraft Version: 1.19.2
Forge Version: 43.3.8

**Describe the bug**
World gen is spitting this out in logs and it is taking considerable amount of time for new chunks to load. 
https://pastebin.com/DHt2Uf0w

I teleported to a few of the locations and majority of these appeared to be Dynamic Trees

**Mods List**

- Waystones [11.4.2]
- Create [0.5.1.f]
- Sophisticated Core [1.19.2-0.6.2.552]
- Chimes [2.0.1]
- FTB Teams [1902.2.14-build.123]
- Stylish Effects [4.3.4]
- Iron Chests [1.19.2-14.2.7]
- Better Compatibility Checker [1.0.10-build.50+mc1.19.2]
- Chat Heads [0.10.31]
- Macaw's Doors [1.1.0]
- Tetranomicon [1.5.3-1.19.2]
- Stoneworks [4.0.2]
- PolyLib [1900.0.3-build.100]
- 'Dustrial Decor [1.3.2]
- Fuel Goes Here [1.19.2-0.1.0.0]
- Farmer's Delight [1.19.2-1.2.4]
- Just Enough Professions (JEP) [2.0.2]
- Resource Pack Overrides [4.0.4]
- Macaw's Roofs - BOP [1.19.2-1.4]
- Environmental [3.0.0]
- Connectivity Mod [1.19.2-4.6]
- Every Compat [1.19.2-2.5.17]
- Decorative Blocks [3.0.0]
- Konkrete [1.8.0]
- Vein Mining [1.1.2+1.19.2]
- Torchmaster [19.2.93]
- BetterF3 [4.0.1]
- Mob Catcher [1.2.12]
- Visual Workbench [4.2.4]
- Fastload-Reforged [3.4.0]
- Highlighter [1.1.4]
- Horse Expert [4.0.0]
- Elytra Slot [6.1.1+1.19.2]
- Jade Addons [3.6.0]
- Immersive Aircraft [0.7.1+1.19.2]
- Borderless Window [1.19.1-1.5.2]
- Mekanism: Generators [10.3.9]
- Smooth Swapping [0.9.2]
- Macaw's Fences and Walls [1.1.1]
- Mekanism: Additions [10.3.9]
- Bad Wither No Cookie Reloaded [3.14.1]
- mutil [5.2.0]
- YUNG's API [1.19.2-Forge-3.8.10]
- Melody [1.0.1]
- YUNG's Better Witch Huts [1.19.2-Forge-2.1.0]
- Macaw's Trapdoors [1.1.2]
- Collective [7.30]
- Create Crafts & Additions [1.19.2-1.2.3]
- Cupboard utilities [1.19.2-2.3]
- Tetra [5.6.0]
- Pam's HarvestCraft 2 - Food Core [1.0.1]
- Bookshelf [16.3.20]
- YUNG's Bridges [1.19.2-Forge-3.1.0]
- Nether's Delight [1.19-3.1]
- Bigger Reactors [0.6.0-beta.6.4]
- Fantasy's Furniture [6.7.0]
- Create Deco [1.3.3-1.19.2]
- Customizable Player Models [0.6.14c]
- When Dungeons Arise [2.1.56-1.19.2]
- Better Foliage [4.0.6]
- Thermal Foundation [10.3.1]
- LazyDFU [0.1.3]
- Memory Leak Fix [1.0.0]
- Additional Lights [2.1.6]
- Pick Up Notifier [4.2.4]
- Jade [8.9.2]
- YUNG's Better Ocean Monuments [1.19.2-Forge-2.1.1]
- Botarium [1.9.1]
- Rubidium Dynamic Lights [1.19.2_v1.4.0]
- Elevator Mod [1.19.2-1.8.10]
- JourneyMap Integration [0.13-44]
- Quartz [0.1.0-beta.2.2]
- Baubley Heart Canisters [1.19.2-2.1.0]
- Zero CORE 2 [1.19.2-2.1.39]
- DEUF - Duplicate Entity UUID Fix [1.19.2-1.3]
- Macaw's Bridges - BOP [1.19.2-1.3]
- Pam's HarvestCraft 2 - Crops [1.0.2]
- Catalogue [1.7.0]
- Explorer's Compass [1.19.2-1.3.0-forge]
- Thermal Expansion [10.3.1]
- YUNG's Better Dungeons [1.19.2-Forge-3.2.2]
- Thermal Dynamics [10.3.0]
- CreativeCore [2.9.3]
- Mouse Tweaks [2.23]
- Macaw's Roofs [2.3.0]
- LootBeams [1.0]
- Embeddium [0.3.3+mc1.19.2]
- Comforts [6.0.7+1.19.2]
- Gpu memory leak fix [1.19.2-1.6]
- FancyMenu [3.0.6]
- Mekanism [10.3.9]
- Patchouli [1.19.2-77]
- Cloth Config v8 API [8.3.115]
- JAOPCA [4.2.9.22]
- CodeChicken Lib [4.3.2.490]
- Curios API [1.19.2-5.1.6.1]
- Ferrite Core [5.0.3]
- Pam's HarvestCraft 2 - Food Extended [1.0.0]
- AttributeFix [17.2.7]
- AppleSkin [2.4.2+mc1.19]
- FTB Quests [1902.5.8-build.345]
- FTB Essentials [1902.3.4-build.109]
- Thermal Cultivation [10.3.0]
- Dynamic Trees for Biomes o' Plenty [1.19.2-3.1.2]
- Architect's Palette [1.3.5]
- Combat Roll [1.1.5+1.19]
- Macaw's Fences - BOP [1.19.2-1.0]
- Shutup Experimental Settings! [1.0.5]
- CoFH Core [10.3.1]
- Entity Model Features [1.2.3]
- Lootr [0.4.25.67]
- Magnum Torch [4.2.3]
- ConnectedTexturesMod [1.19.2-1.1.6+8]
- Enhanced Mob Spawners [1.9.1]
- Easy Villagers [1.19.2-1.1.3]
- GeckoLib [3.1.40]
- Cognition [2.0.3]
- Architectury [6.5.90]
- FTB Ranks [1902.1.16-build.98]
- Simple Discord Rich Presence [3.0.6-build.39+mc1.19.2]
- Tesseract [1.0.35a]
- YUNG's Better Nether Fortresses [1.19.2-Forge-1.0.6]
- Placebo [7.3.5]
- Tetra Extras [0.1.3-1.19]
- Toast Control [7.0.0]
- SuperMartijn642's Config Library [1.1.8]
- CorgiLib [1.0.0.34]
- YUNG's Better Strongholds [1.19.2-Forge-3.2.0]
- Canary [0.3.3]
- Pluto [0.0.9]
- Caelus API [1.19.2-3.0.0.6]
- chunksending mod [1.19.2-2.8]
- Overflowing Bars [4.0.1]
- YUNG's Better Desert Temples [1.19.2-Forge-2.2.2]
- Upgraded Core [1.19.2-4.1.0.1-release]
- Quests Additions [1.4.2]
- CookingForBlockheads [13.3.4]
- Dynamic Trees [1.19.2-1.2.0-BETA1]
- Crash Utilities [6.2]
- Macaw's Furniture [3.2.2]
- Rechiseled [1.1.5c]
- Resourcefulconfig [1.0.20]
- SuperMartijn642's Core Lib [1.1.17]
- Dungeon Crawl [2.3.12]
- Chipped [2.1.5]
- Fusion [1.1.0c]
- FindMe [3.1.0]
- Puzzles Lib [4.4.3]
- Small Ships [2.0.0-b1.0]
- TerraBlender [2.0.1.166]
- Second Chance Forge [1.5.1]
- AlmostUnified [1.19.2-0.7.2]
- Thermal Locomotion [10.3.0]
- Botania [1.19.2-440-FORGE]
- Pam's HarvestCraft 2 - Trees [1.0.1]
- Secrets Of Forging: Revelations [1.3.1-1.19.2]
- Terralith [2.3.12]
- Enhanced Celestials [2.1.0.6]
- Balm [4.6.0]
- Eating Animation [3.0.0]
- Torch Slab Mod [1.7.4]
- Fairy Lights [6.0.1]
- Traveler's Titles [1.19.2-Forge-3.1.2]
- Dynamic Trees Plus [1.19.2-1.1.3]
- Embeddium++ [1.2.4]
- ModernFix [5.13.0+mc1.19.2]
- Origins [1.19.2-1.7.1.3]
- Macaw's Lights and Lamps [1.0.6]
- Upgraded Netherite [1.19.2-5.1.0.9-release]
- Stalwart Dungeons [1.2.8]
- Resourceful Lib [1.1.24]
- Flux Networks [7.1.4.13]
- ColorfulAzaleas [2.3.1]
- Entity Texture Features [5.2.3]
- Entity Collision FPS Fix [2.0.0.0]
- Visuality: Reforged [2.0.2]
- ESSENTIAL Mod [sg0qOo0d]
- Item Filters [1902.2.9-build.51]
- Towns and Towers [1.10]
- Iron Furnaces [3.6.5]
- Journeymap [5.9.7]
- Macaw's Paths and Pavings [1.0.4]
- Hostile Mobs and Girls [6.2.14]
- betterchunkloading mod [1.19.2-2.5
- Rechiseled: Create [1.0.2]
- Touhou Little Maid [1.1.7]
- Better village [3.1.0]
- Biome Makeover [1.19.2-1.6.4]
- Platforms [1.10.7]
- Easy Anvils [4.0.11]
- Fast Suite [4.1.1]
- JeiTweaker [4.0.13]
- memorysettings mod [1.19.2-5.4]
- Better Combat [1.7.1+1.19]
- Refined Storage [1.11.7]
- Thermal Innovation [10.3.0]
- Cultural Delights [0.15.5]
- Biomes O' Plenty [17.1.2.544]
- EnderStorage [2.10.1.181]
- Serene Seasons [NONE]
- Macaw's Bridges [2.1.1]
- Farming for Blockheads [11.3.5]
- Oculus [1.6.9]
- Supplementaries [1.19.2-2.4.19]
- AI-Improvements [0.5.2]
- Diagonal Fences [4.2.6]
- Block Runner [4.2.2]
- Example Mod [1.19.2-1.8]
- FTB Chunks [1902.4.4-build.326]
- FTB Library [1902.4.1-build.236]
- Traverse Reforged [6.2.4]
- Advancement Plaques [1.4.7]
- EntityCulling [1.6.1]
- YUNG's Extras [1.19.2-Forge-3.1.0]
- Chalk [1.6.3]
- Leaves Be Gone [4.0.1]
- Simple Voice Chat [1.19.2-2.5.4]
- Configured [2.1.1]
- Delightful [3.4.1]
- Macaw's Windows [2.2.1]
- Chance Cubes [1.19.2-5.0.2.475]
- ChickenChunks [2.9.4.97]
- Reaper [1.0.4]
- Auudio [1.0.3]
- Armor Statues [4.0.8]
- Library ferret [4.0.0]
- FTB Backups 2 [1.0.23]
- Clayworks [2.1.0]
- YUNG's Better Mineshafts [1.19.2-Forge-3.2.1]
- Pickle Tweaks [7.0.3]
- Universal Bone Meal [4.2.0]
- Just Enough Resources [1.2.3.243]
- Prism [1.0.2]
- Create: Steam 'n' Rails [1.5.3+forge-mc1.19.2]
- Phosphophyllite [0.6.0-beta.8]
- Iceberg [1.1.4]
- Sound Physics Remastered [1.19.2-1.3.1]
- recipeessentials mod [1.19.2-3.2]
- Additional Lanterns [1.1.1]
- CraftTweaker [10.1.53]
- Chunk Pregenerator [1.19-4.4.2]
- TexTrue's Embeddium Options [0.1.1+mc1.19.2]
- Structory [1.0.1]
- cave_dweller [1.7.0]
- AutoRegLib [1.8.2-55]
- ImmediatelyFast [1.2.10+1.19.2]
- eeriemusic mod [1.19.2-1.4]
- Creeper Overhaul [2.0.9]
- Epic Samurai [0.0.17-1.19.2-forge]
- Inventory HUD+(Forge edition) [3.4.7]
- Blueprint [6.2.0]
- MmmMmmMmmmmm [1.19.2-1.7.1]
- Legendary Tooltips [1.4.0]
- §3ImmersiveFX [5.1]
- Mekanism: Tools [10.3.9]
- ShetiPhian-Core [3.11.11]
- Smoothchunk mod [1.19.2-3.5]
- Pineapple Delight [1.0.7]
- Camera Mod [1.19.2-1.0.8]
- Effective (Forge) [1.3.4]
- fastasyncworldsave mod [1.19.2-1.2]
- Sophisticated Backpacks [1.19.2-3.20.1.1013]
- monsters and girls [1.3.3.0]
- AntiGhost [1.19.1-forge42.0.1-1.1.3]
- Controlling [10.0+7]
- Farmer's Respite [1.19-2.0]
- Polymorph [0.46.5+1.19.2]
- Better Advancements [0.3.0.148]
- biomemusic mod [1.19.2-2.2]
- Ender's Delight [1.19-1.2.2]
- Handcrafted [2.0.6]
- Player Animator [1.0.2]
- 3d-Skin-Layers [1.6.2]
- chisels-and-bits [1.3.146]
- Tetra tables looking neat [1.0.2]
- Better Animations Collection [4.0.5]
- Just Enough Items [11.6.0.1019]
- Easy Magic [4.3.3]
- CraftingTweaks [15.1.9]
- Ars Nouveau [3.22.3]
- Spirit [2.2.7]
- Starlight [1.1.1+forge.a3aea74]
- Storage Drawers [11.1.2]
- Lightspeed [1.19.2-1.1.0]
- Nature's Compass [1.19.2-1.10.0-forge]
- Cucumber Library [6.0.10]
- Better Third Person [1.9.0]
- Thermal Integration [10.3.0]
- Vitalize [1.1.1]
- Structory: Towers [1.0]
- Art of Forging [1.7.3-1.19.2]
- Immersive Armors [1.5.6+1.19.2]
- Diagonal Windows [4.0.2]
- Equipment Compare [1.3.2]
- YUNG's Better End Island [1.19.2-Forge-1.0]
- Rubidium Extras [1.19.2_v1.4.3]
- Moonlight Library [1.19.2-2.3.6]
- Quark [3.4-418]
- Quark Oddities [1.18]
- Dynamic Trees for Quark [1.19.2-2.4.0-Beta1]
- Quark Delight [1.0.0]
- Let Me Despawn [1.18-forge-1.0.3]
- Tree Harvester [8.6]
- Physics Mod [2.12.5]

**Comment by davidromrell** [comment]
needs more info to fix or find workaround.

**Comment by supermassimo** [comment]
was fixed
