### ISSUE TITLE
Crash when chopping nether tress - 1.20.1-1.3.0-BETA2

### ISSUE THREAD

**Issue by nickmcski** [ferreusveritas/Dynamic-Trees#852]
**Describe the bug**
Server crash when trying to chop down trees in nether

**To Reproduce**
Chop down one of the trees in the nether; May need to be attached to Nylium or Shroomlight

**Crashes**
Version: 1.20.1-1.3.0-BETA2

Crash Stacktrace: https://gist.github.com/nickmcski/9d6f926bc1f19588e2ad0c809329260a
Full Crash Log: https://gist.github.com/nickmcski/7041bacf5a7686388ff6867bc65b06b7

**Comment by davidromrell** [comment]
1. mods not running, 2. check if reproducible without all non-running mods.

**Comment by supermassimo** [comment]
Can't reproduce
