### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FF101UALviv** [ferreusveritas/Dynamic-Trees#855]
OptiFine Forge 1.19.2
[crash-2024-03-27_18.47.30-client.txt](https://github.com/DynamicTreesTeam/DynamicTrees/files/14776721/crash-2024-03-27_18.47.30-client.txt)

**Comment by davidromrell** [comment]
not compatible

**Comment by supermassimo** [comment]
Crash unrelated to dynamic trees
