### ISSUE TITLE
[1.18.2] Server crash while generating new terrain.

### ISSUE THREAD

**Issue by Arasarhood** [ferreusveritas/Dynamic-Trees#856]
**Describe the bug**
Server crash while generating new terrain.

**To Reproduce**
Load a ridiculous number of mods, then run around in server to generate new chunks.

**Log**
[crash-2024-03-30_20.24.59-server.txt]
(https://github.com/DynamicTreesTeam/DynamicTrees/files/14813698/crash-2024-03-30_20.24.59-server.txt)

**Comment by davidromrell** [comment]
you have 40+ mods that are not running...
