### ISSUE TITLE
Unexpected critical error on startup

### ISSUE THREAD

**Issue by OzdorMiZ** [ferreusveritas/Dynamic-Trees#858]
Bug description:
-Mod fails to load correctly

-Have DynamicTrees installed
-Have other mods installed(listed in the logs)
-See the error occur

Screenshot:
![image](https://github.com/DynamicTreesTeam/DynamicTrees/assets/110551818/b0de991b-0845-404d-b87b-911b9c24b5df)

Are you using OptiFine (or any equivalent mods that mess with rendering)?
-Yes. Currently using Optifine and a couple of rendering API's(listed in the logs)

Additional info:
-I am currently using both the DynamicTrees+ and DynamicTrees - Biomes O' Plenty add-ons.

- Are you running the latest version of Dynamic Trees?
- Yes. The installed version is 1.16.5-0.10.5
- If you are using the DT Biome O' Plenty Add-on do you have the latest version? 
- Yes. The installed version is 1.16.5-2.0.9
- If you are using the DT Thaumcraft Add-on do you have the latest version?
- Not using.

What version of Forge are you running? (e.g. 1.12.2-14.23.5.2768)
-1.16.5-36.2.34

Latest log:
https://gist.github.com/OzdorMiZ/da9a3ff442d5cd6f4a7b1991789705eb

Crash log:
https://gist.github.com/OzdorMiZ/9ca081232839f024b452706237e3854b

**Comment by supermassimo** [comment]
Dynamic Trees is not compatible with Cave Biome API
