### ISSUE TITLE
Distant Horizons Bug

### ISSUE THREAD

**Issue by KintsugiSoul** [ferreusveritas/Dynamic-Trees#859]
When Distant Horizons renders leaves for dynamic trees they do not render, it seems that only the root leaves (right above the tree trunk).
Picture using render distance of 2:
![2024-05-05_07 18 56](https://github.com/DynamicTreesTeam/DynamicTrees/assets/53422294/e64f58e9-c516-4e36-bf7e-ca09d938853b)

**Comment by supermassimo** [comment]
this has been fixed
