### ISSUE TITLE
[suggestion] Dynamic Trees and vanilla combiner

### ISSUE THREAD

**Issue by DjTylerD** [ferreusveritas/Dynamic-Trees#86]
I just discovered your mod that I find exelent, so congratulations to the creators.

you propose 2 generation solutions: fast and true.
could you do a percentage generation, eg 80% Dynamictrees
or add a drop percentage of saplin vanillia, for some mod that we need to sapling to work

ps: sorry I'm french translated by: goggle translation

thank you in advance for studying my request

merci d'avance pour etudier ma demande

**Comment by ghost** [comment]
I won't add mixed dynamic and vanilla tree generation.  It's one or the other.  Use the dirt bucket exchange recipe to convert seeds to vanilla saplings if they're needed.
