### ISSUE TITLE
foliage on dynamic trees does not move during shaders

### ISSUE THREAD

**Issue by FilipKompaniets3** [ferreusveritas/Dynamic-Trees#860]
Does anyone know how to fix this? The leaves on dynamic trees do not move when I have the shader enabled, unlike the foliage of the vanilla tree.

**Comment by supermassimo** [comment]
You need to add the leaves to the shader's foliage file

**Comment by FilipKompaniets3** [comment]
> Вам потрібно додати листя до файлу листя шейдера

Do I need to add a foliage block tag? and to which file in the shader folder should I add this? Sorry, I don't know very well about all this.
