### ISSUE TITLE
1.20.1 FPS Report

### ISSUE THREAD

**Issue by mourninglmb** [ferreusveritas/Dynamic-Trees#862]
When playing on Multiplayer with Dynamic Trees, all player's (2-6) experience extreme frame drop rates when going under/in the under-bush of the tree/leaves. Even when running past trees, just being semi under them causes FPS drop rates. This while also mentioning that we all have relatively good computer systems (Ranging from 300-800 FPS).

**Comment by supermassimo** [comment]
The experimental ALPHA version fixes this. Once its stable enough it will become the base implementation
