### ISSUE TITLE
Trees disappeared after loading world without the mod

### ISSUE THREAD

**Issue by Lacoo99** [ferreusveritas/Dynamic-Trees#865]
Hi, i just loaded my world after removing the Dynamic Trees mod by mistake (i was checking some things) so when it loaded up there were no trees in a 10 chunks radius (wich is my renderization cofig). i tried loading the world with the mod again and the trees doesnt appeared, there are just the shadows of them. can someone help me with this?? thxss
![2024-06-04_21 27 42](https://github.com/DynamicTreesTeam/DynamicTrees/assets/170742537/ac7bcdc6-4d71-4f06-a8f1-3b1e3a4cff16)
![2024-06-04_21 24 01](https://github.com/DynamicTreesTeam/DynamicTrees/assets/170742537/1ef620ff-752e-47f6-b764-3863b8512636)
![2024-06-04_21 25 01](https://github.com/DynamicTreesTeam/DynamicTrees/assets/170742537/b664f512-2858-4607-b27d-005f86e919ca)

**Comment by omegadmm** [comment]
Well not sure if they can fix that, dynamic trees replaces trees with entity-like trees, so not sure if they can do a placeholder if the mod is deleted or disabled.

**Comment by supermassimo** [comment]
This is unavoidable behavour, will happen when you remove any mod with blocks that appear in worldgen
