### ISSUE TITLE
(1.19.2) Looking at trees causes server lag

### ISSUE THREAD

**Issue by MyNameIsNotAshley** [ferreusveritas/Dynamic-Trees#867]
**Describe the bug**
Whenever any player looks at tree branches (not thick or full logs) the whole server starts lagging badly.

**To Reproduce**
Have any player rest their crosshair at a tree branch, bug doesn't happen on tree trunks.

**Additional context**
- This occurs on nether trees aswell.
- This also works in singleplayer.
- We are using the latest DT version for 1.19.2, that being 1.2.0
- We are running Forge 43.3.13
- Everyone in the server has Oculus, Rubidium, Smooth Chunk Save, and Spark installed.

**Mods List** - i put in bold the mods that are noteworthy, but these ended up being just the ones already mentioned above.
1.19.2-forge-betteramethyst-1.0.4
[1.19.2] SecurityCraft v1.9.6.1
architectury-6.6.92-forge
better_climbing-forge-2
betterdays-1.19.2-3.1.0.4-FORGE
cartoon_dweller-1.19.2-1.7.0 (1)
cloth-config-8.3.115-forge
CreativeCore_FORGE_v2.9.4_mc1.19.2
cupboard-1.19.2-2.6
cursed_sheep-1.19.2-1.7.0 (2)
DripSounds-1.19-0.3.0
DynamicTrees-1.19.2-1.2.0
easyexperience-1.6.0
eeriehauntings-1.3.4.3-1.19.2
flashLight-2.0.1.1
From-The-Fog-1.19-v1.9.1-Forge-Fabric
geckolib-forge-1.19-3.1.40
glowingores-1.19.2-1.7
map_atlases-1.19-6.0.4
mimic_dweller-1.19.2-1.7.0
moonlight-1.19.2-2.3.6-forge
PuzzlesLib-v4.4.3-1.19.2-Forge
REIPluginCompatibilities-forge-9.0.90
RespawningAnimals-v4.2.0-1.19.2-Forge
responsiveshields-2.3-mc1.18-19-20.x
RoughlyEnoughItems-9.2.724-forge
Siren_Head_v1.2.7-1.19.2-Requires_Geckolib
**smoothchunk-1.19.2-3.5**
sound-physics-remastered-forge-1.19.2-1.4.2
**spark-1.10.37-forge**
steve_dweller-1.19.2-1.7.0
swingthroughgrass-1.19-1.10.1
The-Man-From-The-Fog-1.3-1.19.2
the_knocker-1.1.1-1.19.2
TheOneWhoWatches-V1.3.0-1.19.2
twigs-forge-1.19.2-3.0.1
v_slab_compat-1.19.2-1.9
oculus-mc1.19.2-1.6.9 
rubidium-mc1.19.2-0.6.2c - (oculus and rubidium are only on client side, so i don't think they matter since the lag is on the server's side)

**Comment by whitecloudwhite** [comment]
if the problem still needs a solution, then remove "the man from the fog". i myself had a horror modpack, and had the same issue. hope this helps.

**Comment by supermassimo** [comment]
This has been identified as an incompatibility with "The Man From The Fog"
