### ISSUE TITLE
Please add support for Regions Unexplored

### ISSUE THREAD

**Issue by MrProton657** [ferreusveritas/Dynamic-Trees#869]
I kindly want to ask you to add support for 1.20.1 versions of Regions Unexplored, Ars-nouveau, Gregtech, and Croptopia.

https://www.curseforge.com/minecraft/mc-mods/regions-unexplored
https://www.curseforge.com/minecraft/mc-mods/ars-nouveau
https://www.curseforge.com/minecraft/mc-mods/gregtechceu-modern
https://www.curseforge.com/minecraft/mc-mods/croptopia

Thank you for your great mod, I really like it.

**Comment by TroubleDarkness** [comment]
\+ Mod compat for Regions Unexplored would be great addition to all Dynamic Trees series.

**Comment by supermassimo** [comment]
Do not suggest ports as feature requests.
Use the forums instead https://github.com/orgs/DynamicTreesTeam/discussions/categories/compatibility-addon-suggestions
