### ISSUE TITLE
Axe speed is unbearably slow in version 1.20.1

### ISSUE THREAD

**Issue by Sh4drenoth** [ferreusveritas/Dynamic-Trees#876]
I made a new world on 1.20.1 and updated my mods accordingly. I had the same modlist for 1.19.2 and didn't run into this issue, so I'm not sure what's causing the error. I timed cutting down a fully grown oak tree at 2 minutes exact regardless of what quality and enchantment level the axe had, lining up with how long it took to chop it by hand. Chopping wood that spawned independently from trees in structures was equally as slow, though they could be harvested by hand consistent with vanilla speeds.

I'm using Forge version 47.1.3 since that's what the curseforge site recommended so I'm not sure what could be causing the conflict.
![Modlist](https://github.com/DynamicTreesTeam/DynamicTrees/assets/58665634/98c42121-5fc0-4ce4-ad99-71e5c10a8b0b)

**Comment by supermassimo** [comment]
this has been fixed, please update DTQuark to 2.5.2
