### ISSUE TITLE
Feature Request: Dynamic Trees support for Upgrade Aquatic, Cultural Delights and Endergetic Expansion [1.19.2]

### ISSUE THREAD

**Issue by weirdspecter** [ferreusveritas/Dynamic-Trees#878]
Currently playing with DynamicTrees vers. 1.19.2-1.1.0 and wanted to request support for three mods: Upgrade Aquatic 1.19.2-5.1.0, Cultural Delights 1.19.2-0.15.1, and Endergetic Expansion 1.19.2-4.0.0.

Upgrade Aquatic has a previous DynamicTrees support mod dating to 1.16, and features the following trees:

- River Tree (with Mulberry fruit)

Cultural Delights does not to my knowledge have an existing DynamicTrees support mod, and features the following trees:

- Avocado Tree (with Avocado fruit pickable by right clicking on leaves with a texture effect)

Endergetic Expansion does not to my knowledge have an existing DynamicTrees support mod, and features the following trees:

- Poise Tree (grown from Poise Bush, with "Poise Clusters" at the top and sides that float away when interacted with)

Thank you greatly for any consideration on supporting either of these mods. I appreciate any one of these would be a substantial effort, but wanted to list the requests together in case any or all caught your eye.

**Comment by supermassimo** [comment]
Do not suggest ports as feature requests.
Use the forums instead https://github.com/orgs/DynamicTreesTeam/discussions/categories/compatibility-addon-suggestions
