### ISSUE TITLE
Crash while initializing

### ISSUE THREAD

**Issue by NyanHype** [ferreusveritas/Dynamic-Trees#88]
I've tried making a modpack with a bunch of mods and included dynamic trees, but it seems like it's returning a crash report.

"Caused by: java.lang.ClassNotFoundException: com.ferreusveritas.dynamictrees.api.worldgen.IBiomeSpeciesSelector"

[crash-2018-06-10_01.25.09-client.txt](https://github.com/ferreusveritas/DynamicTrees/files/2087545/crash-2018-06-10_01.25.09-client.txt)

I'm using the 1.12.2 0.7.7e since i want to also run the thaumcraft compat

**Comment by ghost** [comment]
upgrade dynamictreesbop
