### ISSUE TITLE
Bee nest related crash while afk

### ISSUE THREAD

**Issue by bloodcrisis** [ferreusveritas/Dynamic-Trees#883]
crash report: https://pastebin.com/NEi39eGX

I left the game running, open in the background for about 10 minutes while working on something on my other monitor and it suddenly crashed.

**Comment by VeisCMG** [comment]
Hey, think this is the same issue I've just had happen on 1.20.1, running on an Arclight server with productive bees so unsure if either of those factor into it. 

Crash report: https://pastebin.com/74PhZttR

**Comment by supermassimo** [comment]
should be fixed in beta14
