### ISSUE TITLE
Add Support for Oh The Biomes We've Gone

### ISSUE THREAD

**Issue by FanofGame** [ferreusveritas/Dynamic-Trees#892]
It's the sequel to Oh! The Biomes You'll Go. So, I just figured you might want to add support or compat to it cause you have one for Biomes 'O Plenty. That's about it, thank you for listening to my suggestion, Hope for it to be added.

**Comment by Harleyoc1** [comment]
Please understand [how support suggestions work](https://github.com/orgs/DynamicTreesTeam/discussions/784).
