### ISSUE TITLE
[1.20.1] crash with missing tree

### ISSUE THREAD

**Issue by OrangeSniper** [ferreusveritas/Dynamic-Trees#893]
**Describe the bug**
the game crashed after right-clicking on a certain tree

**To Reproduce**

**Screenshots**
![2024-08-06_17 52 14](https://github.com/user-attachments/assets/0cfbd922-3071-4092-ba0b-2d95a078c586)
**Addi
[crash-2024-08-06_17.52.33-client.txt](https://github.com/user-attachments/files/16516136/crash-2024-08-06_17.52.33-client.txt)
this is a client-side crash, as I am on the server and the server is unaffected
tional context**

**Crashes**

- Dynamic Trees 1.20.1-1.3.0-BETA13
- Dynamic Trees + 1.20.1-1.2.0-BETA3
- Dynamic Trees 1.20.1-3.2.3
- Dynamic Trees 1.20.1-2.5.3

**Comment by supermassimo** [comment]
This should be fixed in Beta14
