### ISSUE TITLE
Axes don't work, MC 1.20.1, DT 1.3.0BETA13

### ISSUE THREAD

**Issue by Throneaway420** [ferreusveritas/Dynamic-Trees#894]
Axes behave the same as fists when attempting to chop dynamic trees. 
MC 1.20.1
Forge 47.3.5
dynamictrees_createcompat-1.0.1
DynamicTrees-1.20.1-1.3.0-BETA13
DynamicTreesBOP-1.20.1-3.2.3
DynamicTreesQuark-1.20.1-2.5.3
DynamicTreesTerralith-1.20.1-1.2.3

Mods:
  [✔] ad_astra-forge-1.20.1-1.15.5
  [✔] AdHooks-1.20.1-10.1.1.1-build.0782
  [✔] advgenerators-1.6.0.6-mc1.20.1
  [✔] aether-1.20.1-1.4.2-neoforge
  [✔] alchemistry-1.20.1-2.3.4
  [✔] alchemylib-1.20.1-1.0.30
  [✔] angelblockrenewed-forge-1.3-1.20
  [✔] AngelRing2-1.20.1-2.2.2
  [✔] Apotheosis-1.20.1-7.4.0
  [✔] ApothicAttributes-1.20.1-1.3.6
  [✔] Aquaculture-1.20.1-2.5.2
  [✔] architectury-9.2.14-forge
  [✔] ars_creo-1.20.1-4.1.0
  [✔] ars_elemental-1.20.1-0.6.5
  [✔] ars_nouveau-1.20.1-4.12.4-all
  [✔] artifacts-forge-9.5.11
  [✔] balm-forge-1.20.1-7.3.6-all
  [✔] bdlib-1.27.0.8-mc1.20.1
  [✔] BiomesOPlenty-1.20.1-18.0.0.592
  [✔] blockydoors-1.20.1-1.0.1
  [✔] Bookshelf-Forge-1.20.1-20.2.13
  [✔] botarium-forge-1.20.1-2.3.4
  [✔] buildinggadgets2-1.0.7
  [✔] caelus-forge-3.2.0+1.20.1
  [✔] carryon-forge-1.20.1-2.1.2.7
  [✔] chemlib-1.20.1-2.0.19
  [✔] CityCraft-1.20.x-(v.1.7.0)
  [✔] cleanswing-1.20-1.5
  [✔] Clear-Water-2.1
  [✔] cloth-config-11.1.118-forge
  [✔] cofh_core-1.20.1-11.0.2.56
  [✔] comforts-forge-6.4.0+1.20.1
  [✔] constructionwand-1.20.1-2.11
  [✔] cookingforblockheads-forge-1.20.1-16.0.6
  [✔] corpse-forge-1.20.1-1.0.12
  [✔] CraftTweaker-forge-1.20.1-14.0.40
  [✔] create_ad_astra_compat-forge-1.20.1-1.0.0
  [✔] create-1.20.1-0.5.1.f
  [✔] createaddition-1.20.1-1.2.4d
  [✔] create-new-age-forge-1.20.1-1.1.2
  [✔] CreateTweaker-forge-1.20.1-4.0.10
  [✔] cristellib-1.1.5-forge
  [✔] Cucumber-1.20.1-7.0.11
  [✔] curios-forge-5.9.1+1.20.1
  [✔] Delightful-1.20.1-3.5.9
  [✔] DungeonsArise-1.20.x-2.1.58-release
  [✔] dynamiclightsreforged-1.20.1_v1.6.0
  [✔] dynamictrees_createcompat-1.0.1
  [✔] DynamicTrees-1.20.1-1.3.0-BETA13
  [✔] DynamicTreesBOP-1.20.1-3.2.3
  [✔] DynamicTreesQuark-1.20.1-2.5.3
  [✔] DynamicTreesTerralith-1.20.1-1.2.3
  [✔] easy_npc_1.20.1-4.5.1
  [✔] easy_villagers-1.20.1-1.0.17
  [✔] easy-villagers-forge-1.20.1-1.1.15
  [✔] EdivadLib-1.20.1-2.0.1
  [✔] elevatorid-1.20.1-lex-1.9
  [✔] elytraslot-forge-6.4.3+1.20.1
  [✔] embeddium-0.3.28+mc1.20.1
  [✔] embeddiumplus-1.20.1-v1.2.13
  [✔] EnchantmentDescriptions-Forge-1.20.1-17.1.18
  [✔] EnderIO-1.20.1-6.1.8-beta-all
  [✔] eureka-1201-1.5.1-beta.3
  [✔] ExtraStorage-1.20.1-4.0.7
  [✔] ExtremeReactors2-1.20.1-2.0.83
  [✔] FarmersDelight-1.20.1-1.2.4
  [✔] FastFurnace-1.20.1-8.0.2
  [✔] FastLeafDecay-32
  [✔] FastWorkbench-1.20.1-8.0.4
  [✔] ferritecore-6.0.1-forge
  [✔] flib-1.20.1-0.0.14
  [✔] FluxNetworks-1.20.1-7.2.1.15
  [✔] ForgeEndertech-1.20.1-11.1.4.0-build.0572
  [✔] ftb-library-forge-2001.2.4
  [✔] ftb-ultimine-forge-2001.1.5
  [✔] geckolib-forge-1.20.1-4.4.7
  [✔] industrial-foregoing-1.20.1-3.5.17
  [✔] ironchest-1.20.1-14.4.4
  [✔] IronJetpacks-1.20.1-7.0.6
  [✔] Jade-1.20.1-forge-11.9.2
  [✔] jei-1.20.1-forge-15.10.0.38
  [✔] JsonThings-1.20.1-0.9.2
  [✔] JustEnoughResources-1.20.1-1.4.0.247
  [✔] kotlinforforge-4.11.0-all
  [✔] LibX-1.20.1-5.0.12
  [✔] lostcities-1.20-7.2.0
  [✔] lostworlds-1.20-0.0.1
  [✔] macawsbridgesbop-1.20-1.3
  [✔] macawsroofsbop-1.20-1.1
  [✔] ManyIdeasCore-1.20.1-1.4.2
  [✔] ManyIdeasDoors-1.20.1-1.2.3
  [✔] mcjtylib-1.20-8.0.5
  [✔] MCV-BiomesOPlenty-1.0.0+1.20.2-Forge
  [✔] mcw-bridges-3.0.0-mc1.20.1forge
  [✔] mcw-doors-1.1.1forge-mc1.20.1
  [✔] mcw-fences-1.1.2-mc1.20.1forge
  [✔] mcwfencesbop-1.20-1.1
  [✔] mcw-furniture-3.3.0-mc1.20.1forge
  [✔] mcwfurnituresbop-1.20-1.2
  [✔] mcw-roofs-2.3.1-mc1.20.1forge
  [✔] mcw-trapdoors-1.1.3-mc1.20.1forge
  [✔] mcw-windows-2.3.0-mc1.20.1forge
  [✔] mekanism_turrets-1.1.8
  [✔] Mekanism-1.20.1-10.4.8.43
  [✔] mekanism-ad-astra-ores-1.0.0
  [✔] MekanismAdditions-1.20.1-10.4.8.43
  [✔] MekanismGenerators-1.20.1-10.4.8.43
  [✔] Mekanism-MoreSolarPanels-1.20.1-1.5.9
  [✔] MekanismTools-1.20.1-10.4.8.43
  [✔] MekanismWeapons-1.20.1-1.5
  [✔] modernfix-forge-5.19.0+mc1.20.1
  [✔] MoreChestVariants-1.5.6+1.20.2-Forge
  [✔] MoreMekanismProcessing-1.20.1-4.0
  [✔] moreoverlays-1.22.7-mc1.20.2
  [✔] MouseTweaks-forge-mc1.20.1-2.25.1
  [✔] MysticalAgriculture-1.20.1-7.0.12
  [✔] oculus-mc1.20.1-1.7.0
  [✔] Paraglider-forge-20.1.3
  [✔] Patchouli-1.20.1-84-FORGE
  [✔] Philips-Ruins1.20.1-4.3.1
  [✔] Placebo-1.20.1-8.6.2
  [✔] Plenty_of_Golems-V1.3.1-Forge_1.20.1
  [✔] polymorph-forge-0.49.5+1.20.1
  [✔] portablemobs-1.2.0-forge-mc1.20
  [✔] Powah-5.0.6
  [✔] Quad-1.2.5+1.20.4-Forge
  [✔] Quark-4.0-460
  [✔] rangedpumps-1.1.0
  [✔] RecipesLibrary-1.20.1-2.0.1
  [✔] recruits-1.20.1-1.11.4
  [✔] refinedcooking-4.0.0
  [✔] refinedstorage-1.12.4
  [✔] refinedstorageaddons-0.10.0
  [✔] resourcefulconfig-forge-1.20.1-2.1.2
  [✔] resourcefullib-forge-1.20.1-2.1.28
  [✔] rftoolsbase-1.20-5.0.4
  [✔] rftoolsbuilder-1.20-6.0.5
  [✔] rhino-forge-2001.2.2-build.18
  [✔] ScalableCatsForce-3.3.1-build-0-with-library
  [✔] sebastrnlib-4.0.0
  [✔] SereneSeasons-1.20.1-9.0.0.46
  [✔] silent-gear-1.20.1-3.6.3
  [✔] silent-lib-1.20.1-8.0.0
  [✔] SkyblockBuilder-1.20.1-5.1.20
  [✔] smallships-forge-1.20.1-2.0.0-b1.4
  [✔] sophisticatedbackpacks-1.20.1-3.20.5.1044
  [✔] sophisticatedcore-1.20.1-0.6.22.611
  [✔] SpartanShields-1.20.1-forge-3.1.1
  [✔] SpartanWeaponry-1.20.1-forge-3.1.3-all
  [✔] Steam_Rails-1.6.4+forge-mc1.20.1
  [✔] StorageDrawers-1.20.1-12.0.4
  [✔] Structory_1.20.x_v1.3.5
  [✔] supermartijn642corelib-1.1.17-forge-mc1.20.1
  [✔] tempad-forge-1.20.1-2.3.4
  [✔] TerraBlender-forge-1.20.1-3.0.1.7
  [✔] Terralith_1.20.x_v2.5.4
  [✔] thermal_expansion-1.20.1-11.0.1.29
  [✔] thermal_foundation-1.20.1-11.0.6.70
  [✔] titanium-1.20.1-3.8.32
  [✔] Towns-and-Towers-1.12-Fabric+Forge
  [✔] twilightforest-1.20.1-4.3.2508-universal
  [✔] valkyrienskies-120-2.3.0-beta.5
  [✔] Voidscape-1.20.1-1.5.389
  [✔] waystones-forge-1.20-14.1.4
  [✔] workers-1.20.1-1.7.8
  [✔] XaeroPlus-2.21+forge-1.20.1-WM1.38.8-MM24.2.0
  [✔] Xaeros_Minimap_24.2.0_Forge_1.20
  [✔] xaeros_waystones_compability-1.0
  [✔] XaerosWorldMap_1.38.8_Forge_1.20
  [✔] YungsApi-1.20-Forge-4.0.5
  [✔] YungsBetterMineshafts-1.20-Forge-4.0.4
  [✔] YungsBridges-1.20-Forge-4.0.3
  [✔] ZeroCore2-1.20.1-2.1.44
  [✔] Zeta-1.0-24

**Comment by xiongshuang** [comment]
I'm having the same bug after updating to 1.3.0BETA13, even after reverting to the previous version. 

Using the add-ons for autumnity, bop, ecologics, neapolitan, quark, terralith, ua, plus, blooming nature, meadow, vinery, and phc.

[full mod list here since it's long](https://github.com/user-attachments/files/16532840/modlist.txt)

**Comment by Throneaway420** [comment]
Well, after further examination it seems axes didn't work on anything they were supposed to. 
https://www.curseforge.com/minecraft/mc-mods/lmft  -  "Load My F***ing Tags"
This fixed it.

**Comment by xiongshuang** [comment]
That works for me as well, thank you!

**Comment by jamestbfraser** [comment]
I'm having the same problem - axes just act like I'm punching it.  Only the chopped block pops out; the tree does not fall.  I tried the mod above to force tag loading, but it did not fix it.  I'm not sure how to import my mod list, but it's basically the create mods and fruitful trees and Dynamic Trees and Dynamic Trees+ and the Fruitful trees adapter mod for Dynamic Trees.  Also, using Forge 47.3.0, and Minecraft 1.20.1 (Java Version).  Thanks for any help you can provide!

**Comment by supermassimo** [comment]
@jamestbfraser sounds like your issue is a different one, please make a new report and include your latest.log

I will mark this as complete since the issue is caused by invalid tags, which is caused by other mods and not base DT
