### ISSUE TITLE
Incopabiluty with realworld mod.

### ISSUE THREAD

**Issue by jazzyPanikhida** [ferreusveritas/Dynamic-Trees#91]
So... There is a mod called realworld, it adds plants, and some of them grow on trees, and they just can't attach to the Dynamic Trees blocks.

P.S And also, can better folliage round them, ot only make leaves fluffy.

**Comment by ghost** [comment]
It's going to be next to impossible for those plants to grow on the trees since the trunks can vary in thickness.  Trunk rounding violates the stylized minecraft aesthetic and I won't provide any effort in achieving it.
