### ISSUE TITLE
Custom sapling shapes doesn't work correctly in treepacks

### ISSUE THREAD

**Issue by WenXin20** [ferreusveritas/Dynamic-Trees#940]
**Describe the bug**
When using custom sapling shapes in the species.json, only the second array will register for the hitbox.

**To Reproduce**
Use this for the shape:
```json 
  "sapling_shape": [
    [0.375, 0, 0.375, 0.625, 0.1875, 0.625],
    [0.25, 0.1875, 0.25, 0.75, 0.5, 0.75]
  ]
  ```
Only the second array gets used. 
If the two arrays are swapped, same result.

**Screenshots**
![image](https://github.com/user-attachments/assets/995467d0-99ef-43d0-a9a7-b2f5d4222ffd)

**Mods List**
`Dynamic Trees v1.3.0-Beta13`

**Comment by supermassimo** [comment]
Fixed in beta 15
