### ISSUE TITLE
overworld trees in nether

### ISSUE THREAD

**Issue by bobbo-s** [ferreusveritas/Dynamic-Trees#955]
**Describe the bug**
overworld trees dont grow properly in the nether, even when bonemealed 1.19.2 forge ver 1.2.2

**To Reproduce**
place a overworld tree in the neter (i used oak) and than bone meal it once, starts off fine, second time leaves disapear, 3rd time the rest of what is left

**Screenshots**
![Screenshot (1687)](https://github.com/user-attachments/assets/ce97346b-7ba8-4f9a-a089-a16c75cef2ec)
![Screenshot (1688)](https://github.com/user-attachments/assets/8458cc40-eee1-45f7-b542-812622427fd6)

**Rendering Glitches**
nope no shaders

**Crashes**
- Are you running the latest version of Dynamic Trees? yes
- What addons are you using? 
- Are you on the latest version for each addon?

**Mods List**
[crash-2024-10-11_17.23.48-server.txt](https://github.com/user-attachments/files/17347579/crash-2024-10-11_17.23.48-server.txt)

**Comment by supermassimo** [comment]
This is because there is no natural light in the nether
