### ISSUE TITLE
Exception Ticking World Repetitive Crash

### ISSUE THREAD

**Issue by MegaNerdModding** [ferreusveritas/Dynamic-Trees#956]
**Crash-Log**
[crash-2024-10-11_17.45.29-server.txt](https://gist.github.com/NerdlyModding/a95e8f99d457ae41c76608673ae128bd)

**Describe the bug**
Dynamic Trees appears to be crashing my game back to desktop/launcher, even when client/server character is sitting still in place.  This happens specifically when in dense forests and has only begun to happen over the past several days (the mod-pack/server world have been running off-and-on for over a month IRL).  The crash is highly inconsistent and does not happen immediately upon loading the world.  Sometimes the server-player can be active/standing still for over half an hour with no crash - other times, it has happened in less than thirty seconds after full world-load.

**To Reproduce**
Steps to reproduce the behavior: Unknown what precisely is causing the error.  Only just started recently and do not know enough about the crash-log reading to tell what mod is incompatible, if at all.  All I can say for certain is that the crash-log points in all regards toward Dynamic Trees (never-mind all of the stack tracing also pointing toward it).

**Rendering Glitches**
No rendering glitches to my knowledge - Using Embeddium 0.3.28+mc1.20.1

**Additional context**
Been running Dynamic Trees on my world/server for over two months with very few compatibility issues up until this point.  Dynamic Trees for Aether was causing crashes at one time upon entering the Aether, but removing the add-on fixed that issue (add-on was not re-added).

**Crashes**
Version of Dynamic Trees: 1.20.1 - 1.4.0-ALPHA02
All other mods are up-to-date to my knowledge (see crash-log).

**Forge Version**
47.3.0. - MC 1.20.1

**Authors Note:**
I have no idea how to change labels or I'd remove the "enhancement" label and add more appropriate ones such as "1.20.1" and others.

**Comment by tabr** [comment]
the same problem
[crash-2024-10-23_11.59.33-server.txt](https://github.com/user-attachments/files/17488334/crash-2024-10-23_11.59.33-server.txt)
[crash-2024-10-23_12.08.10-server.txt](https://github.com/user-attachments/files/17488335/crash-2024-10-23_12.08.10-server.txt)
[crash-2024-10-23_12.12.54-server.txt](https://github.com/user-attachments/files/17488336/crash-2024-10-23_12.12.54-server.txt)
[crash-2024-10-19_11.16.39-server.txt](https://github.com/user-attachments/files/17488337/crash-2024-10-19_11.16.39-server.txt)
[crash-2024-10-19_13.31.19-server.txt](https://github.com/user-attachments/files/17488338/crash-2024-10-19_13.31.19-server.txt)
[crash-2024-10-19_13.33.36-server.txt](https://github.com/user-attachments/files/17488339/crash-2024-10-19_13.33.36-server.txt)
[crash-2024-10-19_13.37.04-server.txt](https://github.com/user-attachments/files/17488342/crash-2024-10-19_13.37.04-server.txt)
[crash-2024-10-21_17.17.22-server.txt](https://github.com/user-attachments/files/17488343/crash-2024-10-21_17.17.22-server.txt)
[crash-2024-10-21_17.22.58-server.txt](https://github.com/user-attachments/files/17488344/crash-2024-10-21_17.22.58-server.txt)
[crash-2024-10-21_17.37.47-server.txt](https://github.com/user-attachments/files/17488346/crash-2024-10-21_17.37.47-server.txt)
[crash-2024-10-21_17.44.33-server.txt](https://github.com/user-attachments/files/17488347/crash-2024-10-21_17.44.33-server.txt)
[crash-2024-10-21_17.47.41-server.txt](https://github.com/user-attachments/files/17488348/crash-2024-10-21_17.47.41-server.txt)
[crash-2024-10-22_21.29.20-server.txt](https://github.com/user-attachments/files/17488352/crash-2024-10-22_21.29.20-server.txt)

**Comment by AnonymousGoat** [comment]
Same problem (although it is muddled by a lot of mods)
[crash-2024-10-23_20.13.12-server.txt](https://github.com/user-attachments/files/17499379/crash-2024-10-23_20.13.12-server.txt)
[crash-2024-10-22_23.42.07-server.txt](https://github.com/user-attachments/files/17499380/crash-2024-10-22_23.42.07-server.txt)

**Comment by MegaNerdModding** [comment]
Sorry to say that I'm glad I'm not the only one experiencing this issue.  Perhaps if more people come forward, this issue might actually get some traction and we may get someone to actually respond that can help.

**Comment by tabr** [comment]
it seems to be there is not problems with DynamicTrees-1.20.1-1.3.3.jar

**Comment by MegaNerdModding** [comment]
> it seems to be there is not problems with DynamicTrees-1.20.1-1.3.3.jar

Obviously there's _**something**_ triggering on Dynamic Trees, or else myself and the other two individuals on here wouldn't be getting flags pointing at the mod in our crash reports.

Perhaps it has to do with the ALPHA02 build and reverting back may assist the issues?

**Comment by supermassimo** [comment]
Please try ALPHA03 and let me know if this is fixed

**Comment by supermassimo** [comment]
As this has not been reported anymore I will assume it has been fixed in beta 3
