### ISSUE TITLE
Seeds dropping from through-command-placed saplings

### ISSUE THREAD

**Issue by LughtMon** [ferreusveritas/Dynamic-Trees#968]
Saplings placed through command or mods still drop their seeds after trying to grow on unappropriate blocks (like stone, gravel etc), even if the option in serverconfig "dynamicSaplingDrops" is set to "false". 

https://github.com/user-attachments/assets/3466930a-2aa8-47a2-ba16-6b9b30903339

**Comment by supermassimo** [comment]
Fixed on 1.3.5
