### ISSUE TITLE
Add chopping speed option

### ISSUE THREAD

**Issue by LughtMon** [ferreusveritas/Dynamic-Trees#969]
I would like to see in serverconfig some option which can change the chopping speed of trees. It can be used for various survival modpacks to aim for more realistic behaviour - if you'll chop the whole tree, it should take some time.

There already is function in server-config called "maxTreeHardness", but setting it to 200 resets the value to 1 after loading world. Now I have it on 190 and it works fine, but the point of making it even slower still stands.

**Comment by supermassimo** [comment]
Added on 1.3.5
