### ISSUE TITLE
Falling tree sound bug

### ISSUE THREAD

**Issue by LughtMon** [ferreusveritas/Dynamic-Trees#970]
When tree falls and the player is further away, the sound still play without any changes - it sounds like the tree has fallen next to the player. The tnt show as example in the video can be a creeper and you can be 50 blocks away, it will still sound like it was next to you. The same thing happens when a tree is on fire.

https://github.com/user-attachments/assets/c1e9a429-3000-4691-9231-71db3a5bc7b8

**Comment by supermassimo** [comment]
Fixed on 1.3.5
