### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Arch23-tech** [ferreusveritas/Dynamic-Trees#973]
I just wonder Mr. maxhyper, I'm a forge user and i really need to know why this mod has its later updates in development if last supported version is 47.1. 3..

what i want to reach out for here is:
do the latest releases for 1.20.1 carry or may carry support for forge version 47.3.5 and above.?

**Comment by Groupix05** [comment]
Forge after 47.1.3 (when forge team disassemble to make neoforge) should work with DynamicTrees, and its addons. Some addons need forge 47.3.0. I played a lot on forge 47.3.0+ and everything works as intended. If you do have issues, try forge 47.1.3 before reporting them. DynamicTrees 1.21 will be only on Neoforge (and fabric). If you want to ask more questions, the discord server is easier for us.

**Comment by supermassimo** [comment]
Answered by groupix05
