### ISSUE TITLE
1.16.5-0.10.5 trees grown from Apple Pips not bearing fruit when fully grown, and only dropping Oak Logs when chopped.

### ISSUE THREAD

**Issue by NotYourLifeline** [ferreusveritas/Dynamic-Trees#978]
**Screenshots**
Serene Seasons Calendar indicating It's summer, appropriate season for growing apple trees: https://ibb.co/tYS5VmQ
Trees fully grown with more than 180+ Bonemeals used, without fruit: https://ibb.co/wKTTTWJ

**Rendering Glitches**
Are you using Sodium (or any equivalent mods that mess with rendering)?:
Better Foliage 2.7.1
Quark r2.4-322
Optifine HD U G8 and BSL shader 8.4

**Additional context**
Serene Seasons 4.0.1.130
No Tree Punching 4.3.0

using all addons:
Dynamic Trees Plus 0.1.0
Dynamic Trees Biomes O Plenty 2.0.9
Dynamic Trees Traverse 2.2.4

modlist: https://jmp.sh/s/LShwwVONiH8DOjcH9Dw5

forge modloader version: 36.2.34

+suggestion: 
I also noticed Apple Pip isn't compatible with Rich Soil from Farmer's Delight, so It'd be nice to get a compatibility patch.

++another bug report:
game crashes if you turn off or turn on a shader while on a server with Dynamic Trees installed.
crash log: https://jmp.sh/s/VAQZgBgLrbHs822vjn0u

**Comment by NotYourLifeline** [comment]
nevermind I figured out there was a server config setting allowing a Bonemeal to make saplings bear fruits.
turning this very specific setting on solved the issue.
teeny tiny unripe apple: https://ibb.co/Fb9FFSH

however devs should make this setting turned ON by default from now on, because the default tree growth is already too slow (whole in-game year: 4 seasons to fully mature) and Apple Trees are pretty scarce in the wild.

also, the crash issue is still present, and I'd still like a compatibility patch with Farmer's Delight.
while at it, being able to list Apple Pip with other saplings for the Market NPC from Farming for Blockheads would be nice as well.

**Comment by NotYourLifeline** [comment]
the problem is, I'm currently experimenting with max growth rate setting and the apples are growing VERY slowly.
64 Bone Meal Growth Pulses + 16 Growth Multiplier + Scale Biome Growth Rate 1 with 10 fully grown Apple Trees
yet they only bear only 1-2 fruits at a time(in about 30 minutes in real life) even when I'm constantly using stacks of Bone Meals on all of them.

this is either bugged, or there needs to be a config setting that controls the exact percentage of the chance an Apple Tree Leaves block could generate a Apple Blossom(that grows into Apple fruit).

**Comment by NotYourLifeline** [comment]
okay apparently **the chance of the Apples generating on the Leaves block depends on Random Ticks**, and It's pretty low from what I've seen.
1 second equals to 20 ticks, so I pumped it up to 2000 ticks per second instead and with command now the trees are bearing fruits in pretty normal rate.
result is still not as extreme as I expected it to be, considering It's in x100 speed: https://ibb.co/Y2W2XwS

and another problem I noticed was that **some of the Apple Pips I planted had turned into Oak Trees instead, and they didn't bear any fruit, and dropped Oak Acorns when chopped down.** which explained why the fruit growth rate was so slow in the first place.
no apples: https://ibb.co/DQZgLDF
Acorn drop: https://ibb.co/K91CVwr

so the mod's default setting is pretty unbalanced, and also definitely bugged as well.

**Comment by NotYourLifeline** [comment]
with more experiment, I figured out the reason why the fruit's growth rate was so low was because of the Global GameRules mod's default setting for RandomTicks was 3 instead of Vanilla's 20.
still, Dynamic Trees mod's default generation rate setting for Apple is pretty low even with that in mind, so setting the World's RandomTickSpeed around 100 is pretty reasonable in my opinion.

**Comment by NotYourLifeline** [comment]
well, now I look like a total lunatic obsessed with Minecraft Apples lol
at least now I won't have to cheat through JEI just to get some apples or run around for hours trying to find one in a village chest or in mines.
I hope there would be a config setting to adjust this in the next version.

**Comment by supermassimo** [comment]
The default rate of randomTickSpeed is 3. If you need higher throughput of apples make an orchard and plant more apples :).
Alternatively, you can increase the fruit production rate using a treepack https://github.com/DynamicTreesTeam/DynamicTrees/wiki/Tree-Packs:-Species#gen-features
