### ISSUE TITLE
Tetra x Dynamic Trees

### ISSUE THREAD

**Issue by Krocceto** [ferreusveritas/Dynamic-Trees#979]
**Feature request rules**
This is just a template to help you post a useful issue.  Erase these rules and any irrelevant categories and content as you see fit.

- Only submit issues related to the latest version of the mod for the currently supported version of Minecraft
- When referring to software versions always use the actual version number and never "latest".
- Do not request support for other mods (that should be done [here](https://github.com/orgs/DynamicTreesTeam/discussions/categories/compatibility-addon-suggestions)) or ports to other versions.
- Make sure feature requests come under the project scope. The details of this can be found on the [CurseForge page](https://www.curseforge.com/minecraft/mc-mods/dynamictrees).

If you are opening this **for any other reason** than to request a new feature, it will be closed without explanation! For bug reports, use the bug report template.

[!][The request beggins here][!]

**Is your feature request related to a problem? Please describe.**
Its not exactly a problem, just an idea

**Describe the solution you'd like**
Adding some kind of recon to the Tetra-made tools for the proper tree chopping

**Describe alternatives you've considered**
SOMEHOW adding Tetra-made tools support for Dynamic Trees so they can just work very well

**Additional context**
Im making a modpack and i realised that in my case, Minecraft 1.20.1 Forge-47.3.12, the Tetra-made axes doesnt seems to work with the dynamic trees, they break well but just dissapear

**Comment by supermassimo** [comment]
This would be better suited as a bug report. Theres no reason for a mod's axes not to work with our trees
