### ISSUE TITLE
Passable leaves bug

### ISSUE THREAD

**Issue by LughtMon** [ferreusveritas/Dynamic-Trees#981]
In server-config of dynamictrees there are "isLeavesPassable" function, which allows entities to go through them. This works fine, however, function "vanillaLeavesCollision" (no matter if true or false) doesn't work (you fall through like it was just airblock). It should slow down the entity and reduce fall damage. Good example how it can work and maybe sound is mod "passable fooliage": https://www.curseforge.com/minecraft/mc-mods/passable-foliage

**Comment by supermassimo** [comment]
Added in in 1.3.6
