### ISSUE TITLE
Strange behaviour when leaves are set set to passable + enhance player movement

### ISSUE THREAD

**Issue by LughtMon** [ferreusveritas/Dynamic-Trees#987]
When leaves are set to passable and also set to enhance players movement, they do slow down the player too much, but most of the time just when moving horizontally. When you go slowly vertically up or down, they do slow you down but when you fall just 1 block of air, they doesn't enhance you at all. This shouldn't also work when you are flying in creative. 

My suggestion is, that leaves should enhance all entities and also make you slow down by 5-10% when walking through them, by 50% when falling slowly through them and slow you exponentially when falling from certain heigh to again, 50%. Adding sound when passing (for example to hear a mob coming) would be welcome :)

Note that the % I have wrote are just my implementation for you to get the idea what how passable leaves can potentially work.

https://github.com/user-attachments/assets/1c088aac-7a71-4764-b13e-da1162e1158e

https://github.com/user-attachments/assets/29f2558b-e613-4b0a-add2-8aadbb7b0b54

**Comment by supermassimo** [comment]
This should be fixed in 1.3.7 when its released
